### ISSUE TITLE
Upgrade tensorflow to 1.4.0

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1003]
Upgrade to TF 1.4.0 requires a little bit of extra typing (for `Tensor`), which is straightforward. But unfortunately there seems to be a bug in the new TF lib, which fails tests on the consecutive test runs (possibly due to some global state?). To reproduce:

```
➜  scio git:(master) sbt
sbt:scio> project scio-tensorflow
sbt:scio-tensorflow> test
// tests run fine the 1st time around
// run tests again:
sbt:scio-tensorflow> test
2018-01-11 16:50:50.406946: F tensorflow/stream_executor/host/host_platform.cc:97] Non-OK-status: gpu::MultiPlatformManager::RegisterPlatform(std::move(platform)) status: Internal:
platform is already registered with name: "Host"
/usr/local/Cellar/sbt/1.0.2/libexec/bin/sbt-launch-lib.bash: line 58: 94206 Abort trap: 6           "$@"
```

and the sbt process exits with `134`.

TF 1.5.0-rc0 seems to have the same issue.

**Comment by ravwojdyla** [comment]
WIP in branch `rav/upgrade_tf_140`

**Comment by nevillelyh** [comment]
I can reproduce this by running `"Tensorflow" should "work for hello-wold"` only in `TensorflowSpec` with `sbt +scio-tensorflow/test`.

**Comment by nevillelyh** [comment]
Added a test to repro the issue. The 2 tests in this spec are identical. 
- Running both tests with `sbt scio-tensorflow/test` works
- Running one of them with `sbt +scio-tensorflow/test` fails with the same "metrics" error.

```
class DebugSpec extends PipelineSpec {
  def test(): Unit = {
    val const = "MyConst"
    val graph = new Graph()
    val helloworld = s"Hello from ${TensorFlow.version()}"
    val t = Tensors.create(helloworld)
    graph.opBuilder("Const", const).setAttr("dtype", t.dataType()).setAttr("value", t).build()
    t.close()

    val session = new Session(graph)
    val r = session.runner().fetch(const).run().get(0)
    try {
      new String(r.bytesValue()) should be(helloworld)
    } finally {
      session.close()
      graph.close()
      r.close()
    }
  }

  "Tensorflow" should "work for hello-wold" in {
    test()
  }

  it should "work again" in {
    test()
  }
}
```

**Comment by nevillelyh** [comment]
Adding `Test / fork := true,` to `scioTensorFlow` project fixed the issue.
