### ISSUE TITLE
Problems with dynamic big query destinations

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#1006]
hello me again, i have a similar issue to https://github.com/spotify/scio/issues/1005 but with big query, ok but is missing support for InsertRetryPolicy which is on Bigquery Io. This, i can raise a pr if you would accept.

The other issue is that i would like to get access to the Write result https://github.com/apache/beam/blob/53c9bf4cd325035fabde192c63652ef6d591b93c/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteResult.java

and its underlying failed inserts which can be present if you set a lenient retry policy. As far as i can tell its not accessible and ive had not luck getting to it. Can you give any advice?

**Comment by nevillelyh** [comment]
Similar to my answer in #1005. Need to find a balance between covering majority of the use cases vs making the API overly complex.

We don't expose `POutput` in `saveAsCustomOutput`. Not sure if we will/should since it'll change the API semantics. Can you do `data.internal.apply(BigQueryIO.write()...)` instead?

**Comment by LukeDefeo** [comment]
Thanks i didn't know about the internal PCollection being available, i can implement my use case of writing the failed inserts somewhere with this.

As for the retry policy there is a clear default which is the beam default of InsertRetryPolicy.alwaysRetry(), shouldn't be too much of an impact to the api?

**Comment by LukeDefeo** [comment]
As for the point about not exposing the POutput internals. Perhaps it could be a field on the tap that we could access. 

Alternatively it could be done similar to beam where you would have the failedInserts on the bigquery tap?

**Comment by nevillelyh** [comment]
Adding result to `Tap` would require an additional type param in `Tap[T]` and make inference harder in some cases. We're also in the middle of an IO/Tap redesign so need to think about this.

OTOH you only want to access `POutput` if retry policy is not the default `alwaysRetry()` right? So we need to support both or neither.

**Comment by LukeDefeo** [comment]
Not sure why it would be an extra type param, let the user access it via pattern matching if its a field on the case class

On the second point yes, they don't make a lot of sense without each other
