### ISSUE TITLE
Investigate external sort

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1011]
https://beam.apache.org/documentation/sdks/java-extensions/#sorter

**Comment by mpasa** [comment]
I've been reading the Beam code. Here's some info about it:

1. It implements a `SortValues` transform, which gets a `SCollection[K, Iterable[K2, V]]` and returns another `SCollection[K, Iterable[K2, V]]`, where the iterable has been sorted by `K2` keys.

2. The sorting of each key is done in a single worker, after shuffling. It is abstracted in a `BufferedExternalSorter`, which internally uses two different sorters. It first tries to fit all data into an in-memory sorter with a fixed memory limit. If the memory limit is exceeded, the data is transferred to an external (disk) sorter. The external sorter uses a Hadoop Sequence File to perform the sorting. Both the memory limit and the directory to store the temporal files in disk can be set when seting up the transform.

3. Keys are sorted using a **lexicographical comparison** of their coder's byte representation. We can't directly use an `Ordering`.

4. The transform force the collection's coder to be a `KvCoder`. The coder of the iterable must be an `IterableCoder`.

## Example
We can write a very basic example to sort people's age by name:

```scala
// Data transformed into a KV
val data = sc.parallelize(Seq("John" -> 5, "John" -> 21, "John" -> 18))
val dataKv= data.map { case (name, age) => name -> KV.of(age, age) }

// Coder needed by the transform
val registry = data.internal.getPipeline.getCoderRegistry
val coder = KvCoder.of(
  registry.getScalaCoder[String](sc.options),
  IterableCoder.of(
    KvCoder.of(
      registry.getScalaCoder[Int](sc.options),
      registry.getScalaCoder[Int](sc.options)
    )
  )
)

// Group and apply external sort
val grouped = dataKv.groupByKey.map(x => KV.of(x._1, x._2.asJava))
val sortValues = SortValues.create[String, Int, Int](BufferedExternalSorter.options())
val sorted = grouped.setCoder(coder).applyKvTransform(sortValues)

// Go back to Scala types
val result = sorted.map(kvIterableToTuple).mapValues(_.map(_.getValue).toList)
result should containInAnyOrder(Seq("John" -> List(5, 18, 21)))
```

## API

I think we could do the same thing as we do with key-value collections, but introducing a new `GroupedSCollectionFunctions` for `(K, Iterable[V])` collections. We define a `sortGroupsBy` that gets a function to transform from our values to the `SortValues` `K2` used to perform the external sort.

```scala
class GroupedSCollectionFunctions[K, V](val self: SCollection[(K, Iterable[V])]) {
    def sortGroupsBy[K, K2](sorter: V => K2)(implicit options: BufferedExternalSorter.Options): SCollection[(K, Iterable[V])])
}
```

## Problems

- The sorting is performed in a single worker, after the shuffling. This can be a problem for big groups, which will spill to disk.
- How we define the coder for `K2`? If we define a `sortGroupsBy[K, K2](f: V => K2)` and we get the `K2` coder from the registry, I'm not sure how to assure the resulting coder will work as expected using its byte representation.

What do you think?

**Comment by nevillelyh** [comment]
Duplicate of #2530. Closing.
