### ISSUE TITLE
Workaround for BEAM-3311 BigTableIO and Iterable of KV

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1031]
Now that BEAM-3311 is closed as a won't fix, we might need a local workaround.

Extend BigTableIO to write Iterable of KV
https://issues.apache.org/jira/browse/BEAM-3311

**Comment by andrisnoko** [comment]
@nevillelyh I will take on this issue since I had initially explored it [here](https://github.com/andrisnoko/beam/blob/bulk-write-working/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java#L734)
