### ISSUE TITLE
Counter not decrementing in unit test

### ISSUE THREAD

**Issue by martinbomio** [spotify/scio#1037]
Decrementing a counter doesn't seem to update the counter while unit testing (haven't checked in dataflow).
Example: 
```scala
val as = sc.parallelize(1 to 10)
as
  .map {x => Seq(total, filtered).foreach(_.inc); x }
  .filter(_ < 5)
  .map {x => filtered.dec; x }
```
in this case filtered should be 6, but is 10

**Comment by andrewsmartin** [comment]
This is on master btw, `sc.initCounter` isn't available in a release yet

**Comment by martinbomio** [comment]
yes, it is. The only difference is that I use ` ScioMetrics#counter` for creating the counter, instead of 
`sc#initCounter` (I am using 0.4.7 and doesn't seem to be available)

**Comment by martinbomio** [comment]
hmm, seems like I was accessing the wrong counter 🙄 . All seems to be working now. Will close this one. Sorry!
