### ISSUE TITLE
Equivalent for mapPartitions

### ISSUE THREAD

**Issue by mcapuccini** [spotify/scio#1053]
Hi! I just bumped into your amazing library 🙂 I developed a Docker-based dataprocessing tool based on Spark (https://github.com/mcapuccini/EasyMapReduce), and I am evaluating if I could do a bit of refactory using Scio, to enable running on Google Dataflow.

My tool feeds Spark partitions through Docker containers, that contain data processing tools. In order to do this I use mapPartitions, which enables me to improve performance by mounting an entire partition into a Docker container. Is there an equivalent for mapPartitions in Scio?

**Comment by yonromai** [comment]
@mcapuccini interesting tool!
@nevillelyh it's hard to abuse dataflow to install & run arbitrary code (like a docker container), compared to spark, right?

**Comment by mcapuccini** [comment]
They did something similar at Google https://github.com/googlegenomics/dockerflow. They discontinued support though. Assuming that there is a Docker socket available in the Dataflow workers, then it should be possible to run the following code in a `map`:

https://github.com/mcapuccini/EasyMapReduce/blob/master/src/main/scala/se/uu/it/easymr/EasyDocker.scala#L49-L99

**Comment by nevillelyh** [comment]
I see 2 questions here:

- If there's a equivalent to Spark's `mapPartitions`. I'm afraid it's a no. Beam doesn't expose internal partitions and the smallest processing group is a bundle but that depends on the runner, mode (streaming vs batch) and other factors and is not user tunable.
- If we can run Docker containers in Dataflow. It's possible but will be hacky. DF runs user code in a container in a worker VM but that's subject to change, i.e. in a sandboxed JVM in the future. We can't spin up another container inside so you'll have to deploy them in a separate GKE cluster or something, which requires a lot of extra work to get credentials and client dependencies to work.

**Comment by mcapuccini** [comment]
Thanks! That clarifies it. I guess I'll stay with my Spark implementation for now.
