### ISSUE TITLE
Add command line option to specify waitUntilDone duration

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1055]
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L360

**Comment by ClaireMcGinty** [comment]
after taking a look how `ScioContext` is set up, I was envisioning implementing this by adding a getter/setter for `jobTimeout` to `ScioOptions.java` and setting it in [ScioContext#parseArguments](https://github.com/spotify/scio/blob/19fee4716f71827ac4affbd23d753bc074c529b8/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L145). that way `ContextScioResult` has access to it when `waitUntilDone` is called. is that roughly what you had in mind? @nevillelyh

**Comment by nevillelyh** [comment]
Pretty much yeah. You shouldn't have to do anything in `parseArguments` since anything in `ScioOptions` will just be passed on. You can do `.as(classOf[ScioOptions])` in `ContextScioResult` and retrieve the setting.

**Comment by regadas** [comment]
#1062
