### ISSUE TITLE
Ability to cancel job from ScioResult

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1056]
IIRC `ScioResult#waitUntilDone` only throws an exception when the timeout is up but won't cancel the job. Need to pass it to the underlying job (might be runner specific?).

**Comment by ClaireMcGinty** [comment]
as far as working this functionality into `ScioResult`, what do you think about modifying `waitUntilDone(duration: Duration = Duration.Inf)` to include an optional boolean like `waitUntilDone(duration: Duration = Duration.Inf, doCancelJob: Boolean = false)` ? The other option would be to just add an entirely new method like `def waitOrCancel(duration: Duration = Duration.Inf): ScioResult  = {...}`

**Comment by nevillelyh** [comment]
+1 on optional argument. Although it might break binary compatibility? But that should be OK if we include this in 0.5.0 release. cc @regadas

**Comment by regadas** [comment]
optional arg sounds good at first glance. I think we can fit it in the 0.5.0 release

**Comment by regadas** [comment]
@ClaireMcGinty are you planing on taking this one? 😄

**Comment by ClaireMcGinty** [comment]
@regadas yep!! it looks like it's as simple as calling `internal.cancel()` (at least, this worked with the batch Dataflow runner...). I'll put up a PR after I get things cleaned up/tested.

**Comment by ClaireMcGinty** [comment]
posted https://github.com/spotify/scio/pull/1058

**Comment by regadas** [comment]
PR #1058
