### ISSUE TITLE
Cassandra "LEAK DETECTED" error when using scio-cassandra

### ISSUE THREAD

**Issue by pemdp** [spotify/scio#1068]
The following error appears when streaming data to Cassandra:

> [error] org.apache.cassandra.utils.concurrent.Ref [] - LEAK DETECTED: a reference (org.apache.cassandra.utils.concurrent.Ref$State@2c23c049) to class org.apache.cassandra.io.sstable.format.SSTableReader$InstanceTidier@1730803416:/tmp/scio-cassandra-1088608348297189114/foo_keyspace/foo_table-ddc8448e-8f88-4d8e-bcc7-3a0d9b5b24cd/mc-3-big was not released before the reference was garbage 

Below is a snippet with a similar stream. The target Cassandra table has only one field which is of the text data type.

```scala
  val data: SCollection[String] = getData()
  val opts = CassandraOptions("foo_keyspace", "foo_table", "INSERT INTO foo_keyspace.foo_table(foo_column) VALUES (?)", "127.0.0.1", 9042)
  data.withFixedWindows(Duration.standardSeconds(10))
    .saveAsCassandra(opts)(Seq(_))
  sc.close()
```

Tested on _Apache Cassandra 3.0.16_ and _Scio 0.4.7_ and _0.5.0-beta1_

**Comment by nevillelyh** [comment]
Sorry for the late response. Just got around to look at this.
@pemdp is this a streaming job? Does the same code work in batch?

**Comment by pemdp** [comment]
@nevillelyh, It was a streaming job. Did you manage to reproduce the issue?

**Comment by nevillelyh** [comment]
Gonna close this since Cassandra bulk writer has a lot of mutable global states that's hard to manage in streaming mode. We documented this and now only recommend this sink for high-throughput batch use cases.
https://github.com/spotify/scio/commit/eb9ef7f937ad89007bc7ada90ad210cbb3689e34
