### ISSUE TITLE
Refactor BigQueryClient

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1073]
`BigQueryClient` grew both in the size of the class/file but also public API, we now support jobs/export/imports - this task is to refactor the client/API to be more consistent across different functions (jobs/export/import etc) - consider pros/cons for pulling the client out of scio to a separate lib.

Related:
 #1060 
 #1049

**Comment by guidj** [comment]
I can take this one

**Comment by guidj** [comment]
I still intend to work on this. Just been busy at work and will be off until the end of the month
If someone wants to pick it up though, I don't mind.
Otherwise, I'll get to it when I'm back.

**Comment by guidj** [comment]
👍

**Comment by jto** [comment]
See https://github.com/spotify/scio/pull/1096

**Comment by guidj** [comment]
@ravwojdyla Hey. When you say "pulling the client out of scio to a separate lib", are you referring to pulling the helper methods out of ScioContext, or removing the scio-bigquery project all together?

**Comment by regadas** [comment]
@guidj are you working on this?

**Comment by guidj** [comment]
Yea, I was @regadas . But I wasn't clear on what @ravwojdyla said about separating the a lib, so halted
I was only refactoring the client code to be neat, and changing the API

**Comment by regadas** [comment]
Closed via #1439
