### ISSUE TITLE
Better support for parameterised queries in @BigQueryType.fromQuery

### ISSUE THREAD

**Issue by jto** [spotify/scio#1078]
Currently String.format is used to set parameter values. For example

```scala
@BigQueryType.fromQuery("SELECT * FROM `some_table` LIMIT %s")
class SomeEntity
```
And then we set the parameters with something like:
```scala
SomeEntity.query.format("10"))
```

It would be nice if the macro `TypeProvider.toTableImpl` was generating a properly typed function based on the wildcards. For example:

```scala
@BigQueryType.fromQuery("SELECT * FROM `some_table` LIMIT %d") // Note the %d instead of %s
class SomeEntity
// ...
// SomeEntity.queryFn has type Long => String
SomeEntity.queryFn("foo") // does not compiles
SomeEntity.queryFn(10) // compiles
``` 

I don't think it's particularly hard to implement but preserving back-compatibility and good IDE support is probably going to be the real challenge here.

**Comment by nevillelyh** [comment]
Yeah shouldn't be hard to add a `queryFn` method to the generated code. But since most params are passed in via python Luigi and stringly typed this probably has low benefit to effort ratio?

**Comment by jto** [comment]
You know that better than I do :)

**Comment by jto** [comment]
Scio I'm following GP033 and you still parse Luigi's parameters and call `TrackEntity.query.format(...)` so a bit more type safety would make sense IMHO.
