### ISSUE TITLE
Split ScioContext in 2 cases Real execution and test

### ISSUE THREAD

**Issue by jto** [spotify/scio#1081]
Related to #575 

The current version of `ScioContext` handles both the "real" execution of pipelines and the local execution of pipelines in tests. 

This leads to almost every methods in `ScioContext` loolking more or less like this:

```scala
def someMethod(param: SomeType): SCollection[T] = requireNotClosed {
    if (this.isTest) {
      // test execution code
    } else {
      // real execution code
    }
  }
}
```

I suggest we turn `ScioContext` into a trait with most methods left unimplemented and create 2 concrete implementations: `TextContext` and `BeamContext`. This way the `if(isTest)`  test can be only done once in the code. 

I think it should be doable without impacting the users.

**Comment by mpasa** [comment]
I second this. How would the code that calls `isTest` look like outside the `ScioContext` class? For example the methods in `Scollection`. A pattern match of the two values of the sealed trait?

**Comment by jbx** [comment]
The nio branch could possibly fix the issues outlined here. Review once that's released.

**Comment by nevillelyh** [comment]
This should be covered by NIO, closing.
