### ISSUE TITLE
S3 IO support

### ISSUE THREAD

**Issue by francescoperera** [spotify/scio#1082]
It doesn't look like there is an S3 IO  in Scio but  I know that it was just added to the Beam Java SDK (https://github.com/apache/beam/pull/4080).
 Are  there plans to add it here as well ?

**Comment by andrewsmartin** [comment]
Hi @francescoperera, we don't have any immediate plans since we don't really use S3 internally - but PRs are certainly welcome :)

**Comment by andrewsmartin** [comment]
Also - you can still do this from Scio, you would just have to drop down to the Java API. https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-beams-java-api-in-scio

**Comment by francescoperera** [comment]
@andrewsmartin thanks for the answer. I will look into and maybe open a PR for it if needed

**Comment by regadas** [comment]
This issue was moved to spotify/scio-contrib#8
