### ISSUE TITLE
Support saving Avro records implicitly to BigQuery

### ISSUE THREAD

**Issue by asydorchuk** [spotify/scio#1083]
It would be nice to have a way to implicitly save Avro records from Scio job directly to BigQuery without a need to explicitly specify schema.

So far I only found a way to do so from GCS: https://github.com/spotify/scio/issues/840

**Comment by nevillelyh** [comment]
We need a library to convert:
- Avro schema to/from bigquery
- Avro generic record to/from bigquery

We have some internal library for this. Can maybe copy and adapt here.

**Comment by skattoor** [comment]
@nevillelyh Do you think you could share some code snippets for this in the meantime? If possible, of course.

**Comment by nevillelyh** [comment]
This could be a good first candidate for the scio-contrib repo, @regadas @ClaireMcGinty WDYT?

**Comment by nevillelyh** [comment]
It's now part of https://github.com/spotify/scio-contrib
