### ISSUE TITLE
Wrong bigquery.TableRow Iterables value encoding 

### ISSUE THREAD

**Issue by calonso** [spotify/scio#1084]
When using BigQueryIO without case classes (i.e, building your own `TableRow`s instead of delegating `@BigQueryType.X` annotated case classes to do so), and when values contain iterables, encoding/decoding is not properly happening.

Test case reproducing it:

```
val row = bigquery.TableRow(("id", 1), ("data", Vector("a", "few", "strings")))

val stream = new ByteArrayOutputStream()
TableRowJsonCoder.of().encode(row, stream)

val decoded = TableRowJsonCoder.of().decode(new ByteArrayInputStream(stream.toByteArray))
decoded shouldBe row
```

The decoded `TableRow` contains `{"id"=1, "data"={"empty"=false, "traversableAgain"=true}}` instead of the expected contents.

I've discovered that this is because the `TableRowJsonCoder` uses `Jackson`'s `ObjectMapper` and it is not prepared to support scala types, therefore, just converting the Iterable (`Vector` above) to java using `JavaConverters` fixes the issue.

```
import collection.JavaConverters._
val row = bigquery.TableRow(("id", 1), ("data", Vector("a", "few", "strings").asJava))

val stream = new ByteArrayOutputStream()
TableRowJsonCoder.of().encode(row, stream)

val decoded = TableRowJsonCoder.of().decode(new ByteArrayInputStream(stream.toByteArray))
decoded shouldBe row
```

This affects loading data in batches into BQ as the intermediate files written to GCS from where the BQ load job then effectively loads have this `{"empty"=false, "traversableAgain"=true}` where an array is expected and the job fails.

**Comment by nevillelyh** [comment]
Just got a chance to look at this. So basically Beam's `TableRowJsonCoder` is encoding Scala `Vector` incorrectly by encoding the `"traversableAgain"` field, but that seems to be outside the scope of Scio? OTOH It IS encoding Java `Iterable`s correctly.

Can we close this?
