### ISSUE TITLE
Stricter Scalac options

### ISSUE THREAD

**Issue by jto** [spotify/scio#1097]
Right know we use very fews options of the Scala compiler:

```
-Xmax-classfile-name 100
-target:jvm-1.8
-deprecation
-feature
-unchecked
-Ydelambdafy:inline
```

Scalac support a number of options for linting the code that we could leverage. 
Here's an example of the options I use on a personal project: https://github.com/jto/validation/blob/v3/tagless2/project/scalaOptions.scala.

We may not want to use all those options in Scio but some of them are easy to satisfy and help with the code quality (dead / unused code detection, accidental type or variable shadowing, etc...).

@nevillelyh what do you think ?

**Comment by nevillelyh** [comment]
:+1: if we can document each options like in your repo.
Also do you want to introduce all of them or gradually in small batches? I'm leaning towards a few at a time, together with code fixes, so it's not too overwhelming and we can validate the changes through releases.

**Comment by jto** [comment]
Definitely gradually with a dedicated PR every time. 
We don't necessarily have to use all the options either.

**Comment by jbx** [comment]
Closing because we've added some. @jto feel free to re-open if you think there are some obvious things lacking
