### ISSUE TITLE
Automatic code formatter ?

### ISSUE THREAD

**Issue by jto** [spotify/scio#1098]
Since we already have guidelines on code style, how about using scalafmt to automatically format the code before compiling ? I think we should be able to conf scalafmt to match our guidelines.

Only downside is that diffing between code written before the formatting and after will be painful.

**Comment by regadas** [comment]
@jto I actually pitched this to @nevillelyh and @ravwojdyla awhile back and i have been using it for some time now... I think i have a nice config for it!

I was planing to try this out in a smaller project ... one that we just released to get some input and tweak it http://github.com/spotify/noether.

**Comment by jto** [comment]
I usually use a sbt plugin to format the code every time it's compiled. 
So both locally and on CI.

**Comment by nevillelyh** [comment]
Fixed in #1372
