### ISSUE TITLE
Should scio-repl include scio-extra?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#110]
Several people have asked about importing breeze, etc. in scio-repl.

**Comment by nevillelyh** [comment]
@ravwojdyla what do you think?

**Comment by ravwojdyla** [comment]
Sounds good - `guava` is 19 - so even if if include Hadoop `2.7.x`, it's not gonna fail correct?

**Comment by nevillelyh** [comment]
`scio-extra` doesn't depend on Hadoop so shouldn't be a problem?

**Comment by ravwojdyla** [comment]
Yea - was just wonder if someone adds hadoop deps - just a theoretical question.
