### ISSUE TITLE
Unsupported type: org.joda.time.DateTime @com.spotify.scio.bigquery.types.BigQueryTag

### ISSUE THREAD

**Issue by vertexclique** [spotify/scio#1104]
Even DateTime support merged, DateTime doesn't work with the latest version (0.5.2).

Getting the error like:
```
Unsupported type: org.joda.time.DateTime @com.spotify.scio.bigquery.types.BigQueryTag
[error]   @BigQueryType.toTable
```

and class is like that:
```scala
object BigQueryOutputs {
  @BigQueryType.toTable
  case class Data(
    submissionAt: DateTime,
  )
}
```

**Comment by nevillelyh** [comment]
@andrewsmartin wanna take a look?

**Comment by andrewsmartin** [comment]
@vertexclique so afaiu Joda's `DateTime` is an absolute point of time (i.e. has a timezone) which means it can easily be converted to `Instant`, which we use to map to BigQuery's `DateTime`. Would that work for you?

Maybe in the `BigQueryType.toTable` case we can do the `DateTime -> Instant` conversion within the macro - @nevillelyh what do you think?

**Comment by nevillelyh** [comment]
Actually we support `LocalDateTime` right? Is that sufficient?
Prefer not to open up new complexity.

**Comment by andrewsmartin** [comment]
Yeah either `LocalDateTime` or `Instant` should be sufficient depending on the use.

**Comment by andrewsmartin** [comment]
@vertexclique will close this for now - please reopen if you have any further issues.
