### ISSUE TITLE
beam-master update to beam 2.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1110]
Some changes to counters are required, some WIP is in #1102 , currently this is blocked on https://issues.apache.org/jira/browse/BEAM-4060, will wait for beam to fix instead of trying to work around this in scio repo.

**Comment by ghilios** [comment]
BEAM-4060 appears to be resolved. Is this unblocked now?

**Comment by nevillelyh** [comment]
Yes I hope so. Most of us are out this week. Will start working on 2.5.0 migration next week.

**Comment by nevillelyh** [comment]
Fixed in #1222.
