### ISSUE TITLE
Give better help, documentation and error messages for pipeline options

### ISSUE THREAD

**Issue by jto** [spotify/scio#1116]
Currently if we forget parameters when running a pipeline Scio just throws an exception.
For example:
```
Exception in thread "main" java.lang.IllegalArgumentException: Missing value for property 'textOutput'
at com.spotify.scio.Args.required(Args.scala:103)
at com.spotify.scio.Args.apply(Args.scala:86)
at com.spotify.data.goldenpath.TopTracksJob$.main(TopTracksJob.scala:43)
at com.spotify.data.goldenpath.TopTracksJob.main(TopTracksJob.scala)
```

`--help` is also not supported, and there's no way to interactively get documentation about the pipeline supported options (I'm thinking about both required and optional parameters).

It would be nice if a scio pipeline provided better errors and documentation about its options.

**Comment by nevillelyh** [comment]
Not sure what we can do with `--help` without changing the `Args` API, since we don't know what flags will be queried until runtime. Any ideas?

**Comment by jto** [comment]
scop has an API that is not that different. We may do something similar ?
`Args` could keep an internal state of all supported options and use it to generate a help text ?

**Comment by jto** [comment]
Hum so we do have to change the API since as you said help is impossible to implement in the current API. Most command parsing libraries un Scala are boilerplate heavy which I'm sure would raise a lot of complaints from our user. (see: [scoopt](https://github.com/scopt/scopt), [ciris](https://cir.is/docs/supported-sources), [scallop](https://github.com/scallop/scallop))

There's [case-app](https://github.com/alexarchambault/case-app) which is fairly close to Beam's PipelineOptions and even provides the [`CaseApp` trait](https://github.com/alexarchambault/case-app#whole-application-with-argument-parsing) which seems to be fairly strait-forward to use.

Do you think deprecating `Args` to improve help / error messages is worth it @nevillelyh ?

**Comment by jto** [comment]
Note that one added benefit would be to fail faster in pipelines like [this example](https://github.com/spotify/scio/blob/master/scio-examples/src/main/scala/com/spotify/scio/examples/extra/BeamExample.scala#L98) which are reading arguments at the very end.

**Comment by BenFradet** [comment]
It would be great if this was supported out of the box, here's what we're doing to circumvent the issue at the moment:

https://github.com/snowplow/snowplow/blob/0a1005181b4f86b44f7c9b24a7a741fdb19fe26f/3-enrich/beam-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.beam/config.scala#L45-L78

**Comment by nevillelyh** [comment]
@jto TBH don't think it'll benefit our internal use cases much since we don't often run scio jobs ad-hoc via command line but instead wrap them in luigi/flo. So once wired up one almost never worry about command line interfaces.

OTOH, is there a way to make `PipelineOptions` interface easier to use, so that we can tap into existing tooling? Some macro to convert case classes to `PipelineOptions`?

But TBH not sure if it's worth the extra work.

**Comment by jto** [comment]
`PipelineOptions` is really not scala-ish and working on a macro sounds like a hard to implement and brittle solution...
