### ISSUE TITLE
Investigate test unit test performances

### ISSUE THREAD

**Issue by jto** [spotify/scio#1123]
We could possibly make the execution of the test suite faster.
@nevillelyh suggest we have a look at `KryoRegistrarLoader` which may be a bottleneck.

**Comment by nevillelyh** [comment]
So `private val registrars: Seq[IKryoRegistrar]` takes 500-1000ms to initialize and happens a couple of times when running `sbt test`. We can probably shave a few seconds off the total run time but not sure that'll make a huge impact.

**Comment by mpasa** [comment]
Creating the test context for each test takes an average of **175ms**. Currently, this is executed **369 times** int a full `sbt test` (249s, 8 threads). It is a total of 64.6s (not sure if we can just divide that by 8 to get the "real" total time). Can we improve that? and is it worth it?

**Comment by mpasa** [comment]
I found out that **PairSCollectionCollection** `sampleByKey` tests both take almost a minute. Also, there are 70 tests that take more than a second. I'll try to investigate what's happening there.

**Comment by nevillelyh** [comment]
@mpasa great findings. Just realized that `ScioContext` checks for the latest Scio release on GitHub and the HTTP request is what caused this latency. I'll bypass this in tests.

**Comment by nevillelyh** [comment]
Most of the recent CI builds are ~10min, seem reasonable enough, closing?
