### ISSUE TITLE
Too many file descriptors potentially messing up sbt console

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1124]
Sometimes after running tests, the sbt console stop echoing back user input even though it's still running. We suspect `junit-interface` caused this and it might be fixable with some settings tweak.

**Comment by jto** [comment]
I'll have a look at this. I can reproduce it every time on my laptop.

**Comment by jto** [comment]
Seems to be caused by https://github.com/sbt/sbt/issues/937

**Comment by jto** [comment]
I tried to workaround the problem using `Tags.limit(Tags.Test, 2)`. Any value above 1 and the test hangs on my machine...

**Comment by jto** [comment]
Does not seem to happen anymore. Closing.
