### ISSUE TITLE
If annotating case classes using BigQueryType other macro annotations aren't preserved

### ISSUE THREAD

**Issue by jbigred1** [spotify/scio#1133]
In our investigations for adding a new macro annotation we encountered a Scio bug.  When a user adds a static macro annotation such as `@BigQueryType.toTable` we noticed that any other annotations are removed if they exist below this one.

An example is

```scala
@BigQueryType.toTable
@Test.myMacroAnnotation
case class TestClass
```

This will result in only the first macro being triggered with the second one being ignored.  This is because macros are processed in order.  Since the actual ordering matters and each successive static macro annotation can change the Abstract Syntax Tree if we leave any other static macro annotations from what is produced by a given macro the other ones are never triggered at all.

In our situation this is actually not that big of a deal.  We can require people to put our macro above `@BigQueryType.toTable` and everything still triggers as expected but this seems like a bug in Scio and could lead to user confusion at some point.

Full Example:

```scala
import scala.annotation.StaticAnnotation
  import scala.language.experimental.macros
  import scala.reflect.macros._

  def validateImpl(c: blackbox.Context)(annottees: c.Expr[Any]*): c.Expr[Any] = {
    println("Testing")
    annottees.head
  }
  class bigQueryTypeConstruct extends StaticAnnotation {
    def macroTransform(annottees: Any*): Any = macro validateImpl
  }

  @BigQueryType.toTable
  @bigQueryTypeConstruct
  case class TestNoPrint()

  @bigQueryTypeConstruct
  @BigQueryType.toTable
  case class TestPrints()
```

Note that testing only prints on the second example.

Set `sys.props("bigquery.types.debug") = "true"` in order to see the full case classes generated while macros expand.

**Comment by nevillelyh** [comment]
Why did you close this? No longer an issue?

**Comment by nevillelyh** [comment]
Duplicate of #1134
