### ISSUE TITLE
KryoException: java.lang.IndexOutOfBoundsException: Index: x, Size: y

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1136]
There has been at least two reports on this error on large "join" jobs, this error **seems** to be triggered on some data - at least in once case, a pipeline would run fine one day, but consistently fail on other day.

Contact: lanx, cpast

Job id example: 2018-04-24_07_44_16-11213165782653977475

**Comment by lxlxlxlx** [comment]
It sometimes fails with this similar but slightly error: 
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 120
