### ISSUE TITLE
JobTest only works with ContextAndArgs

### ISSUE THREAD

**Issue by nollbit** [spotify/scio#114]
It seems like testing with `JobTest` only works if the context in the tested class is created using `ContextAndArgs` (`testId` properly set in https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L59-L65)

If it's using any of the `ScioContext.apply()` initializers testId will always be None and the tests won't work (`testId` always None in https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L73-L83)

Is this by design or would you accept a PR to fix it?

**Comment by nevillelyh** [comment]
It's a case we haven't thought about it. What do you propose? Adding an optional `testId` arg to every `apply()` method?

**Comment by nevillelyh** [comment]
@nollbit anything thoughts?

**Comment by nevillelyh** [comment]
Fixed in #174
