### ISSUE TITLE
 $LATEST in @BigQueryType.fromQuery() macro does not work when tables are partitioned by hour

### ISSUE THREAD

**Issue by tfrojd** [spotify/scio#1149]
The use of  `$LATEST` in  `@BigQueryType.fromQuery()` macro does only work when tables are partitioned by day. If tables are partitioned by hours it does not work.

**Comment by tfrojd** [comment]
If I run the following Macro in a scio pipeline

´´´
  @BigQueryType.fromQuery(
    """
      |SELECT col1, col2
      |FROM `project.dataset.Table_%s`
    """.stripMargin, "$LATEST")
  class PresetActionEntity
´´´

It will compile if the tables are partitioned like  "Table_YYYYMMDD" but not when tables are partitioned like  "Table_YYYYMMDDHH"

**Comment by nevillelyh** [comment]
The partition ordering logic is here. Can you try to reproduce the issue using these methods?
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryPartitionUtil.scala#L57

**Comment by nevillelyh** [comment]
Tested that it works with `table_YYYYMMDDHH` format with the following snippet.

```scala
object Test {
  def main(args: Array[String]): Unit = {
    val bq = BigQueryClient.defaultInstance()
    val t = BigQueryPartitionUtil.latestTable(bq, "scio-playground:neville_eu.table_$LATEST")
    println(t)
  }
}
```

Given 3 tables in `neville_eu` dataset, `table_2018060100`, `table_2018060101` and `table_2018060102`, it correctly returns `table_2018060102`.

It does not work if the date/time string is not a number, i.e. `table_20180601T00`.
Gonna close this as a won't fix.
