### ISSUE TITLE
Add method to create BigQuery table

### ISSUE THREAD

**Issue by chuwy** [spotify/scio#1156]
Basically a wrapper for `bigquery.tables().insert()`. Or is there existing convenient method that I've missed?

**Comment by jto** [comment]
@nevillelyh I agree. Should we add a method in ScioContext to give access to the instance of `com.google.api.services.bigquery.Bigquery` that `BigQueryClient` is using ?

**Comment by chuwy** [comment]
Thanks guys! My initial problem was that I couldn't find a short enough snippet to create a table and at first ended up with something bloated to 15 lines of code. Right now though I've found out I can do just following:

```scala
val options = PipelineOptionsFactory.create().as(classOf[BigQueryOptions])
val service = new BigQueryServicesWrapper(options)
service.createTable(tableRef, schema)
```

Which is good enough for me. But I still think exposing `Bigquery` would be really useful as well.

**Comment by nevillelyh** [comment]
Well we monkey pathed `BigQueryServicesWrapper` to be public so that we can use it in Scio but it's not really intended as a public API. We can add a `BigQueryClient#createTable` method but shouldn't try to match Java API's functionality (hard with arg list vs builder).
