### ISSUE TITLE
scala BigDecimal serializer?

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#1170]
Scala's `BigDecimal` class has some stateful fields that get serialized with the Kryo-derived serializer, which breaks mutation detection checks in the direct runner. Should we register a custom serializer within Scio?

**Comment by nevillelyh** [comment]
Should we submit this to upstream chill?

**Comment by andrewsmartin** [comment]
Sure, I'll open a PR

**Comment by andrewsmartin** [comment]
Upstream pr: https://github.com/twitter/chill/pull/312
