### ISSUE TITLE
Clean up Kryo stuff

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#1172]
`KryoAtomicCoder` has blown up quite a bit with the addition of several custom serializers and could use a bit of clean up. 

- [ ] Move `KSerializer` classes into a subpackage, maybe `coders.serializers`
- [ ] Add a `ScioRegistrar` for our custom serializers and load in `KryoAtomicCoder` to get rid of the `k.forSubclass` bloat.

**Comment by anne-decusatis** [comment]
work in progress at https://github.com/spotify/scio/compare/master...anne-decusatis:clean_up_kryo
