### ISSUE TITLE
scio-tensorflow/zoltar dependency conflicts

### ISSUE THREAD

**Issue by regadas** [spotify/scio#1173]
zoltar seems to be using later versions of the google api's which breaks some of beam's functionality.

**Comment by andrewsmartin** [comment]
Hey @regadas I wonder if we can find another solution for this? https://github.com/spotify/scio/commit/e13b3579651c8eec346d71969e25922ccfe13cfa works within Scio, but users trying to upgrade to 0.5.5 and use `scio-tensorflow` would also have to add this override in their project. Does Zoltar need 1.23.0 or can it be downgraded?
