### ISSUE TITLE
Compress Parquet

### ISSUE THREAD

**Issue by joelostlund** [spotify/scio#1189]
I am trying to compress using the parquet implementation in Scio but nothing seems to happen. Tried adding both to core-site.xml and in code but none of them help.

```
<property>
    <name>parquet.compression</name>
    <value>org.apache.hadoop.io.compress.GzipCodec</value>
    <description>
    </description>
  </property>
```
`
ParquetOutputFormat.setCompression(Job.getInstance(), CompressionCodecName.GZIP)`

**Comment by nevillelyh** [comment]
Fixed in `nio` branch, will be available in 0.7.0 release.
