### ISSUE TITLE
Maybe add DatastoreClient?

### ISSUE THREAD

**Issue by oskoi** [spotify/scio#1203]
I ran into the need inside the job to make requests to Datastore, but api scio does not support this. What about adding a DatastoreClient by analogy with BigQueryClient/BigTableClient?

**Comment by regadas** [comment]
@oskoi if i understood you correctly you need to query datastore from a `DoFn` ... so something along the lines with [BigTableDoFn](https://github.com/spotify/scio/blob/master/scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableDoFn.java) but for datastore is what you need. No need for custom client.

For this we need to create a separate module for it `scio-datastore`. /cc @nevillelyh

**Comment by oskoi** [comment]
@regadas not sure. I have stateful `DoFn`. Here is a small example
```
...
applyTransform(ParDo.of(new DoFn[KV[String, Iterable[Event]], State] {
  @StateId("state")
  private[jobs] val stateSpec: StateSpec[ValueState[State]] =
    StateSpecs.value()

  @ProcessElement
  private[jobs] def processElement(c: DoFn[KV[String, Iterable[Event]], Result]#ProcessContext,
                                   @StateId("state") state: ValueState[State]): Unit =
    c.element().getValue.foreach {
      event =>
        val stateOpt = Option(state.read())
        val currentState = stateOpt.getOrElse {
          val query: Query[Entity] = //some query depending on the event

          val results = (datastore: DatastoreReader).run(query)
          if (results.hasNext) {
            val r = results.next()

            State(...) // state from Datastore
          } else {
            State(...) // empty State
          }
        }

        val nextState = currentState.copy(...)

        state.write(nextState)
        c.outputWithTimestamp(nextState, c.timestamp)
    }
}))
...
```

Now I'm using "com.google.cloud" % "google-cloud-datastore". I would like to have a typed wrapper as done for grpc api (https://github.com/nevillelyh/shapeless-datatype). 

Can `BigTableDoFn` make the stateful processing?

**Comment by regadas** [comment]
@oskoi oh i see! no `BigTableDoFn` is stateless.

Adding a custom client means that we need to keep up with changes on the underlying client and we want to avoid that unless there's a really good reason/implementation detail for it. This case seems more like a convenience where the advantages don't overcome the disadvantages.

wdyt @nevillelyh?

**Comment by nevillelyh** [comment]
I agree. Sounds like you want a light weight Scala wrapper for Datastore client? Feels like it's out of the scope of Scio but maybe worth having somewhere else.

**Comment by oskoi** [comment]
@nevillelyh 
yeah. As for me it would be useful to have this. 
I like the idea of @regadas to put it in a separate module

**Comment by nevillelyh** [comment]
Gonna close this as a won't fix since it feels out of scope. But if you create one in a separate project we're happy to link it here.
