### ISSUE TITLE
NIO branch breaking due to SampleOverrideTypeProvider

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1217]
After rebasing `nio` branch on top of master, BigQuery validation tests broke again due to `SampleOverrideTypeProvider` and compilation order.

My WIP attempt to fix this:
https://github.com/spotify/scio/tree/neville/nio

**Comment by jto** [comment]
Seems to work for me in https://github.com/spotify/scio/tree/julient/fix-SampleOverrideTypeProvider

**Comment by nevillelyh** [comment]
#1218 fixed compilation but it still fails in IntelliJ.
Maybe we can do something [here](https://github.com/spotify/scio/commit/6562d326aadcb1e94349c5350013d0005f31d332#diff-397ab6304a3ddd3dfc2cf84e9670dc98R28) to selectively load the `SampleOverrideTypeProvider`.

**Comment by nevillelyh** [comment]
Seems to be fixed after also fixing the `hamcrest-all` `mockito-all` conflict.
https://github.com/spotify/scio/commit/1ea674542002e070a3b2041f186cb7f2146bbe96
