### ISSUE TITLE
Cyclic dependency between scio and featran.

### ISSUE THREAD

**Issue by jto** [spotify/scio#1223]
`scio-tensorflow` depends on featran (and `scio-core`) and `featran-scio` depends on `scio-core`.
The cyclic dependency is a bit unfortunate.

**Comment by nevillelyh** [comment]
`featran-scio`'s dependency on `scio-core` is `"provided"`, so this shouldn't be a problem as long as the API is binary compatible?

**Comment by jbx** [comment]
@jto - we're leaning towards closing this one since it might not be a problem. What do you think?

**Comment by jto** [comment]
It's not a showstopper but it forces us to release scio and featran at the same time when a major version of scio is released. It also makes scio's test suite fail currently on the static coder branch. It'd be nice to fix it.
