### ISSUE TITLE
Scio-tensorflow PredictDoFn runs very slow because it uses AsyncDoFn

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1224]
Tensorflow saved model predict function uses JavaAsyncDoFn which creates a new Future for each input record. Since the model is evaluated locally and is probably CPU bound, this leads to very slow processing, and the step gets stuck in dataflow with no progress for a long time. 

Directly using DoFnWithResource (blocking inference) is much faster in some rough tests that I did.

Related issue: https://github.com/spotify/scio/issues/1161

**Comment by regadas** [comment]
I think I found the reason, there's a subtle bug in this is the implementation. The funny part is that the async is not the problem but rather the lack of it 😄 . Still, i'll need to benchmark it (#1161) to make sure it is ok.
