### ISSUE TITLE
Upgrade TensorFlow to 1.11.0

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#1242]
https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0

**Comment by nevillelyh** [comment]
Fixed in #1249

**Comment by jbx** [comment]
Blocked on https://github.com/tensorflow/tensorflow/issues/21284

**Comment by regadas** [comment]
Same issue happens with tensorflow 1.10.0. Also checked the dataflow container images and they also still use 'libc6 2.19'
