### ISSUE TITLE
QUESTION: BigTable increment

### ISSUE THREAD

**Issue by marrrcin** [spotify/scio#1247]
I have the following use case: there is a pubsub topic with data I want to aggregate using Scio and then save those aggregates into BigTable.
In my pipeline there is a _CountByKey_ aggregation. What I would like to do is to be able to **increment** value in BigTable for a given key, preferably using `ReadModifyWrite`. In the scio-examples there are only updates related to setting column values but there are none of using atomic increment.
How to do this using Scio / Apache Beam transform?

**Comment by nevillelyh** [comment]
I don't see anything like `ReadModifyWrite` under `com.google.bigtable.v2.Mutation` API so not sure if this is possible. I see 2 possible workarounds:
- save events as a Pubsub topic, consume it from a backend service and increment there
- use a raw Bigtable client in a custom `DoFn`, see `BigtableDoFn` for inspiration.
