### ISSUE TITLE
QUESTION: How to use SCollection in custom PTransform

### ISSUE THREAD

**Issue by marrrcin** [spotify/scio#1251]
I want to arrange my pipeline code into separate PTransforms, however I would like to use `SCollection` abstraction inside of the `PTransform`s `expand` methods. Can I pass `ScioContext` as a parameter and use `sc.wrap()` or is there another patter for obtaining this behaviour?

Is there any Scio equivalent of `PTransform` like `STransform`?

**Comment by marrrcin** [comment]
No, I'm looking for writing something the other way around:
I would like to have such `PTransform` implementation that would take `SCollection` as a parameter of `expand`, so that I could utilize all of the SCollection's methods. 

Optionally I could pass ScioContext into the constructor of my `PTransfrom` - is it safe to do so?

**Comment by nevillelyh** [comment]
Not really since `ScioContext` and `SCollection` are not serializable. Better break up your logic and keep the `PTransform` small.

**Comment by marrrcin** [comment]
So is there any way of obtaining `SCollection` abstraction inside of `PTransform`?

**Comment by nevillelyh** [comment]
No

**Comment by marrrcin** [comment]
OK, thanks. That would be a nice feature however. `SCollection` gives a lot of nice shorthand methods for data transformations.

**Comment by nevillelyh** [comment]
But it will make closure serialization a lot more complex and hard to reason about. Plus this can be worked around by decoupling pipeline logic. So IMO it's out of scope.
