### ISSUE TITLE
AsyncDoFn deadlock

### ISSUE THREAD

**Issue by welvet** [spotify/scio#1262]
We're using Dataflow to build our pipelines. Recently we had an incident with one of them.
Our Dataflow job stopped consuming messages and had 0 CPU load. 
We asked Google support to assist us and they pointed to a deadlock in `ScalaAsyncDoFn.waitForFutures` method call.
Even that `waitForFutures` deadlock was likely a result of our poorly written `processElement` there are still some concerns about `ScalaAsyncDoFn`.
Google pointed us that `DoFn`'s should be stateless and we should avoid adding threading, blocking, queues or pooling.
And I'm quoting the most interesting part of message in Google Case:

The DoFn should not depend on the state of others elements within the bundle. If the process of one element fails, dataflow may rebundle the elements into a different set, and the DoFn instance may be used on another set. The elements may be re-distributed to other bundles. Per the "No Global Shared State" section of the ParDo API documentation: "programs should not access any mutable static variable state in their DoFn, without understanding that the Java processes for the main program and workers will each have its own independent copy of such state"   
   
The normal recommended pattern of DoFn is as you suspected: "process messages synchronously during processElement invocation".  There can be exceptions, but I am not familiar with them or the rest of your application enough to recommend them at this time.  Here are some more guidelines from our team that I hope are helpful. 

1) There are no guarantees of how many times processElement() will be called between startBundle() and finishBundle(). There is no guarantee the number will stay the same if a bundle is re-tried.
2) Avoid adding threading, blocking, queues or pooling. Let Dataflow handle concurrency
3) Make sure processElement is thread-safe

I have links to internal incident ticket and Google Case but will not post them here.

**Comment by regadas** [comment]
@nevillelyh makes sense!

**Comment by nevillelyh** [comment]
Closing for now since it might be misuse of the API and the user has worked around it.
