### ISSUE TITLE
Move less common modules to scio-contrib

### ISSUE THREAD

**Issue by jbx** [spotify/scio#1266]
For things that are unofficially supported.

**Comment by jbx** [comment]
Review after 0.7.0 release

**Comment by nevillelyh** [comment]
For modules like: cassandra, elasticsearch, spanner, misc transforms, DoFns.

**Comment by nevillelyh** [comment]
- [ ] scio-cassandra2
- [ ] scio-cassandra3
- [ ] scio-elasticsearch2 (DEPRECATE)
- [ ] scio-elasticsearch3
- [ ] scio-jdbc
- [ ] scio-memorystore
- [ ] scio-parquet
- [ ] scio-spanner

**Comment by nevillelyh** [comment]
We decided to abandon `scio-contrib` and move everything back. Closing this.
