### ISSUE TITLE
Add streaming benchmark

### ISSUE THREAD

**Issue by regadas** [spotify/scio#1294]
Benchmark at least one long running streaming use case so we can possibly catch potential memory leaks.

**Comment by nevillelyh** [comment]
A few things we need to think about:
- How long is long enough? A day? A week?
- How often do we run this? Same interval as duration?
- What input? Real data, fake one published by a standalone app, or faked with `GenerateSequence`?
- How do we detect leaks, regressions, etc? Can't use `elapsed` if duration is fixed. Memory & CPU stats from DF?

**Comment by nevillelyh** [comment]
So we have the benchmark setup with 1 dummy job now https://github.com/spotify/scio/blob/master/scio-test/src/it/scala/com/spotify/ScioStreamingBenchmark.scala#L97

Should add more logic to cover some common operations and synthetic load to stress test the system?

**Comment by nevillelyh** [comment]
Fixed in #1353
