### ISSUE TITLE
BigQueryType.fromTableRow throws NPE without explanation for nullable fields without an Option

### ISSUE THREAD

**Issue by keithmcneill** [spotify/scio#1303]
When converting from a TableRow to a case class and if the TableRow is missing a field that isn't an Option type, fromTableRow will throw an NPE without any explanation. The Following shows the problem:

```
class MissingFieldTest extends PipelineSpec {

  case class Artist(artist: String, artist2: String)

  "FromJSon should work" should "work" in {
    val goodJson =
      """
        |{
        |    "artist" : "spotify:artist",
        |    "artist2" : "spotify:artist2"
        |}
      """.stripMargin

    val badJson =
      """
        |{
        |    "artist" : "spotify:artist"
        |}
      """.stripMargin

    val goodtr = new JacksonFactory().fromString(goodJson, classOf[TableRow])
    val goodartist: Artist = BigQueryType.fromTableRow[Artist](goodtr)

    val badtr = new JacksonFactory().fromString(badJson, classOf[TableRow])
    val artist: Artist = BigQueryType.fromTableRow[Artist](badtr)
  }
}
```

Gives an exception like:
```
java.lang.NullPointerException
    at com.spotify.MissingVectorTest$$anonfun$1$$anonfun$3.apply(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1$$anonfun$3.apply(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1.apply$mcV$sp(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1.apply(MissingFieldTest.scala:16)
    at com.spotify.MissingVectorTest$$anonfun$1.apply(MissingFieldTest.scala:16)
    ....
```

An error message beyond an NPE would be nice, since it is kinda hard to figure out what is going on.

**Comment by keithmcneill** [comment]
To avoid a lot if !null checks for each and every field in each and every row that passes through the code you could wrap the serialization of all the fields in 1 big try/catch(NPE) and only run through the null checks if the NPE fires.  

Kinda seems like pre-mature optimization, but that is a lot of fields within a lot of rows over time.

**Comment by nevillelyh** [comment]
But then we won't be able to distinguish NPEs caused by null fields or other genuine bugs in the code. Also stacktrace won't pinpoint exact location of the generated code so we won't know which field caused the NPE, kinda defeats the purpose.

We can try adding the check & message at the leaf level and micro-benchmark first.
