### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1305]
There're quite a lot lately, some from deprecated Beam APIs and some from scala/java compiler.

**Comment by nevillelyh** [comment]
@mpasa thanks! I fixed the bigtable ones already in `nio` branch (targeted for 0.7.0). Don't want them in `master` right now since it'll be a pain to rebase.

**Comment by mpasa** [comment]
I've been checking the `AvroIO.to` to `FileIO.write` (`com.spotify.scio.io.dynamic`) but I'm not sure how to entirely replace it.

- We cannot use the `DynamicAvroDestinations` anymore, so we'd need to simulate it with `FileIO.write` methods. That includes the destination function, default destination and the filename policy. 
- We can define a destination function with `FileIO.write().by(...)`
- `FilenamePolicy` seems that can be replaced with `FileIO.write().withNaming`
- `FileIO.Write` seems to not accept windowed writes. 

Anyone with more knowledge of the `FileIO` API can confirm this?

**Comment by nevillelyh** [comment]
Fixed most warnings in `v0.7` branch.
Most of the remaining ones are due to `DoFnTester` being deprecated. https://issues.apache.org/jira/browse/BEAM-3159

**Comment by nevillelyh** [comment]
Fixed most `DoFnTester` usages except scio-test/src/test/scala/com/spotify/scio/util/random/RandomSamplerTest.scala which relies on its determinism.
