### ISSUE TITLE
remove TensorFlow Graph model prediction

### ISSUE THREAD

**Issue by regadas** [spotify/scio#1309]
@ravwojdyla @yonromai @nevillelyh 

should we remove this as part of `0.6.0`?

https://github.com/spotify/scio/blob/7e97fa3b631b3962f3eee7dc3cbc8f468dc8081c/scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala#L204-L208

**Comment by ravwojdyla** [comment]
I was thinking - maybe not yet, ppl might still produce frozen TF graphs. How about we first remove it from sptf (upcoming release), and maybe in the future release remove from scio? What do you think?
