### ISSUE TITLE
saveAsJdbc does not have a way to configure the batch size

### ISSUE THREAD

**Issue by ccarpita** [spotify/scio#1311]
Configuring the batch size for streaming inserts can be a potentially useful strategy for managing deadlock frequency at the expense of insert performance.

Current snippet of code in scio-jdbc:
```scala
var transform = jio.JdbcIO.write[T]()
          .withDataSourceConfiguration(getDataSourceConfig(writeOptions.connectionOptions))
          .withStatement(writeOptions.statement)
```

Proposed feature change:
```scala
var transform = jio.JdbcIO.write[T]()
          .withDataSourceConfiguration(getDataSourceConfig(writeOptions.connectionOptions))
          .withStatement(writeOptions.statement)
          .withBatchSize(writeOptions.batchSize)
```

This would require a batchSize option on writeOptions as well, perhaps `Option[Int]: None`.

**Comment by syodage** [comment]
Fixed with https://github.com/spotify/scio/pull/1314
