### ISSUE TITLE
Deadlocks frequently happen with Scio JDBC insert + multiple workers

### ISSUE THREAD

**Issue by ccarpita** [spotify/scio#1312]
Repro steps:

1. Create a test database with a schema that has a primary key including multiple fields.
2. Create a job which writes 1M+ records to the table, randomly generated
3. Launch the batch job with 3+ workers that continuously write data

**Comment by regadas** [comment]
@syodage can you take a look at this?

**Comment by ccarpita** [comment]
I'm going to close this, as I believe our particular use case was caused by having a backed up streaming queue interfering with backfills, coupled with a large insert batch size. I think being able to configure the batch size would be very helpful for teams with multiple writers, though.
