### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1316]
We have a lot of import aliasing like `import org.apache.beam.sdk.{io => gio}` dating back from the Google Cloud Dataflow SDK era. Most of these are no longer needed after the NIO refactoring and just confusing and inconsistent.

**Comment by mpasa** [comment]
Should they be removed in the nio branch or can this be done in the master branch?

**Comment by nevillelyh** [comment]
This should wait till NIO branch work is done and merged back to master. We're going through a lot of refectoring in that branch right now.

**Comment by nevillelyh** [comment]
Fixed in NIO/v0.7 branch
