### ISSUE TITLE
After upgrading from scio 0.4.7 to 0.5.7, PCollections "both have unique_name" error

### ISSUE THREAD

**Issue by mirascarvalone** [spotify/scio#1323]
After upgrading from Scio 0.4.7 to 0.5.7, several dataflow jobs are unable to start due to an error of the form 

```INFO: Exception in thread "main" java.lang.IllegalArgumentException: pipeline: PCollections [GCS Path]/part-*1 and [GCS Path]/part-* both have unique_name "[GCS Path]/part-*"```

**Comment by nevillelyh** [comment]
The error was thrown from https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/PipelineValidator.java#L129
