### ISSUE TITLE
How to pass GCP credentials

### ISSUE THREAD

**Issue by epifab** [spotify/scio#1335]
Hello,
I'm very new to Scio, I'm trying to read from a pub/sub topic.
Of course, I keep getting a 403 error, and I couldn't figure out a way to pass my GCP credentials unless I have `gcloud` installed.
Am I missing something?

**Comment by nevillelyh** [comment]
Try setting `GOOGLE_APPLICATION_CREDENTIALS`? For more details see:

https://github.com/spotify/scio/wiki/FAQ#how-do-i-fix-invalid-default-bigquery-credentials

**Comment by epifab** [comment]
it seems to me that those credentials have to be stored in a file? is there any way to build them from environment variable? (`GOOGLE_APPLICATION_CREDENTIALS` have to point to a file...)

**Comment by nevillelyh** [comment]
Don't think so. But it's best to consult Google docs?

**Comment by epifab** [comment]
the trouble is that I want to deploy my dataflow job from CI, and I can't have a file with credentials hanging around for security reason. I could find a workaround with python in the past, so I suspect there is a way of doing this.. will investigate more

**Comment by nevillelyh** [comment]
Use a wrapper script to write the file and delete afterwards (may not be needed if CI destroys the environment)? That's what we do with CI.
Gonna close this. Feel free to update if you make any progress :)
