### ISSUE TITLE
Kryo serializers {JodaLocalDateTimeSerializer, JodaLocalTimeSerializer } made private.

### ISSUE THREAD

**Issue by ra1861** [spotify/scio#1341]
Hi,

It was done in this commit:
https://github.com/spotify/scio/commit/01811c5ddc99b33819d9e1892c3eb5340c527571

We are using these classes {JodaLocalDateTimeSerializer, JodaLocalDateSerializer} in our code.
I have not found any Release notes about the change.

Can you provide any motivation behind the change and potential workaround.

Thanks, Ruslan

**Comment by nevillelyh** [comment]
These are sort of internal API and should not be used directly by end users.
We can revert this but would be nice to understand how you're using them @ra1861?

**Comment by nevillelyh** [comment]
We already register these serializers [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala#L107) so you shouldn't have to do it in your code? @ra1861

**Comment by jto** [comment]
I think the problem appears when people are migrating from older Scio versions (`0.4.smth`) to a newer version. At some point `JodaLocalDateTimeSerializer` and `JodaLocalTimeSerializer` needed to be registered explicitly.

It's not necessary anymore since as @nevillelyh pointed out Scio does it automatically now.

I think we can close the issue.

**Comment by ra1861** [comment]
Yes, we are migrating from 0.4.x.
I see now that scio registers these serializers, so we don't need to (https://github.com/spotify/scio/blob/e1fe564f43e4ef55bcefc8fdf0a779b5fb7434b6/scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala#L109-L110).
Thanks.

**Comment by ra1861** [comment]
Actually, I was too quick.
Now our unit-tests are failing with:
```
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: org.joda.time.LocalDate
[info] Note: To register this class use: kryo.register(org.joda.time.LocalDate.class);
[info] Serialization trace:
```
I cannot find any related docs which says you need to do anything special about scio context and  Kryo serialization set-up for tests specifically.

**Comment by regadas** [comment]
@ra1861 can you provide a failing job example?

**Comment by nevillelyh** [comment]
Looks like we're using `forSubclass` which calls `Kryo#addDefaultSerializer` instead of `forClass` which calls `Kryo#register` for `joda-time` types. Should be OK to change since people almost never extend those types?
