### ISSUE TITLE
saveAsBigQuery with a custom retry policy

### ISSUE THREAD

**Issue by epifab** [spotify/scio#1342]
`saveAsBigQuery` is great, but it doesn't allow you to specify a custom `InsertRetryPolicy`

**Comment by nevillelyh** [comment]
Can you use [`customOutput`](https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-beams-java-api-in-scio) for this particular case? We're not aiming to wrap 100% Beam functionalities, especially those less commonly used or hard to wrap with idiomatic scala.

**Comment by epifab** [comment]
`customOutput` works fine, although not ideal. I'd have loved to experiment with `TypedBigQuery` for example. Another interesting thing is that the insert retry policy becomes vital when you run a pipeline on DataFlow for example, as the default policy there would be to retry failures forever

**Comment by nevillelyh** [comment]
What failures are you experiencing? We rarely hear anything like that from our internal jobs.

**Comment by epifab** [comment]
For example, if the json structure does not match what bigquery expect, then we see an error log in dataflow and the message from pubsub seems not to be acknowledged. The same message will be tried again and again

**Comment by nevillelyh** [comment]
Shouldn't be a problem if you use type safe API though?

**Comment by epifab** [comment]
How would I be 100% sure and at compile time that my `TableRow` objects are compatible with the BigQuery table I'm attempting to write to?

**Comment by nevillelyh** [comment]
You can't, that's why the type safe API exists in the first place.

**Comment by nevillelyh** [comment]
Gonna close this for now. Don't think we should make it easier to drop bad records instead of encouraging users to build more defensive code. Plus you can always work around it with a custom output.

**Comment by epifab** [comment]
To clarify, by "type safe API" you mean `TypedBigQuery`?

**Comment by nevillelyh** [comment]
Yes. Majority of our pipelines use the type safe API so we almost never get insert failures due to bad records.

**Comment by epifab** [comment]
I see. Well that's a good input. I'm very new to Scio but the typed API looks very promising. I'll have a closer look, thanks!
