### ISSUE TITLE
Pubsub to GCS windowed writes

### ISSUE THREAD

**Issue by pariksheet** [spotify/scio#1343]
Hello team,
I am trying to consume messages from pubsub and write into hourly directory in GCS.

How do I avoid the additional groupby which is hampering performance drastically?

Do you have any reference example for my use case, I guess this is fairly common.

Thanks in advance.

Regards,
Pari

**Comment by nevillelyh** [comment]
Are you using one of the file based sinks with dynamic destination? Seems like a question more appropriate for the Dataflow team?

**Comment by pariksheet** [comment]
Hi Neville, Thanks for your response.

I first tried with WindowFilenamePolicy,
-                       window.apply("Write",
-                                       AvroIO.write(JAVA.class).withWindowedWrites().withNumShards(options.getNumShards())
-                                                       .to(new WindowedFilenamePolicy(options.getOutput().get(), options.getTopic())).withTempDirectory(
-                                                                       FileBasedSink.convertToFileResourceIfPossible(options.getOutput().get())));
-               }

I understood from the forum that above code uses additional groupBy.

So I tried with 
+               window.apply("Write", FileIO.<JAVACLASS, JAVACLASS>writeDynamic()
+                               .via(AvroIO.sink(JAVA.class))
+                               .by(JAVACLASS::getInstance)
+                               .withDestinationCoder(AvroCoder.of(JAVA.class))
+                               .to(options.getOutput())
+                               .withNumShards(options.getNumShards())
+                               .withNaming(key -> FileIO.Write.defaultNaming(Long.toString(key.getTime_dimension()), ".avro"))
+                               );

It did not help much.

As spotify uses pubsub/gcp heavily, I though I could get most feasible answer.

I will post my question in stackoverflow as well.

Thanks,
Pari

**Comment by nevillelyh** [comment]
This seems like a question for Beam/FileIO authors. Closing for now. Feel free to update if you find a solution.
