### ISSUE TITLE
Create BQ tables for data-integration-test in IT

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1369]
Right now they are created manually. We should run it in `beforeAll` in the same test. Need to figure out compilation order though.

**Comment by ClaireMcGinty** [comment]
some scope expansion related to bigquery IT:

- [ standardize on EU location for BQ reads + temp tables ]
- [ port bigquery IO tests from scio-core to scio-bigquery? ]
- [ test fixture to copy over `bigquery-public-data` dataset (which is in US datacenter) to `data-integration` project in EU ]

**Comment by ClaireMcGinty** [comment]
it's easier to just override retention policy directly in BQ so our test fixtures never expire. closing this ticket for now.
