### ISSUE TITLE
Code managing best practices

### ISSUE THREAD

**Issue by marrrcin** [spotify/scio#1409]
It would be nice if there was a piece of documentation explaining what are the best practices of decoupling the code when using Scio. 

As for plain Apache Beam, it's fairly easy to have clean project structure with separate transforms (PTransforms) in different files. Moreover, those PTransforms are then are squashed in DataFlow UI, so the internal transforms are enclosed. Writing pipelines in Scio has great productivity impact thanks to lots of built in helpers/transforms based on SCollection, but it quickly becomes hard to manage, as only thing (as per my knowledge) you can do is to refactor parts of the pipeline into methods inside the main class. 

I have a few parts in my code, that generate multiple pipeline branches in loops and because of the inability to use PTransform alongside the SCollection (https://github.com/spotify/scio/issues/1251), looking at the pipeline in DataFlow UI is cumbersome.

How do you manage big pipelines at Spotify? Could you provide some guidelines for that?

**Comment by nevillelyh** [comment]
You can refactor reusable transforms into methods in other objects in separate files. Not supporting composite transform is intentionally to prevent end users from having to deal with complex serialization issues. Also this way anything visible from the UI without expanding boxes is user code and anything inside a composite is library code.
