### ISSUE TITLE
Add doc page that covers app packaging

### ISSUE THREAD

**Issue by jto** [spotify/scio#1420]
https://github.com/spotify/scio/wiki/Getting-Started says nothing about packaging and deploying a job. It should provide an complete guide going from bootstrapping a project, to running it in production.

**Comment by marrrcin** [comment]
https://github.com/spotify/scio/wiki/FAQ#how-do-i-deploy-scio-jobs-to-dataflow

**Comment by nevillelyh** [comment]
The FAQ item looks good enough, closing.
