### ISSUE TITLE
hadoopDistCache should bypass GCS in DirectRunner?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#143]
Right now it requires `stagingLocation` to be set and copies HDFS file to GCS before pulling it.
https://github.com/spotify/scio/blob/0c90f00a2507cf5c184f1bc6f1941a43836af3bf/scio-hdfs/src/main/scala/com/spotify/scio/hdfs/package.scala#L128

Maybe it should skip that and pull from HDFS directly if `stagingLocation` is not available, or if it's running in local mode?

**Comment by andrewsmartin** [comment]
Closed via c08495b
