### ISSUE TITLE
Option to set streaming inserts for saveAsTypedBigQuery

### ISSUE THREAD

**Issue by brabster** [spotify/scio#1448]
I can't see any way to enable streaming inserts for bigquery without falling back to a custom output and losing the neat type safety features in the `saveAsBigQuery` method on `SCollection`.

I think it'd be neat to have an option to set the insert mode. If I've missed something, then an example on the Wiki would be helpful.

**Comment by regadas** [comment]
@brabster right now if your `input` is unbounded `saveAsBigquery` should be doing streaming inserts.
```
/**
 * The default behavior if no method is explicitly set. If the input is bounded, then file
 * loads will be used. If the input is unbounded, then streaming inserts will be used.
 */
```
However, if you need to customize `InsertRetryPolicy` ... then you need to use `customIO` right now.

**Comment by brabster** [comment]
OK cool thanks @regadas, where was that documented? I missed it completely!

I also think a custom IO with BigQuery example would be useful, particularly if you can use the type-safe generated stuff with it, as I couldn't work out how to yesterday.

**Comment by ClaireMcGinty** [comment]
@brabster it's documented in the underlying Beam IO implementation: [BigQueryIO.java](https://github.com/apache/beam/blob/89e322198828702db239998d6dd29a574fe04898/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java#L1078)

We can work on adding an example for custom BQ IO :)

**Comment by ClaireMcGinty** [comment]
@brabster I added an example to our BigQuery wiki: https://github.com/spotify/scio/wiki/Type-Safe-BigQuery

hope that helps!

**Comment by brabster** [comment]
Thanks, that would have saved me time!
