### ISSUE TITLE
Pipeline test will fail if one uses beam FileSystems and GCS bucket.

### ISSUE THREAD

**Issue by BartoszJanota** [spotify/scio#1455]
According to https://github.com/spotify/scio/wiki/FAQ#how-do-i-access-various-files-outside-of-a-sciocontext one should use `FileSystems` in order to access files outside of ScioContext.

This works in `scio-repl`:

```
scio> import org.apache.beam.sdk.io.FileSystems
import org.apache.beam.sdk.io.FileSystems

scio> val fs = FileSystems.matchNewResource("gs://some-bucket/file", false)
fs: org.apache.beam.sdk.io.fs.ResourceId = gs://some-bucket/file

scio>
```

this will also work in a normal pipeline run, but it will not work in a any local test run (using `PipelineSpec`) to test the pipeline.

If one uses `FileSystems.matchNewResource("gs://some-bucket/file", false)` in a pipeline, during the tests it will throw: 

```
java.lang.IllegalArgumentException: No filesystem found for scheme gs
	at org.apache.beam.sdk.io.FileSystems.getFileSystemInternal(FileSystems.java:459)
	at org.apache.beam.sdk.io.FileSystems.matchNewResource(FileSystems.java:529)
        ...
```

Quick fix:

One needs to use `FileSystems.setDefaultPipelineOptions(PipelineOptionsFactory.create)` before trying to reach a resource with `FileSystems`.

Side note: method `matchNewResource` from `FileSystems` takes two parameters, whereas the linked Scio documentation has an example with only one.

**Comment by ClaireMcGinty** [comment]
Looking at the Beam code, they manually set `FileSystems.setDefaultPipelineOptions(PipelineOptionsFactory.create)` in their [pipeline test framework](https://github.com/apache/beam/blob/4a92d28967a1c3fbe4719d8599bdde7b9ff2e31f/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java#L463) so I think it's reasonable for us to set it in ours, i.e. when initializing `ScioContext` in the test context.

**Comment by GabrielC101** [comment]
I've been running into this problem outside the context of Testing. This solution was extremely helpful.
