### ISSUE TITLE
For Bigtable, scio should discourage using BigtableIO from the dataflow sdk

### ISSUE THREAD

**Issue by rgruener** [spotify/scio#146]
To read/write to Bigtable, there are currently 2 APIs within scio.

For writing you can use [saveAsBigtable from scio-core](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L923) which uses BigtableIO pulled in from the dataflow sdk. This has been labeled the v2 Bigtable API within the scio-examples. You can also use [saveAsBigtable from scio-bigtable](https://github.com/spotify/scio/blob/master/scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala#L92) which comes from bigtable-hbase-dataflow and is labeled the v1 Bigtable API.

Currently the implementation from within the dataflow SDK is highly suboptimal to the bigtable-hbase-dataflow one which has batching of writes across rows, retries on failed writes, and is actually supported by the Bigtable team as opposed to the dataflow SDK which is supported by the dataflow team.

Scio seems to encourage using the dataflow API (hence labeling it v2) which should not be the case for now. I would actually recommend removing the bigtable v2 api from Scio to force users to use the scio-bigtable package. Using it can result in rather huge performance improvements (several orders of magnitude in some cases) so I think the api breaking change is worthwhile.

In the longer term, the features included in the hbase dataflow connector will be moved to within the dataflow sdk (once the dependency on hbase can be removed) but until then Scio should stick to the v1 api. This relates to https://github.com/spotify/scio/issues/127

Thoughts? @nevillelyh @ravwojdyla

**Comment by nevillelyh** [comment]
Removed in #149
