### ISSUE TITLE
[scio-tensorflow] Inferred schema not compatible with tf.data_validation inferred schema

### ISSUE THREAD

**Issue by martinbomio** [spotify/scio#1485]
Scio's `_inferred_schema.pb` does not follow the same semantics as the schema file inferred by tensorflow's data_validation for the same dataset.

Data validation schema is created with:
```python
    import tensorflow_data_validation as tfdv

    train_stats = tfdv.generate_statistics_from_tfrecord(....)
    train_schema = tfdv.infer_schema(train_stats)
```

Scio inferred schema looks something like this:
```feature {
  name: "someLongVector"
  value_count {
    min: 0
    max: 33
  }
  type: INT
  presence {
    min_fraction: 1
    min_count: 1503058
  }
}
feature {
  name: "someLongScalar"
  type: INT
  presence {
    min_fraction: 1
    min_count: 1503058
  }
  shape {
  }
}
```

and tf.data_validation one looks something like this:
```feature {
  name: "someLongVector"
  value_count {
    min: 1
  }
  type: INT
  presence {
    min_count: 1
  }
}
feature {
  name: "someLongScalar"
  type: INT
  presence {
    min_fraction: 1
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
```

this is the case class definition of the dataset that is used to create the tf records:
```scala
case class Features(someLongVector: List[Long], someLongScalar: Option[Long])
```

**Comment by andrewsmartin** [comment]
Thanks for reporting @martinbomio! Figured this might be the case. We've been discussing internally if it makes sense to deprecate this now that TFDV is available. It's probably best for Scio to just worry about TF record I/O and let TFDV do the `Schema` inference (maybe from Luigi?).

**Comment by andrewsmartin** [comment]
The difference with some of these numbers does seem worth looking into though.

**Comment by martinbomio** [comment]
@andrewsmartin I agree, specially since there's a way to get the `feature_spec` from the inferred schema from tensorflow. Might be better to not mess with that.

About the numbers created by tf.data_validation, I am still not sure if I understand what they represent, need to look at how they are generated.

**Comment by brianmartin** [comment]
Given input here as well as some more discussion internally, it makes sense to deprecate (and eventually remove) the schema functionality entirely. This is in favor of using `tf.data_validation`, as it will be most actively maintained.

We're targeting deprecation for the 0.7.x release.

cc @regadas @yonromai

**Comment by regadas** [comment]
Closing this since we will deprecate schema inference.
