### ISSUE TITLE
Support type safe arguments in `JobTest`

### ISSUE THREAD

**Issue by jto** [spotify/scio#1567]
Given that scio now supports [type safe arguments](https://github.com/spotify/scio/blob/master/scio-examples/src/main/scala/com/spotify/scio/examples/MinimalWordCountTypedArguments.scala#L36-L41), we could also support them in `JobTest`.

So instead of writing:

```scala
JobTest[com.spotify.scio.examples.WordCount.type]
      .args("--input=in.txt", "--output=out.txt")
// ...
```

one could use:

```scala
JobTest[com.spotify.scio.examples.WordCount.type]
      .args(JobTest.Arguments(
          input = "in.txt",
          output = "out.txt"
      ))
// ...
```

**Comment by nevillelyh** [comment]
@jto same question, still worth pursuing?
