### ISSUE TITLE
Support numeric type in BigQuery macro

### ISSUE THREAD

**Issue by regadas** [spotify/scio#1573]
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric-type

**Comment by ClaireMcGinty** [comment]
cc @lazyval (I'm not able to actually assign you to the issue, I think you can add yourself?)

**Comment by lazyval** [comment]
@ClaireMcGinty nope, can't assign myself :-(

**Comment by regadas** [comment]
Closed via #1599
