### ISSUE TITLE
Generic schema from Coder

### ISSUE THREAD

**Issue by mpasa** [spotify/scio#1590]
I'm opening this issue to discuss a possible feature. Please feel free to close it if this has already been discussed or I'm wrong with something basic.

Since version 0.7, Scio have type-safe coders, including its derivation from case classes. This gives us more freedom to do things at compile time. 

## Current problems with different IO
Currently, we use different ways to achieve similar actions with different IO sources:

- Writing to BigQuery requires a case class annotated with `@BigQueryType.toTable`.
- Writing parquet using `saveAsParquetAvroFile` expects a `SCollection` of Avro records and a schema (if we're using `GenericRecord`).

## The idea
Let the coder derive its own schema. It would be something similar to how Spark encoders work. That way, we could write both to parquet (deriving generic records and their schema directly) or BigQuery using the same information derived from the case class in compile time.

## Problems
- It only works for a very limited subset of coders. Spark currently limits encoders to case classes and a limited number of types.
- Some types of the schema could not be supported by different IO sources. For example, complex structures like lists or maps.  

What do you think?

**Comment by jto** [comment]
related: https://github.com/spotify/scio/issues/1177

**Comment by mpasa** [comment]
Thanks Julien. After reading the other issue, I think that what I'm saying here would be solved using an implicit `SchemaCoder` instead of a normal `Coder`. The BigQuery or Avro schemas can be built from the Beam schema provided by the coder.

You can close the issue if you want, and we can continue the discussion in the other issue. I will open a new one to add support to some functions using `SchemaCoder` if it's available in the future.

**Comment by regadas** [comment]
Let's close this. Thx for raising this @mpasa 👍
