### ISSUE TITLE
Possibility to use @BigQueryType.fromTable and @AvroType.toSchema together

### ISSUE THREAD

**Issue by mpasa** [spotify/scio#1595]
Imagine that you want to read data from BigQuery and export it to Avro without knowing the schema beforehand. Something like this:

```scala
@BigQueryType.fromTable("project:dataset.table")
@AvroType.toSchema
class Foo

sc
  .typedBigQuery[Foo]()
  .saveAsTypedAvroFile("gs://...")
```
1. We first generate a case class with the schema from Big Query
2. Then, we generate the Avro schema from the case class

This is currently not possible as `@BigQueryType.fromTable` macro checks that the class has no flags. The main problem of concatenating the macros (aside from the implementation) is that both of them generate a companion object with a `schema` of different types, so they would be overriding each other.

Do we currently have another way of achieving the same behaviour? maybe using two different classes?

**Comment by regadas** [comment]
Hi @mpasa!

Correct! currently it's not possible. The way to do it is to create 2 different `class`'s and then add a map function to convert the types.

```scala
@BigQueryType.fromTable("project:dataset.table")
class BQFoo

@AvroType.toSchema
class AvroFoo
```

**Comment by mpasa** [comment]
```scala
@AvroType.toSchema
class AvroFoo
```

Currently, this won't work, as the macro expects a case class with the schema known beforehand. I think this could be interesting, but I don't know if you want to touch the macros before having #1177 solved, which would make this more or less trivial.

**Comment by regadas** [comment]
@mpasa yup in the current available `AvroType` macros you need to either provide the schema using for example `@AvroType.fromSchema` or it can be inferred from the case class args `@AvroType.toSchema`. I updated the example coz it was wrong 😄 

Yeah, we don't intend to change this before #1177.

**Comment by mpasa** [comment]
Thanks @regadas. You can close this issue if you want then.

**Comment by regadas** [comment]
👍 Yeah we can reopen this or reference this in a later stage.
