### ISSUE TITLE
ScioContext.close() swallows pipeline errors

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#1617]
I had a scio job running on SparkRunner which was failing on driver code during the resolution of splits to read. But I did not find out the reason until I replaced `sc.close()` with calling directly Beam code.

Looks like context is calling result's `waitUntilDone()` here
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L498
which does `Await.ready(finalState, duration)` but if the future fails with error, only status is reported back but not the actual cause with stack trace.

**Comment by JozoVilcek** [comment]
I believe `pipeline.run()` is always non-blocking. Indicated also by existence of `PipelineResult.waitUntilFinish()` method. My job is blocking as it correctly reports FAILED state.

**Comment by JozoVilcek** [comment]
Hm, it seems that in case of `SparkRunner` it's `result.waitUntilFinish()` can throw exception while it should only report back state. I guess it make sense to open this on Beam's SparkRunner instead of Scio

**Comment by JozoVilcek** [comment]
Asked for opinion on Beam side as well
https://issues.apache.org/jira/browse/BEAM-6484

**Comment by regadas** [comment]
Yup, this is indeed a Beam related issue.
