### ISSUE TITLE
Avoid using ExecutionContext.Implicits.global in ContextScioResult

### ISSUE THREAD

**Issue by pishen** [spotify/scio#1624]
According to [this line](https://github.com/spotify/scio/blob/v0.7.0/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L507), Scio is using `ExecutionContext.Implicits.global` when running the Future `f` on next line, which wraps a blocking call `internal.waitUntilFinish()`. This may starve the global execution context since `ExecutionContext.Implicits.global` only contains limited and uncustomizable number of threads.

Would it be possible to make the ExecutionContext into an implicit parameter and let users decide what ExecutionContext they want to use?

**Comment by regadas** [comment]
Hi @pishen, interesting that you brought this up. i would say that unless you are starting/managing N jobs from the same pool, you are unlikely to hit the starvation point. 

However, I do agree that this is not really ideal/elegant and we probably should allow for that possible use case.

**Comment by pishen** [comment]
@regadas We are managing multiple Scio jobs through an Akka-HTTP server, that's why I found this problem.

**Comment by regadas** [comment]
@pishen That's what i thought 😄 I'm looking into it! Thanks for reporting this!

**Comment by regadas** [comment]
Closing this, since it's addressed by #1666
