### ISSUE TITLE
ScioIO write's Future[]

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#1628]
Hello, I have a question regarding ScioIO. I am writing custom one and wonder what should I return from write() method as Future[T]. Native scio IOs are calling `makeFuture()` on `ScioContext` which claims it will be completed when pipeline ends. E.g.
https://github.com/spotify/scio/blob/master/scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala#L262
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L549
However, this is private to scio package.

Any API guidance on what IOs outside of scio should do? I think if would be nice to have support around pipeline lifecycle (this time, about pipeline being finished) from Scio.

**Comment by ClaireMcGinty** [comment]
Hi, thanks for bringing this up!

First, I would note that `ScioIO`'s `write()` method returns not just a `Future[T]` but a `Future[Tap[T]]`. `Tap`s represent fixed, external datasets that can be materialized into an `SCollection` or in-memory iterator. So, the `Future` returned by `write()` doesn't reflect the status of the actual write operation, but rather the status of the `Tap` opening operation. Several of our `ScioIO` implementations do not meet this criteria, for example DB writes like JDBC, BigTable or Spanner, which return [`EmptyTap`](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/io/Tap.scala#L63). So first I would check whether your IO implementation represents a fixed or transient dataset, and then whether your use case really needs a `Tap` (most don't - [here's an example](https://github.com/spotify/scio/blob/master/scio-examples/src/main/scala/com/spotify/scio/examples/extra/TapExample.scala) of `Tap` usage. In this case they block on the `Tap` future before opening it into an SCollection.).

Second, related to support around pipeline lifecycle, I do see your point, not all of our design choices around `ScioIO` were made with custom `ScioIOs` in mind, and we try not to make public methods that directly modify pipeline state. As an end user though, if your Scio job is using the materialization of the `Tap`, you'll effectively have the same behavior as `makeFuture()` (the job will fail to complete if the `Tap` future fails).

I hope that's helpful :)

**Comment by regadas** [comment]
just an FYI that the return type in `Tap`'s will change in the next version. It will simply things a little bit.
