### ISSUE TITLE
Some anchor links in spotify.github.io site are broken

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#1637]
i.e.: https://spotify.github.io/scio/FAQ.html#how-do-i-use-the-snapshot-builds-of-scio does not link to that specific answer. If you inspect the code in chrome, it looks like Paradox is replacing any non-`\w` character in headers with a `-` when generating anchor IDs. So "How do I use the snapshot builds of Scio?" generates the anchor ID `#how-do-i-use-the-snapshot-builds-of-scio-`.

**Comment by regadas** [comment]
@ClaireMcGinty yeah ... so i guess right now we can just go ahead and add `-` on all of them 😄 there are a couple other examples where we do that already ... so i guess it's fine

**Comment by regadas** [comment]
closed via #1641
