### ISSUE TITLE
Can we add an option to pass a project id to BigQueryIO.writeTableRows using withLoadJobProjectId(projectId)       }

### ISSUE THREAD

**Issue by hqm** [spotify/scio#1645]
There was a change as of Apache Beam 2.4  in the way Beam sets the project id for bigquery load jobs when saving  an SCollection out to igQuery table. Previously Beam would use the dataflow project id, but they changed it to default to trying to run the BigQuery Load job using the project id of the target table's owner. 

They added a new API call, withLoadJobProjectId()
https://beam.apache.org/releases/javadoc/2.7.0/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.Write.html#withLoadJobProjectId-java.lang.String-

Can we add an option to SCollection to optionally pass this project id, so we have control over it from Scio?

**Comment by regadas** [comment]
Hi @hqm you can always use the beam's `BigQueryIO` and set more intricate options. i.e

```scala
val bq: BigQueryIO.Write[TableRow] = BigQueryIO.writeTableRows()
      .to(table)
      .withLoadJobProjectId(projectId)

sc.applyInternal(bq)
```

hope this helps.

**Comment by jbx** [comment]
@hqm - we're going to close this for now since there is an alternative solution. Let us know if that doesn't work for you and we'll reinvestigate.

**Comment by regadas** [comment]
Hi @hqm don't know what happened but I have you the wrong method, I'm sorry! See the above updated example!
