### ISSUE TITLE
Executing code after closeAndWait

### ISSUE THREAD

**Issue by jwiklund** [spotify/scio#1682]
It would be useful to be able to register to execute code after close (and wait), currently it is hard to write a utility method that would for example resize a bigtable cluster after a scio job has been completed and make it composable with and without metrics (eg you would need closeAndWaitAndResizeCluster as well as closeAndPublishMetricsAndResizeCluster) and so on.

**Comment by regadas** [comment]
Hi @jwiklund! I think it will be better if you expand your comment with an example of how you are doing things right now. IMO composing actions after a `sc.close().waitUntilDone()` can be achieved with the help of other data types like `Try` or even `Future` depending on what you are trying to achieve. i.e:

```scala
Try(sc.close().waitUntilDone())
  .map { sr =>
    Metrics.publish(...) // some metrics lib
  }
  .map { sr =>
    BigtableUtil.updateNumberOfBigtableNodes(...) // provided by scio-bigtable
  }
```

**Comment by guidj** [comment]
@regadas I think one (bad) pattern I've seen libraries using is to wrap the close function for themselves, thus creating the `closeAndX` and `closeAndZ` situation, which is ok if there is the only thing you want, but it's problematic when you do want to execute multiple steps before/after running the job, and you have different libraries wrapping `sc.close*` themselves

One way scio could aid is to provide a goodies class that one could use to wrap the context with pre-process and post-process ops. For example:

```
class ContextWrapper( preOps: Seq[ScioContext => Try[_], 
                                        postOps: Seq[(ScioContext, ScioResult) => Try[_]]) {

  def closeAndWait(): Try = {
     // gracefully chain pre ops checking failure after each one
     val scioResult = sc.close().waitUntilDone()
     // gracefully chain post ops checking failure after each one
  }
}
```

That way, libraries would provide a these functions for you to chain yourself.  What do you think?

Of course, one can always create such class for their own project.

**Comment by anish749** [comment]
Related:
https://github.com/spotify/scio/issues/1848

**Comment by mewppis** [comment]
Being tracked in #2030
