### ISSUE TITLE
VoidCoder's decode method is unimplemented

### ISSUE THREAD

**Issue by tomcham** [spotify/scio#1695]
Scio Version: 0.7.1

The Void coder decode method as implemented in https://github.com/spotify/scio/blob/v0.7.1/scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala#L37 will throw an exception when deserializing.

Beam's VoidCoder https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/VoidCoder.java#L49 returns null.

I was upgrading from Scio 0.5.4 and encountered this issue upgrading to Scio 0.7.1

**Comment by jto** [comment]
The `Void` type is (or should be) unhabited. The actual implementation is meant to be absurd so I'd rather have it throw than return `null`.

How did you end up in a situation where the `Coder[Void]` was actually called ?

**Comment by jto** [comment]
Closing since there hasn't been any activity in several days
