### ISSUE TITLE
scio-spanner: KryoException when using MutationGroup

### ISSUE THREAD

**Issue by sgireddy** [spotify/scio#1703]
```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
columns (com.google.cloud.spanner.Mutation)
mutations (org.apache.beam.sdk.io.gcp.spanner.MutationGroup)
Disconnected from the target VM, address: '127.0.0.1:51278', transport: 'socket'
```
      val spannerOutput = SpannerIO.write()
        .withProjectId(projectId)
        .withInstanceId(spannerInstanceId)
        .withDatabaseId(spannerDatabaseId)
        .grouped()

      val list = sc.parallelize(0 to 10)

      list
      .flatMap(p => Try {
        val taskMutation = Mutation.newInsertOrUpdateBuilder("Tasks")
          .set("TaskId").to(UUID.randomUUID().toString)          
          .set("ReceivedAt").to(Timestamp.now())
          .build()

        val tests = (0 to 5).map( i => {
          Mutation.newInsertOrUpdateBuilder("test")
            .set("id").to(i)
            .set("time").to(Timestamp.now())
            .set("value").to(i)
            .build()
        })

        MutationGroup.create(taskMutation, tests.asJava)

      } match {
        case Success(value) => Some(value)
        case Failure(exception) =>
          println(exception)
          None
      })
      .saveAsCustomOutput("spannerOut", spannerOutput)

      sc.close().waitUntilFinish()

**Comment by regadas** [comment]
@sgireddy Thx for creating this issue! Yeah apparently we missed a coder and it's fallbacking to Kryo which misses the respective `Serializer`.

While we don't release a new version you can temporarily fix it by adding:

```scala
  implicit def mgCoder: Coder[MutationGroup] =
    Coder.beam(SerializableCoder.of(classOf[MutationGroup]))
```

**Comment by sgireddy** [comment]
@regadas  thank you for quick response and workaround, this unblocked me, looking forward to 0.7.2.
