### ISSUE TITLE
Get a beam coder from a scio coder

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#1708]
I am using the beam Api directly to write files using TextIO. The call looks something like this:
```
 FileIO
                    .writeDynamic[DayPartition, RawEvent]()
                    .to(basePath)
                    .by((input: RawEvent) => input.dayPartition())
                    .via(Contextful.fn[RawJustDataEvent, String]((element: RawDataEvent) => element.payload), TextIO.sink())
                    .withDestinationCoder(...)
```
I need like to supply a destination coder ( a Beam coder) to this api. Can i use one of the auto generated scio coder's somehow for this?

E.g i can do 

```
val coder = Coder[DayPartition]
```

But the type is a sealed trait Coder, can i access the internals?

**Comment by regadas** [comment]
@LukeDefeo you can convert it o a `beam` coder with:

```scala
CoderMaterializer.beam(scioContext, coder)
```

**Comment by LukeDefeo** [comment]
Thanks that worked
