### ISSUE TITLE
0.7.2 incompatible error

### ISSUE THREAD

**Issue by git4sun** [spotify/scio#1721]
Just tried 0.7.2 update. Got this exception:
`Class org.apache.beam.model.pipeline.v1.RunnerApi$StandardPTransforms$Primitives does not implement the requested interface org.apache.beam.vendor.grpc.v1_13_1.com.google.protobuf.ProtocolMessageEnum`

Changing the version back to 0.7.1 will solve the problem.

**Comment by ClaireMcGinty** [comment]
@git4sun can you confirm which version of Beam you're using, and which commands you're using to run your job?

**Comment by git4sun** [comment]
It’s 2.9.0

**Comment by ClaireMcGinty** [comment]
Can you upgrade to Beam 2.10.0 and re-run?

**Comment by bbhoss** [comment]
I got this as well, upgrading to 2.10 fixed it, but now my graph is too big. It seems like every iteration of beam they make the graphs more complex

**Comment by jto** [comment]
Closing this issue and opening another one (#1734) about the graph size.
