### ISSUE TITLE
how to get SpannerWriteResult from SpannerIO.write 

### ISSUE THREAD

**Issue by sgireddy** [spotify/scio#1730]
This is a question, not a bug:

I am trying to get SpannerWriteResult as written below with scio ( template: https://github.com/orfeon/DataflowTemplates/blob/73f1d09d06ba35a99a43822c865ec332a3667800/src/main/java/net/orfeon/cloud/dataflow/templates/BigQueryToSpanner.java). 

Here is my pipeline: Pubsub -> upsert Multiple Spanner Tables as Independent Tasks -> Pubsub (I am emitting sideOut get Mutations/MutationGroups, I couldn't figure-out a way to use DynamicDestinations which is probably a better approach. I think updating pubsub after all tasks are complete is more important)

     public static void main(final String[] args) {

        final BigQueryToSpannerPipelineOption options = PipelineOptionsFactory.fromArgs(args).as(BigQueryToSpannerPipelineOption.class);

        final Pipeline pipeline = Pipeline.create(options);
        final SpannerWriteResult result = pipeline
                .apply("QueryBigQuery", BigQueryIO.read(RecordToStructConverter::convert)
                        .fromQuery(options.getQuery())
                        .usingStandardSql()
                        .withQueryPriority(BigQueryIO.TypedRead.QueryPriority.INTERACTIVE)
                        .withTemplateCompatibility()
                        .withCoder(AvroCoder.of(Struct.class))
                        .withoutValidation())
                .apply("ConvertToMutation", ParDo.of(new StructToMutationDoFn(options.getTable(), options.getMutationOp())))
                .apply("StoreSpanner", SpannerIO.write()
                        .withFailureMode(SpannerIO.FailureMode.REPORT_FAILURES)
                        .withProjectId(options.getProjectId())
                        .withInstanceId(options.getInstanceId())
                        .withDatabaseId(options.getDatabaseId()));

        result.getFailedMutations()
                .apply("ErrorMutationToStruct", FlatMapElements
                        .into(TypeDescriptor.of(Struct.class))
                        .via(r -> MutationToStructConverter.convert(r)))
                .apply("StoreErrorStorage", new StructToAvroTransform(options.getOutputError(), options.getFieldKey(), options.getUseSnappy()));

        pipeline.run();
    }

I tried to follow the example https://spotify.github.io/scio/examples/TapExamples.scala.html didn't work. How do I use SpannerIO.write as a transform instead of saveAsCustomOutput?

**Comment by sgireddy** [comment]
I think I got it. 
    val future1 = tbl1Mutations.internal.apply(spannerOutGrouped)

**Comment by sgireddy** [comment]
Ran into another issue using SpannerWriteResult approach. Here is my stackoverflow question, appreciate your help.

https://stackoverflow.com/questions/55129010/dataflow-spanner-cant-verify-serialized-elements-of-type-spannerschema-have-we

**Comment by jbx** [comment]
Awesome that you found a solution. We'll take a look at some of this a bit more though since some of that code does smell a bit.

**Comment by regadas** [comment]
Another way would be to just use 

https://github.com/spotify/scio/blob/f7670f2fa43eb25c1c29843dbb721b9743ae5e9b/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L167-L171
