### ISSUE TITLE
The size of the serialized JSON representation of the pipeline exceeds the allowable limit for the API

### ISSUE THREAD

**Issue by jto** [spotify/scio#1734]
That error has been reported by several users after migrating to 0.7.2.
Might be caused by a change in Scio or by the new Beam version.

**Comment by bbhoss** [comment]
Thanks for opening this, I’m glad I’m not alone. I have been digging into this all week but haven’t gotten anywhere. We had a bunch of traits marked as serializable that I don’t think need to be, so I am trying to unwind them to see if maybe things are getting overserialized. It could also be some implicits blowing it up, but I haven’t investigated. FYI we had a job that was totally fine on 0.6.x that we had to split up when moving to 0.7.0. When trying to use the half baked experiment for uploading the graph to GCS, I see that the graph size has at least doubled on this job to nearly 20MB where it was under 10 before.

**Comment by bbhoss** [comment]
To be clear, the doubling happened when going to beam 2.10/0.7.2, but 0.7 started this trend.

**Comment by ClaireMcGinty** [comment]
I've been testing job graph serialization on an extremely simple pipeline (literally just `sc.parallelize(1 to 100)`). Dataflow serializes job graphs using [DataflowPipelineTranslator.jobToString](https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java#L216) so I used that to directly examine the JSON output for the internal job `Pipeline`. The graph size spikes after this [commit](https://github.com/spotify/scio/commit/d7133bc0fc48f250c00b836cc9b220b0c168f62b#diff-a4043bca34b46c764c6273ca38bb7a3c) that has `CoderMaterializer` wrap Beam/Record/KvCoders in a `WrappedBCoder`.

Before that commit, the serialized job graph step looked like:
```
 "output_info" : [ {
        "output_name" : {
          "@type" : "http://schema.org/Text",
          "value" : "output"
        },
        "user_name" : {
          "@type" : "http://schema.org/Text",
          "value" : "parallelize@{PipelineGraphSizeTest.scala:18}/Read(CreateSource).out0"
        },
        "encoding" : {
          "@type" : "kind:windowed_value",
          "is_wrapper" : {
            "@type" : "http://schema.org/Boolean",
            "value" : true
          },
          "component_encodings" : [ {
            "@type" : "org.apache.beam.sdk.coders.VarIntCoder"
          }, {
            "@type" : "kind:global_window"
          } ]
        }
      } ],
```

After that commit, the step looks like:
```
      "output_info" : [ {
        "output_name" : {
          "@type" : "http://schema.org/Text",
          "value" : "output"
        },
        "user_name" : {
          "@type" : "http://schema.org/Text",
          "value" : "parallelize@{PipelineGraphSizeTest.scala:18}/Read(CreateSource).out0"
        },
        "encoding" : {
          "@type" : "kind:windowed_value",
          "is_wrapper" : {
            "@type" : "http://schema.org/Boolean",
            "value" : true
          },
          "component_encodings" : [ {
            "@type" : "org.apache.beam.sdk.coders.CustomCoder",
            "type" : {
              "@type" : "http://schema.org/Text",
              "value" : "com.spotify.scio.coders.WrappedBCoder"
            },
            "serialized_coder" : {
              "@type" : "http://schema.org/Text",
              "value" : "%82SNAPPY%00%00%00%00%01%00%00%00%01%00%00%04%83%aa%0f%a0%ac%ed%00%05sr%00%25com.spotify.scio.coders.WrappedBC%01%0f%e0%a6%de%ab|%00<=%98%02%00%03Z%00%0dbitmap$init$0[%00%0astackTracet%00%1e[Ljava/lang/St%11%19%90Element;L%00%01ut%00%22Lorg/apache/beam/sdk/c%01j%08s/C%01%07 ;xr%00 org.%09%25%00.%01%25%10.sdk.%0d%9e%05%25<C%dd%d5%89%ae%bc~%f8%02%00%00xp%01ur%11}%14.lang.F}%00%1c%02F*<<%fd%229%050%1c%00%00%00%18sr%00%1b%01%aeZ1%00%b0a%09%c5%9a&6%dd%85%02%00%04I%00%0alineNumberL%00%0edeclaringClasst%00%12L%01H%11%f6%01%19d;L%00%08fileNameq%00~%00%08L%00%0amethod%15%12 xp%00%00%06%17t%00%10%01<%09%84 Threadt%00%0b%09%09%00.%01%1a%14t%00%0dget%19%cf%00s%01O%1c%07%00%00%00%a6t%00'^%bf%01%25!0Exception$t%00%0b%05%12<.scalat%00%11prepareJV%00%04%b4t%9a%15%02%01%87%10%0ft%00%06<A%09%00>%15%96%0c%dft%00&^%96%002U%02%00$%11A%10creat%19%d7%0c't%00*^A%00%05%c5<Materializer$t%00%17B%15%00%11%e6%00%04A7%15%99%14%1bq%00~%00%18%01%05%00%19%01%05%00%1a%11%19%10%02%b3t%003Bq%00lScioContext$$anonfun$paralle%01z%10$1t%00%11%1d%25%11t%14%05apply%15%5c%00%af%01k%00%1d%01%05%00%1e%01%05%00%1f%15%19%0c%09t%00%1cnu%00%01.L%1et%00%10requireNotClosed%15A%05Z%00%22%0d'%00%0b%1d%9a%11%22%10%00%12t%000Bc%000examples.PipeA%d4@GraphSizeTest$t%00%1bR%19%00%11%df%10%04main%09b%18%ff%ff%ff%fft%00/%bab%00%01%b1%00(%01%05%00)%15FX%fet%00$sun.reflect.NativeMe-8AccessorImplt%00%1d^%1b%00m)%1c%07invoke0%09[%0c%00%00%00>%01j%00-%01%05%0c.t%00%06%09%1e%15%1d%0c+t%00(.x%00$DelegatingN|%00%00!n%1f%00%05%80%01g%001%11^%10%01%f2t%00%18a%bfi%d9%11%dc%09Z%08t%00%0b%09%09F8%00D%00bt%00%07sbt.Runt%00%09Run1{%00%0a%09%bf%00M5%81%0c%00%00%00%5c%01t%009%01%05%18:t%00%04run%19%fb%00D%01%16%11%1b %09execute$%15%a0%04%00P. %00%00%0eU%e3%10run$4%11%c5%10%00%0ct%00%25%853%1c.runtime%05%b1%188.JFunc%81Z(0$mcV$spt%00%16B%14%00%05,%01fU%f6%10%00%0at%00%1e%01%ddDutil.InterfaceUtilieaV%00%132%18%00%11%fe%0c%03get%15%97%0c%fdt%00%10%01G8TrapExit$Appt%00%0e%11%0f%154%04ruM%ac%0c%00%00%02%ec%01%8a%00%0a%01%05%00%0b%01%05%10Lsr%00&jb%06HVarIntCoder%c0K2%da%a9KVh%c18v5%00%14Atomic%055%1c%c7%ec%b5%cc%85tPF%095%00*jj%00$Structured%059@s%bf%12%0e%d5%d46%11%02%00%00xq%00~%00%03"
            }
          }, {
            "@type" : "kind:global_window"
          } ]
        }
      } ]
```

In more complicated pipelines I think this is responsible for a lot of the added graph size as it impacts the Coders at every step. Removing the extra `WrappedBCoder` wrapper returns the graph to its original state - it seems redundant, as far as I can tell?

This is just an analysis from 0.7.0 - 0.7.2, @bbhoss I'll look into what Scio 0.6 was doing differently as well.

**Comment by ClaireMcGinty** [comment]
from a quick look at 0.6.1, seems like the main difference between that and 0.7.0 is that there are about ~50 more jars being staged in 0.7.0 so the job graph has a lot more overhead there. Does that match your experience @bbhoss?

**Comment by bbhoss** [comment]
I wasn't paying too much attention to graph size pre 0.7. I would be surprised if the increased deps list at the top of the graph pushed us over the edge though. Digging around I think the biggest difference is the serialized coders are there and much larger.

**Comment by bbhoss** [comment]
So I fooled around with this a little bit locally. I removed the `WrappedBCoder.create` calls and it allows my job to be submitted.

**Comment by bbhoss** [comment]
Just hit this again in the latest version, on a job with only 500 steps (our other job that was failing is over 1k). I didn't even know there was a max before updating to 0.7, I wonder if there is still something left to fix here. Could you share the code you used to inspect the graph or suggest any other tips to investigate this? Thanks
