### ISSUE TITLE
How to (re)use ScioIO "dynamicaly"?

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#1740]
I am in need of having an IO to dynamically react on what is happening in pipeline. E.g. imagine a pipeline where one part of it is materialising it's output to HDFS as parquet files. Then, there is a `Wait.on()` transform to delay second part until first processing is finalized and then needs from received `SCollection[String]` of directories load those parquet data back for some sort of post processing. 
Now, my question is, how is it possible to load those with `ParquetAvroIO`. It implements `ScioIO` which needs `ScioContext` to operate. However, after pipeline is started, scio context is not available and I do not see a way to materialize it back such as `ScioContext.wrap(pipeline)`.

What are my options here? Is there a way how scio can help me or I have to rewrite needed IOs into `PTransforms` myself?

**Comment by anish749** [comment]
Short answer: I don't think you can reuse IO dynamically.

Once a `ScioContext` / beam `Pipeline` is closed, it has its outputs defined. To process the outputs dynamically further, you would need to create a new ScioContext (and a new DataFlow Job) and read inputs from HDFS again into a SCollection in the new ScioContext. You can't read a SCollection from a ScioContext that is closed into another new ScioContext. (you can't share a SCollection between contexts).

Ideally to solve the problem you are facing at scale, you would need to use something like Luigi / Airflow which allows you to create DAGs and manage multiple pipelines dynamically.

**Comment by JozoVilcek** [comment]
I am not interested in launching a new job, just loading data from some source on demand, therefore as a reaction to elements coming via `SCollection`. Beam has a tool for this I believe in form of `PTransforms[]` where if you have `SCollection[String]`s  and those are file patterns, you could expand it to content of a e.g. parquet files if ine has an operator in form of `PTransform[PCollection[String], PCollection[T]]` ... if I am not mistaking.
Another abstraction is off course, a `beam.io.Source[T]`.
I guess Scio does not have alternatives and it's IO logic can not be used in form of there Beam primitives. So there is not way.

Would be great if one can enclose and arbitrary sequence of Scio operations into an PTransform and then use to expand incoming `PCollection[]` / `SCollection[]` by it.

**Comment by anish749** [comment]
I think you can use something like `myScoll.transform("transformName") { theScoll => theScoll.map...groupBy...join....(someOtherScoll) } `
The function `transform` takes a fn `SCollection[T] => SCollection[U]` as an argument and is a wrapper around Beam's PTransform.
Note that this API is experimental, and depending on your version this api might not be available.

**Comment by JozoVilcek** [comment]
I learned a bit from Beam side
https://lists.apache.org/thread.html/add2cc01bc0780c1c3db324b0a34132f89d955168c6420cfa572ad6e@%3Cuser.beam.apache.org%3E

I guess for what I need it needs to be done / supported at `Source[]` level of IOs. `ScioIO` abstraction is not build for it and can not be used in such way. Thanks
