### ISSUE TITLE
DataflowRunner scheduler hangs

### ISSUE THREAD

**Issue by FelipeQuirce** [spotify/scio#1744]
Hi,

When I a streaming job using --runner=DataflowRunner, the job is scheduled properly but the process hangs until I kill it.
This makes developing CI pipelines really tricky.

Thanks

**Comment by regadas** [comment]
Hi @FelipeQuirce how are you closing your `ScioContext`?

**Comment by anish749** [comment]
Might be completely unrelated, but if it started occurring suddenly, on March 11th, during a similar time there was an incident with Dataflow: https://status.cloud.google.com/incident/cloud-dataflow/19001

**Comment by FelipeQuirce** [comment]
> Hi @FelipeQuirce how are you closing your `ScioContext`?

I was doing close() and then waitUntilFinish() that's why is waiting.
I seems like an odd behaviour too me, because the finish with the scheduling when the runner is not a local one.

Thanks

**Comment by jbx** [comment]
Closing for now. Thanks for the report Felipe!
