### ISSUE TITLE
Question: Allow PrioritizedImplicits Construction for pipelines using Scio

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1748]
I might be wrong here, or there might be better solution, but I was trying out some extensions for joins and in most of our pipelines we use extensive implicits on top of SCollection, to add helper methods / wrappers. Sometimes these helper function names start conflicting with the ones provided by implicit conversions in Scio. Separating implicits in a `trait SCollectionImplicits` from `object SCollection` would help in prioritising these implicits.

in user's code we can then have:
```
object ScioHelpers extends SCollectionImplicits with LowPrioProjectSpecificImplicits
...

import ScioHelpers._
```

An example of a conflicting naming: We have a scenario where having counters during development, makes designing pipelines very easy.
Currently adding counters is a very manual step. Eg. We would like to inner join two PairSCollections, but closely keep track of values which get filtered in the inner join / track duplicates which cause partial cross joins. This leads to either using a cogroup / full outer join and then flatMap to update counters. The counters are a very appropriate way of monitoring how and where bugs introduced after pipeline development in upstreams start affecting data quality adversely beyond a certain user defined threshold. This also makes it easy while troubleshooting errors.

To solve this we would like to have an extension like:
```
def join[W: Coder](that: SCollection[(K, W)], joinMetrics: JoinMetrics*): SCollection[(K, (V, W))] = self.transform { me =>
    me.cogroup(that)
      .flatMap {
        case (k, (iv, iw)) =>
          joinMetrics.foreach(_.updateCounters(iv, iw))
          for {
            v <- iv
            w <- iw
          } yield (k, (v, w))
      }
  }
```
but the `left.join(right, JoinMetrics.metricType(...))` would conflict because of a multiple implicits in scope, and hence we need to use a different name like `left.joinWCounts(right, JoinMetrics.countUnMatched("a", "b"))`.

I also think better integration with counters and the scenario described above can be a good feature for Scio as well.

**Comment by regadas** [comment]
@anish749 Thanks for raising this. yeah currently in `scio` we do have have a lot of `implicits` that are brought into scope through package objects or objects. The reason behind this decision was to make it easier to use without requiring too much `import`. (important for ppl new to scala) 

However, we are in the process of uplifting some of this things and with that decrease the priority on some of them, so expect some changes in the upcoming versions.
