### ISSUE TITLE
Distributed ML/statistics algorithms

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#176]
- [ ] Bootstrapping
- [ ] SGD from Breeze
- [ ] BFGS/L-BFGS from Breeze
- [ ] Logistic regression
- [ ] Random forest
- [ ] GBM
- [ ] GLM
- [ ] K-means http://theory.stanford.edu/~sergei/papers/vldb12-kmpar.pdf
- [ ] Streaming K-means http://papers.nips.cc/paper/3812-streaming-k-means-approximation.pdf
- [ ] <s>XGBoost4J</s> http://dmlc.ml/2016/03/14/xgboost4j-portable-distributed-xgboost-in-spark-flink-and-dataflow.html

**Comment by ravwojdyla** [comment]
Related #166

**Comment by znichols** [comment]
Maybe logistic regression / GLM stuff also?

**Comment by nevillelyh** [comment]
I have a WIP branch of XGBoost here https://github.com/nevillelyh/xgboost/tree/neville/scio

**Comment by nevillelyh** [comment]
Dataflow workers run in Docker and messes up with XGBoost communication so it's a no go.

**Comment by ravwojdyla** [comment]
So these use cases can be solved by doing ML in Spark and pre/post processing in Scio, this can be done via https://github.com/spotify/limbo
