### ISSUE TITLE
Possibly wrong code in FAQ

### ISSUE THREAD

**Issue by andremissaglia** [spotify/scio#1817]
I was looking at the FAQ, when I came found this code:
https://spotify.github.io/scio//FAQ.html#how-do-i-read-pubsub-input-in-a-local-pipeline-
```
sc.customInput("ReadFromPubsub",
  PubsubIO.read()
    .topic("projects/data-university/topics/data-university")
    .idLabel("id")
    .timestampLabel("ts")
    .withCoder(StringUtf8Coder.of())
    .maxNumRecords(50)
    .maxReadTime(Duration.standardMinutes(10))
```

The problem is that these methods don't exist. Not in the [Beam PubsubIO](https://beam.apache.org/releases/javadoc/2.11.0/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.Read.html), and not in the [Scio PubsubIO](https://spotify.github.io/scio/api/com/spotify/scio/io/ScioIO.html).

Is there something I'm missing here? I am trying to read from pubsub in batch, but as far as I know, there is no way to do that out-of-the-box.

**Comment by nevillelyh** [comment]
Fixed in #1825.
