### ISSUE TITLE
Split elasticsearch bulk requests based on its size and document size

### ISSUE THREAD

**Issue by regadas** [spotify/scio#1829]
ES doesn't deal well when bulk requests become too big. We should be able to split the request base on its size and document size.

**Comment by KieranCTaylor** [comment]
Has this issue been looked at / resolved yet? I would be interested in tackling.

**Comment by regadas** [comment]
Hi @KieranCTaylor go for it!

**Comment by KieranCTaylor** [comment]
Great I will jump on this week and see what I can do

**Comment by KieranCTaylor** [comment]
Hey @regadas is this not satisfied by the ES write param maxBulkRequestSize?

**Comment by RustedBones** [comment]
@regadas isn't this closed since we now have `maxBulkRequestBytes` setting ?

**Comment by RustedBones** [comment]
On `scio-elasticsearch8`
- `maxBulkRequestOperations` for the max number of operations in a bulk request
- `maxBulkRequestBytes` for the max total size of operations in a bulk request
