### ISSUE TITLE
Question: Support for ScioContext.onClose()

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1848]
I saw that the Scio Context has a function called `onClose(() => ())` [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L498-L502) which allows someone to add callbacks to the pipeline before it is executed.

However this is private and is used by BQ reads internally in Scio to run queries before starting a pipeline.

I was wondering if it would be a good idea to make this API public and have broader use cases for it.

Example use cases:
I want to run some code before starting a pipeline, but after defining it, eg: Make sure replication in some database slave is complete, before querying via Scio Jdbc, and stuff like that. Pretty similar to how it is used to run a query for BQ.

Another example that I can think of would be to check if dependencies exists and only then start a dataflow job.
If it is not an expected thing, I am happy to have my common components in `com.spotify.scio` package and then have my pipelines call my common code. (I do expect to have some common code for checking database replication, and things like that as add-ons to a pipeline IO.)

**Comment by regadas** [comment]
Hi @anish749 the **TL;DR** it that `onClose` is meant to be used internally, if you use it ... you shouldn't! 

From your examples those checks/resource managers could easily be done outside of `scio` and possibly provided as libs.

**Comment by anish749** [comment]
It is definitely possible to do this outside of Scio, and we do this today as well. However it requires a lot of layers of boilerplate code.

_From a user code perspective:_
We can make decisions and checks about whether to submit a job to dataflow or not. A job submissions can have a lot of preconditions:
 - are the files present / complete?
 - does the service account / user have correct permissions? (we don't do this, and jobs fail late)
 - does the output bucket exist? (we don't do this, and jobs fail late, after processing n-1 stages)
 - is there enough external resources available (eg: writing to cloudsql from multiple independent jobs, we don't want to overload the database with too many jobs / connections, we might just wait for this to finish)

Of course all of the above can be done in luigi, but that needs an extra layer, and more things to keep in mind while maintaining code.

Here are some inspirations / attempts / thoughts on making the whole structure simple.
[RFC1](https://docs.google.com/document/d/1JGiurBmefY5yHPgOvj2TeEZD2FHcw6-bbG5PDPYeXcc/edit#), [RFC2](https://docs.google.com/document/d/1U99vQMsXL2gAM9IG-035PtGM1mH6sAPAXxKl4vMqLas/edit#)


_From an extra lib perspective_ (not scio-core):
Having `onClose` allows extra code to be executed which can do things like job graph analysis, logging usage of specific transforms, replace transforms / logic based on graph analysis.

**Comment by regadas** [comment]
Most of the mentioned points are quite valid and there are many more use cases. However, I believe that these points  are mainly related to orchestration/scheduling and they are way better tackled by this layer or lib that eventually wraps `scio`, sure it's yet another thing that you need to worry about but it's a better separation of concerns. 

TBH, I still need to give it a little bit more thought, but i would probably be more interested in making these two layers interact better.

> job graph analysis, logging usage of specific transforms, replace transforms / logic based on graph analysis.

These tasks are interesting and we probably should allow use case for it. As it stands `onClose` doesn't offer a good semantic and it should be more terse.

**Comment by anish749** [comment]
I agree.

**Comment by mewppis** [comment]
Currently being tracked in #2030
