### ISSUE TITLE
Provide a filter function on SCollection based on sub-types

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1855]
We have a model where we are having co-products and an SCollection of co-products.

We want to filter a certain sub-type.

As of now we are doing:
```
sCollection[SuperType]
      .filter(_.isInstanceOf[MySubType])
      .map(_.asInstanceOf[MySubType])
```

In this method we are having to add `@SuppressWarnings(Array("org.wartremover.warts.AsInstanceOf"))` and the type casting is very wide and not checked at compile time to make sure this is possible.

I was trying to move this `asInstanceOf` from my pipeline code into a common function and came up with 
```
    /**
     * Filter an SCollection[T] and keep all elements is the same as the given Subtype `ST` of `T`
     *
     * @tparam ST subtype to filter and keep
     * @return SCollection[ST]
     */
    def filterType[ST <: T: Coder: ClassTag]: SCollection[ST] =
      self
        .flatMap {
          case st: ST => Some(st)
          case _      => None
        }

  }
```

This would allow the type to be checked at compile time in my pipeline code and also no `asInstanceOf`

Do you think Scio should support this use case? given that we are a Scala / FP api for Beam.

**Comment by regadas** [comment]
Hi @anish749 not sure if this belongs in `scio`. If I understand correctly you probably can just do something like:

```scala
    import scala.reflect._
    def instanceOf[A, B: ClassTag](a: A)(implicit ev: B <:< A): Option[B] = a match {
      case e: B => Some(e)
      case _ => None
    }

    sCollection[SuperType]
      .flatMap(instanceOf[SuperType, MySubType])
```

no need to make an extension to `SCollection`

**Comment by anish749** [comment]
Yes, that’s similar to what I am using. And given that this is not a part of Scala  collections, it makes sense to not have it here
