### ISSUE TITLE
Expose Beam's BigQuery WriteResult

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1864]
Beam's BigQuery Write Transform gives our the errors and failures as a [`WriteResult`](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteResult.java) output when writing a PCollection to BigQuery.

Currently Scio Exposes a Tap of the output table and the `WriteResult` is not accessible any more.

It would be nice to preserve this functionality of Beam and expose the error records as an `SCollection` to the user.

I am not sure if `saveAsBigQuery` should be modified, but maybe we can have something like `writeToBigQuery` which returns `(SCollection[TableRow], SCollection[BigQueryInsertError])`

One side effect of not having this is that this results in unconsumed reads and a `DropInputs` transform appearing in Dataflow UI which is hard to understand and reason about when writing to Big Query

**Comment by regadas** [comment]
Hi @anish749 we are aware of this and we do have plans in future to address it. Unfortunately, I can 't really give you a timeline for this.

**Comment by anish749** [comment]
As a short term solution do you think it is a good idea to have a no-op after the transform? This would make sure we don't have an `UnconsumedRead` and the name in the Dataflow is more understandable. Right now it comes up as `DropInputs1` which is kind of misleading.

Beam is running [this](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/UnconsumedReads.java) after creating the pipeline to add these annoying and misleading drop inputs.

This becomes especially confusing when the write happens from inside a PTransform (`sColl.transform`)

I can try this in a PR.

**Comment by anish749** [comment]
> yeah I can see this happening if you have failed inserts when using unbounded collection.

I am doing this for a bounded SCollection. The Drop Inputs is added by this transform [here](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/UnconsumedReads.java) which is executed by beam when the graph creation is complete but before sending to Dataflow.

> if you are referring to adding a transform that consumes those errors, we could add it and at leas log them.

I am not sure if we should log it, what if it is a few billion records ¯\\_(ツ)_/¯ and some one is doing something crazy!!! Or we can put a limit on the number of errors to log, and something like `take(1000)` and then log all of them... That might work, but the problem is `Take` transform from beam does an aggregation, which will be an expensive one if there are a billion error records. It would be best to have some thing like `approxTake(minRecords = n)` (I haven't thought how to do it, just putting out the idea. I used `take` for something like this for tracing to BQ, and it was a disaster because it went for a global aggregation.)

I am doing this [here](https://ghe.spotify.net/payments/pipeline-subs-platform/blob/5d1121ff31fd73cb23411b95973b7fab9de2cd79/pipeline-subs-platform-scio/src/main/scala/com/spotify/data/common/magics/TraceableSCollectionFunctions.scala#L125-L150), which works well in doing a dev/null, but doesn't log.

**Comment by regadas** [comment]
@anish749 ah yes I see now that it will also show up for bounded collection's The thing that was confusing me initially is that the failed inserts collection will always be empty so there's nothing to read. However since this is based on the URN it will still be considered to be consumed.

What about adding a `handleErrors: BigQueryInsertError  => Unit` to `BigQueryTable.WriteParam` where the default is `_ => ()`  and update `BigQueryTable` IO.

**Comment by regadas** [comment]
@anish749 I really quick draft just to see how it looks https://github.com/spotify/scio/pull/1867

**Comment by anish749** [comment]
> What about adding a `handleErrors: BigQueryInsertError => Unit` to `BigQueryTable.WriteParam` where the default is `_ => ()` and update `BigQueryTable` IO.

This is a nice idea. I liked the `SCollection[BigQueryInsertError] => Unit` part.

**Comment by regadas** [comment]
Closed via #1867

**Comment by JunyuanZheng** [comment]
hi, I have some questions regarding to this one. can you provide an example about how to actually use this feature?

thanks!

**Comment by anish749** [comment]
This is exposed via the IO. I doesn't have a corresponding `saveAsBigQueryTable(..)` the allows you to access `WriteResult`.
So you would need to access directly.
Example of what you would need to implement is [here](https://github.com/spotify/scio/blob/ab2915de0728bbc20cc6b47712dffa42de7b7b13/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala#L57-L71):

```scala
val param = BigQueryTypedTable.WriteParam(....) {
  errors => 
    // whatever you want to do with the errors.
}

scollection.write(BigQueryTypedTable(.....))(param)
```
an example of the write param is [here](https://github.com/spotify/scio/blob/ab2915de0728bbc20cc6b47712dffa42de7b7b13/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala#L232)
