### ISSUE TITLE
Update BQ<->Avro converters in scio-extra to match latest BQ spec

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1880]
We have these converters in `scio-extra`:
https://github.com/spotify/scio/tree/master/scio-extra/src/main/scala/com/spotify/scio/extra/bigquery

We should update the type mapping and conversion, especially the date/time types, `NUMERIC`, etc. to match the ones used in latest BQ Avro export.
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/StorageUtil.scala
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala#L69

**Comment by syodage** [comment]
Found this in BigQuery docs, https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro 

Try to see the code gen part for some missing types and found a bug in apache Avro regarding a couple of logical types. https://issues.apache.org/jira/browse/AVRO-2392 , working on getting that address in 1.8.2 branch. I will try to get a PR ready with the rest of the missing stuff.

**Comment by regadas** [comment]
@syodage did you make any progress on this?

**Comment by syodage** [comment]
@regadas sorry for the late reply, Here is the branch I am working on https://github.com/spotify/scio/tree/shameera/avro_bq_logical_type_conversion . still WIP state.

**Comment by HectorLagos** [comment]
I would like to contribute on this one, let me know if help is needed

**Comment by nevillelyh** [comment]
@syodage still working on this?

**Comment by syodage** [comment]
@nevillelyh yeap, can wrap this one quick. in the testing phase.

**Comment by syodage** [comment]
@nevillelyh https://github.com/spotify/scio/pull/2602
