### ISSUE TITLE
Improve Coder derivation speed by caching implicit searches

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1898]
I am having a project with around 75 Scio Pipelines, and I added a pipeline with a lot of ADTs, and I am heavily using `sCollection.transform` (at least 10) which means I am passing around a lot of `SCollection[T]` around, this is resulting in multiple Coder derivations of the same type.
I also noticed the same in another pipeline which had the code broken down into multiple functions and passed around `SCollection[...]`

Adding the following implicit helps improve this to a large extent.
```
import com.spotify.scio.coders.Coder
import shapeless.Cached
package object pipelines {
  implicit def shapelessCache[T]: Coder[T] = Cached.implicitly[Coder[T]]
}
```

The compile time improved from 131s to 45s for this project.

I would push this change and test it out for a week to see for failures in the pipelines I have, but I am not expecting problems, since static `Coder` derivation is deterministic.

Should this be a present here for all coders?

**Comment by jto** [comment]
I'm not sure caching implicit in Scio is generally safe given that different Coder implicit resolution might occur with different implicit scopes.

**Comment by anish749** [comment]
@jto I agree.

**Comment by regadas** [comment]
Yeah I agree with @jto !
