### ISSUE TITLE
ScioContext.bigQuerySelect no longer exists, is there something equivalent? 

### ISSUE THREAD

**Issue by hqm** [spotify/scio#1903]
I'm upgrading to the latest 0.7.4 scio, and it looks like the ScioContext.bigQuerySelect method has been removed. 
Can you point me at an example of how to do a dataflow BigQuery "SELECT" query in scio now, which returns an
SCollection[TableRow] ? 

I.e., is there a way to not have to modify my exisiting codebase to use the Type safe
BigQuery mechanism, and still just get a vanilla SCollection[TableRow] from a
bq query?

**Comment by nevillelyh** [comment]
It's moved and documented in this migration guide:
https://spotify.github.io/scio/migrations/v0.7.0-Migration-Guide.html#you-may-need-to-explicitly-add-a-dependency-one-of-scios-subprojects-in-your-build-file
