### ISSUE TITLE
Typed BigQuery issue

### ISSUE THREAD

**Issue by git4sun** [spotify/scio#1912]
Here's my code:

    @BigQueryType.fromQuery("SELECT account_name, account_id FROM [Test.preference]")
    class Row

and when I call from sc:

    sc.typedBigQuery[Row]()
          .flatMap { r => ... }

It doesn't compile with the following error:

    type arguments [com.xxx.scoring.TestScoring.Row] do not conform to method 
        typedBigQuery's type parameter bounds [T <: 
        com.spotify.scio.bigquery.types.BigQueryType.HasAnnotation]

**Comment by nevillelyh** [comment]
Do you have any compiler/sbt log?

**Comment by git4sun** [comment]
The error is thrown by sbt. Here are some more:

    [error]         sc.typedBigQuery[Row]()
    [error]                                       ^
    [error] one error found
    [error] (Compile / compileIncremental) Compilation failed

**Comment by nevillelyh** [comment]
That's not enough context to do any sort of meaningful triage. Closing this. Feel free to reopen when you dig up more.

**Comment by git4sun** [comment]
I figured out what's causing the problem. When I change the project structure in build.sbt, I only `dependOn` the common project that has the `macroSettings` which has the scala reflect dependency. Need to also include the `macroSettings` in the subproject for the annotation to work. Should the error message be missing scala-reflect or something that helps debug?
