### ISSUE TITLE
Support for elasticsearch 7

### ISSUE THREAD

**Issue by asydorchuk** [spotify/scio#1918]

**Comment by ClaireMcGinty** [comment]
i have a branch up with the new ES high level rest client if anyone interested would like to try it out; it's only tested on DirectRunner + local ES cluster so it's not quite battle-tested yet :) https://github.com/spotify/scio/compare/claire/elasticsearch7

**Comment by nevillelyh** [comment]
I think it's fine to just PR this so others can start testing. The ES* modules are best-effort support anyway so as long as there's some basic unit tests.

**Comment by ClaireMcGinty** [comment]
PR'ed it, although the existing unit tests can only be described as minimalist :P
