### ISSUE TITLE
readAll workaround for metadata size limit

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1927]
Right now job submission might fail if the input paths are too long. We could work around that by writing the paths to a text file on GCS and do readAll on it.

**Comment by nevillelyh** [comment]
On second thought this is probably a runner specific optimization better left to the users for flexibility. Not sure if it belongs to Scio.

**Comment by jto** [comment]
Yeah it sounds like it should be fixed in Beam directly

**Comment by nevillelyh** [comment]
Doesn't seem relevant enough. Closing.
