### ISSUE TITLE
Make SideInput extendable with wrapping

### ISSUE THREAD

**Issue by sisidra** [spotify/scio#1967]
It would be nice to support delegating/forwarding pattern in SideInput API for easy extensions?
Currently it is heavily sealed with many member being private.

For example, I want to create a `MySideInput` that reuses `SparkeySideInput`:
```
package com.spotify.scio.values  // Dirty workaround for problematic private members...

class MyLookupSideInput(val delegate: SideInput[SparkeyReader]) extends SideInput[MyLookup] {
  override val view: PCollectionView[_] = delegate.view  // This is problematic because private

  override def get[I, O](context: DoFn[I, O]#ProcessContext): MyLookup = {
    val reader: SparkeyReader = delegate.get(context)  // This is problematic because private
    new MyLookup(reader)
  }
 }
```

I can quickly imagine 2 solutions:
* Remove `private` modifiers from `get` and `view`, as class it is not exposed to pipeline anyway, it should be quite safe to loosen those.
* Provide `WrappingSideInput` for this one specific use case that users can extend.
* or both?

**Comment by nevillelyh** [comment]
Maybe something like a `SideInput[A]#def map(f: A => B): DelegateSideInput[B]`?

**Comment by sisidra** [comment]
Something like that might be an option.

**Comment by nevillelyh** [comment]
Someone else brought up that if `f: A => B` is expensive, or in some cases `A` or `B` itself is a lookup table, e.g. Sparkey where we want to deserialize value bytes to protobuf, then it's desirable to have a on-heap cache to save CPU cycles.

Sounds like 2 related issues?

**Comment by nevillelyh** [comment]
@iyahimovitz any updates? @O-OF-N is also interested in this. Would be great to see a branch/PR so we can discuss over there.

**Comment by nevillelyh** [comment]
Another note, the abstraction should support state for the purpose of caching, see #2101.
