### ISSUE TITLE
Wrong += & +== semantics in MutableBF

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#1981]
Looks like `MutableBF`'s `+=` & `++=` methods return copies instead of mutating themselves which is counter intuitive.

They should probably be renamed to `+` & `++`?

**Comment by anish749** [comment]
This is a hard one. the behavior depends on the size of the set bits. Can you share an example.

The problem arises because the Filter is modeled as a disjunction, but I found bringing mutability in this model to be rather hard.

Mutability is easy if we model a linked list with a Node like we do in java /oops. This becomes hard when we use a cons cell model to create a linked list. It’s hard because when the first element is added to the list, it’s instance type changes.

Here the Bloom Filter is modeled as a disjunction, and when the types change, it returns a new object. 

This would get fixed if we do not use a disjunction model and keep everything in once class. What do you think?

**Comment by nevillelyh** [comment]
:+1: on making it a single class, so it behaves more like a traditional mutable data structure. TBH we don't even need monoid/aggregator for this right? Just `MutableBF` with `create()`, `add(item: T)` & `merge(other: MutableBF)` methods.
Disjunction model seems more useful when it's used in the true immutable `reduce` manner.

**Comment by anish749** [comment]
Yes... 
We have a few requirements here:
- We need a mutable BitSet during aggregation.
   - Something that supports fast insertions and `or` operation.
- We don't want to allocate memory upfront.
  - We decide the size of the BitSet based on the estimated number of keys from the user. This means that during unit test, we would be having a very high estimate, and less number of elements. If we allocate the complete memory for the BitSet, we would need very high memory while running tests. The mutation detector creates multiple copies during a `JobTest`, this means we would need somewhat around 4 times the memory of the actual BitSet during the JobTest. 
- We need a way to aggregate a `SCollection` into a BitSet + some values.

Solutions:
 - We can define this as a combine function similar to [`T-Digest`](https://github.com/apache/beam/blob/master/sdks/java/extensions/sketching/src/main/java/org/apache/beam/sdk/extensions/sketching/TDigestQuantiles.java) and other sketchs from Beam.
 - We can define one class `BloomFilter` and back it by a `GrowableBitSet` which basically does not allocate memory to store 0s, something along the lines of [this](https://github.com/typelevel/cats-collections/blob/master/core/src/main/scala/cats/collections/BitSet.scala) from cats, but mutable to make it much faster.
 - We can define an aggregator which converts into an immutable BF with only `mayBeContains` method at the `present` step. Something like [this here](https://gist.github.com/anish749/426427f72c9c2fa00eaaa90ee03c8507) + memory optimizations

What do you think?

**Comment by nevillelyh** [comment]
Like 2 and 3, either should be simple enough to implement and optimize, while still being relatively idiomatic scala and potentially can be made public API later?

**Comment by nevillelyh** [comment]
This can be solved by #1997

**Comment by anish749** [comment]
@nevillelyh For option 3, which BitSet implementation would be good? If it is a public API, and it is an immutable BF, that the user can save and serialize to disk, then I think we would need to optimize the memory, as the user is mostly going to use that BF in an unit test, and we don't want to use the full memory in the unit test.

**Comment by nevillelyh** [comment]
Do we really need to worry about unit test performance, assuming it's usually a few mock items?
For the intended use case, I imagine the user will set an appropriate `capacity` and insert `n` items close to full capacity in the final BF. In that case a full, uncompressed, dense bit set is more efficient?
If that's the case, we can probably use EWAH during mutable aggregation and Java `BitSet` in the final immutable result?

**Comment by nevillelyh** [comment]
Closing since my pending PR removes this.
