### ISSUE TITLE
Connecting To Docker via ScioContext Options

### ISSUE THREAD

**Issue by akashsethi-dh** [spotify/scio#1991]
Hi,

I am using the google-emulator for bigTables and I want to point or change the default adminHost, dataHost and port. But Using the BigTableOptions I specified all three value [i.e. adminHost, dataHost and port] but it was still connecting to the bigquery server instead of connecting to docker container for the same.

When I was looking the code then its turns out that scio is only using the projectId and instanceId from the bigTableOptions and king of ignoring the other options.

Is there any other way I can point to docker Container?

Thanks

**Comment by nevillelyh** [comment]
@akashsethi-dh looks like #2003 should fix this for you?
