### ISSUE TITLE
Coder derivation for nested case class

### ISSUE THREAD

**Issue by cmiao** [spotify/scio#1992]
Here is my simplified case class, when I try to generate Coder for it, different behaviours are observed, can someone help explain them ? Thanks!
```scala
import com.spotify.scio.coders.Coder

case class SampleField(name: String, fieldType: SampleFieldType)

sealed trait SampleFieldType
case object IntegerType extends SampleFieldType
case object StringType extends SampleFieldType
case class RecordType(fields: Vector[SampleField]) extends SampleFieldType
```
**Compiler error when trying to derive coders**

```scala
implicit val fieldTypeCoder = Coder[SampleFieldType]  
implicit val fieldCoder= Coder[SampleField]
// Cannot find an implicit Coder instance for type:
// [error] 
// [error]   >> pipeline.SampleField
//...
```
**Coders are null when type annotations are added**

```scala
implicit val fieldTypeCoder: Coder[SampleFieldType] = Coder[SampleFieldType]  // fieldTypeCoder: null
implicit val fieldCoder: Coder[SampleField] = Coder[SampleField] // fieldCoder: null
```

**Coders derived successfully when a random class added in between**
```scala
implicit val fieldTypeCoder = Coder[SampleFieldType]  // fieldTypeCoder: Disjunction(pipeline.SampleFieldType, Map(0 -> Record(pipeline.IntegerType, ), 1 -> Record(pipeline.RecordType, (fields, Fallback(scala.collection.immutable.Vector))), 2 -> Record(pipeline.StringType, )))

case class Foo()  
implicit val fooCoder = Coder[Foo]  // fooCoder: Record(pipeline.Pipeline.Foo, )
  
implicit val fieldCoder= Coder[SampleField] // fieldCoder: Record(pipeline.SampleField, (name, Beam(StringUtf8Coder)), (fieldType, Disjunction(pipeline.SampleFieldType, Map(0 -> Record(pipeline.IntegerType, ), 1 -> Record(pipeline.RecordType, (fields, Fallback(scala.collection.immutable.Vector))), 2 -> Record(pipeline.StringType, )))))
```

**Comment by jto** [comment]
This is likely to be a bug in the Coder derivation. I'll need to have a look at it.

**Comment by anish749** [comment]
I have faced a similar issue, and it is confusing.

I am not sure if my explanation is correct, but here are my thoughts, @jto might be able to explain better. 

`Coder[SampleField]` is calling `Coder.apply[T](implicit c: Coder[T])` this requires an implicit `Coder[T]`  The compiler now starts searching for an implicit, and finds it defined as `implicit val xyzCoder: Coder[SampleField] = ....` It now places this implicit there. The actual coder derivation code was never called by the compiler.

**Coders are null**
During run time, when the object is created all `val`s are allocated, but the Coder derivation happens at compile time. Hence during run time it gets the default value of an Object of type Coder that was supposed to be there from compile time. This seems very counter-intuitive. You cannot derive a Coder[T] at compile time and see that as a value (`val`) at run time.

How I fixed it was to use `implicit def coderSampleField: Coder[SampleField] = Coder.gen[SampleField]`
this would succeed if all coder implicit of the parameters are present, else it would give an error about not finding a `LowPriority` implicit.

 - Defining an implicit shouldn't call another implicit (`Coder[T]`).
 - Coders should be `implicit def`, not `implicit val`

**Coders derived successfully when a random class added in between**
I don't know

**Comment by regadas** [comment]
I took a moment to look at this and indeed there's a bug. This seems to be related to typeclass derivation of recursive types.

**Comment by jto** [comment]
Working on this.

**Comment by jto** [comment]
## Automatic derivation

```
case class SampleField(name: String, fieldType: SampleFieldType)
sealed trait SampleFieldType
case object IntegerType extends SampleFieldType
case object StringType extends SampleFieldType
case class RecordType(fields: Vector[SampleField]) extends SampleFieldType

"Coder[SampleField]" should compile
"Coder[SampleFieldType]" should compile

SampleField("hello", StringType) coderShould roundtrip()
```

✅ compiles and run properly.

## Compiler error when trying to derive coders

```
implicit val fieldTypeCoder: Coder[SampleFieldType] = Coder[SampleFieldType] 
implicit val fieldCoder: Coder[SampleField] = Coder[SampleField]
```

This does not compile and gives

```
[error] [E8] scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
[error]      forward reference extends over definition of value fieldTypeCoder
[error]      L469:     implicit val fieldTypeCoder: Coder[SampleFieldType] = Coder[SampleFieldType]
[error]                                                                           ^
[error] [E9] scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
[error]      forward reference extends over definition of value fieldCoder
[error]      L470:     implicit val fieldCoder: Coder[SampleField] = Coder[SampleField]
```
✅ makes sense bc. the implicit is basically referencing itself. No derivation involved here.

## Coders are null when type annotations are added

✅  Gives the same compilation error.

I suspect you only see those errors bc. you're testing in a Scala REPL and not in a "proper" scala file.

@regadas what's the bug you found ?

**Comment by anish749** [comment]
@jto 

The test case that you wrote works, because one of the classes in falling back to Kryo. I think it is the one with `Vector`. I need to check again.

The following minimal example doesn't compile:

```
case class Outer(a: Inner)
case class Inner(o: Outer)

object RecurType {
  def main(args: Array[String]): Unit = {
    def c = Coder[Outer]
  }
}
```

**Comment by jto** [comment]
Hum good catch. Will look into this.

**Comment by regadas** [comment]
@jto hm yeah, the fallback is hiding the issue. I only had a quick look at this  but iirc the issue here is that we are ignoring the generated `lazy val` tree. However if we don;t ignore it we rapidly get a `StackOverflowException` when get the typeclass instance for a given `Param` here https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala#L40
