### ISSUE TITLE
PubsubIO reads should use beam.PubsubIO#withCoderAndParseFn to transform messages

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#1994]
This ticket is an extension of https://github.com/spotify/scio/issues/1970 root cause. Instead of performing a `beam.PubsubIO.Read` then a map from `PubsubMessage => T`, we can use [withCoderAndParseFn](https://github.com/spotify/beam/blob/0255c3284f34e8a40e11ee7d470b1c3d277d40e1/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java#L779) directly.

This method will be made public in Beam 2.14.

**Comment by regadas** [comment]
Cool this will be nice!

**Comment by nevillelyh** [comment]
We're on 2.14. now so this is unblocked.

**Comment by ClaireMcGinty** [comment]
It should be in [2.15.0](https://github.com/apache/beam/blob/release-2.15.0/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java#L791).
