### ISSUE TITLE
support accessing all counters within JobTest

### ISSUE THREAD

**Issue by catherinejelder** [spotify/scio#2007]
I would like to be able to access counters within in a JobTest without knowing their names in advance, maybe with a `.counters` method that returns all counters.

**Comment by nevillelyh** [comment]
Should be easy to impl. It's a matter of adding methods similar to `counter/distribution/gauge` [here](https://github.com/spotify/scio/blob/master/scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala#L167) that take an assertion `fn` and calling it in the `metricsFn` [here](https://github.com/spotify/scio/blob/master/scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala#L218).

**Comment by ra1861** [comment]
@catherinejelder Can you, please, provide an example code snippet, showing how do you want _to access counters within in a JobTest_.
