### ISSUE TITLE
BigQueryType failing for Repeated[Record] type

### ISSUE THREAD

**Issue by nownikhil** [spotify/scio#2068]
Exception: java.lang.ClassCastException: scala.collection.convert.Wrappers$SeqWrapper cannot be cast to org.apache.avro.generic.GenericData$Array

I am trying to convert GenericRecord to CaseClass, BigQueryType fails while AvroType succeeds.
Code to reproduce error:

```
case class Repeat(field1: String)
case class QQ(repeat: List[Repeat])

 def main(args: Array[String]): Unit = {
    val converter = AvroType.fromGenericRecord[QQ]
    val bqConverter = BigQueryType.fromAvro[QQ]

    val s = "{ " + "\"type\" : \"record\", " +
      "\"name\": \"GenericAccountRecord\", " +
      "\"fields\": [ " +
      "{\"name\": \"repeat\", \"type\": {" +
      "\"type\": \"array\", \"items\": {\"type\": \"record\", \"name\": \"somename\", \"fields\": [{ \"name\": \"field1\", \"type\": \"string\" }] }" +
      "}}" +
      "]" +
      "} "

    val schema = new Schema.Parser().parse(s)
    val repeatedRecord1 = new GenericRecordBuilder(schema.getField("repeat").schema().getElementType)
    repeatedRecord1.set("field1", "val-field1")
    val repeatedRecord2 = new GenericRecordBuilder(schema.getField("repeat").schema().getElementType)
    repeatedRecord2.set("field1", "val-field2")
    val genericRecordList: List[GenericRecord] = List(repeatedRecord1.build(), repeatedRecord2.build())

    val record = new GenericRecordBuilder(schema)
    record.set("repeat", genericRecordList.asJava)

    val genRecord = record.build()
    val caseRecord = converter(genRecord)
    println(caseRecord)
    println(bqConverter(genRecord))

}
```

Output:
QQ(List(Repeat(val-field1), Repeat(val-field2)))
java.lang.ClassCastException: scala.collection.convert.Wrappers$SeqWrapper cannot be cast to org.apache.avro.generic.GenericData$Array
....

Implementation for list type is different for AvroType and BigQueryType

https://github.com/spotify/scio/blob/master/scio-avro/src/main/scala/com/spotify/scio/avro/types/ConverterProvider.scala#L89

https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala#L115

**Comment by ClaireMcGinty** [comment]
hey! Is this an issue you're seeing on real Avro data or just in this test case? Since in practice `GenericData` does implement repeated types using `GenericData.Array`, a subtype of `List`, whereas in your test data you're just using a wrapped Java list directly. Although I don't see why we couldn't change the BigQuery `fromAvro` macro to cast to a plain Java list instead of `GenericData.Array`, since it's a subtype

**Comment by nownikhil** [comment]
I am seeing it in real data while trying to read from BigQuery. I changed it locally to java.util.List and it worked.

**Comment by nevillelyh** [comment]
I can verify that changing `.asInstanceOf[GenericData.Array[AnyRef]]` to `.asInstanceOf[List[AnyRef]]` fixes the issue. The former was too narrow anyway. I'll submit a PR.
