### ISSUE TITLE
Document / Example for ScioExecutor / ScioRunner

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2074]
We have the `sc.run(ScioRunner)` [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L659), but it is not well documented? Is this supposed to be exposed publicly?

In connection with #2030 #1848 and #1682 ,
Ideally for this to be a public API, we should have 

`def run(executor: ScioExecutor): ScioExecutionContext = executor.run(this)`

This is because `ScioRunner` is a sealed trait, and `ScioExecutor` is not. Is my understanding correct or what is the suggested fix?

I am trying to define my `ScioExecutor` as:

```scala
  class WrappedScioExecutor extends ScioExecutor {
    private val delegatedDefaultExector = ScioRunner.default
    override def testId(sc: ScioContext): Option[String] = delegatedDefaultExector.testId(sc)
    override def isTest(sc: ScioContext): Boolean = delegatedDefaultExector.isTest(sc)
    override def run(sc: ScioContext): ScioExecutionContext = {
      // Things to run before calling `run`
      val ctx = delegatedDefaultExector.run(sc)
      // Things to run after calling `run`
     ctx
    }
  }
```

On another note, `ScioRunner` might be a overloaded term, and cause confusion with other "Runner"s

**Comment by regadas** [comment]
Hi @anish749! Thanks for reporting this! We are still in alpha phase and we are in the process of documenting all the changes that `0.8.x` will have.

Regarding `ScioRunner` the existing api is the intended one. `ScioRunner` is not overridable and it's required, i.e:

```scala
val sc: ScioContext = ???

sc.run(ScioRunner(new ScioExecutor { ... }))

// alternative

ScioRunner(new ScioExecutor { ... }).run(sc)
```

Regarding the name,  yes ... it still might be subjected to change.

**Comment by regadas** [comment]
Documentation for this will be part of #2075

**Comment by anish749** [comment]
Thanks, I was testing out the alpha version, and documenting the changes required in our repos.

Out of curiosity, why is `ScioRunner(new ScioExecutor { ... })` pattern needed?

**Comment by regadas** [comment]
@anish749 there's some logic that needs to run regardless of the provided `ScioExecutor` like setting up counters and so on.

Also it's nice to provide both alternatives, so we need to make sure the same stuff get's applied in both situations.

I noticed that we require a small change to this though to actually make this the only way to run.

**Comment by regadas** [comment]
Closing this one now ... part of #2076
