### ISSUE TITLE
An alternate constructor for Coder.xmap

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2089]
I was seeing a few cases where I want to use private constructors, and not fallback on Kryo coders.

For this I was resorting to `Coder.xmap`. I think it would be nice to have something like the following:
```
def using[A, B](f: A => B, t: B => A)(implicit coderA: Coder[A]): Coder[B] = Coder.xmap(coderA)(f, t)
```

This would make Coder definitions more intuitive / easier to read.

I am drawing the function signature from `Ordering.by`
```
def by[T, S](f: T => S)(implicit ord: Ordering[S]): Ordering[T]
```

**Comment by regadas** [comment]
@anish749 yeah i think we can improve the `CoderGrammar` api.

`disjunction` as a `Coder` as context bound so the api seems unbalanced. Maybe we can add a few methods there and also probably rename `xmap` to `imap` which is what it really is 😄

**Comment by jto** [comment]
Not sure I see the benefit. You can just write `Coder.xmap(Coder[A])(f, t)` and be done with it. Why would you need more ?

**Comment by jto** [comment]
Does not seem like a lot of value and has not seen any activity since the issue was open. Closing.
