### ISSUE TITLE
Custom metrics in StackDriver

### ISSUE THREAD

**Issue by david-cromberge** [spotify/scio#2094]
I would like to ask how to report custom metrics from a SCIO job to StackDriver?

My current job is using the dataflow runner, and I have a simple metric defined within my transform logic as follows:

```scala
private val expandFactor = ScioMetrics.counter("expansion_factor")
```

It is my understanding that there are certain [naming conventions](https://cloud.google.com/monitoring/custom-metrics/) to adhere to when using Stackdriver, none of which present a problem to my example name above.  

I would be grateful if somebody could specify whether this scenario is supported, and if so, how to go about reporting metrics for use in StackDriver.  I cannot seem to locate any of my custom metrics in the metrics explorer as yet.

Affected version: v0.8.0-alpha2

**Comment by david-cromberge** [comment]
This may have been related to the fact that I was originally using a gauge, which may not have been supported.  The counter is showing up correctly in the StackDriver metrics explorer.  Thanks!

**Comment by Incomplete95** [comment]
Hi @david-cromberge, I have the same issue which is metrics don't show in metrics explorer of stackdriver, but I'm logging `Distribution` and `Counter`. So I'm thinking if some codes are missing, maybe some function to report metrics I guess. Which function did you use to report the metrics after creating and using them? Is that call within your transform or after the pipeline finishes? Thanks!
