### ISSUE TITLE
Inconsistent type of `thatNumKeys`

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2103]
The estimated number of keys used to construct Bloom Filters in `sparse*` transforms. It's `Long` pretty much everywhere except `sparseIntersectByKey`.

@anish749 any particular reason?

https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala#L883

**Comment by anish749** [comment]
I don't think this should be different. It looks like a bug which was there.
I played around a bit, and it is somewhat okay..
`BFSettings(width: Int, capacity: Int, numBFs: Int)`
```
optimalBFSettings("", Int.MaxValue.toLong + 2, 0.01)
= BFSettings(1286484759,134217728,17)
```

We can make it `Long` for the time being,

But there are some checks that we should put around this. I need some time to understand and debug this. I believe there are some things overflowing here and there, but not sure.


```
optimalBFSettings("", Int.MaxValue.toLong * Int.MaxValue, 0.99)
=BFSettings(2807628,134217728,-31)
```
```
 optimalBFSettings("", Long.MaxValue, 0.99)
= BFSettings(2807628,134217728,0)
```
The number of BFs doesn't look right. Not sure how this would behave at that scale.

**Comment by nevillelyh** [comment]
`Int.MaxValue.toLong * Int.MaxValue` will definitely overflow the BF ;)
I guess we keep `Long` to make it less likely to overflow, and add some sanity checks if needed.
