### ISSUE TITLE
JsonIO requires Encoder and Decoder for read or write

### ISSUE THREAD

**Issue by sisidra** [spotify/scio#2123]
`com.spotify.scio.extra.json.JsonSCollection` requires implicit `Decoder` for elements although it needs only `Encoder` for writing.

Similarly `com.spotify.scio.extra.json.JsonScioContext#jsonFile` requires implicit `Encoder` for elements although it only needs `Decoder` for reading.

Desired API:
* Only Encoder is needed for writing json data
* Only Decoder is needed for reading json data

**Comment by regadas** [comment]
@sisidra makes sense thanks for spotting this! 👍

**Comment by sisidra** [comment]
@regadas The writer api seems to be coupled with reader api because it requires to return a tap for reading. What is your take on how to deal with it for situations like this issue?

**Comment by sisidra** [comment]
Maybe another option would be to maintain multiple classes - WriteOnlyIO, ReadOnlyIO and ReadWriteIO (reusing previous 2?). Smth like that..
Not ideal, but not a fan of changing a data type of a Tap either. :/

**Comment by regadas** [comment]
we can at least remove the need for `Encoder` in `jsonFile` #2141 

TBH, not sure if it's worth adding a new IO and respective `saveAsJson` that returns `String` and hence removing the need for `Decoder[T]`

**Comment by sisidra** [comment]
Doesn't ScioIO signature prevent different types for tap and scollection itself i.e. is it possible to make tap type `String`?

**Comment by regadas** [comment]
@sisidra yup we prevent it, because seems a bit incoherent to have `ScioIO[T]` and then have a write that returns `Tap[B]`. My point (and sorry for the confusion with the new IO) was more into add a new method `saveAsJson` where we basically `jsonColl.map(encode).write(TextIO)` hence my doubt if we should add it or not

**Comment by regadas** [comment]
Closing this. #2141 improves current implementation. 

Writing without adding a `Decoder` can be done as I mentioned in previous comment.
