### ISSUE TITLE
BigQuery Storage API query string support.

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2137]
From Beam doc:
> SDK versions 2.11.0 and 2.12.0 do not support reading with a query string; you can only read from a table.

We implemented Storage API support a while ago that reads from table only. Need to look into this. 

https://issues.apache.org/jira/browse/BEAM-7033
https://issues.apache.org/jira/browse/BEAM-7034

**Comment by regadas** [comment]
Closed via #2204
