### ISSUE TITLE
SideOutput + Flatten Example

### ISSUE THREAD

**Issue by cejj** [spotify/scio#2148]
Hi,

I was trying to build a pipeline which generates multiple outputs and then combines them something similar to in Java as shown below

```
PCollectionList<String> collectionList = PCollectionList.of(aCollection).and(bCollection);
PCollection<String> mergedCollectionWithFlatten = collectionList
    .apply(Flatten.<String>pCollections());

// continue with the new merged PCollection
mergedCollectionWithFlatten.apply(...);

```

How do I do this in Scio with SideOutputs?

Thanks,
Jayadeep

**Comment by regadas** [comment]
Hi @cejj what you want in scio is a `union` we have several examples where you see `union` being used i.e https://spotify.github.io/scio/examples/TriggerExample.scala.html

you can also check https://github.com/spotify/scio/blob/efe05e2829bc21c779167192822383a0d37cab8c/scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala#L81-L131

**Comment by regadas** [comment]
Hope this helps! Closing for now
