### ISSUE TITLE
Support for both legacy and SQL 2011 BigQuery syntax

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#216]
It's probably better to support both in parallel for easy transitioning. There're 2 options as I see it.

1 Feature flag. To do this we need

- Some annotation e.g. `@BigQueryOptions.legacySql` to be used with `@BigQueryType.fromQuery`
- Additional Boolean arguments to `ScioContext#bigQuerySelect`, `BigQueryClient#getQueryRows` and `BigQueryClient#getQuerySchema`, etc.

2 Automatically detect query syntax

- Either with comments in the query string i.e. `-- legacy.sql=true`
- Or by patterns in the query string, e.g. `[project:dataset.table]` vs `` `project.dataset.table` ``

I'm leaning towards 2 but not sure which solution. Comments is more predictable but seems hacky. Automatically detection sounds nice but there might be edge cases?

**Comment by andrewsmartin** [comment]
@nevillelyh +1 on automatic detection - AFAIK just the presence of a `:` in the query string should be enough because to the best of my knowledge it is not allowed in field names and isn't part of the language itself, only the project name in legacy SQL. Will have to double check this though.

**Comment by andrewsmartin** [comment]
The only downside is that there isn't an explicit way for users to switch in the future - as in it's not so obvious that just changing the query syntax is all that's needed. But as long as we document it I guess it's fine?

**Comment by nevillelyh** [comment]
There're a few catch though. In legacy SQL project name can be omitted, i.e. `[dataset.table]` and it'll default to the billing project. Also there could be extreme edge cases like `WHERE field LIKE "[abc:def.ghi]"`. Just wanna make sure we cover all the grounds.

**Comment by nevillelyh** [comment]
http://stackoverflow.com/questions/39003334/programmatically-detemine-if-a-query-is-legacy-or-sql-2011-syntax

**Comment by nevillelyh** [comment]
Got auto detection working in https://github.com/spotify/scio/tree/neville/bq
Need to polish it up and add integration tests before submitting PR

**Comment by ravwojdyla** [comment]
Is it really a problem for users to decide which syntax to use, and which deps to select? I would prefer to be explicit over implicit, and just stick with the simple and _working_ solution - separate deps, with going forward default to sql-2011 starting from scio `0.2.0`? I see how this is a fancy etc - but why complicate things (less code -> less bugs)?

**Comment by nevillelyh** [comment]
Fixed in #218
