### ISSUE TITLE
sbt pack doesn't work

### ISSUE THREAD

**Issue by ra1861** [spotify/scio#2162]
If one follows [README](https://github.com/spotify/scio/blob/master/README.md#quick-start)
~/projects/common/scio (master % u=)$ sbt pack
[info] Loading settings for project scio-build from plugins.sbt ...
[info] Loading project definition from ./projects/common/scio/project
[info] Loading settings for project scio from version.sbt,apache.sbt,build.sbt ...
[info] Resolving key references (27522 settings) ...
[info] Set current project to scio (in build file:./projects/common/scio/)
[error] Expected ';'
[error] Not a valid command: pack (similar: tasks, cc)
[error] Not a valid project ID: pack
[error] Expected ':'
[error] Not a valid key: pack (similar: package, packageDoc, packageSrc)
[error] pack
[error]     ^

**Comment by nevillelyh** [comment]
Are you running from this repo?

README says generate new project with the template first. 
`sbt new spotify/scio.g8`

**Comment by ra1861** [comment]
Sorry, I after trying a few times I understand now that the doc actually mean.
Created a PR to address this issue: #2163 .

**Comment by luli2949** [comment]
Hi there,
I followed the instructions to first run `sbt new spotify/scio.g8` and then `cd scio-job/` and then when I run `sbt pack`,
I encounter the same issue as you have. What did you end up doing to fix this problem? Below is the output from my terminal. Thanks!

> (base) ebm-guest-10-164-240-221:scio-job luli$ sbt new spotify/scio.g8
> [info] welcome to sbt 1.4.0 (N/A Java 14.0.1)
> [info] loading settings for project scio-job-build from plugins.sbt ...
> [info] loading project definition from /Users/luli/scio-job/project
> [info] loading settings for project root from build.sbt ...
> [info] set current project to scio-job (in build file:/Users/luli/scio-job/)
> [warn] there's a key that's not used by any other settings/tasks:
> [warn]  
> [warn] * root / run / classLoaderLayeringStrategy
> [warn]   +- /Users/luli/scio-job/build.sbt:32
> [warn]  
> [warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
> [warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
> [info] set current project to scio-job (in build file:/Users/luli/scio-job/)
> name [scio job]: organization [example]: DataflowRunner [yes/NO]: DataflowFlexTemplate [yes/NO]: FlinkRunner [yes/NO]: SparkRunner [yes/NO]: Skipping ignored file: /var/folders/fy/ynsb40pd2rs5zhtmx3jnwkww0000gn/T/giter8-186108428049915/src/main/g8/$if(DataflowFlexTemplate.truthy)$metadata.json$endif$
> 
> Template applied in /Users/luli/scio-job/./scio-job
> 
> (base) ebm-guest-10-164-240-221:scio-job luli$ cd scio-job/
> (base) ebm-guest-10-164-240-221:scio-job luli$ sbt pack
> [info] welcome to sbt 1.4.0 (N/A Java 14.0.1)
> [info] loading settings for project scio-job-build from plugins.sbt ...
> [info] loading project definition from /Users/luli/scio-job/scio-job/project
> [info] loading settings for project root from build.sbt ...
> [info] set current project to scio-job (in build file:/Users/luli/scio-job/scio-job/)
> [warn] there's a key that's not used by any other settings/tasks:
> [warn]  
> [warn] * root / run / classLoaderLayeringStrategy
> [warn]   +- /Users/luli/scio-job/scio-job/build.sbt:25
> [warn]  
> [warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
> [warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
> [error] Not a valid command: pack (similar: tasks)
> [error] Not a valid project ID: pack
> [error] Expected ':'
> [error] Not a valid key: pack (similar: package, rpmPackger, packageDoc)
> [error] pack
> [error]     ^
> 
>

**Comment by regadas** [comment]
Hi @luli2949 sorry about this. The steps were a bit outdated. I just updated them to reflect the update scio.g8

https://github.com/spotify/scio/blob/master/README.md#L35-L61
