### ISSUE TITLE
Document `scio.ignoreVersionWarning`

### ISSUE THREAD

**Issue by NJAldwin** [spotify/scio#2175]
Each time a `ScioContext` class is initialized, scio makes a HTTP call to GitHub to check if there's a newer version.  If there is, it logs a warning.

The warning itself can be disabled with the system property `scio.ignoreVersionWarning`, and now that flag disables the HTTP call too as of #2173.

However, this is still undocumented.  It currently defaults to enabled, always making this call, but there's no indication of it anywhere in the docs or in the logs unless there's a new version available.  Since it's a really dangerous thing to run arbitrarily in production, it should definitely be documented, loudly.  (I'd say it should even be disabled by default, but that's a separate issue).

**Comment by nevillelyh** [comment]
Mind making a PR? Maybe in the FAQ page?

**Comment by nevillelyh** [comment]
Alternatively we can do the check only in testing, by checking `ScioContext.isTest`, WDYT?
