### ISSUE TITLE
scio-spanner 0.7.4 does not work with scio 0.7.4

### ISSUE THREAD

**Issue by spkrka** [spotify/scio#2189]
When serializing spanner classes - Mutation, Struct, et.c. - scio falls back to using kryo, which fails to serialize them:
```
Cause: java.lang.UnsupportedOperationException:
at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:222)
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
```

There is a fix for that in this commit: https://github.com/spotify/scio/commit/502f48ecd2926fd8efec022b3fd4ebc6d04e704c
but it was never released.

Suggested fix: make a new release of scio-spanner.

**Comment by nevillelyh** [comment]
Gonna close this as a won't fix since we're moving forward with 0.8 releases.
