### ISSUE TITLE
Remove scalastyle

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2200]
Given that currently most of the codebase relies on `scalafmt` and `scalafix` to keep the codebase in check, I don't think that `scalastyle` provides enough value anymore and in fact sometimes can be a bit annoying.

**Comment by nevillelyh** [comment]
They aren't 100% equivalent though? There're things covered by scalastyle only like license header?

**Comment by regadas** [comment]
It's true they are not; but i found that most of things don't really provide that much value; I find myself most of the time ignoring it and scalafmt/scalafix do a really good job in avoiding/fixing some of the common pitfalls;

RE: headers we can use `sbt-header` to check and add the same header everywhere.

**Comment by jto** [comment]
👍 Let's get rid of scalastyle.
