### ISSUE TITLE
Use vendored Guava from Beam

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2206]
This is a bit inline if the effort of reducing guava usage #2205. The idea is to minimize possible breaking changes/conflict dependencies.

We have a couple of more places where we use `Guava` directly:

* [GuavaAsyncDoFn](https://github.com/spotify/scio/blob/master/scio-core/src/main/java/com/spotify/scio/transforms/GuavaAsyncDoFn.java)
* [GuavaAsyncLookupDoFn](https://github.com/spotify/scio/blob/master/scio-core/src/main/java/com/spotify/scio/transforms/GuavaAsyncLookupDoFn.java)
* [RemoteFileUtil](https://github.com/spotify/scio/blob/master/scio-core/src/main/java/com/spotify/scio/util/RemoteFileUtil.java)

WDYT, about using `Beam`'s vendored version?

**Comment by nevillelyh** [comment]
Not sure we can use vendored ones for those cases since the async client is user supplied and most likely using vanilla `com.google` guava.

**Comment by regadas** [comment]
Yup agreed, we should keep it to a min! 

Yeah the first two cases, I agree with you, since they are user facing might be problematic! However, we do have plenty of internal stuff that is not exposed and those are very good candidates I think.

**Comment by nevillelyh** [comment]
:+1: on reducing dependency or using vendored ones whenever possible.

**Comment by nevillelyh** [comment]
After #2242, all gone except public API e.g. `AsyncDoFn` and internals of forked code, e.g. cassandra, examples. Closing for now.
