### ISSUE TITLE
Move away from Hash128[K] bounds for scio's transforms

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2218]
`Hash128` is needed for all transforms that use `BloomFilter`s. Internally this typeclass provides the actual hashing algorithm to be used. The default implementation is only available for primitive types, and converts each element to a `ByteBuffer` and then uses `CassandraMurmurHash`.

Exposing this to the user has the benefit of allowing the user to override the Hash algorithm. and the drawback of having another context bound and a bit hard to use non-primitive types.

Given that Scio already has `Coder` as a context bound on all those transforms, we can partially reuse this. We can use the materialized Beam Coders to convert any type `T` to a `Array[Byte]` and then use the `Hash128[Array[Byte]]` to hash.

Benefits:
 - This removes the implicit context bound of `Hash128`.
 - We can now leverage `Coder` derivations in Scio so that these transforms work for a lot of types instead of just primitive types out of the box.

Drawback:
 - The user can't override the hashing algorithm. (Is this needed?)

This had been in my mind for while now, and I tried to test this out for a small pipeline (6.5M elements) and I don't any difference in performance.

**Comment by nevillelyh** [comment]
Related to #1999 

:+1: on this. The implicit hash instances can also be confusing when one uses non-standard key, e.g. case classes or tuples as recently discussed on internal SO.

I don't think most people override hashing fn. And even though this might break backwards compat, but only when people explicitly pass in `Hash128[K]` explicitly. So yeah we should do this as part of the BF refactor.

**Comment by anish749** [comment]
Perfect. Here is the example code I tried:

Will try to make these into a PR sometime soon, but I was thinking about fixing #1997 separately since this change is a breaking change and a major version is in beta now, so might as well make the breaking change with 0.8 instead of having a breaking change in a patch version. WDYT?

```scala
/**
 * Helper class which gives a `T` => `Array[Byte]` encode function using a beam Coder.
 */
private[scio] case class ByteArrayEncoder[T](beamCoder: beam.Coder[T]) {
  @transient
  private lazy val bos = new ByteArrayOutputStream()
  def encode(t: T): Array[Byte] = {
    bos.reset()
    beamCoder.encode(t, bos)
    bos.toByteArray
  }
}

/**
 * Utilies to derive a Hash128[K] or a [[ByteArrayEncoder]] from a [[Coder]]
 * for a given [[ScioContext]]
 */
private[scio] object ByteArrayEncoder {

  /**
   * Given a type `T` with a [[Coder]] context bound, gives a [[ByteArrayEncoder]] for
   * that type and the given ScioContext
   */
  def apply[T: Coder](sc: ScioContext): ByteArrayEncoder[T] =
    ByteArrayEncoder(CoderMaterializer.beam(sc, implicitly[Coder[T]]))

  /**
   * Given a type `T` with a [[Coder]] context bound, gives a [[Hash128]] for
   * that type and the given ScioContext.
   */
  def hash128[T: Coder](sc: ScioContext): Hash128[T] = {
    val bae = apply(sc)
    Hash128.arrayByteHash.contramap(bae.encode)
  }
}
```

Usage:
```scala
implicit val hash128: Hash128[K] = ByteArrayEncoder.hash128(self.context)
```

**Comment by regadas** [comment]
I have some concerns about this; Modifying the hash algo might be something that very few do (or even none; that we know of) However, I like the idea of allowing customization and the idea of keeping Hash separate from Coder. Even-though we can use them together both can be optimized differently; I don't like the idea of `Coder[T]` potentially change Hashing properties; Coder's a kinda optimized for wire.

Primitive types is a valid point, we could come up with a new Hash typeclass that is specialized. This would probably benefit other implementations and would allow us to decouple even more from algebird;

regarding context bounds, we could eventually offer extra methods with hash as a param; but i don't get why is it a problem.

**Comment by anish749** [comment]
Closing this, as we now use Guava's Funnel instead.
