### ISSUE TITLE
ContextAndArgs.typed no longer accepting lisp-case args

### ISSUE THREAD

**Issue by danielnorberg** [spotify/scio#2221]
In Scio 0.8.0-beta1 `ContextAndArgs.typed` stopped accepting lisp-case arguments. This change seems to have been introduced in https://github.com/spotify/scio/pull/1780 in response to https://github.com/spotify/scio/issues/1770. Deprecating lisp-case is mentioned in https://github.com/spotify/scio/issues/1770 but should we really drop support completely in 0.8? Existing code/scheduled workflows/pipelines using lisp-case will break.

Repro: 

```scala
object LispCaseArgsTest {
  case class MyArgs(fooBar: String)
  def main(args: Array[String]): Unit = {
    val (sc, argz) = ContextAndArgs.typed[MyArgs](Array("--foo-bar", "baz"))
    assert(argz.fooBar == "baz")
  }
}
```

The above works in 0.7.4 but fails with `java.lang.Exception: Required option --foo-bar not specified` in 0.8.0-beta1.

**Comment by regadas** [comment]
Hi @danielnorberg! yeah indeed some of the pipelines might break; they will not start; The end goal is to be consistent with Beam, but i guess we could support both at the same time (issuing deprecated warns if used) and remove support for it after 0.8.

**Comment by nevillelyh** [comment]
I'm leaning towards skipping "deprecation" since it'll be a runtime not compile warning, and will most likely be ignored. So it'll hit people again once we remove it.

**Comment by regadas** [comment]
On a second thought I agree with @nevillelyh ppl will not look at the logs and it will be same thing once we actually remove it ... so we remove it now. Let's jsut document this in the Migration doc.
