### ISSUE TITLE
Support `readFiles` in addition to/instead of `readAll` in `SCollection`

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#2263]
`ReadAll` methods in Beam are [being deprecated in favor of `ReadFiles`](https://lists.apache.org/thread.html/ebd369a1de528981473031a439d381ec2a721bf4bc7fb12c94081136@%3Cdev.beam.apache.org%3E)--we could probably deprecate [`SCollection#readAll`](https://github.com/spotify/scio/blob/f8c9df51deff5f9e67fa0a35145828911221ffb1/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L1069) and add a `def readFiles[U: Coder](read: PTransform[PCollection[FileIO.ReadableFile], PCollection[U]])` method as its successor?

**Comment by syodage** [comment]
@ClaireMcGinty checked on this a bit,  it seems SCollection#readAll doesn't comply with the FooIO#readAll even though both has the same method name(may be they were when it was introduced but not now, another example we shouldn't completely trust the scala docs). SCollection#readAll gets a PTransfrom[String] and return a PTransform[U], as it sounds this is simply a convenient wrapper for SCollection#applyTransform method. 

I suggest to deprecate this method in favor of applyTranform and remove in future release as it may confuse with the FooIO.readAll method as we did now.
