### ISSUE TITLE
SCollection of recursive types produces NotSerializableException

### ISSUE THREAD

**Issue by jgogstad** [spotify/scio#2269]
I'm new to this project, so please bear with me.

I have a `SCollection` with a type referring to a recursive type, it produces this exception when I `flatMap` over it

```
Caused by: java.io.NotSerializableException: PipelineOptions objects are not serializable and should not be embedded into transforms (did you capture a PipelineOptions object in a field or in an anonymous class?). Instead, if you're using a DoFn, access PipelineOptions at runtime via ProcessContext/StartBundleContext/FinishBundleContext.getPipelineOptions(), or pre-extract necessary fields from PipelineOptions at pipeline construction time.
        at org.apache.beam.sdk.options.ProxyInvocationHandler.writeObject(ProxyInvocationHandler.java:176)
```

I reproduced the error in the test for derivation of recursive encoders, please see the linked PR.

This is the problematic path, if it's not obvious to you:

* `com.spotify.scio.values.PCollectionWrapper.parDo` materializes the coder, [link](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala#L58). This gives a `com.spotify.scio.coders.WrappedBCoder`.
* [`CoderTranslation.toProto`](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/CoderTranslation.java#L82) does not recognize `WrappedBCoder` and to triggers serialization through [`toCustomCoder`](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/CoderTranslation.java#L113)

Please note that this path is not caused by the recursive type, but the recursive types fails to serialize with the error above.

**Comment by ClaireMcGinty** [comment]
interesting, I looked at your example, @jto do you think it's possible the lazy recursive reference to `bc` in CoderMaterializer is somehow bringing `o: PipelineOptions` into the closure? https://github.com/spotify/scio/blob/ca8d49c16adf30ce41e9d27e6729d4ee9422e360/scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala#L90

**Comment by jto** [comment]
@ClaireMcGinty Yeah that's definitelly what happening bc. of the lazy val. I totally overlooked it when I tried to support recursion in 1ce2c4b
