### ISSUE TITLE
Enforce explicit naming of execution steps

### ISSUE THREAD

**Issue by yhrn** [spotify/scio#2301]
To make it as easy as possible to keep streaming jobs updatable it would be great if there was a way to enforce explicit naming of all steps.

For example, there could be a way of configuring the Scio context in such a way that the pipeline will fail startup if a step without an explicit name is encountered, or there could be some simple helper mechanism for writing a test that will fail if there are such steps.

**Comment by nevillelyh** [comment]
How are you setting it? Maybe it's not propagated to the test?

**Comment by yhrn** [comment]
I was hard coding it in my main job class along with a bunch of other options that definitely has an effect and I was also printing out the options before creating a `ScioContext` from them and could see that this option got set.

**Comment by nevillelyh** [comment]
Actually I was wrong. `StableUniqueNames` only guarantees that all transforms have unique names, which they already do, even with our auto-generated ones e.g. `flatMap@MyJob.scala:123`. What we need is an option to disable the automatic call-site based name generation and warn/fail if one isn't explicitly set.

**Comment by andrewsmartin** [comment]
Been a while for me, but I agree that it's probably OK that the internal transforms can just use the given name as a prefix the callsite-based names for the internal versions are unlikely to change with any real frequency. If they do, it would be across Scio version boundaries from the user's point of view, which could complicate on-the-fly streaming updates anyway? So maybe it's an edge case we don't need to worry about.

**Comment by yhrn** [comment]
From my point of view as a streaming job owner with many downstream jobs I wouldn't see it as an edge case. I have tested updating jobs from 0.7 to 0.8 and that worked. We simply stay away from any method that results in steps that get call site based names.

**Comment by andrewsmartin** [comment]
Good to know, thanks @yhrn. @nevillelyh how feasible is it to give deterministic names to all of Scio's internal transforms? Alternatively, could Scio provide some tooling to generate a [transform name mapping](https://cloud.google.com/dataflow/docs/guides/updating-a-pipeline#Mapping) somehow?
