### ISSUE TITLE
Make AsyncDoFn aware of PipelineOptions

### ISSUE THREAD

**Issue by f-loris** [spotify/scio#2433]
While using [`BaseAsyncLookupDoFn`](https://github.com/spotify/scio/blob/163c47801aa4cce1f3bff4145637a8fb3df600cf/scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java)  I stumbled upon the case that I need to access `PipelineOptions` while creating a new client. The reason behind is, that some parameters from the `PipelineOptions` are needed to construct my client.

My proposal would be to add the `PipelineOptions` as a parameter in `newClient()`: https://github.com/spotify/scio/blob/163c47801aa4cce1f3bff4145637a8fb3df600cf/scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java#L106 This would also have the implication that calling `newClient` can only happend at `@StartBundle` as only `StartBundleContext` can provide access to `PipelineOptions`.

What do you think about this? Are there maybe some alternatives which I missed?
I'm looking forward to your feedback! I'm also open to contribute the necessary enhancements.

**Comment by nevillelyh** [comment]
`PipelineOptions` is not serializable though so it'll create extra complication. What about extracting settings you need from `PipelineOptions` as primitive types like `String`, `Int`, and pass them to your `DoFn` impl constructor as class members? You can then use them in `newClient()` without referencing `PipelineOptions`.

**Comment by f-loris** [comment]
Thanks for your quick response. Indeed, that's how I fixed it at the moment. Forgot to mention that. 

The reason why I asked is, that I thought that it might makes others live easier that they don't need to map their configuration to serializeable representations and that it is theoretically also aware of templates, where the options can change after construction.

Anyway, I'm totally fine to close this issue as I think it is not in the scope of Scio, especially considering the rare case of templates :)
