### ISSUE TITLE
Pretty Debugger

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2475]
We have `SCollection[T]#debug()` as a useful method to help with debugging unit tests / running things locally to see the output. Currently the debug() internally calls the `toString` method.

If a `Schema[T]` is available, it would be nice to show a prettified version like #2464 to the user.
```
┌──────────────────────────────┬──────────────────────────────┬──────────────────────────────┬──────────────────────────────┬──────────────────────────────┬──────────────────────────────┬──────────────────────────────┐
│int_field                     │long_field                    │float_field                   │double_field                  │boolean_field                 │string_field                  │array_field                   │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│1                             │null                          │null                          │null                          │null                          │null                          │[]                            │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘

```

To support streaming, it can show 1 table for each window frame of the SCollection.

**Comment by regadas** [comment]
After our conversation about this I thought about it a little bit more ... and ... even though this is nice I under how this will look like in the dataflow logs in google console, my guess is that will look a bit bad?

**Comment by nevillelyh** [comment]
Yeah and as I pointed out in https://github.com/spotify/scio/pull/2464#issuecomment-561223383 this won't work for a lot of types without `Schema[T]`.

**Comment by anish749** [comment]
@regadas I am not sure if this is a good idea to have it in dataflow logs, or for any runner other than the Direct Runner.

**Comment by jto** [comment]
Do we have any plan for this ? If not let's close the issue

**Comment by nevillelyh** [comment]
Closing this for now.
