### ISSUE TITLE
API is missing the 'collect' function.

### ISSUE THREAD

**Issue by seacourtaw** [spotify/scio#249]

**Comment by ravwojdyla** [comment]
@seacourtaw could you explain what would mean by `collect`? There already is `materialize` and you can use `SideInputs`.

**Comment by seacourtaw** [comment]
Sure. I was thinking of Seq.collect. Example usage: http://ochafik.com/blog/?p=393

**Comment by nevillelyh** [comment]
That was intentionally left out since it might be confused with Spark's RDD `collect()` which does something completely different.

**Comment by ravwojdyla** [comment]
@nevillelyh correct Spark's RDD has `collect()` for materializing but also functional `collect` + scalding has functional `collect`. I'm 👍 for the PR.

**Comment by seacourtaw** [comment]
@ravwojdyla, @nevillelyh: I'll see if I can get you a PR together at some point.

**Comment by andrewsmartin** [comment]
@seacourtaw my bad for stepping on your toes with https://github.com/spotify/scio/pull/268! Didn't see until now that you were considering putting up a PR yourself. Sorry about that.

**Comment by andrewsmartin** [comment]
Added in 	43f5a5f

**Comment by seacourtaw** [comment]
@andrewsmartin: no toe-stepping. I wouldn't have gotten round to this for another week or two. Many thanks.
