### ISSUE TITLE
Be more explicit about `scio-extra` support level

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2517]
Should it be marked "experimental", "beta" or something else that indicates the support level?

**Comment by ClaireMcGinty** [comment]
+1 on "experimental" since it matches Beam's language whereas for me, "beta" implies a stable release someday?

https://github.com/apache/beam/blob/261b401530a069dc0353d080418c5e4c4efaad5d/sdks/java/core/src/main/java/org/apache/beam/sdk/annotations/Experimental.java#L26-L32

**Comment by nevillelyh** [comment]
How do we implement this? Add `@experimental` to all APIs in the package? That'll only affect future release. Or just document it in README?

**Comment by regadas** [comment]
+1 in adding this to README and also adding it to the public classes.

On other news but kinda of related ... I was actually thinking in decoupling `scio-extra`. Currently whomever depends on this modules gets unfortunate situation of getting a lot of unneeded dependencies possibly leading to some unwanted issues.

**Comment by nevillelyh** [comment]
What new modules should we decouple them into? Annoy, JSON (circe) & Sparkey problem deserve their own. Not sure about BigQuery (just Avro conversion?). Checkpoint, `nn` (nearest neighbor) & `libsvm` are super old and hacky. Better deprecate?

**Comment by regadas** [comment]
Yup I was thinking something along those lines ... I can sketch something up and propose cause I want to also to accommodate for other "incoming" modules.

**Comment by nevillelyh** [comment]
Most modules in `scio-extra` are marked with `experimental` or `deprecated`, closing.
