### ISSUE TITLE
Update Dataflow SDK to 1.7.0

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#252]
New Dataflow SDK [release](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/releases/tag/v1.7.0).

**Comment by ravwojdyla** [comment]
Plain bump PR -> https://github.com/spotify/scio/pull/253

**Comment by ravwojdyla** [comment]
There seems to be some change in the way BQIO handles Integers/Long. For tests using BQIO, `expected` values are encoded via `TableRowJsonCoder` - which codes `TableRow` as `Json` (`Long` becomes `Integer`). This was fine in `1.6.1` as `actual` (coming from pipelines) values in `TableRow`s were Integer (at least during the matching) as well, after bumping to `1.7.0` this is no longer the case. `TableRow`s coming from pipeline results use `Long` while `TableRow`s in expected values use `Integer` (even if input values are `Long` - the conversion `Long` -> `Integer` happens after `TableRowJsonCoder` encode/decode cycle) thus mismatch. I'm working on fixing this.

**Comment by ravwojdyla** [comment]
Push the change that is fixing tests - by forcing the use of Int on the `actual`, still not sure where the difference is coming from.

**Comment by nevillelyh** [comment]
We were using `Int`s in `expected` before. Maybe should change them to `Long` instead?

I suspect they changed equality behavior of table row fields?

**Comment by nevillelyh** [comment]
You're right `TableRowJsonCoder` did something funky with `expected`. I'll leave this alone.

**Comment by ravwojdyla** [comment]
More on the issue:
 * http://stackoverflow.com/questions/33622227/dataflow-mixing-integer-long-types
 * http://stackoverflow.com/questions/7316689/forcing-jackson-to-deserialize-to-specific-primitive-type

Serialization ... 💀

**Comment by ravwojdyla** [comment]
If I understand things correctly - I don't like how `DataflowAssert` does encode/decode cycle on `expected` values but NOT on `actual` - thus in case of `TableRow` we end up with this inconsistency (apart from TableRow/Jackson Int/Long "optimization").

I think we should (and will submit PR shortly) enforce encode/decode on `actual` too to keep it consistent and that would also solve the problem of how TableRow/Jackson handles Int/Long.

Interestingly there is `DeserializationFeature.USE_LONG_FOR_INTS` maybe TableRow Coder should enforce it - given that in BQ there is no "Integer", only "Long". But that is probably up to DF/BQ.

**Comment by ravwojdyla** [comment]
Updated PR -> #253 with serde cycle.
