### ISSUE TITLE
Upgrade to the new Datastore API

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#256]
Pending upgrade of SDK to `1.7.0` via #253 , let's upgrade [deprecated](https://cloud.google.com/datastore/docs/apis#cloud-datastore-api-v1beta2-deprecated) datastore API.

**Comment by mpavlov** [comment]
I'll work on this

**Comment by nevillelyh** [comment]
There's a PR recently merged. Can we close this?

**Comment by ravwojdyla** [comment]
@nevillelyh I believe this is still pending some changes @mpavlov is working on to move to the new API.
