### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#261]
There are flaky tests causing travis to fail, which requires manual work (restarts).
Tests to fix:
- [x] Algebird.aggregate of Double with multiple aggregators [example](https://travis-ci.org/spotify/scio/jobs/160748144)
- [x] Algebird.sum with HyperLogLog: Falsified after 50 passed tests. [example](https://travis-ci.org/spotify/scio/jobs/160598959)
- [x] PoissonValueSampler [example](https://travis-ci.org/spotify/scio/jobs/158783154)

**Comment by ravwojdyla** [comment]
@nevillelyh you have been working on this before - do you have any pointers, ideas why would this still be a problem?

**Comment by ravwojdyla** [comment]
Algebird.sum with HyperLogLog is still problematic [example](https://travis-ci.org/spotify/scio/jobs/161188960)

**Comment by nevillelyh** [comment]
b1f8003fc752fae4a6a3c3010da9407661399ed4 should fix flaky RandomSamplerTest once and for all.
Fail that I didn't catch it all this time...
