### ISSUE TITLE
parquetAvroFile not reading files partitioned on cloud storage: java.io.IOException: Not a directory

### ISSUE THREAD

**Issue by sgireddy** [spotify/scio#2627]
We are backing up our pubsub messages to GCS partitioned by Date, so all files are stored as gs://bucket/<rest-of-path>/ingestionDate=2020-xx-xx/part-*.snappy.parquet. 

I am able to read if the parquet file is in a local folder but not when it is in gcs. Here are the options I tried:
 
    sc.parquetAvroFile[PubsubDataMessage](filePath) where filePath is
  
    gs://bucket/path/ingestionDate=2020-01-01/part-*.parquet
    gs://bucket/path/ingestionDate=2020-01-01/part-001.parquet  (full file name)
    Moved parquet files to another folder (to rule out special character "=")
    gs://bucket/path/test/part-001.parquet
  
  
I was able to load parquet files as below, so I don't think this is a permissions issue.
 
      storage.list("bucket", 
                          Storage.BlobListOption.prefix(path),
                          Storage.BlobListOption.currentDirectory())

Here is a part of the exception:

    Exception in thread "main" java.io.IOException: Not a directory
      at java.io.UnixFileSystem.createFileExclusively(Native Method)
      at java.io.File.createNewFile(File.java:1012)
      at com.google.api.client.extensions.java6.auth.oauth2.FileCredentialStore.<init>(FileCredentialStore.java:84)
      at com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromFileCredentialStoreForInstalledApp(CredentialFactory.java:346)
      at com.google.cloud.hadoop.util.CredentialConfiguration.getCredential(CredentialConfiguration.java:150)
      at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1508)
      at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1593)
      at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1554)
      at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:553)
      at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:506)

**Comment by nevillelyh** [comment]
Does it work with a path with no `=`?

**Comment by jto** [comment]
This looks like an issue between `dataproc` and `gcs` to me. I suggest you contact Google's support on this one.

**Comment by sgireddy** [comment]
It didn't work without "=" in the path, doesn't seem like a special character issue. It must be something that beam is not able to read "gs://" as I was able to read with regular java code. I will contact google support.

**Comment by nevillelyh** [comment]
Actually you’re saving files, `filePath` should be a directory without `/part-*.parquet` part. Try that?

**Comment by sgireddy** [comment]
I am reading from GCS not saving. Tried directory, absolute file path, with and without special characters and wildcard characters. No luck. When I debug looks like the code is looking for CSV list of files, but not clear if it is looking relative path or just bucket name then csv list or just a file. Loading single absolute path from local file system worked fine, looks like this is a "gs://" issue. Also not clear why it is invoking createFileExclusively when I am reading.

      val (sc, cmdlineArgs) = ContextAndArgs(args)
      sc.parquetAvroFile[BulkDataMessage]("gs://bucket/test/")    
        .map(x => {
          println(x)
          x
        })
        .saveAsTextFile(s"/tmp/file/", 1)
      sc.run().waitUntilDone()

**Comment by nevillelyh** [comment]
Are you running with direct runner? Feel free to post a reproducible snippet if you think it’s indeed a bug.

**Comment by sgireddy** [comment]
I was using DirectRunner, just tried with DataflowRunner but its not going far enough from my IDE to submit to dataflow, I will have to submit manually. Here is my code:

        object GCSToBigQuery extends App {

        val (sc, cmdlineArgs) = ContextAndArgs(args)
        sc.parquetAvroFile[BulkDataMessage]("gs://xxxxxxxxxxxx/buckets/sg-test/part-*.snappy.parquet")
            .map(x => {
            logger.info(x.getBody.toString)
            x
            })
            .saveAsTextFile("gs://xxxxxxxxx/buckets/test/", 1)
        sc.run().waitUntilDone()

        }

**Comment by nevillelyh** [comment]
Can't reproduce. I ran this test but changing `private val dir` from a local temp dir to somewhere on GCS. All tests pass.
https://github.com/spotify/scio/blob/master/scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala

BTW you're doing `extends App`, a long short but try `def main()` instead?

**Comment by sgireddy** [comment]
@nevillelyh thank you for pointing out these test cases, I was able to repro exact same issue with these test cases (Tests failed:3, passed: 3). All tests are failing with this error and looks like related to google credentials. Looks like the issue is related to my credentials that beams wants more than regular java SDK. 
closing the bug as scio has nothing to do with it.
