### ISSUE TITLE
Possibly regression from #2424, map side inputs

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2628]
In #2424 we replaced `SideMap` with vanilla `asMapSideInput` & `asMultiMapSideInput` which are backed by GCS/external storage on DF and is possibly causing a performance regression.

We should review all `as*SideInput` usages.

**Comment by marrrcin** [comment]
I'm trying to join 8M+ rows with small map using `asMapSideInput` and it seems to be horribly slow right now.
