### ISSUE TITLE
Any example of running Scio Jobs on Flink?

### ISSUE THREAD

**Issue by RohitR1** [spotify/scio#2642]
Is there any good tutorial or example of running Scio Jobs on Flink or Spark?

Is there any good tutorial or example of running Scio Jobs on Flink or Spark with docker builds?

Thanks

**Comment by regadas** [comment]
Hi @RohitR1 most of our examples (under `scio-examples`) run with Flink (1.9.2). With #2785 which should be out in the next `0.8.4` you will be able to run them through the `sbt` console. Instead of using `--runner=DataflowRunner` you would be using `--runner=FlinkRunner`.
