### ISSUE TITLE
Fold by key not working with Set in key

### ISSUE THREAD

**Issue by skybox2** [spotify/scio#2644]
When using `.foldByKey` on a key-value SCollection that has a Set in the key, the output is different than expected when the sets are created with items in different orders.
```
  it should "Fold sets correctly" in {

    val sets = Seq(
      (Set(1,2), List("hey")),
      (Set(2,1), List("hi"))
    )
    runWithContext {
      sc =>
        val setsCollection = sc.parallelize(sets)
        setsCollection.foldByKey debug()
    }
  }

// Output:
//(Set(1, 2),List(hey))
//(Set(2, 1),List(hi))
```
It works fine when the sets are created with the same ordering:
```
  it should "Fold sets correctly" in {

    val sets = Seq(
      (Set(1,2), List("hey")),
      (Set(1,2), List("hi"))
    )
    runWithContext {
      sc =>
        val setsCollection = sc.parallelize(sets)
        setsCollection.foldByKey debug()
    }
  }
// Output: (Set(1, 2),List(hey, hi))
```

**Comment by kythyra** [comment]
Interesting, I cannot reproduce the bug within my context.
Are you using `Set` from the Scala standard library?
Also, can you share the context where this test is failing (eg. commit or project)?

**Comment by skybox2** [comment]
It's a company project so I can't share the commit directly, but I'm running the test inside of a class that extends PipelineSpec. Scio version is `0.7.4-lib235`.
```
import com.spotify.scio.testing.PipelineSpec

class SetKeyTest extends PipelineSpec {
  it should "Fold sets correctly" in {

    val sets = Seq(
      (Set(1,2), List("hey")),
      (Set(2,1), List("hi"))
    )
    runWithContext {
      sc =>
        val setsCollection = sc.parallelize(sets)
        setsCollection.foldByKey debug()
    }
  }
}
```

**Comment by kythyra** [comment]
Ok, I can reproduce the issue by using Scio `0.7.4`.
You've found a quite peculiar bug, congratulations.

I cannot pinpoint where this breaks, however to give you a hint I think it depends on the implementation that Scala uses for small sets.

I've tried running your example for which Scala instantiates
`class scala.collection.immutable.Set$Set2`
(Set2 is just an optimised implementation of a small set containing 2 elements)
Your example outputs as you reported:
```
(Set(1, 2),List(hey))
(Set(2, 1),List(hi))
```


Scala uses these optimised implementations until sets with 4 elements, so then I tried running a similar example, but using a 5 elements set, for which Scala instantiates
`class scala.collection.immutable.HashSet$HashTrieSet`
And the output of `foldByKey` is:
```
(Set(5, 1, 2, 3, 4),List(hey, hi))
```

By forcing your example to use HashSet
```
val sets: Seq[(Set[Int], List[String])] = Seq(
      (Set(1, 2), List("hey")),
      (Set(2, 1), List("hi"))
    ).map {
      case (k, v) =>
        (HashSet() ++ k, v)
    }
```
The output of `foldByKey` is...
```
(Set(1, 2),List(hi, hey))
```

(You can inspect instantiated classes by using `.getClass`)

**Comment by skybox2** [comment]
@kythyra nice, thanks for the looking into this and offering up a fix

**Comment by jto** [comment]
Hi @skybox2,

IMHO you should not use `Set` as a key since the order of the elements in a `Set` are not garanteed and hence two different implementations of `Set(1, 2, 3)` may be different once serialized.

I think the "real" issue here is that `com.spotify.scio.coders.instances.SetCoder.verifyDeterministic` should throw a `NonDeterministicException`.

@nevillelyh wdyt ?

**Comment by kythyra** [comment]
@jto I think you're right.

Note that the Apache Beam coder for `java.util.Set` throws `NonDeterministicException` by default.

https://github.com/apache/beam/blob/279a05604b83a54e8e5a79e13d8761f94841f326/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/SetCoder.java#L46

It's a pity that the decision of determining keys equality by comparing the encoded bytes does not allow for easy usage of `Set`s as keys...

**Comment by kythyra** [comment]
> @kythyra nice, thanks for the looking into this and offering up a fix

@skybox2 I was not proposing a fix, I was suggesting a starting point for investigating this issue.
Using `HashSet` is not guaranteed to work because of how Beam implements key equality:

> Two keys of type K are compared for equality not by regular Java Object.equals(java.lang.Object), but instead by first encoding each of the keys using the Coder of the keys of the input PCollection, and then comparing the encoded bytes. This admits efficient parallel evaluation. Note that this requires that the Coder of the keys be deterministic (see Coder.verifyDeterministic()). If the key Coder is not deterministic, an exception is thrown at pipeline construction time. 

https://beam.apache.org/releases/javadoc/2.0.0/org/apache/beam/sdk/transforms/GroupByKey.html
