### ISSUE TITLE
SMB "least bucket replication"

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2652]
The SMB implementation currently supports joining sources with different bucket sizes, since bucket size is required to be `2^n`. However when reading such sources, the maximum parallelism is bounded by the one with the smallest bucket size.

One improvement we discussed is to replicate the smallest input to all workers. For example, say we have 3 sources of 8, 4, 2, and want to use parallelism of 8. Each worker thread may read the following buckets. This way each worker may read 2x/4x data from input 2, 3, but can filter them out by re-hashing the key.

```
worker input1 input2 input3
0           0      0      0
1           1      1      1
2           2      2      0
3           3      3      1
4           4      0      0
5           5      1      1
6           6      2      0
7           7      3      1
```

A few things we should discuss:
- A better name for this strategy?
- What's the target parallelism? It can be largest bucket size, user defined, or some heuristics based on file size?
- How configurable do we want this to be?

**Comment by Illedran** [comment]
One possible issue with replicating the input with the smaller number of buckets is that the size of each bucket is not taken into account. For example, it could be that buckets in input3 which is being replicated are much larger than the ones in input1 or input2. In such a situation, it would be nice to notify the user to rebucket using more buckets.

**Comment by jto** [comment]
@nevillelyh do you think we could instead split buckets from the input with the smallest bucket size in bundles and use a `SplitableDoFn` to do the actual reading?

**Comment by annicai** [comment]
Would be great if the solution to this would also consider shards and multi-partitioned inputs. If one dataset has 1024 buckets, and an other. 2048 buckets, but 4 shards per bucket, the actual max parallelism would be 2048*4, replicating the first 1024 buckets 2*4 times. Also if 100 partitions of that dataset (2048 buckets, 4 shards) is read in the join max parallelism would be 2048*4*100. In this case, you probably don’t want to replicate the first dataset 2*4*100 times, but instead want to have the parallelism configurable.
