### ISSUE TITLE
TableRow#getRecord is broken

### ISSUE THREAD

**Issue by nullobject** [spotify/scio#2673]
When you call `TableRow#getRecord` it will fail with an error:

```
class java.util.LinkedHashMap cannot be cast to class com.google.api.services.bigquery.model.TableRow
```

This happens because `getRecord` tries to cast the value as a `TableRow`, when it's actually a `LinkedHashMap`:

```scala
 def getRecord(name: AnyRef): TableRow = r.get(name).asInstanceOf[TableRow]
```

## How to Reproduce

```scala
sc
  .tableRowJsonFile(input) // {"foo":{"bar":"baz"}}
  .map(_.getRecord("foo")) // getRecord will explode
  .debug()
```

**Comment by regadas** [comment]
Hi @nullobject Thanks for reporting this! indeed this should return something like `Map[String, AnyRef]`
