### ISSUE TITLE
Share memory in multi-threaded DistCache environment

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#272]
Right now on multi-core workers each worker might pull a duplicate copy of the `DistCache` file in its `DoFn` instance. This can be more problematic if each of them load the file into memory or `mmap` it. We can probably share the file and `DistCache` content with a singleton atomic map or something.

https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala#L64

**Comment by ravwojdyla** [comment]
DistCache is already synchronized, and threads ("workers") have the same file? So why `might pull a duplicate copy`?

**Comment by nevillelyh** [comment]
I'm stupid, completely forgot about it. So a unique GCS file will only be downloaded once right?
But each `DoFn` instance may still load it as a separate in-memory collection?

**Comment by ravwojdyla** [comment]
Yep. We could maybe make it easier to load distcache files to memory etc - like wrappers on top of RandomAccessFiles etc, but seems like something user should take care of. Currently for example Sparkey should not duplicate memory and happily share data between workers (we could test it actually).

**Comment by nevillelyh** [comment]
Well I guess if the user reads all lines and does `toMap` there's not much we can do about it.
I'm gonna close this. But we should test and verify the Sparkey case.
