### ISSUE TITLE
Error when offset <= 1 Hour in SlidingWindows

### ISSUE THREAD

**Issue by LovreB** [spotify/scio#2745]
When using .withSlidingWindows(), if offset is set to one hour or more the IllegalArgumentException `"SlidingWindows WindowingStrategies must have 0 <= offset < period and 0 < size"` appears. This seems to be due to the implementation order when creating sliding windows, as the Sliding window is first created with an offset but with default period (which is set to one hour), and the default period is set first in the next row. 

I.e, when calling 

```
.withSlidingWindows(
          Duration.standardHours(25), // Period
          Duration.standardHours(24), // Size
          Duration.standardHours(23) // Offset
        )
```
The actual arguments in the creation of the windows in SlidingWindows.java (in Apache Beam), will be `period = 3600000, size = 90000000, offset = 82800000`, i.e.  size and offset is correct but period isn't. Hence the condition `!(offset.isShorterThan(period)` triggers.

**Comment by jto** [comment]
@LovreB Unless I'm missing something, you seem to have the arguments in the wrong order. See the definition of `withSlidingWindows`: 
https://github.com/spotify/scio/blob/9061180845c62c277e7dbc0ed3aca7fe2b43a01e/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L970-L975

So taking your example, the call should be (using of named parameter to avoid ambiguities):

```scala
coll.withSlidingWindows(
  size   = Duration.standardHours(24),
  period = Duration.standardHours(25),
  offset = Duration.standardHours(23)
)
```
In that case the condition is verified:
 
```
0 <= offset < period and 0 < size
0 <= 23h    < 25h     and 0 < 24h`
```

**Comment by jto** [comment]
(closing the issue since there seem to be no bug)

**Comment by LovreB** [comment]
@jto It is a bug indeed. Even if my comments in the code were in the wrong order (don't know how that happend), the behaviour of the code stays the same. I.e the condition you mention should be satisfied, but is not. 

When .withSlidingWindows is called, Slidingwindows with the selected size are created. 
```
 def withSlidingWindows(
    size: Duration,
    period: Duration = null,
    offset: Duration = Duration.ZERO,
    options: WindowOptions = WindowOptions()
  ): SCollection[T] = {
    var transform = SlidingWindows.of(size).withOffset(offset)
    if (period != null) {
      transform = transform.every(period)
    }
    this.withWindowFn(transform, options)
  }
```
These are initialized using default size, which happens to be one hour if size is larger than one hour. 
```
  public static SlidingWindows of(Duration size) {
    return new SlidingWindows(getDefaultPeriod(size), size, Duration.ZERO);
  }
```
```
static Duration getDefaultPeriod(Duration size) {
    if (size.isLongerThan(Duration.standardHours(1))) {
      return Duration.standardHours(1);
    }
```
Which, as an effect, when withOffset(offset) is called, period (one hour) is less than 23 hours and `0 <= offset < period` is violated.

**Comment by jto** [comment]
Hi @LovreB ,
Thanks for the clarification. I opened a PR fixing the issue.
