### ISSUE TITLE
error writign PubSub stream to GCS

### ISSUE THREAD

**Issue by ahsandar** [spotify/scio#275]
Getting following error for below code 

`Exception in thread "main" java.lang.IllegalArgumentException: Write can only be applied to a Bounded PCollection`
```
object StreamingPubSub {
  val RAND_RANGE = 7200000
  def main(cmdlineArgs: Array[String]): Unit = {
    // set up example wiring
    val (opts, args) = ScioContext.parseArguments[ExampleOptions](cmdlineArgs)
    val dataflowUtils = new DataflowExampleUtils(opts)
    dataflowUtils.setup()

    val sc = ScioContext(opts)


    sc.pubsubTopic(opts.getPubsubTopic)
    .timestampBy {
        _ => new Instant(System.currentTimeMillis() - (scala.math.random * RAND_RANGE).toLong)
      }
    .withFixedWindows((Duration.standardHours(1)))
    .groupBy(_ => Unit)
    .toWindowed
    .toSCollection
    .saveAsTextFile(args("output"))


    val result = sc.close()

    // CTRL-C to cancel the streaming pipeline
    dataflowUtils.waitToFinish(result.internal)
  }
}
```
Maybe I am confusing window with bounded , or do I need to apply a some kind of transform to achieve this, can someone be of assistance

**Comment by nevillelyh** [comment]
Please read the manual on bounded vs unbounded `PCollection` and IO:
https://cloud.google.com/dataflow/model/pcollection

**Comment by ahsandar** [comment]
Thanks @nevillelyh , 
got the response i was looking for from a `Google` engineer http://stackoverflow.com/questions/39865774/error-writing-pubsub-stream-to-cloud-storage-using-dataflow
