### ISSUE TITLE
Java Enum coders are non deterministics

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2761]
Going from Scio 0.7.4 -> 0.8.1+ breaks GBK operations where the key contains a Java Enum.

This is because the derived java enum coder is not deterministic, as it uses java serialization instead of kryo from 0.7.4. Since Java serialization is not deterministic, it fails.

This bug is related to this change:
https://github.com/spotify/scio/pull/2065/files

Here is a PR with a test case that for determinism. #2762

**Comment by regadas** [comment]
Hi @anish749 yeah good catch I overlooked the fact that `SerializableCoder` plays safe even though java Enum use different serialization mechanism and is deterministic.
