### ISSUE TITLE
Error: Method code too large!

### ISSUE THREAD

**Issue by Zhdanovich** [spotify/scio#2767]
Hello,
First of all, thank you for the amazing library.

I'm using Scio version `0.8.2`, I was adding new code to my pipeline and got a compile error, here is part of the stack trace:

```
12:34:54.208 [pool-8-thread-4] DEBUG com.spotify.scio.bigquery.types.TypeProvider$ - Will dump generated UserAction of com.ikea.search.stats.SessionGAExport from /Users/kirill/Developer/ikea/search-backend/data-extraction/data-exports/src/main/scala/com/ikea/search/stats/SessionGAExport.scala to /var/folders/h_/lggjkfk11tx2zwh950_pzj_r0000gn/T/kirill/generated-classes/UserAction-5d5bfe36.scala
[error] Could not write class com/ikea/search/ab/BootstrapJob$ because it exceeds JVM code size limits. Method runJob's code too large!
[error] one error found
```

This error doesn't make sense since `runJob` method is only 7 lines of code. I'm happy to provide more details. It would be also great if you can suggest how to debug this issue.

**Comment by regadas** [comment]
Hi @Zhdanovich!

I think the culprit here might be the generated case class from the `BigQueryType` macro. Possibly it has way too many fields? I would try just using a few of them to see if really is related to that.

Let me know of what you find!

**Comment by Zhdanovich** [comment]
Didn't help. The issue appears when I add more fields to a helper case class that is used in the file with an error.

**Comment by regadas** [comment]
@Zhdanovich can you provide an example that replicates this?

**Comment by Zhdanovich** [comment]
Maybe I will write to reproduce it, but for now, we fixed the problem by moving to Apache Beam library. Thanks

**Comment by sfines-clgx** [comment]
I can reproduce it with a 1 line method

**Comment by regadas** [comment]
Hi @sfines-clgx do you have a shareable example? Thanks

**Comment by sfines-clgx** [comment]
Pasted here because of dumb corporate firewalls:
`package com.corelogic.dataprep

import com.corelogic.gcp.schema.Models.{CandidateCompKeying, SubjectKeying, SubjectProperty}
import com.corelogic.gcp.scoring.Distance
import com.github.nscala_time._
import com.spotify.scio._
import com.corelogic.scio.Implicits._
import com.spotify.scio.values.SCollection
import org.joda.time.Instant
import com.spotify.scio.bigquery._
import com.corelogic.gcp.schema.Implicits._

/**
 * This is a test case to prove method too large exceptions....
 */
object BreakTestModels {

  case class A1(
                 a: Option[String],
                 b: Option[String],
                 c: Option[String] = None,
                 d: Option[String],
                 e: Option[String],
                 f: Option[String] = None,
                 g: Option[String] = None,
                 h: Option[String] = None,
                 i: Option[String],
                 j: Option[String] = None
               )

  case class A2(
                 a: Option[String],
                 b: Option[String],
                 c: Option[String],
                 d: Option[String],
                 e: Option[String],
                 f: Option[String],
                 g: Option[String],
                 h: Option[String],
                 i: Option[String],
                 j: Option[String]
               )

  case class A3(
                 a: Option[Instant],
                 b: Option[String],
                 c: Option[Double],
                 d: Option[Boolean]
               )


  case class G1(a: Double, b: Double, c: Option[String])


  case class L1(a: Option[G1] = None,
                b: Option[String] = None,
                c: List[String] = List.empty
               )


  case class A4(a: Option[Double], b: Option[Instant], c: Option[Double],
                d: Option[Double], p: Option[Double], m: Option[Long]
               )

  case class V1(
                 s: Option[String], a: Option[Boolean], d: Option[Instant], i: Option[Instant], p: Option[String],
                 c: Option[Double], m: Option[Double], p2: Option[Double], l1: Option[Double], l2: Option[String], s2: Option[Double],
                 c2: Option[String], q1: Option[String], b1: Option[String], s3: Option[String], c3: Option[String], c4: Option[String],
                 d2: Option[String], e: Option[String], i2: Option[String], n: Option[String], p3: Option[String], p4: Option[String],
                 r: Option[String], r2: Option[String], r3: Option[String], r4: Option[String], s4: Option[String], t1: Option[String],
                 u2: Option[String], u3: Option[String], c5: Option[String], c6: Option[String],
                 a2: Option[String], c7: Option[Double], c8: Option[Double], a3: Option[String],
                 a4: Option[Boolean])


  case class P1(
                 b1: Option[Double] = None,
                 b2: Option[Double] = None,
                 b3: Option[Double] = None,
                 b4: Option[Double] = None,
                 b5: Option[Double] = None,
                 r1: Option[Double] = None,
                 s1: Option[Double] = None,
                 f1: Option[Double] = None,
                 l1: Option[Double] = None,
                 s2: Option[Double] = None,
                 y1: Option[Double] = None,
                 a1: Option[Boolean] = None,
                 a2: Option[Double] = None,
                 a3: Option[Double] = None,
                 a4: Option[Instant] = None,
                 b6: Option[Double] = None,
                 c1: Option[Double] = None,
                 d1: Option[String] = None,
                 e1: Option[String] = None,
                 f2: Option[Double] = None,
                 f3: Option[Double] = None,
                 g1: Option[Double] = None,
                 g2: Option[Double] = None,
                 h1: Option[Double] = None,
                 h2: Option[String] = None,
                 h3: Option[Double] = None,
                 h4: Option[Double] = None,
                 i1: Option[Double] = None,
                 i2: Option[Double] = None,
                 l2: Option[String] = None,
                 m1: Option[Double] = None,
                 m2: Option[Double] = None,
                 m3: Option[Double] = None,
                 m4: Option[Double] = None,
                 m5: Option[Int] = None,
                 m6: Option[Double] = None,
                 n1: Option[String] = None,
                 p1: Option[Double] = None,
                 p2: Option[Boolean] = None,
                 p3: Option[String] = None,
                 p4: Option[Double] = None,
                 p5: Option[Instant] = None,
                 p6: Option[Double] = None,
                 p7: Option[Int] = None,
                 p8: Option[Double] = None,
                 p9: Option[Double] = None,
                 pa: Option[Double] = None,
                 r2: Option[Double] = None,
                 r3: Option[Double] = None,
                 s3: Option[Double] = None,
                 s4: Option[Double] = None,
                 s5: Option[Double] = None,
                 s6: Option[Double] = None,
                 s7: Option[String] = None,
                 s8: Option[Double] = None,
                 w1: Option[Double] = None
               )


  case class I1(a1: Option[String] = None, a2: Option[String] = None, a3: Option[Boolean] = None,
                c1: Option[String] = None, c2: Option[String] = None, d1: Option[String] = None,
                e1: Option[String] = None, i1: Option[String] = None, n1: Option[String] = None,
                p1: Option[String] = None, r1: Option[String] = None,
                r2: Option[String] = None, r3: Option[String] = None, r4: Option[String] = None,
                s1: Option[String] = None, t1: Option[String] = None, u1: Option[String] = None,
                u2: Option[String] = None, c3: Option[String] = None, c4: Option[String] = None)


  case class P2(s1: Option[String], d1: Option[Instant], p1: Option[Double],
                c1: Option[String], l1: Option[Double], s2: Option[Double],
                a1: Option[Boolean], m1: Double, m2: Double)

  case class P3(d1: Option[Instant], s1: Option[String], p1: Option[Double], a1: Option[Boolean],
                m1: Double, m2: Double)

  case class L2(d1: Option[Instant], p1: Option[Double], a1: Option[Boolean], m1: Double, m2: Double)

  case class C1(s1: Option[String], d1: Option[Instant], c1: Option[String], q1: Option[String])

  case class C2(v1: V1, m1: Double, m2: Double)

  case class S1(  i1: String,
                  f1: String,
                  a1: String,
                  c1: Option[String] = None,
                  a2: Option[A1] = None,
                  a3: Option[P1] = None,
                  c2: Option[A2] = None,
                  a4: Option[Double] = None,
                  l1: Option[Double] = None,
                  l2: Option[Double] = None,
                  r1: Option[String] = None,
                  l3: Option[Long] = None,
                  l4: Option[Long] = None,
                  i2: Option[String] = None,
                  r2: Option[Int] = None,
                  e1: Option[Instant] = None,
                  p1: Option[String] = None,
                  s1: Option[Instant] = None,
                  s2: Option[Double] = None,
                  s3: Option[String] = None,
                  p2: Option[String] = None,
                  d1: Option[Instant] = None,
                  v1: List[V1] = List.empty,
                  t1: Option[Double] = None,
                  a6: Option[Boolean] = None,
                  i3: Option[Instant] = None,
                  c3: Option[Double] = None,
                  m1: Option[Double] = None,
                  s4: Option[Double] = None,
                  l6: Option[String] = None,
                  s5: Option[Double] = None,
                  b1: Option[String] = None,
                  s6: Option[String] = None,
                  p3: Option[String] = None,
                  c4: Option[Double] = None,
                  c5: Option[Double] = None,
                  i4: I1 = I1(),
                  l5: Option[L1] = None,
                  f2: Option[String] = None,
                  a5: Option[A4] = None,
                  v2: Option[V1] = None,
                  s7: Option[S2] = None,
                  e2: Option[L2] = None,
                  e3: Option[P3] = None,
                  e4: Option[P2] = None,
                  e5: Option[C2] = None,
                  e6: Option[C1] = None,
               )




  case class S2(
                 f1: String,
                 i1: String,
                 r1: String,
                 n1: String,
                 l1: Double,
                 l2: Double,
                 p1: S1
               )

  case class C3(
                 f1: String,
                 i1: String,
                 r1: String,
                 l1: Double,
                 l2: Double,
                 p1: S1
               )


  case class C4(
                 f15:String,
                 s1:String,
                 s2:String,
                 s3:S1,
                 c1:String,
                 c2:String,
                 c3:S1,
                 d1:Double
               )
}

class BreakTheCompiler {
  import BreakTestModels._

  private def createConversionRecord(r: (S2, List[C3])) = {
    val (s, cl) = r
    cl.map { c =>

      (s, c, 1234.1, s.p1, c.p1)
    }
  }

  def expandRecords(joined: SCollection[(String, (S2, List[C3]))]): SCollection[(String, (S2, C3, Double, S1, S1))] = joined.flatMapValues(createConversionRecord)
}
`

**Comment by sfines-clgx** [comment]
@regadas I've had mixed luck reproducing it - if I have a private location than I can send the actual code (minus critical IP) which will probably be more reliable, though it's definitely related to the size of case classes.

**Comment by regadas** [comment]
Hi @sfines-clgx, I had a better look at this and I think this is due to the amount of `Coder` being generated for these big classes.

I used your example as a test and managed to drop the class size from 432K to 120K. To achieve this we need to pre generate the `Coder` and make sure they are in scope. This will also drop your compile time considerably.

i.e:

```
class BreakTheCompiler {
  import BreakTestModels._
  import com.spotify.scio.coders._

  implicit val s1Coder = Coder.gen[S1]
  implicit val s2Coder = Coder.gen[S2]
  implicit val c3Coder = Coder.gen[C3]

  private def createConversionRecord(r: (S2, List[C3])) = {
    val (s, cl) = r
    cl.map { c =>

      (s, c, 1234.1, s.p1, c.p1)
    }
  }

  def expandRecords(joined: SCollection[(String, (S2, List[C3]))]): SCollection[(String, (S2, C3, Double, S1, S1))] = joined.flatMapValues(createConversionRecord)
}
```
