### ISSUE TITLE
Resume Apache Beam port for 0.2.0

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#277]
Right now we have an old [apache-beam](https://github.com/spotify/scio/tree/apache-beam) branch that works with Beam 0.1.0, and a [neville/beam-0.2.0](https://github.com/spotify/scio/tree/neville/beam-0.2.0) branch that compiles against Beam 0.2.0 but fails tests.

We need to fix those, update `apache-beam` branch to 0.2.0, and resume cherry picking commits from master.

- [x] fix tests in `neville/beam-0.2.0` branch
- [ ] update `apache-beam` branch to 0.2.0
- [ ] cherry pick commits from `master`
- [ ] address cherry picking issues in #279

**Comment by andrewsmartin** [comment]
Many tests are failing because of this issue (which may or may not be a problem on the Scio side - investigation in progress). https://issues.apache.org/jira/browse/BEAM-741

**Comment by nevillelyh** [comment]
Let's close this and use #279 to track all things Beam.
