### ISSUE TITLE
BQ Write with Schema fails with NPE

### ISSUE THREAD

**Issue by anish749** [spotify/scio#2787]
Trying to write a `SCollection[T: Schema]` using `.saveAsBigQuery(..)` I get a NPE because Beam doesn't know the `TableSchema`

This originates from [here](https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala#L730)

**Comment by regadas** [comment]
Hi @anish749 can you provide the full stack trace? This sounds s bit fishy since `TableSchema` should be derived from the underlying `PCollection` `Schema` which is set in the line below?

**Comment by anish749** [comment]
You are right, it is not the one from where I thought it originates.
I am not having the stack trace in a parseable format to paste here, and it is in google log viewer. Let me share it privately.

**Comment by RustedBones** [comment]
BQ based on beam schema has been dropped in 0.12. Closing the issue
