### ISSUE TITLE
Beam migration

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#279]
Let's use this issue to track commits or changes left behind when migrating Scio to Apache Beam.
Current working branch is https://github.com/spotify/scio/tree/apache-beam.

Script to find missing commits:
```bash
./scripts/cccp.sh master apache-beam > cccp.txt
```

Spreadsheet to keep track of missing commits
https://docs.google.com/spreadsheets/d/1zD175kZDfGP3wFbwybj9P2DWSyCvf6TMe9NLoaDzBuY/edit#gid=0

Other tasks:
- [x] Fix broken `com.spotify.scio.values.SCollectionTest#randomSplit()` test
- [x] Refactor `ScioResult`
- [x] Recover and consolidate lost changes in #377 
- [x] Drop scala 2.10 and prepare for 2.12
- [x] Fix flaky `SCollection#debug()` tests
- [x] Fix and re-enable `scio-bigtable`
- [x] Re-enable `scio-examples`
- [x] Re-port all `scio-examples`
- [x] Add scala 2.12 support #323 (blocking on https://github.com/twitter/chill/pull/281)
- [x] FIXMEs and TODOs
- [x] Re-apply https://github.com/spotify/scio/commit/cdcb55cdea3bc15a0ce4421ab598f3d537ded362 "Modernize with java 8 features"

**Comment by nevillelyh** [comment]
Script for figuring out commit discrepancies.
```bash
#!/bin/bash
# Chief Commit Cherry Picker

if [ $# -ne 2 ]; then
    echo "Usage: cccp.sh <src> <dst>"
    exit 1
fi

SRC=$1
DST=$2

git log --format='%aI %s' $SRC > _src.txt
git log --format='%h %aI %s' $SRC > _srch.txt
git log --format='%aI %s' $DST > _dst.txt
git log --format='%h %aI %s' $DST > _dsth.txt

diff _src.txt _dst.txt > _diff.txt

IFS=$'\n'
echo "Commits only in $SRC"
for l in $(grep '^< ' _diff.txt | cut -c 3-); do
    grep "$l" _srch.txt
done
echo
echo "Commits only in $DST"
for l in $(grep '^< ' _diff.txt | cut -c 3-); do
    grep "$l" _dsth.txt
done

rm -f _src.txt _srch.txt _dst.txt _dsth.txt _diff.txt
```

**Comment by nevillelyh** [comment]
Diff as of Wed Oct  5 20:10:21 EDT 2016
9e23151 - (HEAD -> neville/beam-0.2.0) turn of sbt-scoverage highlighting
```
Commits only in master
8ccd223 2016-09-25T15:43:25-04:00 switch to FluentBackoff in Taps (#270)
bc93a30 2016-09-17T18:33:00-04:00 Add tests for PatchedAvroIO
16d6c2c 2016-09-17T18:32:27-04:00 Add JUnit interface for sbt
12f152c 2016-09-16T22:16:02-04:00 Add compression codec to AvroIO
4ae2c25 2016-09-16T13:17:04-04:00 update run docstring
cecb505 2016-09-15T14:26:39-04:00 update scio-core to use datastore api v1
4795107 2016-09-14T17:48:40-04:00 Remove obsolete BigQueryIO patch
2cbadb5 2016-09-14T16:09:16-04:00 Bump sdk to 1.7.0
f8c44f5 2016-09-12T21:07:47-04:00 Use InProcessPipelineRunner in REPL (#246)
ce1c068 2016-09-07T16:07:12-04:00 Closes #170. Use InProcessPipelineRunner.
7cb2aec 2016-08-18T15:27:22+02:00 Shutdown in finally (#217)
e7b58b6 2016-08-12T11:29:46-04:00 refactor HDFS #200 (#212)
6622e45 2016-08-10T17:23:46+02:00 bump dataflowSdkVersion to 1.6.1
72b4a31 2016-07-21T15:22:37-04:00 update bigtable version (#199)
f33750a 2016-07-07T23:42:43-04:00 Mitigate DataflowSDK 330 bug (#193)
d4cdf2e 2016-07-01T15:39:53-04:00 add function to update the number of bigtable nodes (#188)
d2b4770 2016-07-01T14:12:04-04:00 remove redundant joda-time dependency

Commits only in neville/beam-0.2.0
60db0f2 2016-10-05T16:04:26-04:00 WIP: porting to beam 0.2.0
7986ee7 2016-10-05T16:05:35-04:00 WIP exclude examples from build
2b2d99d 2016-08-19T10:39:30-04:00 monkey patch BigQuery utilities
d0af02a 2016-08-19T10:25:26-04:00 port BigQuery utilities from Beam 0.1.0-incubating
f95fb3a 2016-08-19T10:10:15-04:00 bump Beam dependency to 0.2.0-incubating
bc59010 2016-08-04T19:06:12-04:00 update netty-tcnative version
1aa0c97 2016-07-01T14:35:59-04:00 add scio2beam.sh
9bc4afa 2016-07-01T14:12:04-04:00 remove redundant joda-time dependency
ec1d9b4 2016-06-22T15:29:52-04:00 fix imports in scio-examples
296a8cd 2016-06-22T15:13:45-04:00 update Java examples
c878bc1 2016-06-22T15:27:11-04:00 disable BigtableExample and test
31ff5f9 2016-06-22T15:12:08-04:00 disable scio-bigtable in build.sbt
945da71 2016-06-22T15:02:55-04:00 fix imports scio-bigtable
223e8a6 2016-06-22T15:05:04-04:00 fix imports scio-repl
fa86133 2016-06-22T15:02:48-04:00 fix imports scio-test
0c933c2 2016-06-22T14:58:36-04:00 fix imports scio-hdfs
e8d4f54 2016-06-22T14:50:12-04:00 fix imports scio-bigquery
1611128 2016-06-22T14:50:04-04:00 fix imports in scio-core
b134810 2016-06-22T14:04:17-04:00 [BEAM-302] Switch to Beam dependency
```

**Comment by nevillelyh** [comment]
Pushed a new https://github.com/spotify/scio/tree/neville/beam WIP branch for 0.4.0

**Comment by nevillelyh** [comment]
The latest `apache-beam` branch now compiles with Beam 0.4.0 and passes most tests.

List of missing commits from master:
```
47e808f 2016-12-13 17:57:25 -0500 Bump bigtable version to 0.9.4 (#362)
b69d634 2016-11-01 18:28:02 +0100 bump protobuf-generic to 0.1.1
8dd3fca 2016-10-23 19:30:40 -0400 add schema metadata to protobuf file
8a177d4 2016-10-23 19:00:17 -0400 add metdata to PatchedAvroIO
282b725 2016-10-22 20:12:49 -0400 fix update number of bigtable nodes
5078bb6 2016-10-17 11:39:05 -0400 upgrade Dataflow Java SDK to 1.8.0
c237aa8 2016-10-13 11:40:09 -0400 upgrade to bigtable 0.9.3
16ad74b 2016-10-12 22:29:33 -0400 remove duplicate import in SCollection.scala
8ccd223 2016-09-25 15:43:25 -0400 switch to FluentBackoff in Taps (#270)
bc93a30 2016-09-17 18:33:00 -0400 Add tests for PatchedAvroIO
16d6c2c 2016-09-17 18:32:27 -0400 Add JUnit interface for sbt
12f152c 2016-09-16 22:16:02 -0400 Add compression codec to AvroIO
4ae2c25 2016-09-16 13:17:04 -0400 update run docstring
cecb505 2016-09-15 14:26:39 -0400 update scio-core to use datastore api v1
4795107 2016-09-14 17:48:40 -0400 Remove obsolete BigQueryIO patch
2cbadb5 2016-09-14 16:09:16 -0400 Bump sdk to 1.7.0
f8c44f5 2016-09-12 21:07:47 -0400 Use InProcessPipelineRunner in REPL (#246)
ce1c068 2016-09-07 16:07:12 -0400 Closes #170. Use InProcessPipelineRunner.
7cb2aec 2016-08-18 15:27:22 +0200 Shutdown in finally (#217)
e7b58b6 2016-08-12 11:29:46 -0400 refactor HDFS #200 (#212)
6622e45 2016-08-10 17:23:46 +0200 bump dataflowSdkVersion to 1.6.1
72b4a31 2016-07-21 15:22:37 -0400 update bigtable version (#199)
f33750a 2016-07-07 23:42:43 -0400 Mitigate DataflowSDK 330 bug (#193)
d4cdf2e 2016-07-01 15:39:53 -0400 add function to update the number of bigtable nodes (#188)
d2b4770 2016-07-01 14:12:04 -0400 remove redundant joda-time dependency
```

**Comment by nevillelyh** [comment]
Spreadsheet to keep track of missing commits
https://docs.google.com/spreadsheets/d/1zD175kZDfGP3wFbwybj9P2DWSyCvf6TMe9NLoaDzBuY/edit#gid=0

**Comment by nevillelyh** [comment]
So all runners (including `DirectRunner`) are non-blocking in 0.4.0 and `BlockingDataflowPipelineRunner` is removed. For backwards compatibility I added `waitUntilFinish` to block on `ScioContext#close()` for `DirectRunner`. See https://github.com/spotify/scio/commit/395aa6d3eb3702e7f274534e12001a7eafcc127d.

Or shall we make all runners block by default and add a `closeAsync()` alternative?

@ravwojdyla thoughts?

**Comment by ravwojdyla** [comment]
I would be +1 to waitUntilFinish (asynchronous by default), it would be more compatible with both hadoop and dataflow. Naming: or waitForCompletion which is what hadoop/scalding is calling it.

**Comment by nevillelyh** [comment]
In that case we still have to block if `ScioContext#isTest` is true for `JobTest` to run properly. And it require more user code change. Most existing jobs use blocking runner and assumes that `sc.close()` blocks on both local and Dataflow.

`sc.close()` blocking and `sc.closeAsync()` non-blocking seems the least intrusive.

**Comment by ravwojdyla** [comment]
I understand, but still think it would be better to be consistent with dataflow (hadoop). Another way could be to deprecate close, and add submit and waitForCompletion to the context. Close would be deprecated and would be blocking (like most cases), it would just call waitForCompletion, and submit would be default behaviour - in this case nonblocking. This way it is a more explicit and more consistent with other frameworks. This way user won't need to change immediately, while deprecation would inform them that they should move to the new API. About non blocking tests we could use AsyncFlatSpec, I'm using it in limbo to test results of futures.

**Comment by nevillelyh** [comment]
Cool so how about this:

- Make `sc.close()` async in all cases to be more consistent with DF
- Except if `sc.isTest` is true then block so that `JobTest` can run successfully
- Add `ScioResult#waitUntilFinish` to support blocking behavior
- Document that in the migration notes

**Comment by nevillelyh** [comment]
All sets down.
No need to re-apply cdcb55c "Modernize with java 8 features" since HDFS IO is upstream in 0.6.0 and we got rid of `BigtableMultipleWrite`.
