### ISSUE TITLE
Chaining file IO

### ISSUE THREAD

**Issue by abergmeier** [spotify/scio#2794]
I have pipelines, where I would like to have files written in order.
Perhaps something like:

```
sc.textFile("foo").map(...).saveAsTextFile().map(...).saveAsTextFile()
```

Currently I am using `saveAsTextFile` which has only limited utility due to returning `ClosedTap`.

I found `TextIO.TypedWrite` in Beam. On first glance it seems to be able to allow chaining.
How would one use it from Beam?

**Comment by jto** [comment]
Hi @abergmeier 

You can simply write:

```scala
val coll1 = sc.textFile("foo").map(...)
coll1.saveAsTextFile()
coll1.map(...).saveAsTextFile()
```

(closing)

**Comment by abergmeier** [comment]
So if I understand you correctly, `saveAsTextFile` follows the order in the source code? So these are never executed in parallel?

**Comment by jto** [comment]
There's no order. The runner decides how the code should be executed.
In that case it will parallelize the execution.

**Comment by abergmeier** [comment]
> In that case it will parallelize the execution.

My question was about chaining. I only want to have fileT2 produced after fileT1. Parallelizing is explicitly what I do not want.
