### ISSUE TITLE
Dynamic Destination for Parquet Files on GCS

### ISSUE THREAD

**Issue by jayadeep-jayaraman** [spotify/scio#2824]
Is there an example of FileIO.WriteDynamic for Parquet files. I see that there is saveAsDynamicTextFile and saveAsDynamicAvroFile. It would be great if we can have a similar saveAsDynamicParquetFile API.

**Comment by regadas** [comment]
Hi @cejj at the moment we don't have such example. If you come up with one, could you make a PR? 😄

**Comment by cejj** [comment]
Sure let me work on it.

**Comment by cejj** [comment]
@regadas - I have created an example. Can you let me know the process for raising a PR and submitting the example ?

**Comment by regadas** [comment]
Hi @cejj sorry for the late reply! There's no process really, just make a PR against `master` 😄
