### ISSUE TITLE
Question: Any known complications with scoverage + Scio?

### ISSUE THREAD

**Issue by danxmoran** [spotify/scio#2825]
Sorry if this isn't the right place to ask, it's just the only place I can think to start.

My team uses scoverage + codecov to track and report coverage in our Scala projects. The setup doesn't seem to work for our scio-pipeline code: We enable scoverage and run the pipeline using `runWithRealContext`, and the generated coverage reports are empty.

I see that you've got a similar coverage setup in this repo. Have you been able to get coverage working for the example pipelines included here? If so, do you have any tips to help us debug?

**Comment by nevillelyh** [comment]
Have looked our CircleCI config? https://github.com/spotify/scio/blob/master/.circleci/config.yml#L133
You need to run `coverage` before `test` and `coverageReport` plus optionally `coverageAggregate` (if using multi-projects) afterwards.

**Comment by danxmoran** [comment]
Yes, that's where I first checked. I believe we're doing effectively the same thing in our GitHub actions (example [here](https://github.com/DataBiosphere/clinvar-ingest/blob/master/.github/workflows/validate-pull-request.yaml)), but with a few tweaks:
* We expand the definition of `coverage` to an explicit `set ThisBuild/coverageEnabled := true`
* We skip `coverageReport` because it's supposedly [not needed any more ](https://github.com/DataBiosphere/clinvar-ingest/blob/master/.github/workflows/validate-pull-request.yaml)in 1.6.0

These commands work fine to generate coverage for code outside of a scio / beam pipeline (I see coverage for the fields in objects generated by `sbt-buildinfo` that are used to construct the pipeline), but no data is generated for code inside of pipelines.

Does it matter that we're using `runWithRealContext` during tests? I'm not sure of all the differences between a "real" and test context.

**Comment by nevillelyh** [comment]
`runWithRealContext` should work since it's still running a local `DirectRunner` (just without `testId`) and should still be instrumented.

Can you verify that `test` produces `target/scala-2.*/scoverage-data`?

**Comment by danxmoran** [comment]
The directory is produced, but `scoverage-data/scoverage.coverage` only contains data for my `BuildInfo` objects.

**Comment by nevillelyh** [comment]
Closing since we can't repro. Feel free to reopen when you have more info.

**Comment by danxmoran** [comment]
In case anyone else finds this with a similar problem: It turns out the issue was the use of build timestamp in `sbt-buildinfo`, paired with our use of `sbt` in batch mode from CI. Removing that key made things work!
