### ISSUE TITLE
Slow encoding performance in SeqLikeCoder

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2880]
For some types like `TraversalOnce` and `Iterable` there's a second traverse of the collection. Depending on its size we might actually see some big perf degradation.

In some runners causes #2868

**Comment by nevillelyh** [comment]
Re-iterating an `TraversableOnce` will also crash the coder right?

**Comment by regadas** [comment]
yeah, in the case of `TraversableOnce` data would not be encoded because the underlying collection was already traversed.
