### ISSUE TITLE
Join favors smaller LHS

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#289]
So right now a `lhs.join(rhs)` looks like this:
```scala
a.context.wrap(keyed).flatMap { kv =>
      val (key, result) = (kv.getKey, kv.getValue)
      for {
        a <- result.getAll(tagA).asScala.iterator
        b <- result.getAll(tagB).asScala.iterator
      } yield (key, (a, b))
    }
```

Which gets translated to `lhs.flatMap(a => rhs.map(b => (key, (a, b))))` and can be slow if `lhs` is extremely large, i.e. 600K in one case, which causes 600K iterator concatenation.

And we see the following message in worker logs:
`CoGbkResult has more than 10000 elements, reiteration (which may be slow) is required.`

This is also counter-intuitive for Scalding users who are used to larger LHS. Plus it makes it harder to replace `.join` with `.hashJoin`.

I thought about checking LHS and RHS sizes before the for/yield, but `result.getAll(tagA)` is a lazy `Iterable` so size is O(n). The easiest compromise may be to reverse order things inside `for {}`, and document that RHS should be smaller?

Another good to have is accumulators for each join stage, e.g. `leftMaxGroup`, `leftMinGroup`, `rightMaxGroup`, `rightMinGroup`.

**Comment by ravwojdyla** [comment]
Do you have benchmark results for reverse order?
