### ISSUE TITLE
SCollection.withWindowFn does not allow upper type bound for WindowFn

### ISSUE THREAD

**Issue by mkuthan** [spotify/scio#2956]
Current implementation of SCollection.withWindowFn does not accept typed WindowFn.

Please look at example custom WindowFn implementation, I have to use AnyRef instead of domain type AdEvent:
https://github.com/mkuthan/beam-examples/blob/b6ba82845e1a3394154d0ba4805a29cef5d5c46e/src/main/scala/org/mkuthan/beam/examples/AdEventWindowFn.scala#L17

I would really appreciate SCollection.withWindowFn signature with upper bound type :)

Thanks,
Marcin

**Comment by nevillelyh** [comment]
Should be a small and hopefully source compat fix. Mind creating a PR?

**Comment by mkuthan** [comment]
PR has been prepared. But I have to admit that I didn't test the change locally, Scio build is really heavy ... let's see what CI will say.
