### ISSUE TITLE
Drop Java 7?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#298]
We can migrate the following things once on Java 8:
- [ ] Replace `joda-time` with `java.time`
- [ ] Stream API, lambdas, `Optional` in Java code

**Comment by andrewsmartin** [comment]
This is blocked by #323, support for jvm8 was added in scala 2.11.4 http://stackoverflow.com/a/25926359/2391705

**Comment by nevillelyh** [comment]
Let's track this in #323. Closing this.
