### ISSUE TITLE
Introduce a second type parameter in `withWindowFn` for better type safety.

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2980]
This is not done right now so we don't break backwards compat.

https://github.com/spotify/scio/pull/2975#discussion_r425094916

**Comment by nevillelyh** [comment]
Seems not easily fixable based on #3351. Let's leave it till we drop 2.12?

**Comment by nevillelyh** [comment]
Closing since not easily fixable more of a Beam issue with erasure.
