### ISSUE TITLE
ValueProvider support for ScioIO

### ISSUE THREAD

**Issue by labianchin** [spotify/scio#2982]
It would be good if ScioIO's implementation supported ValueProvider as parameter for input paths. In particular [PubSubIO](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala).

Support for such is important in order to [create templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates).

In our team, we are moving some of the streaming pipelines to support templates. At the moment, this means rewriting in Beam SDK APIs.

**Comment by labianchin** [comment]
Possibly relates to https://github.com/spotify/scio/issues/696 .

**Comment by regadas** [comment]
Hi @labianchin thanks for creating this. Seems that it's a dup of #696 as you pointed out!

Do you mind if we keep just one? can you comment that one instead? I actually like the idea of reviving this subject!

**Comment by regadas** [comment]
We believe that *Flex Templates* offers more flexibility and Google seems to be on the same page. For that reason we will not add *Traditional Template* support.
