### ISSUE TITLE
Add support for introspecting avro-wrapped protobufs

### ISSUE THREAD

**Issue by harveyxia** [spotify/scio#303]
Currently Scio supports Protobufs by [wrapping them inside an avro file](https://github.com/spotify/scio/wiki/Protobuf). It would be nice to have a tool to introspect avro-wrapped protobufs, something similar to `avro-tools`. Such a tool could be an extension of the existing [`gcs-tools`](https://github.com/spotify/gcs-tools.)

**Comment by nevillelyh** [comment]
Dup of #265 
It's not as easy since Protobuf schema is not attached to the file and doesn't support have a equivalent of Avro `GenericRecord` or `Schema` but I'll think about it.
