### ISSUE TITLE
Use HLL+ for approximate distinct counts over vanilla HLL

### ISSUE THREAD

**Issue by hansencc** [spotify/scio#3030]
Beam offers approximate distinct count implementations using HLL+ that has accuracy and performance benefits over HLL.

https://github.com/apache/beam/blob/master/sdks/java/extensions/sketching/src/main/java/org/apache/beam/sdk/extensions/sketching/ApproximateDistinct.java

https://github.com/apache/beam/blob/master/sdks/java/extensions/zetasketch/src/main/java/org/apache/beam/sdk/extensions/zetasketch/HllCount.java 

It would be nice to allow these implementations to be leveraged through Scio.

**Comment by nevillelyh** [comment]
I'm thinking something down the line of this, a good Java impl with light Scala wrapper & coder
https://github.com/spotify/scio/pull/2651
