### ISSUE TITLE
Potentially misleading documentation in aggregateByKey

### ISSUE THREAD

**Issue by hansencc** [spotify/scio#3031]
In the docs for [aggregateByKey](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala#L608), the documentation around memory allocation is potentially misleading.

> To avoid memory allocation, both of these functions are allowed to modify and return their first argument instead of creating a new `U`.

When the `zeroValue` is modified, it leads to undesired behaviors.

**Comment by nevillelyh** [comment]
Making the `zeroValue` argument passing by name, i.e. `=> U` so that it's recreated every bundle instead of reused, should fix the issue.
