### ISSUE TITLE
waitUntilDone/Finish nomenclature confusing

### ISSUE THREAD

**Issue by nhelferty** [spotify/scio#3032]
While the docstrings are good, "waitUntilDone" and "waitUntilFinish" mean exactly the same thing in English and this seems like a potential source of confusion (and I don't think people are making the intended connection to the specific DONE state). We found several uses of waitUntilFinish after an incident when we basically always want "waitUntilDone".

I'd suggest changing one and/or the other name to make the distinction clearer, e.g. one "waitUntilSucceeded" instead of "Done", or something like that.

Thanks!

**Comment by jto** [comment]
Hi @nhelferty.

Thanks for the feedback. 
Scio simply forwards those calls to methods in Beam that have the same names. 
I don't think it would be wise to depart from this naming.

**Comment by nhelferty** [comment]
@jto Thanks for responding! just noting while `waitUntilFinish` is in Beam (and I agree keeping that in sync is wise) `waitUntilDone` is Scio-only

**Comment by nevillelyh** [comment]
And Beam's `waitUntilFinish()` returns a enum `State` with `DONE` as success.
https://beam.apache.org/releases/javadoc/2.22.0/org/apache/beam/sdk/PipelineResult.State.html

Adding another method might make this more confusing? And what would we call it, `waitUntillSuccess`? Maybe deprecate `waitUntilDone` while we're at it and save this for 0.10.0?
