### ISSUE TITLE
Using BigQuery fromQuery in a dataflow template

### ISSUE THREAD

**Issue by marselasulku** [spotify/scio#3036]
Hi! 

I'm trying to create a BigQuery to Bigtable (with some extra processing) dataflow template. I'm planning to trigger this dataflow job every 24 hrs. 

I'm seeing that after I create the template, the first run properly process all the data and finishes. If I run the same template again, it doesn't read any of the data. I also tried using `@BigQueryType.fromQuery()` and also `sc.bigQuerySelect(selectQuery)`, and both methods resulted in the same behavior. The select query fed into these is one that selects all rows so if anything there should be an equivalent or more number of rows than the previous run. 

I didn't think this would be a caching issue but just to be safe I did try generating the template with the `-Dbigquery.cache.enable=false` flag and that didn't work.

I do know that BigQuery temp tables are TTLed for 24 hrs (and in my attempts, my reruns have been <24 hrs apart), not sure if that has anything to do with it. 

I'm using scala `2.13.1`, scio `0.9.1`, beam `2.20.0`, and sbt `1.3.0`

I'm just trying to better understand what is going on?

**Comment by regadas** [comment]
@marselasulku Hi, hard to tell what's going on, I'll need to try to replicate this.

To clarify, the job runs successfully but no data is read or does the job hang?

Also,
> -Dbigquery.cache.enable=false flag and that didn't work.

job ran but no data?

Thanks

**Comment by marselasulku** [comment]
@regadas 

both methods I tried (`@BigQueryType.fromQuery()` and also `sc.bigQuerySelect(selectQuery)`) result in the following behavior: 

- I run the template, all rows are read and processed correctly. The job finishes successfully. 
- I run the same template a second time (without regenerating the template), the job reads 0 rows and finishes successfully. 

This happens both when the template was compiled with the `-Dbigquery.cache.enable=false` and without the flag. 

Here's some screenshots: 

**typedBigQuery, first run:** 
<img width="990" alt="typedBigQuery_first" src="https://user-images.githubusercontent.com/14287230/84532486-2cd0a100-ac9b-11ea-8d15-f68328b5cf09.png">

**typedBigQuery, second run:** 
<img width="1041" alt="typedBigQuery_second" src="https://user-images.githubusercontent.com/14287230/84532493-2e9a6480-ac9b-11ea-8db7-78812c989d7b.png">

**bigQuerySelect, first run:** 
<img width="1266" alt="bigquerySelect_first" src="https://user-images.githubusercontent.com/14287230/84532572-54c00480-ac9b-11ea-9d9e-27f52dc21046.png">

**bigQuerySelect, second run:** 
<img width="1022" alt="bigquerySelect_second" src="https://user-images.githubusercontent.com/14287230/84532568-525daa80-ac9b-11ea-9dd2-53b09ecdc560.png">

**Comment by regadas** [comment]
Hi @marselasulku so i had a look at this and with the current version (0.9.1) unless you can use `flex templates` traditionally templated Bigquery jobs will not work. In short, bq job id is generated statically at graph construction time.

**Comment by marselasulku** [comment]
can you use flex templates in Scio?

**Comment by regadas** [comment]
Hi @marselasulku you can ... I compiled an example project https://github.com/regadas/scio-dataflow-flex-template-example.

**Comment by regadas** [comment]
We believe that *Flex Templates* offers more flexibility and Google seems to be on the same page. For that reason we will not add *Traditional Template* support.

The solution is to run the job as a *Flex Template* job.
