### ISSUE TITLE
`AvroBucketMetadata` should validate keyPath

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#3038]
When extracting keys since it's stringly typed. A typo in the key would cause `null` value & a single null bucket.

**Comment by ClaireMcGinty** [comment]
@nevillelyh thoughts on also validating that the user-specified key class matches the schema type? I.e if user specifies an SMB read with key class `String` then the Avro `Schema` of the key class should be a `Schema.create(Type.STRING)`, etc. I think it would be helpful especially for fields that are easily mistaken (i.e. is an ID field represented as Bytes or a String?), as well as validating that the key field isn't something like Map that can't be deterministically compared.

**Comment by nevillelyh** [comment]
Yeah that should be nice too, but Avro, TF might need a bit more logic for `ByteBuffer`, `ByteString`, etc.
For validating determinism, we can delegate to `keyCoder.verifyDeterministic()` right?

**Comment by ClaireMcGinty** [comment]
yeah the keyCoder check sounds good!

I guess any class in {ByteString, ByteBuffer, byte[]} could map to an Avro `BYTES` field...Similarly there's the old Avro CharSequence/String issue.
