### ISSUE TITLE
Support Dataflow templates

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3061]
Currently `Dataflow` has 2 types of templates:

* [ ] Traditional template
* [ ] Flex template

Related issues #696 and #2982 reference `ValueProvider`'s which is inherently related to `traditional` template model. To support this model we will need to address some changes in `IO` params.

Flex template, this model should work out of the box, however it would be good if we could have some docs around this and perhaps some `scio-flex-template.g8` to allow some quickstarts.

**Comment by sfines-clgx** [comment]
Can I upvote this? I would like to upvote this. My usecase here is that I launch about 3k jobs to process a large amount of data in meaningful chunks, and driving this using other mechanisms is a real pain

**Comment by bkhuong** [comment]
Any updates on the docs / quickstarts for scio flex templates?

**Comment by regadas** [comment]
Hi @bkhuong sorry for late reply. This fell under my radar.

We don't have specific docs for yet (maybe you can help us out? 😄  ) but we do have support for them in our https://github.com/spotify/scio.g8

Give it a try and let us know.

**Comment by regadas** [comment]
I'll close this issue as per discussion we will not add direct support for `Traditional templates` because `Google` is pushing for `Flex Templates`. Flex Templates are more versatile then `Traditional` even-though they still have some use cases where they shine. It's possible to use `Traditional Templates` by using `Beam IO` directly. 

Flex template, this model should work out of the box. I'll create a separate issue to track the addition of related docs.
