### ISSUE TITLE
Handle repl arguments gracefully

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#31]
Currently an invalid argument to repl would break scio context creation. Handle invalid and extra arguments gracefully in repl.

**Comment by nevillelyh** [comment]
Would also be nice if args can be modified inside a session without restarting the REPL.

**Comment by nevillelyh** [comment]
Fixed in https://github.com/spotify/scio/commit/f9c93df6ec3117187cdf8117b101c2853d57ecfa
