### ISSUE TITLE
Need a SideOutput example

### ISSUE THREAD

**Issue by sfines** [spotify/scio#313]
I have a complex data flow that I'm trying to represent in SCIO on Scala. In the java google libraries, I would branch types by using SideOutputs, however, while I can define SideOutputs in SCIO, I do not see an equivalent to PCollection.get(TupleTag<>) which would allow me to work on the relevant SideOutput- the best I see are map() or flatMap(). 

There seem to be no examples using this mechanism, and the only example I can find in the codebase at all are in SCollection.scala and that's a relatively limited use in randomSplit().

**Comment by jonopwell** [comment]
Yes, an example would be helpful.

**Comment by nevillelyh** [comment]
Did you look at the doc for `SCollection#withSideOutput`?
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L659

**Comment by nevillelyh** [comment]
Also how do you envision it to work? Side output is not a commonly used pattern so we didn't cover all the possible cases. It'd be great if you can show a snippet of what you intend to do.

**Comment by sfines** [comment]
so basically, we receive a heterogenous collection of data types, and we need to be able to split it and process each subtype with a unique subflow- in java it's something like

`  PCollectionTuple output = converted.get(RowToDataPostHandler.dataPost).apply("ProcessRecords",
                ParDo.of(new ParserHandler())
                        .withOutputTags( ParserHandler.glucoseTag,
                                TupleTagList.of(
                                        Lists.newArrayList(ParserHandler.errorRow,
                                                ParserHandler.insertionTag,
                                                ParserHandler.meterTag,
                                                ParserHandler.alertSettingsTag,
                                                ParserHandler.userEventTag,
                                                ParserHandler.deviceSettingsTag,
                                                ParserHandler.senderInformationTag))));


        output.get(ParserHandler.glucoseTag).apply(ParDo.named("GlucoseTableConverter")
                .of(new DoFn<IdentifiedGlucoseRecord, TableRow>(){
                    @Override
                    public void processElement(ProcessContext c) throws Exception {
                        log.info("Processing Glucose Records");
                        c.output(IdentifiedGlucoseConverter.format(c.element()));
                    }
                })
        );

        output.get(ParserHandler.insertionTag).apply(ParDo
                .named("InsertionTableConverter")
                .of(new DoFn<AbstractPublicDataPostData, TableRow>(){
            @Override
            public void processElement(ProcessContext c) throws Exception {
                c.output(IdentifiedInsertionConverter.format((IdentifiedInsertionRecord) c.element()));
            }
                }));

        output.get(ParserHandler.meterTag).apply(ParDo
                .named("MeterTableConverter")
                .of(new DoFn<AbstractPublicDataPostData, TableRow>(){
                    @Override
                    public void processElement(ProcessContext c) throws Exception {
                        c.output(IdentifiedMeterConverter.format((IdentifiedMeterRecord) c.element()));
                    }
                }));
               `

I've got about 45 different types embodied in this data packet and it can't be changed at the source.

**Comment by nevillelyh** [comment]
Does this look close to what you want?

```scala
val errorOut = SideOutput[Error]()
    val insertionOut = SideOutput[Insertion]()
    val meterOut = SideOutput[Meter]()
    val alertOut = SideOutput[Alert]()
    val userEventOut = SideOutput[UserEvent]()
    val records: SCollection[Record] = _

    val (mainOut, sideOuts) = records
      .withSideOutputs(errorOut, insertionOut, meterOut, alertOut, userEventOut)
      .map { case (r, ctx) =>
        // output to sides
        ctx.output(errorOut, new Error)
        ctx.output(insertionOut, new Insertion)
        ctx.output(meterOut, new Meter)
        ctx.output(alertOut, new Alert)
        ctx.output(userEventOut, new UserEvent)

        // main output
        r
      }
    val errors: SCollection[Error] = sideOuts(errorOut)
    ...
```

**Comment by sfines** [comment]
For creating the side outputs, yes. How about using them? (PCollection has a .get(TupleTag<>) method) what is the SCollection idiomatic way to handle that?

**Comment by sfines** [comment]
one other thing- the java api allows for you to call ctx.output() multiple times, does this hold true for scio?

**Comment by nevillelyh** [comment]
Do you mean `PCollectionTuple#get(): PCollection[T]`?
The last line in my snippet `val errors: SCollection[Error] = sideOuts(errorOut)` is more or less the same?

Looking at my example
- `SideOutput[T]` are equivalent to `TupleTag[T]`
- 2nd argument of lambda, `ctx: SideOutputContext[T]` wraps `DoFn#ProcessContext` and gives you access to side outputs
- 2nd return value of `map` is `sideOuts: SideOutputCollections` and wraps `PCollectionTuple` which gives you access to outputs as `SCollection[T]s`.

And to answer your question `ctx.output()` just calls `DoFn#ProcessContext#sideOutput` so yes it handles multiple invocations.

**Comment by sfines** [comment]
Great! that works!

**Comment by jonopwell** [comment]
Thanks, Neville!
