### ISSUE TITLE
Scala API for Scio Transforms

### ISSUE THREAD

**Issue by anish749** [spotify/scio#3131]
We have some awesome transforms in Scio's [transforms package](https://github.com/spotify/scio/tree/master/scio-core/src/main/java/com/spotify/scio/transforms). When using them in Scala pipelines, it can be less idiomatic. It would be nice to have first class support for this.

I was using `RateLimiterDoFn` and `DoFnWithResource` and I was hoping to have something like these on an `SCollection[T]`
```scala
def mapWithResource[R, U: Coder](resource: => R, resourceType: ResourceType)(fn: (R, T) => U): SCollection[U]
```
or 
```scala
def rateLimitPerWorker(recordsPerSecond: Double): SCollection[T]
```

I can send a PR with some of the stuff if it fits in here.

**Comment by regadas** [comment]
@zwycl will take a stab at this.
