### ISSUE TITLE
Have CircleCI run sbt mdoc + paradox when anything in "/site" folder is changed in a PR

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#3151]
Changes to any of the markdown files in `/site` could cause `sbt site/mdoc` to fail if a code snippet is incorrect, or `sbt site/paradox` to fail if a `@ref` link is broken or something. Maybe we could the CircleCI "when" clause: https://circleci.com/docs/2.0/configuration-reference/#the-when-step-requires-version-21 to execute these commands if any site files are in the git diff?

It would also be nice to have CircleCI push the site to GH pages when the PR is merged, but the credentialing might be an issue

**Comment by regadas** [comment]
@RustedBones will take this one! Thank you!
