### ISSUE TITLE
BigQuery StorageIO should include projection & predicate in test ID

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#3181]
Right now if we read from a table twice using different predicate & projections, `JobTest` will fail due to duplicate test IDs (the table spec). Users can work around it by union-ing the predicates & projection and do the split in Scala. But that might be wasteful if the predicates & projections are disjoint and we end up transferring a lot of rows/columns that'll be thrown away in Scio.

This should be fixed by including predicates & projections in the test ID.

**Comment by moscowart** [comment]
Working on it

**Comment by regadas** [comment]
@moscowart Thank you for pushing this on!

**Comment by moscowart** [comment]
Fixed in https://github.com/spotify/scio/pull/3466
