### ISSUE TITLE
Try repl based on Ammonite

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#32]
Ammonite has a couple of interesting repl features, in an enhancment, but would be interesting. Link: https://github.com/lihaoyi/Ammonite

**Comment by nevillelyh** [comment]
Guess we don't want the file system / shell replacement parts? Enhanced REPL & terminal sounds interesting.

**Comment by ravwojdyla** [comment]
Yep - the REPL/terminal itself is the interesting part.

**Comment by alexarchambault** [comment]
FYI, the [modified Ammonite](https://github.com/alexarchambault/ammonium) that [jupyter-scala](https://github.com/alexarchambault/jupyter-scala) rests on, now has some basic support for Scio. See [this session](https://gist.github.com/alexarchambault/09bdcf2b3d58bc04c4a7ed30906e141f) for example.

The code that interfaces the REPL with Scio is [here](https://github.com/alexarchambault/jupyter-scala/tree/master/scio/src/main/scala) - it's originally inspired by the `scio-repl` module from Scio.

jupyter-scala allows to run the same code in notebooks ([example](https://gist.github.com/alexarchambault/e309c8f735a4278f6912107ee72fe7a2)).

(I hope to push for the changes in the modified Ammonite in main line at some point - these mainly have to see with Java serialization and a few changes for jupyter-scala.)

**Comment by nevillelyh** [comment]
Thanks! We'll give it a try.

**Comment by nevillelyh** [comment]
This hasn't been touched forever, closing for now.
