### ISSUE TITLE
Add more documentation to BigQuery API

### ISSUE THREAD

**Issue by lindahamp** [spotify/scio#3208]
Would it be possible to add some documentation to [these](https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala) types? They are exposed but lack documentation, so it's a bit hard to understand how/when to use them? Specifically thinking about `Query` and `Table`. 

Also, adding some documentation [here](https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala#L107-L135) could be nice as well since it's currently lacking.

**Comment by liufuyang** [comment]
question links are move to 
https://github.com/spotify/scio/blob/master/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala

And 
https://github.com/spotify/scio/blob/master/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala#L107-L135

(Though I am not sure which lines exactly for now)

**Comment by jasmineytchen** [comment]
I would like to pick this up if it is still open.

**Comment by liufuyang** [comment]
I added a few things via this PR
https://github.com/spotify/scio/pull/3376 

Do you think there is more to add? You can continue with adding extra doc if you feel there is more things can be added 👍 

I will not add more doc than the ones I already have in my PR above :)
