### ISSUE TITLE
Scio Extras GenericRecord to TableRow Conversion Doesn't work for Enums

### ISSUE THREAD

**Issue by yohoos** [spotify/scio#3226]
The `toTableRowField` function in `com.spotify.scio.extra.bigquery.ToTableRow` needs a case statement like `case x: EnumSymbol => x.toString` to support `org.apache.avro.generic.GenericData.EnumSymbol`

The existing `case x: Enum[_] => x.name()` doesn't seem to work for Enums in a GenericRecord.

Stacktrace:
`INFO: SEVERE: 2020-08-05T21:06:15.713Z: com.spotify.scio.extra.bigquery.AvroConverters$AvroConversionException: ToTableRow conversion failed:could not match class org.apache.avro.generic.GenericData$EnumSymbol
INFO:   at com.spotify.data.csdata.util.VoxToTableRow$.toTableRowField(VoxToTableRow.scala:83)
INFO:   at com.spotify.data.csdata.util.VoxToTableRow$.$anonfun$toTableRow$2(VoxToTableRow.scala:60)
INFO:   at scala.Option.foreach(Option.scala:407)
INFO:   at com.spotify.data.csdata.util.VoxToTableRow$.$anonfun$toTableRow$1(VoxToTableRow.scala:59)
INFO:   at com.spotify.data.csdata.util.VoxToTableRow$.$anonfun$toTableRow$1$adapted(VoxToTableRow.scala:58)`

**Comment by nevillelyh** [comment]
Should be a simple fix, mind submitting a quick PR?

**Comment by regadas** [comment]
Closed via #3232
