### ISSUE TITLE
`scio-google-cloud-platform`

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3237]
Issues #3202 #3231 gave second thoughts. One of the end goals of moving things out of `scio-core` is to really keep it with core types, minimal dependencies and allow users to not pull extra cruft. That's what led to the separation of `bigtable`, `bigquery` and `spanner`. Now with the separation of `datastore` and `pubsub` we will end up with a lot of modules (possibly more in the future).

* `scio-bigtable`
* `scio-bigquery`
* `scio-spanner`
* `scio-pubsub`
* `scio-datastore`

In reality cruft separation doesn't really happen:

```bash 
cs resolve com.spotify::scio-bigtable:0.9.3 --scala 2.13 | grep bigquery

com.google.api.grpc:proto-google-cloud-bigquerystorage-v1:0.90.0:default
com.google.api.grpc:proto-google-cloud-bigquerystorage-v1alpha2:0.90.0:default
com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta1:0.90.0:default
com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta2:0.90.0:default
com.google.apis:google-api-services-bigquery:v2-rev20191211-1.30.9:default
com.google.cloud:google-cloud-bigquery:1.106.0:default
com.google.cloud:google-cloud-bigquerystorage:0.125.0-beta:default
````

```bash
cs resolve com.spotify::scio-bigquery:0.9.3 --scala 2.13 | grep bigtable

com.google.api.grpc:proto-google-cloud-bigtable-v2:1.9.1:default
```

Dependency wise, all share a lot of the same underlying dependencies i.e `grpc`, `google-cloud`, `beam-sdks-java-io-google-cloud-platform` and it`s hard to actively make transitive dependencies `provided` 

On a side note: Coders for these modules have been leaving within `scio-core` and they should ideally be in their respective submodule meaning that `BigQuery` `TableRow` coders should be under `scio-bigquery` requiring users to:

```scala
import com.spotify.scio.coders._
import com.spotify.scio.bigquery.coders._

// if we had scio-google-cloud-platform
import com.spotify.scio.gcp.coders._
```

Because of this I'm entertaining the idea of bringing `GCP` IO's together; one potential side-effect is that it would allow us to solve dep conflict better when used together.

wdyt?

**Comment by jto** [comment]
It makes total sense to me 👍  Let's do this.

**Comment by regadas** [comment]
Cool Cool! I'll propose smth really soon!
