### ISSUE TITLE
Release 1.0.0?

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#325]
Does it make sense given that there are already production users? http://semver.org/#how-do-i-know-when-to-release-100

Or maybe we want to wait until after the migration to Beam?

**Comment by nevillelyh** [comment]
We don't really follow semver since we don't guarantee compatibility between minor versions and I'd prefer to keep it that way so that we can move fast (release often) and not be bogged down by tech debts.

We're not selling this as a product so no point sugarcoating versions.
