### ISSUE TITLE
Mutable `ScalableBloomFilter`

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#3279]
This came up last week during an internal training. It's one of the oldest Scala code at Spotify and used heavily by some large-ish pipelines (via copy/paste). The original PR here:
https://github.com/twitter/algebird/pull/494

Since it's not a Monoid we're better off using Guava BF here. Also seems the current impl ser/de the entire `List[BF]` to append to the first (largest) one. So in practice we can just pretend a new BF if `bfs.head` is full or only ser/de the first BF to add items. As a bonus we'll also have better/more predictable coder behavior.

**Comment by nevillelyh** [comment]
I'm thinking something down the line of this, a good Java impl with light Scala wrapper & coder
https://github.com/spotify/scio/pull/2651

**Comment by kellen** [comment]
CLosed by #3339

**Comment by nevillelyh** [comment]
Did a more thorough benchmark, old Algebird based SBF vs new MSBF.
1. Create new filter with fpp = 0.01 and initial capacity of 128, insert 100 elements
2. Encode, decode, add 2x more elements (200, 400, ...)
3. Repeat 2 until 102400 elements.

New implementation seems to perform ~40% better pretty consistently.

https://docs.google.com/spreadsheets/d/1DgtFSGm9vkDiIbHZjXR_01fr6zlJycV3U5IUayI73xo/edit#gid=0
