### ISSUE TITLE
Better logging when Sparkey doesn't fit in RAM

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#3280]
We download Sparkey files to worker local disk and can easily check if file size >= RAM (optionally + some head room for JVM etc.) so it's easily to identify job slowness due to Sparkey lookup hitting disk.

Sparkey also uses `MappedByteBuffer` under the hood so we can expose `isLoaded` to compute % of chunks in RAM. That could be reported as a job metric for easy troubleshooting.
https://github.com/spotify/sparkey-java/blob/master/src/main/java/com/spotify/sparkey/ReadOnlyMemMap.java#L37

**Comment by nevillelyh** [comment]
Exposing loaded/total sparkey file bytes:
https://github.com/spotify/sparkey-java/pull/46

**Comment by regadas** [comment]
Closed via https://github.com/spotify/scio/commit/f9a9c4169397d9a047bee5bac00584b6072779ea and https://github.com/spotify/scio/commit/960ef259d76e29fda8a173d8acbe4f1638da7544
