### ISSUE TITLE
Port to Beam 0.3.0

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#330]

**Comment by andrewsmartin** [comment]
Blocked at the moment by https://issues.apache.org/jira/browse/BEAM-945

**Comment by nevillelyh** [comment]
That ticket's closed. What else are we missing?

**Comment by andrewsmartin** [comment]
There aren't any blockers, just have to do it.

**Comment by nevillelyh** [comment]
0.4.0 is out. Back to #279 for tracking
