### ISSUE TITLE
improve SMB Source autoscaling heuristic

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#3304]
As a `BoundedSource`, `SortedBucketSource` is split by Dataflow based on a desired byte size per source value (unless the user overrides this using the `TargetParallelism` parameter), provided by DataflowRunner. However, the value Dataflow requests isn't optimal for SMB, probably because the throughput of an SMB join is overall lower than a typical file-based source. Right now we "adjust" for that by just multiplying it by a factor of 0.5:

https://github.com/spotify/scio/blob/master/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java#L100

But this is definitely not optimized--empirically a lot of teams using this seem to be seeing better performance with a higher target parallelism than what `TargetParallelism.auto()` comes up with. We should put some more thought into how the optimal split size is computed, whether it's just tweaking the 0.5 value to something lower, or something more nuanced.

**Comment by ClaireMcGinty** [comment]
Right now, the autoscaling heuristic used to `split()` the `SortedBucketSource` is really basic: it gets `desiredSizeBytes` from the Runner; multiplies it by a `DESIRED_SIZE_BYTES_ADJUSTMENT_FACTOR` to adjust for the lower throughput of SMB read compared to a basic sequential file read; computes the estimated byte size of all sources; then divides the estimated source size by the adjusted desired byte size, and rounds up to the next power of 2 to produce the "optimal" parallelism.

In practice this seems kind of hit-or-miss for real datasets. I think there are other factors we could take into account, for example:

- the amount of bucket replication required if the sources have drastically different bucket counts
- the size of the bucket files themselves
- # of open connections to GCS that would be required, including shards
- the user's job configuration, i.e. maxNumWorkers or machine type (we have access to `PipelineOptions`)

@nevillelyh , any more ideas for this?

**Comment by ClaireMcGinty** [comment]
@nevillelyh - did you come to any solid conclusions about max # open GCS connections? Or is it such a niche case that we shouldn't spend a lot of time on it? On my end, it seems like an easy upgrade to the current heuristic is to go with the _most common number of buckets among sources_. I.e. if 3 sources have 64 buckets and 1 has 128, choose 64. Still validating a bit/trying to determine a tiebreaker.

**Comment by nevillelyh** [comment]
Yeah I think #3407 should improve auto-scaling in `sortedBucketTransform` & picking the right parallelism might improve more.
Don't think there's much we can do w.r.t. GCS connections, anything we might come up with seem hacky.

**Comment by ClaireMcGinty** [comment]
ultimately closed via improved documentation in https://github.com/spotify/scio/pull/3449
