### ISSUE TITLE
rules_scala build

### ISSUE THREAD

**Issue by jamesthompson** [spotify/scio#3308]
I'm wondering if anybody has any knowledge of people using `scio` at scala version 2.12 with `rules_scala` / `bazel-deps`?

I'm having difficulty getting this up and running and would love to know if there's a trick with the imports to resolve the macros properly. 

I'm currently seeing this, which I think should obviously not be an issue with the provided coders (runs fine in sbt):
```
scio/Wordcount.scala:20: error:
Cannot find an implicit Coder instance for type:

  >> (String, Long)
```

when I have the scio-core target on the classpath along with beam_sdks_java_core and beam_runners_direct_java.

**Comment by nevillelyh** [comment]
We got it working internally a long time ago. You need something like these `macroSettings` in sbt:
https://github.com/spotify/scio/blob/master/build.sbt#L326

So probably some of these settings?
https://github.com/higherkindness/rules_scala/blob/master/docs/newdocs/macros.md#macros-and-ijars
https://libraries.io/github/bazelbuild/rules_scala

**Comment by jamesthompson** [comment]
@nevillelyh Wondering why if you got it functioning, the team didn't decide to proceed with bazel/rules_scala instead of sbt? I thought bazel rules_scala was in use at Spotify?

**Comment by jto** [comment]
Hi @jamesthompson 
AFAIK there's only one team internally that uses Bazel to build a Scio pipeline. Almost all of our pipelines are built with SBT.

**Comment by nevillelyh** [comment]
@jamesthompson did you get it working?

**Comment by jamesthompson** [comment]
I didn't thus far. If there was an example small case repo that could be shared, it would help greatly @nevillelyh 
I think the ergonomic benefits with bazel for a new repo would really outweigh the cons of sbt. Thanks for checking in.

**Comment by nevillelyh** [comment]
My bazel knowledge is very outdated (3+ yo). But we got it working before and currently have repos using standard `rules_scala`. You just need to include the macro deps & make sure macro is working during compilation.

Closing. Feel free to update once you have something.
