### ISSUE TITLE
Support enumerations in BigQueryType

### ISSUE THREAD

**Issue by mbruggmann** [spotify/scio#331]
We would like to be able to use enumerations in our case classes, and have that mapped to a string field in BigQuery:
```scala
object SomeEnum extends Enumeration {
  type SomeEnum = Value
  val v1, v2 = Value
}
import SomeEnum._

@BigQueryType.toTable
case class SomeCaseClass(id: String, v: SomeEnum)

// in your job
sc.bigQuerySelect(...)
  .map(BigQueryType.fromTableRow[SomeCaseClass])
  .map(...)
  saveAsTypedBigQuery(...)
```

**Comment by andrewsmartin** [comment]
@mbruggmann we can do this, the only thing I'm hesitant about is that this mapping would not be bilateral (in the sense that type information is lost going from Enum -> String, so we can't go the other way) and this would be inconsistent with the other Scala <-> BQ types. This could cause some potential confusion IMO. What do you think?

**Comment by mbruggmann** [comment]
@andrewsmartin I guess this really only applies if you supply the case class yourself, in which case  there is a clear mapping from the enum to the string field (`toString`) and from the string field to the enum (`withName`), no?

**Comment by andrewsmartin** [comment]
@mbruggmann I see, I should have looked more closely at your code! So you're saying that even when reading, as long as you supply the case class and specify what fields should be parsed as Enum then it should be all good. In that case I am 👍 on this, although one thing to keep in mind is that if you do supply the case class instead of letting the macro take care of it, then you will have to change it manually if the table schema changes - but we can leave that choice to the user. Will look into it today.

**Comment by ravwojdyla** [comment]
@mbruggmann currently there is clear mapping between BigQuery types and Scala types. If we add Enumerations - which does not have representation in BigQuery - there is no Symbols (or predefined String values) type in BigQuery. If we add Enumerations to BigQuery macros, soon most likely other scala structures will creep in (`case object`?). If we use `withName` - there is possibility that there will be value coming from BQ that was not defined in the Enumeration - thus resulting in an exception (+/- error handling, but how?) It's debatable if Enumeration should be part of Scio/BQ-macros or user code. Another thing completely is java enums, which are anti pattern in distributed systems?

What is the problem you are trying to solve by using @mbruggmann? And why are Enumerations good for you?

Would it be a problem for you to:

```
sc.typedBigQuery[BQT]().map(r => makeEnumSafeRecord(r)).<rest-of-logic>
```

**Comment by nevillelyh** [comment]
+1 on what rav said, I prefer to handle this in user land and prevent feature creep.
Can we close this?

**Comment by mbruggmann** [comment]
@ravwojdyla @nevillelyh Our use case is that we have one job writing an enum (as in, one of a set of known values) into BQ, which is read back from later in downstream jobs. Currently we treat this field as a string everywhere, but we would like to enforce that it is in the set of known values. 

I'm fine with doing this in user land, although it'd be neat to only have one case class instead of two.

**Comment by ravwojdyla** [comment]
@mbruggmann alright - thanks. For now let's keep it in the user land, if this keep on coming as a feature request we might reevaluate. Also correct me if I'm wrong but if you use `typed` BigQuery API, you will need just one case class - you own Enumeration based one.
