### ISSUE TITLE
Use scala meta for BQ macros

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#332]
New intellij supports meta generated types now.

**Comment by ravwojdyla** [comment]
Pending on drop of scala 2.10. Also blog post is out: https://blog.jetbrains.com/scala/2016/11/11/intellij-idea-2016-3-rc-scala-js-scala-meta-and-more/

**Comment by kanterov** [comment]
Are there any blockers ATM?

Did we consider having similar to https://github.com/tpolecat/doobie approach? In Doobie, you define a schema for case class yourself, and then there is a way to verify that query has a compatible schema. 

I see there are at least these benefits:

- better compilation times because you don't verify schema in compile, but doing it in tests
- out of box IDE support, because case class already has fields defined
- support of custom injections, like `String -> ADT`
- support mapping nullable to non-nullable, doobie typechecks this with a warning, useful when BigQuery reports field as nullable, while it isn't possible

**Comment by nevillelyh** [comment]
No blocker, just not prioritized high enough.

Yeah `BigQueryType.toTable` is similar to the doobie approach, but using macros instead of shapeless for deriving converters. https://github.com/nevillelyh/shapeless-datatype has a similar approach for BQ <-> case class conversion using shapeless and can be expanded to handle this.

My concern is too many options might confuse users, especially since most aren't familiar with the magic behind these components.

**Comment by dgouyette** [comment]
You can make a cross compilation (2.11 and 2.11)
I wrote a macro to make something like that : 

```
import scala.meta.{Defn, Term, abort}
import scala.meta._
import collection.immutable.Seq


class Mutation extends scala.annotation.StaticAnnotation {


  inline def apply(defn: Any): Any = meta {
    defn match {
      case Term.Block(Seq(t: Defn.Class, companion: Defn.Object)) =>
        val caseClassFields: Seq[Term.Param] = t.ctor.paramss.flatten

        val caseClassFieldsOpt = caseClassFields.collect { case t@Term.Param(_, _, Some(targ"Option[$tpe]"), _) => t }
        val caseClassFieldNonOpt = caseClassFields.diff(caseClassFieldsOpt)


        val oldTemplateStats: Seq[Stat] = companion.templ.stats.getOrElse(Nil)
        val method =
          q"""
            import com.spotify.scio.bigtable.Mutations
            def toMutation(value : ${t.name}) : (com.google.protobuf.ByteString, Iterable[com.google.bigtable.v2.Mutation])   =  {
              import cats._, cats.data._, cats.implicits._
              (com.google.protobuf.ByteString.copyFromUtf8(value.id),
              List(..${
            caseClassFieldNonOpt map (p =>
              q"""Mutations.newSetCell("family",
                           com.google.protobuf.ByteString.copyFromUtf8(${Lit.String(p.name.value)}),
                           com.google.protobuf.ByteString.copyFromUtf8(value.${Term.Name(p.name.value)}.show))
              """)
          }) ++

              List(..${
            caseClassFieldsOpt map (p =>
              q"""value.${Term.Name(p.name.value)}
                   .map(pp =>Some(Mutations.newSetCell("family",
                      com.google.protobuf.ByteString.copyFromUtf8(${Lit.String(p.name.value)}),
                      com.google.protobuf.ByteString.copyFromUtf8(pp.show)))
                    )
                   .getOrElse(None)
              """)
          }).flatten
              )}
        """
        val updatedCompanion = companion.copy(templ = companion.templ.copy(stats = Some(method.stats ++ oldTemplateStats)))
        //abort(updatedCompanion.syntax)
        Term.Block(Seq(t, updatedCompanion))
      case _ => abort("Mutation must annotate a class")
    }
  }
}

```
it's already works in scala 2.11
I hope, it'll be useful

**Comment by jto** [comment]
Scalameta is no longer intended to replace the current macro system: 

- https://scalameta.org/#Notontheroadmap
- https://github.com/scalacenter/macros

I suppose this issue should be closed.
