### ISSUE TITLE
sortMergeTransform to output larger bucket/shards as input

### ISSUE THREAD

**Issue by ChristopherLee** [spotify/scio#3326]
I think it would be very useful to be able to use `sortMergeTransform` but output a different bucketing/sharding scheme from the original dataset. It seems like it should be possible to be able to output to a larger bucketing/sharding scheme (ie. if the input dataset has 1024 buckets, you should be able to output to 2048) from the original dataset, as it would just mean instead of a worker outputting a single file, it would need to output it to two files.

**Comment by ClaireMcGinty** [comment]
As of the latest version of Scio, you are able to specify a larger bucket size in an SMB transform! It does mean that some of the keys will need to be re-hashed to ensure they get written to the right output bucket, but there's nothing preventing you from specifying a larger # bucket than the input(s).

As for sharding, do you have a use case example for needing a larger # shards? the main reason to increase shard count in SMB sink is if some of the buckets are skewed and can't be efficiently grouped and sorted on a single worker... but that's circumvented in the SMB transform as the full bucket is never materialized in memory.

**Comment by ChristopherLee** [comment]
We originally used 2 shards in our dataset when generating very large SMB datasets that needed to do a full shuffle/sort and was hitting some memory issues. I think we could have probably used 2x the buckets instead, and that is actually what I plan to test soon. I was concerned that when using the `sortMergeTransform` on some additional data that we'd join would want to have a matching bucket/sharding scheme, but after our other conversation, maybe thats not as strict of a requirement. As long as these datasets of varying buckets and shards will be able to be joined, I think the need for outputting multiple shards from the `sortMergeTransform` isn't necessary so I think this can be closed.
