### ISSUE TITLE
Scio BigQuery client could inherit labels from Beam/Dataflow job

### ISSUE THREAD

**Issue by mkuthan** [spotify/scio#3333]
We are using labels on each and every GCP resource for better accountability. So every Dataflow job (and every resource consumed by the job) is labeled with job name. Together with costs BigQuery export we will get nice and detailed costs report for every Dataflow job.

One missing piece of the puzzle is a BigQuery jobs spawned by Scio. What do you think about labels inheritance, e.g. labels form the job will be passed to the com.google.api.services.bigquery.model.JobConfiguration created by internal Scio BigQuery client?

BTW. I need to fill similar change for Beam BigQueryIO and its internal BigQuery client :)

**Comment by jto** [comment]
Just had a look at that. Sadly Beam does not expose `com.google.api.services.bigquery.model.JobConfiguration` in its `BigqueryIO` so it seems to need a fix in Beam.

**Comment by mkuthan** [comment]
@jto that's true than we can't fix beam.BigQueryIO but what about Scio internal client? As I understood Scio code, scio.BigQueryIO make initial query export to temporary dataset using internal client.

**Comment by jto** [comment]
@mkuthan Not necessarily which might be smth wwe should look into...

**Comment by mkuthan** [comment]
Thanks a lot!
