### ISSUE TITLE
java.lang.NoSuchMethodError when using GCP credentials

### ISSUE THREAD

**Issue by richiesgr** [spotify/scio#3338]
Hi
I've been able to run the wordcount example without problem.
But when I try to access data located in a bucket with credentials I get 
` Exception in thread "main" java.lang.NoSuchMethodError: com.google.cloud.hadoop.util.CredentialOptions$Builder.setServiceAccountPrivateKeyId(Ljava/lang/String;)Lcom/google/cloud/hadoop/util/CredentialOptions$Builder;
[error] 	at com.google.cloud.hadoop.util.HadoopCredentialConfiguration.getCredentialFactory(HadoopCredentialConfiguration.java:170)
[error] 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1442)
[error] 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1510)
[error] 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1486)
[error] 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:541)
[error] 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:494)
[error] 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
[error] 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:93)
[error] 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2701)
[error] 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2683)
[error] 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:372)
[error] 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
[error] 	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:500)
[error] 	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:469)
[error] 	at com.spotify.scio.parquet.GcsConnectorUtil$.setInputPaths(GcsConnectorUtil.scala:54)
[error] 	at com.spotify.scio.parquet.avro.ParquetAvroIO.read(ParquetAvroIO.scala:56)
[error] 	at com.spotify.scio.parquet.avro.ParquetAvroIO.read(ParquetAvroIO.scala:47)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:77)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:74)
[error] 	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:705)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext(ScioIO.scala:74)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext$(ScioIO.scala:70)
[error] 	at com.spotify.scio.parquet.avro.ParquetAvroIO.readWithContext(ParquetAvroIO.scala:47)
[error] 	at com.spotify.scio.ScioContext.read(ScioContext.scala:859)
[error] 	at com.spotify.scio.parquet.avro.package$ParquetAvroFile.map(package.scala:85)
[error] 	at com.dv.Repartition$.main(Repartition.scala:42)
[error] 	at com.dv.Repartition.main(Repartition.scala)`

the version generated are 
val scioVersion = "0.9.4"
val beamVersion = "2.23.0"
val sparkVersion = "3.0.0"

I'm trying to run it on Dataflow runner like this
`sbt "runMain com.dv.Repartition --project=<project> --runner=DataflowRunner --zone=us-east1-b --input=<bucketin>--output=<bucketOut>"
`
I'm sure it's a dependencies problem but how to find what ?

**Comment by regadas** [comment]
Hi @richiesgr this seems like a dependency issue. You can use SBT `evicted` or even [sbt-dependency-graph](https://github.com/sbt/sbt-dependency-graph). If you share your dependencies I can try help you out.

**Comment by richiesgr** [comment]
[out.txt](https://github.com/spotify/scio/files/5262077/out.txt)
Attached Thanks

**Comment by nevillelyh** [comment]
Please look for possible conflicts & try excluding or pinning versions.
Also latest Beam Spark runner still depends on Spark 2.4.6. Don't think this is something we can support.

https://mvnrepository.com/artifact/org.apache.beam/beam-runners-spark/2.24.0
