### ISSUE TITLE
Provide lite version of scio context or warning user on GBK

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#334]
Provide lite version of context without performance issue prone methods like groupbykey etc, or warn (possibly through deprecation).

**Comment by nevillelyh** [comment]
I prefer warning over a separate class. We should also think about how to do this without being too intrusive.

**Comment by ravwojdyla** [comment]
Turns out that in certain situation GBK in Cloud Dataflow can be more performant than using combine. Closing for now, open later if needed.
