### ISSUE TITLE
containsInAnyOrder matcher failing with bigquery.TableRow 

### ISSUE THREAD

**Issue by marselasulku** [spotify/scio#3355]
I'm facing a weird issue with the containsInAnyOrder matcher and not sure how to fix it. 

Here's a screenshot of the error output when I run my tests:
<img width="1694" alt="Screen Shot 2020-09-25 at 1 32 14 PM" src="https://user-images.githubusercontent.com/14287230/94313741-20174680-ff34-11ea-93a5-7c30634ede5d.png">

This is the test 
```
      .output(CustomIO[STableRow]("Write Event To BigQuery"))( events => {
        events.map(f => f.sDataType) should containInAnyOrder (Seq[STableRow](OUTPUT_VALID_EVENTS).map(f => f.sDataType))
        events.map(f => f.location) should containInAnyOrder (Seq[STableRow](OUTPUT_VALID_EVENTS).map(f => f.location))
        events.map(f => f.tableRow) should containInAnyOrder (Seq[STableRow](OUTPUT_VALID_EVENTS).map(f => f.tableRow))
      })
```

for some reason, the line comparing the tableRows is failing despite output that shows they are the same. The tableRow field is of type `com.spotify.scio.bigquery.TableRow`

scio version 0.9.0
scala version 2.12.12

**Comment by marselasulku** [comment]
actually just figured out what the issue was. 

I passed in a pubsub message with a boolean field. When I was building my expected TableRow, I set the field like this: `.set("field_name", "true")` but it should have been `.set("field_name", true)`. 

The logging should maybe be a little bit more clear for cases like this. I'll leave this open so you all can determine if you want to change the logging

**Comment by nevillelyh** [comment]
Yeah `TableRow`s are really just JSON, have no standard Java type mapping or `equals` impl. I'd map the fields you want to compare to something else for assertion.

Also this happens inside Beam Java matcher, not a lot we can do :shrug:

**Comment by regadas** [comment]
Since we have a custom printer when using `SCollection` matchers we can alleviate this pain when comparing `GenericJson` types. By default `toString` is used and in this case the default impl is terrible.

#3367 should help
