### ISSUE TITLE
Add support for checkpoints/snapshots

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#337]
Add support for snapshots similar to scalding. Only for batch mode.

**Comment by nevillelyh** [comment]
Although a desirable feature, not sure if we want to handle this ourselves though. Should probably escalate to Dataflow guys and handle there?

**Comment by ravwojdyla** [comment]
Probably makes more sense to first add support in beam, and then adjust in scio. Reopen if there is support in beam. Closing for now.

**Comment by ravwojdyla** [comment]
Beam issue: https://issues.apache.org/jira/browse/BEAM-1458

**Comment by ravwojdyla** [comment]
#639 PR
