### ISSUE TITLE
Simplify "stream to date-partitioned BQ table" usecase

### ISSUE THREAD

**Issue by bcleenders** [spotify/scio#3372]
When a user wants to stream data to a date-partitioned BQ table, the way to do this is:

```scala
//noinspection ScalaStyle
class DayPartitionFunction()
  extends SerializableFunction[ValueInSingleWindow[TableRow], TableDestination] {
  override def apply(input: ValueInSingleWindow[TableRow]): TableDestination = {
    val partition = DateTimeFormat.forPattern("yyyyMMdd").withZone(DateTimeZone.UTC)
      .print(input.getWindow.asInstanceOf[IntervalWindow].start())
    new TableDestination("myproject:mydataset.mytable_" + partition, "")
  }
}

object MyJob {
    ...
    .saveAsCustomOutput(
       "myOutputName",
        BigQueryIO.writeTableRows().to(
          new DayPartitionFunction())
          .withSchema(JsonSchemaHelpers.tableSchema)
          .withWriteDisposition(WriteDisposition.WRITE_APPEND)
          .withCreateDisposition(CreateDisposition.CREATE_IF_NEEDED))
}
```

which is a lot of code for a (seemingly) simple operation.

If this is a common usecase (I'm not sure), maybe we could make this a bit simpler. E.g. removing the need for the `DayPartitionFunction` class would be nice.

**Comment by jasmineytchen** [comment]
I would like to take a stab at this.

**Comment by Mao1990** [comment]
Is the expected API become like:

```
BigQueryIO
        .writeTableRows()
        .toDatePartitionTable("my-project:my-dataset.my-table")
```

And generated table name like `myproject:mydataset.mytable_" + partition`?

**Comment by syodage** [comment]
@jasmineytchen are you working on this?

**Comment by jasmineytchen** [comment]
hey @syodage, I think the use case described is already supported [here](https://github.com/spotify/scio/blob/master/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/dynamic/syntax/SCollectionSyntax.scala#L115:L127). 

I am still on it however, and am now exploring the possibility to incorporate this into BigQueryIO itself.

**Comment by nevillelyh** [comment]
Closing since this is supported by dynamic destination.
