### ISSUE TITLE
TableRow::getRecord throws a null pointer exception if a field is requested but does not exist.

### ISSUE THREAD

**Issue by sfines-clgx** [spotify/scio#3378]
If a field does not exist in the TableRow, the getRecord method will throw a NullPointerException instead of returning null or some other value.

**Comment by regadas** [comment]
Hi @sfines-clgx can you provide an example? from a quick look it seems to behave as expected...

**Comment by sfines-clgx** [comment]
more specifically, getRecord()

**Comment by sfines-clgx** [comment]
Here's the unit test, because I can't upload a .scala attachment:

`import com.spotify.scio.bigquery._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should

class TestNullGetRecord extends AnyFlatSpec with should.Matchers{
  "a null field name" should "not throw an NPE" in {
   val dummy =  List(("a", 1), ("b", 2))
    val row = TableRow(dummy :_*)
    val result = row.getRecord("c")
    result should be (null)
  }
}
`

**Comment by regadas** [comment]
@sfines-clgx Ah I see! yeah that one will throw, nice catch! https://github.com/spotify/scio/blob/master/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/TableRowSyntax.scala#L80

From slack you already have a path for this! Awesome! 🙏

**Comment by sfines-clgx** [comment]
Yeah, I will get the PR in this weekend.. can't do it on company time, unfortunately.

**Comment by regadas** [comment]
Hi @sfines-clgx were you able to get something together?

**Comment by sfines-clgx** [comment]
I've been swamped, tbh, I have the test case but am just now coming out of a release cycle so I should have time in the next week or so
