### ISSUE TITLE
Any sample of Scio fat jar instead of running with target?

### ISSUE THREAD

**Issue by RohitR1** [spotify/scio#3419]
Is it possible to use Scio fat jar, i.e.

instead of 
```bash
target/universal/stage/bin/job --output=gs://mybucket/wc/ --runner=FlinkRunner --flinkMaster=localhost:8081
```

Is it possible to use a fat jar and submit to flink, And Sample repo is avilable?

**Comment by regadas** [comment]
Hi @RohitR1 

It it is possible. You can find an example on how to accomplish this in our [spotify/scio.g8](https://github.com/spotify/scio.g8)

https://github.com/spotify/scio.g8/blob/master/src/main/g8/build.sbt#L98-L118.

You will need to use `sbt-assembly` and bare in mind that the above is just an example and is catered towards Dataflow flex templates you will need to adjust the assembly rules a bit for Flink. 

Gonna close this for now. We can continue the discussion if needed! Thanks!
