### ISSUE TITLE
Enable custom KryoSerializer and/or Dataflow Coder

### ISSUE THREAD

**Issue by ElPicador** [spotify/scio#343]
One of our job was taking a huge number of workers, so we tried to understand why.

The job as the following:

```
pub/sub[String] -> 
  parse[MyObject] -> 
  keyBy[(MyCaseClass, Int)] -> 
  Aggregator[(MyCaseClass, Long)] -> 
  pub/sub[(MyCaseClass, Long)]
```

We had ~30k messages/s from pubsub, and the job took ~30 workers to run.
By using a custom Dataflow coder for `MyCaseClass` (a simple mapping of fields) the job now takes ~3 workers to run.

Furthermore, we use the algebird [SpaceSaver](https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala). 
We tried some micro-benchmarking on coding -> decoding with Kryo for 100k objects:
- Build-in coder/decoder: 2600ms
- Custom : 150ms

It seems that Custom coders is a huge improvement to performances. 

Perhaps having a `log.warning` when scio see a default coder for any class?
Furthermore, it'll be nice to be able to add custom kryo coders easily. Today we had to copy/paste the `RichCoderRegistry` class to add some of ours. 
We also used the [ScalaKryoInstantiator](https://github.com/twitter/chill/blob/develop/chill-scala/src/main/scala/com/twitter/chill/ScalaKryoInstantiator.scala) from chill.

**Comment by nevillelyh** [comment]
I agree we should look into enable user defined Kryo `Serializer[T]` or Dataflow `Coder[T]`.
Not sure about warning though since that might be too noisy.

**Comment by nevillelyh** [comment]
@ElPicador I'm surprised that Kyro is so much slower than custom coder for a simple case class. Can you put the case class, custom coder & benchmark code in a gist? I'd prefer to not encourage user defined coders since they're error prone, but we should look into the performance problem.

**Comment by ElPicador** [comment]
The mapping of the case class was made with a custom Dataflow Coder, not a Kryo one.

We only use a specific Kryo coder for SpaceSaver, because it contains scala Maps: https://gist.github.com/ElPicador/74a274bba171eb69b7717a515236ad75.

The benchmark was made on my compute using scalameter: https://gist.github.com/ElPicador/d8ef6195d279ea042bfbb064ba1d4b4e

**Comment by ElPicador** [comment]
> Not sure about warning though since that might be too noisy.

We lost a lot of time trying to figure why our jobs where using a lot of workers. And most of our issues where because of having generic coders. So a warning would have been a huuuuge help for us 😄

**Comment by nevillelyh** [comment]
Added a slightly more longer benchmark that covers `KryoAtomicCoder`, `KryoAtomicCoder` with custom `KSerializer`, and handcraft `AtomicCoder`.

https://github.com/spotify/scio/commit/b3e752b9f95cac6a58b9ab6d9f2d025001b94d57

The differences aren't as significant though. Any idea what else could be causing problem?

```
[info] ::Benchmark KryoAtomicCoder.roundTrip::
[info] cores: 12
[info] hostname: foobar
[info] name: Java HotSpot(TM) 64-Bit Server VM
[info] osArch: amd64
[info] osName: Linux
[info] vendor: Oracle Corporation
[info] version: 25.111-b14
[info] Parameters(size -> 10000): 30.911682
[info] Parameters(size -> 20000): 59.259351
[info] Parameters(size -> 30000): 88.841885
[info] Parameters(size -> 40000): 118.772575
[info] Parameters(size -> 50000): 148.626651
[info] 
[info] ::Benchmark CustomKryoAtomicCoder.roundTrip::
[info] cores: 12
[info] hostname: foobar
[info] name: Java HotSpot(TM) 64-Bit Server VM
[info] osArch: amd64
[info] osName: Linux
[info] vendor: Oracle Corporation
[info] version: 25.111-b14
[info] Parameters(size -> 10000): 24.935573
[info] Parameters(size -> 20000): 48.615749
[info] Parameters(size -> 30000): 74.526586
[info] Parameters(size -> 40000): 98.930947
[info] Parameters(size -> 50000): 121.382545
[info] 
[info] ::Benchmark NativeAtomicCoder.roundTrip::
[info] cores: 12
[info] hostname: foobar
[info] name: Java HotSpot(TM) 64-Bit Server VM
[info] osArch: amd64
[info] osName: Linux
[info] vendor: Oracle Corporation
[info] version: 25.111-b14
[info] Parameters(size -> 10000): 16.318835
[info] Parameters(size -> 20000): 32.587384
[info] Parameters(size -> 30000): 48.765908
[info] Parameters(size -> 40000): 65.089004
[info] Parameters(size -> 50000): 81.390727
[info] 
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
```

**Comment by ElPicador** [comment]
Apart from the size of the test (I did my tests on 1M operations), I don't know :/

**Comment by nevillelyh** [comment]
I looked at `SpaceSaver` more closely and realized that `SSMany` has extra an field `buckets` that needs to be ser/de-ed with the default serializer. That's probably the main cause of performance difference.

Also noticed that you're using a private constructor of `SSMany`. It's better if this is added to [chill-algebird](https://github.com/twitter/chill/tree/develop/chill-algebird/src/main/scala/com/twitter/chill/algebird) directly. Do you want to contribute there instead? Note that you'll have to patch `algebird` first to expose that ctor.

We should also include `chill-algebird` in `KryoAtomicCoder` by default.

Meanwhile we'll look into supporting custom Kryo registrators in `KryoAtomicCoder` but that's not easy given the current design.

**Comment by nevillelyh** [comment]
https://github.com/spotify/scio/pull/348 adds `chill-algebird` to `KryoAtomicCoder`, This should address your case once we add `SpaceSaver` serializer to `chill`.

**Comment by ElPicador** [comment]
It needs to have a specialized serializer in Algebrid first: https://github.com/twitter/algebird/issues/577

**Comment by nevillelyh** [comment]
@ElPicador thanks looking forward to that. Thoughts on #351?
