### ISSUE TITLE
Missing tcnative dep in 0.9.5

### ISSUE THREAD

**Issue by oguzhanunlu** [spotify/scio#3441]
Hi,

I recently upgraded my dataflow job to Scio 0.9.5 and received the same exception from https://github.com/spotify/scio/issues/2933 

`Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod`

where I have `org.apache.beam:beam-runners-google-cloud-dataflow-java:2.24.0` in addition to `scio-core:0.9.5`.

Unlike 0.9.3 or 0.9.4, scio 0.9.5 doesn't have `io.netty:netty-tcnative-boringssl-static:2.0.30.Final` , was that intentional?

I think I can just add tcnative to my app and continue for now but wanted to bring it to your attention.

**Comment by regadas** [comment]
Hi @oguzhanunlu this fell off my radar. This will be fixed in the next release.

Thanks for reporting!

**Comment by oguzhanunlu** [comment]
Thanks @regadas !
