### ISSUE TITLE
read multiple keyranges from one read in BigTableIO

### ISSUE THREAD

**Issue by saverma21** [spotify/scio#3447]
Currently, BigTableIO only supports single keyRange lookup, we would like to request multiple key ranges lookup in the same read instead of having to do multiple reads. Something like below

def bigtable(
    bigtableOptions: BigtableOptions,
    tableId: String,
    keyRange: Seq[ByteKeyRange],
    rowFilter: RowFilter
  )

Can you add this to the BigTableIO? Thanks!

**Comment by regadas** [comment]
Hi @saverma21 this is actually being addressed by #3442. Thanks

**Comment by saverma21** [comment]
cool - I will close this then
