### ISSUE TITLE
Allow `.withHotKeyFanout` on `SCollectionWithSideInput.`

### ISSUE THREAD

**Issue by harveyxia** [spotify/scio#345]
One way to deal with hot keys is to selectively fan out keys that the programmer expects to be hot. This can be done with `.withHotKeyFanout(K => Int)`. The ability to access a side input inside the `K => Int` fanout factor function would be a convenient way to do that, but currently the `SCollectionWithSideInput` does not possess that functionality.

**Comment by nevillelyh** [comment]
Before we jump into adding that, what's your side input like and how do you want to use them? If it's a single value/set/map, etc., does `.cross(rhs).withHotKeyFanout` work for you?

**Comment by harveyxia** [comment]
It is just a single map. And I wasn't aware of that approach, I'll try it, thanks!

**Comment by nevillelyh** [comment]
@harveyxia if my suggestion works I'd prefer to close this and not over complicate `SCollectionWith*` APIs. Thoughts?

**Comment by harveyxia** [comment]
Feel free to close this issue, I was able to work around it by just by building in the side input information into the elements themselves. Thanks
