### ISSUE TITLE
TapsTest fails on some machines after 10 sec timeout

### ISSUE THREAD

**Issue by artmoskvin** [spotify/scio#3478]
[TapsTest](https://github.com/spotify/scio/blob/master/scio-test/src/test/scala/com/spotify/scio/io/TapsTest.scala#L88) fails with ` java.util.concurrent.TimeoutException: Future timed out after [10 seconds]` when running on my local machine which has more than enough resources (MBP 16" 2019, 2.4 GHz 8-Core Intel Core i9, 16 GB). I verified that `.jvmopts` are picked up by `sbt`. If I increase the timeout to 20 sec, the test passes. 

The issue doesn't exist on CI machines. So I'm opening this issue to see if anyone else has it.

**Comment by RustedBones** [comment]
`TapsTest` have been refactored some time ago. We're internally not experiencing any issue. Feel free to re-open if you are still affected
