### ISSUE TITLE
add optional user-supplied BiFunction between SMB sink's GroupByKey and SortValues steps

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#3503]
We've gotten feedback internally from SMB users who are writing data as an SMB sink and want to leverage that to avoid shuffles elsewhere in their pipeline. For example, take the following use case, where we want to decorate user event data using the aggregated # events per user:

```scala
val data: SCollection[GenericRecord] = ...

data
  .keyBy(_.get("user_id")
  .groupByKey
  .flatMap { case (userId, events) =>
    events.map(_.toBuilder().setNumEvents(events.size).build()
  }
  .saveAsSortedBucket(AvroSortedBucketIO
    .write(classOf[String], "user_id", schema)
    .to(...)
  )
```

you can see that in this case, the pipeline has to do two GBK operations on the same key, flattening out the results in between in order to conform to the SMB api. This is a common enough pattern that @nevillelyh and I were thinking we could offer the user the ability to supply some kind of `BiFunction<K, Iterable<V1>, Iterable<V2>>` that would be applied as a `MapElements` step in between SMB Sink's `GroupByKey` and `SortValues` steps:

https://github.com/spotify/scio/blob/cd3b11d7b8afec27ad64a2b6e6e21f42ea3fcf34/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java#L204-L212

The above example could then be simplified to:

```scala
val data: SCollection[GenericRecord] = ...

data
  .saveAsSortedBucket(AvroSortedBucketIO
    .write(classOf[String], "user_id", schema)
    .to(...)
    .withGroupMappingFn { case (userId, events) =>
      events.map(_.toBuilder().setNumEvents(events.size).build()
    }
  )
```

that way there would only be a single shuffle operation in the pipeline, eliminating redundancy. Note that the input and output types of the BiFunction (`V1` and `V2`) may be different types, so we might have to add some logic to figure out the Coder for each.

**Comment by ClaireMcGinty** [comment]
@syodage would you be interested?

**Comment by syodage** [comment]
@ClaireMcGinty since users have access to the key`K` in  value`V1`, should we support `Function<Iterable<V1>, Iterable<V2>>`?  this then aligns with `mapValues`

**Comment by ClaireMcGinty** [comment]
I think it's a cleaner API to use the BiFunction that includes `K` in the signature - just because it makes it more clear that it's a key group being operated on, and so that users don't have to do something ugly like `values.headOption.map(_.getKey).getOrElse(...)` to extract the group's key from the first element :P

**Comment by nevillelyh** [comment]
Talked IRL. If `numShards > 1`, each `Iterable<V>` might only contain a random subset of values and defeats the `.size` use case or potentially other ones that require all values of the same key.
Also since we group on bucket+shard ID, the raw, lazy `Iterable<V>` post GBK can be huge and might require spilling to disk for sorting. Materializing them into a multi-map inside `GroupMappingDoFn` will likely OOM.
