### ISSUE TITLE
Porting distributed build Annoy (ann4s)

### ISSUE THREAD

**Issue by mskimm** [spotify/scio#3536]
I'm an author of [ann4s](https://github.com/mskimm/ann4s) which is building Annoy Index on Apache Spark.
As mentioned in README, I had built an index of 117M 64-dimensional vectors using 100 nodes in 5 minutes.

I would like to port ann4s to this project by PRs. Is this a good idea?

**Comment by regadas** [comment]
Hi @mskimm, thanks for reaching out and for the interest in Scio!

I believe it will be better if you do it under your own project by having a module structure and publishing them separately. i.e

```
modules
├── spark-ann4s
└── scio-ann4s
```

If you have doubts/questions around Scio feel free to also reach us on [Slack](https://slackin.spotify.com/).

**Comment by mskimm** [comment]
Thanks for your comments. I will get started as you said.
