### ISSUE TITLE
[FeatureRequest] updateNumberOfBigtableNodes can take specific cluster as a parameter

### ISSUE THREAD

**Issue by sisidra** [spotify/scio#3541]
Currently `com.spotify.scio.bigtable.syntax.ScioContextOps#updateNumberOfBigtableNodes` updates all clusters for the instance.
That is not desired behaviour if each cluster is dedicated for specific task - one for batch jobs, another for service, etc.
Desired API is to allow change node count for only specific cluster (dedicated for batch jobs).

Proposed API change:
```
- def updateNumberOfBigtableNodes(
-    projectId: String,
-    instanceId: String,
-    numberOfNodes: Int,
-    sleepDuration: Duration = DefaultSleepDuration
-  )
+ // Empty list means *all* clusters, for backwards compatibility.
+ private val DefaultClusters: List[String] = List.empty()
+ def updateNumberOfBigtableNodes(
+    projectId: String,
+    instanceId: String,
+    numberOfNodes: Int,
+    clusterId: List[String] = DefaultClusters,
+    sleepDuration: Duration = DefaultSleepDuration
+  )

- def updateNumberOfBigtableNodes(
-    bigtableOptions: BigtableOptions,
-    numberOfNodes: Int,
-    sleepDuration: Duration
-  )
+ def updateNumberOfBigtableNodes(
+    bigtableOptions: BigtableOptions,
+    numberOfNodes: Int,
+    clusterId: List[String] = DefaultClusters,
+    sleepDuration: Duration
+  )
```

**Comment by sisidra** [comment]
Maybe `getBigtableClusterSizes` should also be included in change.

**Comment by sisidra** [comment]
Alternative is to introduce functions with different name that take single instance as parameter, e.g. `updateNumberOfBigtableClusterNodes`, `getBigtableClusterSize`.

**Comment by regadas** [comment]
Hi @sisidra! updating only selected clusters makes sense to me!

Changes would need to be added here https://github.com/deacondesperado/scio/tree/update_beam_226/scio-google-cloud-platform/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java and then propagated to the Scala API.

Adding an extra argument should be enough here.

**Comment by syodage** [comment]
@sisidra are you still working on this? if so could you give an update?
