### ISSUE TITLE
Provided `--filesToStage` do not get added

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3561]
Currently we override the `filesToSatge` option with the jar's detected in the classpath discarding the values being passed. 

We should be able to append instead. Something like this can work.

```scala
    val providedFiles = options
      .as(classOf[DataflowPipelineWorkerPoolOptions])
      .getFilesToStage()
      .asScala
    val filesToStage = RunnerContext.filesToStage(options, classLoader, artifacts ++ providedFiles)

    options
      .as(classOf[DataflowPipelineWorkerPoolOptions])
      .setFilesToStage(new java.util.ArrayList(filesToStage.asJavaCollection))
```

Also because this option is runner specific we should look into the other supported contexts.

**edit**: I think it would actually be better if we only add jars from classpath if `filesToStage` are not set.

**Comment by mkuthan** [comment]
Fully agree that it would be better to follow Beam convention. 

"If you set this option, then only those files you specify will be uploaded (the Java classpath will be ignored)."
