### ISSUE TITLE
Give deterministic names to internal transforms.

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#358]
See #357

**Comment by nevillelyh** [comment]
Sub-transforms in a composite should get the same `CallSites.getCurrent` or `.withName` from provider but we should double check.

**Comment by andrewsmartin** [comment]
@nevillelyh can we close this? We can open separate issues later for anything that comes up with internal transform names

**Comment by nevillelyh** [comment]
Yeah sounds good.
