### ISSUE TITLE
Bigquery `TableRow` default coder

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3606]
With the move to `scio-google-cloud-platform` the default coder for `TableRow` became the `GenericJson` coder. This coder differs from `TableRowCoder` (backed by Jackson ObjectMapper) slightly in value conversion. 

`JsonObjectParser` converts every (int, float, double) to `java.math.BigDecimal`. Users updating to 0.10.0 if casting values will face smth like:

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
```

1) We could introduce back `Coder[TableRow]`. Users migrating will need to:

```
import com.spotify.bigquery.coders._
```

**or**

2) we can change the `Coder[T <: GenericJson]` to use jackson `ObjectMapper` instead. This would make things smooth for those using this module but it would break things for those relying on this coder.

I think I'm going with option 1) since users will need to migrate to that new module which already introduces some other changes.

**Comment by nevillelyh** [comment]
How did it work before? Did we have an `Coder[TableRow]` instance in the default import scope?
