### ISSUE TITLE
BigTable Future not implemented

### ISSUE THREAD

**Issue by joelostlund** [spotify/scio#363]
Hey,

Currently, BigTable Futures are not implemented. When calling the .saveAsBigTable function you will get an error saying that the future aren't implemented yet for BigTable. We would like to use this in our project to check the completeness of a insert into BigTable.

I am referring to this:

https://github.com/spotify/scio/blob/c19c0f7d37ca5031fcb30718ec9305217ca3d0b8/scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala#L128

**Comment by ravwojdyla** [comment]
Thanks @joelostlund. How do you imagine checking the completeness of your Bigtable load to look like (please keep the `Tap` interface in mind)? Is checking the final stat of scio result not enough for your use case?

**Comment by nevillelyh** [comment]
It was intentional since a Bigtable `Tap[T]` represents all cells that satisfies a query, not just mutations written from the `SCollection` in a partial update. And that's inconsistent with other taps that are atomic.

**Comment by nevillelyh** [comment]
@joelostlund can we close this since it's out of scope.

**Comment by joelostlund** [comment]
Yes you can
