### ISSUE TITLE
Move `AvroType` to separate sub-projects

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#3710]
To make ways for Scala 3 migration.

**Comment by nullobject** [comment]
For the time being, will 0.10.x packages for the bigquery subproject be published to maven?

**Comment by regadas** [comment]
With 0.10.x they are published as `scio-google-cloud-platform`.

If you are moving to this release, have a look at https://spotify.github.io/scio/migrations/v0.10.0-Migration-Guide.html since there are a few other changes.

**Comment by nullobject** [comment]
@regadas Thanks, exactly what I was looking for :+1:

**Comment by jto** [comment]
I'm working on the `AvroType` part.

**Comment by RustedBones** [comment]
Probably a won't do if we move away from macros in favor of magnolify
