### ISSUE TITLE
Avoid duplicated work in `BaseAsyncLookupDoFn`

### ISSUE THREAD

**Issue by jto** [spotify/scio#3711]
## The problem 

The current implementation of `processElement`

1. Check if cache existence for `input`
1. If the cache returns value return it
1. otherwise, aquire a semaphore
1. call `asyncLookup` and pass it `input`. It return a future: `F`
1. Maintain a list of the currently executing futures
1. release a semaphore at the end each future execution
1. make sure all the future are completely executed when "finishing" the bundle. 

However, because Beam processes elements per bundle, the same lookup may be executed multiple time before a value is actually cached.

Consider the following example: We lookup some value per `userId`.

We may have to process a bundle a values looking like this:

```
uid0
uid0
uid0
uid1
uid0
uid0
```

Assuming `maxPendingRequests > 6`, all those elements will be processed simultaneously. So the following futures will be created:

- A future doing a lookup with key `uid0`
- A future doing a lookup with key `uid0`
- A future doing a lookup with key `uid0`
- A future doing a lookup with key `uid1`
- A future doing a lookup with key `uid0`
- A future doing a lookup with key `uid0`

We can see the same work is done 5 times. This issue is likely to happen if 
- The dataset being processed is heavily skewed
- lookup execution takes a while

## Proposed solution

Maintain a `Map` of all the currently executing future indexed by `A` and just return the same future all five time, avoiding unnecessary work.
 
## Caveat

Probably need a good retry strategy ?

**Comment by nevillelyh** [comment]
How big of an impact is this though? If the client has good async behavior, and the payloads are small enough, it doesn't add too much network overhead? OTOH the extra concurrent map would potentially require more locking per element?
Retry, staleness (unlikely but if the external service is fast changing, or if the DoFn input stream is very slow) are other complexities.

**Comment by jto** [comment]
Potentially big positive impact, but ofc. ymmv.

Given that lookups typically query an external system, the time lost locking is very likely to be negligible compared to network IO. However in some cases (I tried it on my hackweek kv thingy) it can make lookup 5 or 10 times faster. 
One thing to consider is it's not necessarily only about the Scio job. It can also reduce the stress on the system being looked up.

Wdyt about implementing this under an opt-in flag ? I'm sure we can find users internally that could try it out and see how it impacts performances.

**Comment by nevillelyh** [comment]
Yeah that could work, and we'd memorize only for as long as the map has a key, basically as long as the request roundtrip. Need to be careful with any potential race condition though.
