### ISSUE TITLE
scio-bigquery version 0.10.0 is not available

### ISSUE THREAD

**Issue by fortega** [spotify/scio#3720]
Hello!
i'm trying to upgrade to version 0.10.0 but cannot find bigquery package in base maven repo:
https://search.maven.org/artifact/com.spotify/scio-bigquery_2.13

I try using bq 0.9.6 and doesnt work...

Thanks!

**Comment by nevillelyh** [comment]
Hi all GCP specific dependencies were moved into `scio-google-cloud-platform` starting 0.10.0.
https://spotify.github.io/scio/Changelog.html#breaking-changes-since-scio-0-10-0-
