### ISSUE TITLE
Provide a way to unsafely allow another runner version

### ISSUE THREAD

**Issue by turb** [spotify/scio#3739]
The beam version is auto-hardcoded in `BuildInfo` and checked in `VersionUtil`, preventing the use of a different version that the one scio has been built with.

We need to run scio on Beam 0.29+ (not released to this date) to leverage apache/beam#14349 which is critical for us, outweighing the risk.

TBC: it seems this check is not triggered during an execution on Dataflow, but it *is* while running tests.

The only solution to override this is either:
- have a patched `VersionUtil` in the source code, which is obviously bad
- rebuild scio with this version, which may become cumbersome for such a little change, especially if it requires then to publish the artifacts to a repo

Both ways makes it delicate to upgrade scio (e.g. 0.10.0 to 0.10.1).

What do you think of a way to disengage/alter the runner version safety? It may be a parameter like `--scioUnsafeAllowRunnerVersion=0.29-SNAPSHOT` or even an env var.

**Comment by nevillelyh** [comment]
It fails this assertion right? https://github.com/spotify/scio/blob/2a297c055cd5d351441748f787345ddd3b34318d/scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala#L140

We can probably make it a warning? Runners have been fairly stable and we have other ways to manage versions internally so it's probably fine to loosen it up a bit.

**Comment by turb** [comment]
> It fails this assertion right?
> 
> https://github.com/spotify/scio/blob/2a297c055cd5d351441748f787345ddd3b34318d/scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala#L140

Yes.

> 
> We can probably make it a warning? Runners have been fairly stable and we have other ways to manage versions internally so it's probably fine to loosen it up a bit.

It would be perfect.
