### ISSUE TITLE
Access underlying BigQueryStorage API Avro to write out as parquet

### ISSUE THREAD

**Issue by jamesthompson** [spotify/scio#3747]
Is there currently a way to access the Avro data streamed from the BigQueryStorage API as either GenericRecord or SpecificRecord? 

I'm trying to figure out a way to take a BigQuery table unknown at compile time, and stream from that table using the storage API then to serialize it as a parquet file. 

Currently I can only find a way to access an `SCollection[TableRow]` from the `bigQueryStorage` method in the library. 

So far I've been trying to find a way to use the `TableFieldSchema` from the BigQueryStorage client directly with something like `BigQueryAvroUtilsWrapper.toGenericAvroSchema(tableId, tableFieldSchemaList)`, but I'm stuck going from `TableRow -> GenericRecord / SpecificRecord`.

I know I can probably just traverse a `TableRow` using the `Schema` from the BigQuery client myself, but I'm hoping this is already a solved problem.

Any help you can provide would be greatly appreciated.  Thanks again for this fantastic library.

**Comment by nevillelyh** [comment]
Thanks for the kind words! You'll have to use a custom input and drop down to the Java API like this:

```scala
sc.customInput("Read", beam.BigQueryIO
        .read(new SerializableFunction[SchemaAndRecord, GenericRecord] {
          override def apply(input: SchemaAndRecord): GenericRecord = input.getRecord
        })
        .from("table")
        .withSelectedFields(List("a", "b").asJava)
        .withRowRestriction("WHERE ..."))
```

That'll give you an `SCollection[GenericRecord]`. Although to write `GenericRecord` as Parquet you'll need its schema when calling `saveAsAvroParquet` which isn't available until inside that `SerializableFunction`. So you'll have to get the schema separately with something like this:

```scala
val bigquery: BigQuery = com.spotify.scio.bigquery.client.BigQuery.defaultInstance()
val avroSchema = bigquery.tables.storageReadSchema(tableSpec, selectedFields, rowRestriction)
```
