### ISSUE TITLE
TypeSafe BigQuery causes IOException inserting LocalDateTime

### ISSUE THREAD

**Issue by idreeskhan** [spotify/scio#376]
I'm using the TypeSafe BigQuery API but encountering issues with a field using `LocalDateTime`. When it tries to insert into the table, it throws the following exception:
```
Exception: java.lang.RuntimeException: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"generic::out_of_range: Mismatch between format character 'T' and string character ' '","location":"timestamp","message":"Mismatch between format character 'T' and string character ' '","reason":"invalid"}],"index":0}]
com.google.cloud.dataflow.sdk.io.BigQueryIO$StreamingWriteFn.flushRows(BigQueryIO.java:2510)
com.google.cloud.dataflow.sdk.io.BigQueryIO$StreamingWriteFn.finishBundle(BigQueryIO.java:2466)
com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.finishBundle(DoFnRunnerBase.java:159)
com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.finishBundle(SimpleParDoFn.java:196)
com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.finishBundle(ForwardingParDoFn.java:47)
com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.finish(ParDoOperation.java:65)
com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:80)
com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:710)
com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.access$500(StreamingDataflowWorker.java:99)
com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:535)
```

### Reproducing

I am reading from a Pub/Sub subscription and parsing the messages into instances of `MyClass` and then attempting to save it into BigQuery.

**Case Class Example**
```
  @BigQueryType.toTable
  case class MyClass(timeField: LocalDateTime)
```

**Relevant Code Example**
``` 
  val dateFormat = "yyyy-MM-dd HH:mm:ss.SSSSSS"
  val formatter = DateTimeFormat.forPattern(dateFormat)

  val sc = ScioContext(seidrOpts)

  sc.pubsubSubscription("my-subscription").map(
    m =>
      MyClass(formatter.parseLocalDateTime(m))
  ).saveAsTypedBigQuery("my_table")
```

I quickly put together the above code as an example of what I'm trying to do, but it should replicate the problem.

### Alternative to Reproduce
A possible faster method to test is to pre-create a table in BigQuery that has a column with a `DATETIME` type, and a conflicting case class that has the same field with a String type. Attempting to use the TypeSafe API to save a string of format `yyyy-MM-dd HH:mm:ss.SSSSSS` or `yyyy-MM-dd HH:mm:ss` will fail with the same exception. But a format of `yyyy-MM-dd'T'HH:mm:ss.SSSSSS` or `yyyy-MM-dd'T'HH:mm:ss` will get properly transformed into a `DATETIME` in BigQuery. I've tested this myself and manage to reproduce the same results even though it is a bit hacky.

### Fixing
I believe that all that needs to be fixed is the format in [bigquery/package.scala](https://github.com/spotify/scio/blob/ec8c42d4b552e6583a64fc43bdf6aebddd23204c/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala#L141), but I'm not sure. A similar problem also exists for the `TIMESTAMP` type or `Instant`

If I'm doing something wrong, please feel free to tell me. I can possibly take a look at fixing if needed.

**Comment by nevillelyh** [comment]
Did you annotate `MyClass` with `@BigQueryType.toTable`?

**Comment by idreeskhan** [comment]
Yes, sorry I accidentally removed that when editing the formatting for the issue. Will re-add

**Comment by nevillelyh** [comment]
I can confirm the same error when writing rows into BQ.

Conversion works fine.
```scala
@BigQueryType.toTable
case class MyRecord(time: LocalDateTime)

val r = MyRecord(LocalDateTime.now())
val bqt = BigQueryType[MyRecord]
println(bqt.toTableRow(r))
println(bqt.schema)
```

And I get the following `TableRow` and schema, which seems to conform to the `YYYY-[M]M-[D]D[ [H]H:[M]M:[S]S[.DDDDDD]]` specification in https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types.
```
{time=2016-12-21 14:17:21.061000}
{fields=[{mode=REQUIRED, name=time, type=DATETIME}]}
```

Can you raise it to the BigQuery guys, via stackoverflow?

**Comment by idreeskhan** [comment]
Yea I can try to do that. As far as I could tell, the spec format listed there seems to match what's allowed in Standard SQL, but not this.

**Comment by nevillelyh** [comment]
Thanks. Also the conversion code is [here](https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala#L141) if you wanna toy with it.

**Comment by idreeskhan** [comment]
See #377
