### ISSUE TITLE
Writing to Datastore only supports an average entity size of < 20KB

### ISSUE THREAD

**Issue by harveyxia** [spotify/scio#378]
This is an issue on Google's Dataflow API, follow the issue [here](https://issues.apache.org/jira/browse/BEAM-991).

**Comment by nevillelyh** [comment]
Seems fixed in Beam 2.1.0 which we are already on. Closing for now.
https://issues.apache.org/jira/browse/BEAM-991
https://github.com/apache/beam/pull/3302
