### ISSUE TITLE
Any plans to support beam schema?

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#3785]
Beam schema / row allows for some pretty neat constructs. For example

```
 PCollection<KV<Row, Row>> aggregated = purchases
      .apply(Group.byFieldNames("userId', "country")
          .aggregateField("cost", Sum.ofLongs(), "total_cost")
          .aggregateField("cost", Top.<Long>largestLongsFn(10), "top_purchases")
          .aggregateField("cost", ApproximateQuantilesCombineFn.create(21),
            Field.of("transactionDurations", FieldType.array(FieldType.INT64)));
```

We can define an aggregation that groups on any set of fields in the row and compute multiple aggregations in 1 step.  I looked but couldn't find an equivalent in scio. Assuming I'm not mistaken Is there some plan to support beam Schemas and beam Rows? 

Maybe it could start with some helper utilities, given we already have type class driven encoder / decoders. We could auto generate the schemas from a Scala class. Additionally we could auto generate a toRow and fromRow function given a scio coder.

Thoughts?

**Comment by nevillelyh** [comment]
Not really. We have some macro based support for deriving `Row`/`Schema` but they won't work with Scala 3. Plus we don't use Beam SQL internally. So the plan is to remove them gradually (#3695).

For types already supported by Beam e.g. Avro,you can just drop down to Java SDK?
