### ISSUE TITLE
Update to avro 1.8.1

### ISSUE THREAD

**Issue by Khrol** [spotify/scio#385]
Avro 1.8.1 was released quite some time ago.
Is it possible to update to it?
https://github.com/spotify/scio/blob/master/build.sbt#L29

**Comment by nevillelyh** [comment]
We could but historically Avro version compatibility has been an issue and [upstream](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/pom.xml#L71) is still using 1.7.7. Is there some particular feature from 1.8.1 you want?

You can also do a `dependencyOverrides` in your project SBT.

**Comment by Khrol** [comment]
> Is there some particular feature from 1.8.1 you want?

We are trying to migrate to out-of-the-box logical datetime types introduced in 1.8.1.

Thank you for `dependencyOverrides` advice. We'll check this option.

**Comment by nevillelyh** [comment]
Cool I'm gonna close this for now. Feel free to reopen if you run into any problem.

**Comment by SamSchlegel** [comment]
Should this be reconsidered for 0.3.x now that apache/beam depends on 1.8.1? https://github.com/apache/beam/blob/master/pom.xml#L106

**Comment by SamSchlegel** [comment]
This may be a blocker: https://github.com/sbt/sbt-avro/pull/29

**Comment by nevillelyh** [comment]
That doesn't block us from upgrading dependency. Users will have to wait till they can compile schemas into 1.8.1 classes. @SamSchlegel Would you mind submitting a PR?

**Comment by nevillelyh** [comment]
Fixed in #510
