### ISSUE TITLE
ContextAndArgs.typed doesn't support comma separated list options

### ISSUE THREAD

**Issue by redbaron** [spotify/scio#3864]
Some command line arguments should be parsed into a list.  From https://beam.apache.org/releases/javadoc/2.4.0/org/apache/beam/sdk/options/PipelineOptionsFactory.Builder.html:

>   --x=1 --x=2 --x=3 (list style simple property, will set the "x" property to [1, 2, 3])
>   --x=1,2,3 (shorthand list style simple property, will set the "x" property to [1, 2, 3])

Scio support former, but not latter, it seems to parse values as a single string with commas in it

```
import com.spotify.scio.ContextAndArgs
final case class Args(lst: List[String])
val (sc, args) = ContextAndArgs.typed[Args](Array("--lst=a,b,c"))

scala> args.lst
val res0: List[String] = List(a,b,c)

scala> args.lst.length
val res1: Int = 1
```

Untyped parser parses it as a list correctly though:

```
> val (sc, args) = ContextAndArgs(Array("--lst=a,b,c"))
val sc: com.spotify.scio.ScioContext = com.spotify.scio.ScioContext@8876fb08
val args: com.spotify.scio.Args = Args(--lst=[a, b, c])

scala> args.list("lst")
val res2: List[String] = List(a, b, c)

scala> args.list("lst").length
val res3: Int = 3
```

Because of this problem, it is not possible to run such scio jobs as dataflow flex template. On the API level parameters are passed as a map (https://cloud.google.com/dataflow/docs/reference/rest/v1b3/LaunchTemplateParameters):

```
    "launch_parameter": {
      "jobName": "streaming-beam-sql-'$(date +%Y%m%d-%H%M%S)'",
      "parameters": {
        "inputSubscription": "'$SUBSCRIPTION'",
        "outputTable": "'$PROJECT:$DATASET.$TABLE'"
      },
      "containerSpecGcsPath": "'$TEMPLATE_PATH'"
    }
  }'
```

Therefore passing multiple arguments with the same name wont work. Indeed gcloud CLI checks for it:

```
$ gcloud dataflow flex-template run myjob --parameters lst=a --parameters lst=b
ERROR: (gcloud.dataflow.flex-template.run) argument --parameters: "lst" cannot be specified multiple times; received: a, b
```

**Comment by kellen** [comment]
`ContextAndArgs.typed` now removed
