### ISSUE TITLE
Methods that Compiled in 0.9.x Generate a MethodTooLargeError in 0.10.x

### ISSUE THREAD

**Issue by stfines-clgx** [spotify/scio#3885]
The macros which generate code for 0.10.x are generating v. large methods for implementations which only have a few lines at best; 

We've discussed this error before in Slack; it seems to occur with very large case classes.

**Comment by sfines-clgx** [comment]
Here is an example method which raises the error. 

`
class BundlerWorker extends DataflowJobExecutionTask {
  implicit val ec = scala.concurrent.ExecutionContext.global
  override def runTask(work: WorkUnit)(args: Array[String]): Option[WorkResponse] = {
    implicit val runContext = RunContext(
      fips = work.fips.head,
      geocell = "",
      runDate = work.extraConfig.runDate.get,
      runMode = work.execution.runMode.description,
      runGroupId = work.runGroupId,
      runId = work.runId
    )
    val pipelineOptions = makePipelineOptions(work.fips.head, work.overRideArrayArgs(args))
    val job = new BundlerJob(config)
    val result = job.runBundler(pipelineOptions)
    result.map(WorkUnitResult.from(work, _))
  }
}
`

**Comment by kellen** [comment]
See solution in #4066
