### ISSUE TITLE
Skew join `hotKeyThreshold` should scale with `sampleFraction`?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#394]
Right now in `skewedJoin` `hotKeyThreshold` is used as is to check key frequency but frequencies in the `CMS` may scale if a smaller `sampleFraction` is used. Should we scale `hotKeyThreshold` proportionally also or at least document it? @ravwojdyla?

**Comment by ravwojdyla** [comment]
👍 to documentation.
