### ISSUE TITLE
How to Implement Custom Sinks

### ISSUE THREAD

**Issue by sfines** [spotify/scio#399]
Scio-ers, 
I know how to implement Sinks in DataFlow, but how are such implemented inside of SCIO? 

SF

**Comment by nevillelyh** [comment]
Take a look at:
https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-dataflow-java-sdk-api-in-scio

and
https://github.com/spotify/scio/pull/384

**Comment by nevillelyh** [comment]
@sfines gonna close this for now. Feel free to re-open if you run into problems.
