### ISSUE TITLE
Cannot run scio-repl from SBT

### ISSUE THREAD

**Issue by joelostlund** [spotify/scio#400]
When I do the following:

```
➜  scio git:(master) sbt run
[info] Loading global plugins from /Users/joel/.sbt/0.13/plugins
[info] Loading project definition from /Users/joel/code/scio/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to scio (in build file:/Users/joel/code/scio/)
[success] Total time: 0 s, completed Jan 18, 2017 1:52:54 PM
```
It does not start the SCIO repl anymore as described in https://github.com/spotify/scio/wiki/Scio-REPL#start-from-sbt-console-scala-211x-only

I suspect this to be a bug. Could you please help out?

**Comment by nevillelyh** [comment]
`scio-repl/runMain com.spotify.scio.repl.ScioShell` works for me. Should we fix either `build.sbt` or the doc?

**Comment by ravwojdyla** [comment]
If I add:

```
  mainClass in Compile := (mainClass in scioRepl in Compile).value,
  fullClasspath in Compile ++= (fullClasspath in scioRepl in Compile).value,
```

it runs fine, need to double check if this is safe tho.

**Comment by nevillelyh** [comment]
IMO maybe better documenting it and leave `build.sbt` alone. REPL is probably not the first thing that comes mind when people do `sbt run`. A bit counter intuitive.

**Comment by ravwojdyla** [comment]
Users will have to look at the documentation regardless of the solution, #403 fixed this issue, so maybe for now let's keep it the way it was.
