### ISSUE TITLE
 Methods that Compiled in 0.10.x Generate a MethodTooLargeError in 0.11.0

### ISSUE THREAD

**Issue by jvexiau** [spotify/scio#4005]
Hi,  

It s may be a duplicate of issue #3885

but for me it s from 0.10.4 to 0.11.0 ,

A lot of methods launch this exception. 

Is there a workaround ? 

thanks 

an example of a small method : 

```scala 
def mergeFields(accounts: SCollection[Account]): SCollection[(MergedAccount)] = 
  accounts.withName("Merge Fields").map(a => MergedAccount(a))
```

Account is a huge case class

**Comment by kellen** [comment]
The solution to `MethodTooLargeError` in general is to use `Coder.gen` outside the pipeline method so that generated coder code is not unnecessarily bloating that method.
