### ISSUE TITLE
Give XGBoost another shot

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#401]
We ran into problem with docker last time when running in Dataflow since dockerized workers can't communicate with parameter server.

We can try running parameter server in `main` this time. This might circumvent the networking if `main` runs in a GCP VM.

**Comment by richwhitjr** [comment]
Starting to experiment with this now.  I am launching the Rabit instance in the main and passing the configuration to the workers. DirectRunner works but still having network issues with the workers connecting back to the GCP parameters server.

**Comment by richwhitjr** [comment]
This is working on a local branch.  The main issue though is that XGBoost does not publish jars.  What is the best way to put a dependency on it?  Travis etc will fail on not finding the dependencies and it can be a surprising experience for users.  

Maybe the best option is to create a new subproject named scio-boost and find a way to disable the build in CI.  We can explain how to build the package in the README section of that sub project.

**Comment by nevillelyh** [comment]
Housekeeping: I'm leaning towards closing this. We should recommend vanilla XGBoost on single machine training, and in the near future `scio-zoltar` for distributed prediction. Any objections?

**Comment by richwhitjr** [comment]
Sounds good.  We get most of this for free when we integrate zoltar. Vanilla XGboost also works in Scio if you are careful with packaging and jni initialization.
