### ISSUE TITLE
Scio pipelines should be executable with a classpath referencing a local repository

### ISSUE THREAD

**Issue by flylo** [spotify/scio#4016]
My team has upgraded from scio 9.3 to scio 10.4 and now we are unable to execute pipelines straight from intellij because our entire `~/.m2` cache is being filtered out in local execution. In the intellij runtime, most classpath jars are in `user.home`. When we try to run pipelines straight from IJ, we get `NoClassDefFoundError` because the entire classpath is filtered out of `PipelineOptions.filesToStage`.

Example exception in a dataflow job:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/beam/sdk/options/PipelineOptions
```

Relevant logs in the pipeline launch process:
```
{"timestamp":"2021-09-21T20:25:51.510Z","level":"INFO","thread":"main","logger":"org.apache.beam.runners.dataflow.util.PackageUtil","message":"Uploading 4 files from PipelineOptions.filesToStage to staging location to prepare for execution.","context":"default"}
```

^ As you can see, only 4 files are uploaded (our classpath should contain ~200 dependencies)

We've tracked this down to the difference in behavior between 9.3 and 10.4. This is the functionality in 9.3
https://github.com/spotify/scio/blob/v0.9.3/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L141

```
CoreSysProps.UserDir.value
> /Users/zacp/path/to/repo/root
```

And this is in 10.4
https://github.com/spotify/scio/blob/main/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L150

```
sys.props("user.home")
> /Users/zacp
```

So, anything in my `~` directory is not being staged. This includes the entirety of `~/.m2` and `~/.ivy`. We're manually setting our `filesToStage` for now, but it seems like this is possibly undesired default behavior.

**Comment by sfines-clgx** [comment]
I can concur that this is also happening to me

**Comment by sfines-clgx** [comment]
@flylo In the interrim, I copied the following into my pipeline and stripped out the offending logic:
`
  // THESE WORK AROUND SCIO #4016 which filters out local resources
  def filesToStage(
      pipelineOptions: PipelineOptions,
      classLoader: ClassLoader,
      localArtifacts: Iterable[String],
      extraLocalArtifacts: Iterable[String]
  ): Iterable[String] = {
    val artifacts = if (localArtifacts.isEmpty) {
      detectClassPathResourcesToStage(pipelineOptions, classLoader)
    } else {
      localArtifacts
    }

    val finalLocalArtifacts = artifacts ++ extraLocalArtifacts
      .iterator
      .map {
        case path if path.endsWith(".jar") =>
          path.substring(path.lastIndexOf("/") + 1, path.length) -> path
        case path =>
          path -> path
      }
      .toMap
      .values

    logger.debug(s"Final list of extra artifacts: ${finalLocalArtifacts.mkString(":")}")
    finalLocalArtifacts
  }

  /**
   * Borrowed from DataflowRunner.
   */
  private[this] def detectClassPathResourcesToStage(
      pipelineOptions: PipelineOptions,
      classLoader: ClassLoader
  ): Iterable[String] = {
    val sanitize: String => String = _.replace("\\", "/")

    val classPathJars = PipelineResources
      .detectClassPathResourcesToStage(classLoader, pipelineOptions)
      .asScala

    logger.debug(s"Classpath jars: ${classPathJars.mkString(":")}")

    classPathJars
  }

// In the main pipeline do:
val sc = ScioContext.apply(
      options,
      filesToStage(
        options,
        this.getClass.getClassLoader,
        Iterable
          .empty[String],
        Iterable.empty[String]
      ).toList
    )
`
