### ISSUE TITLE
Extend BigQueryType auto generated case classes 

### ISSUE THREAD

**Issue by martinbomio** [spotify/scio#407]
Would be nice to be able to extend the `@BigQueryType.formQuery` and even `@BigQueryType.toTable` auto generated classes with a trait to be able to abstract some common properties from them.
Example:
```scala
  sealed trait WithUserId {
    def user_id: String
  }

  @BigQueryType.fromQuery(
    """
      |SELECT
      |  user_id,
      |  ...,
      |FROM
      |  `some_project.some_dataset.some_table`
    """.stripMargin) class SomeWithUserId extends WithUserId

  @BigQueryType.fromQuery(
    """
      |SELECT
      |  user_id,
      |  ...,
      |FROM
      |  `some_project.some_other_dataset.some_other_table`
    """.stripMargin) class SomeOtherWithUserId extends WithUserId
```

This way we can abstract some common logic. Example:

```scala
def groupByUserId[T <: WithUserId](x: SCollection[T]): SCollection[(String, T)] = {
  x.groupBy(_.user_id)
}
```

**Comment by ravwojdyla** [comment]
Right now this fails immediately because of the quasiquotes we use to accept annotations, we should be able to adjust those to accept extra traits. This might be doable +/- some dragons I'm not aware of.
What do you think @nevillelyh ?

**Comment by nevillelyh** [comment]
The problem with this is we have no control over what's in the `WithUserId` trait and it might interfere with the macro in unexpected ways that are hard to debug.

I prefer a simpler approach, i.e. implicit conversion of each generated class to `WithUserId`. For example:
```scala
implicit def someToWithUserId(x: SomeWithUserId): WithUserId = new WithUserId {
  def user_id: String = x.user_id
}
```

It's not too much more code but easier to understand and reason about.

**Comment by martinbomio** [comment]
@nevillelyh that would work but the drawback is that we lose the reference to other attributes of `SomeWithUserId`

**Comment by nevillelyh** [comment]
@martinbomio can you give an example use case?

A function like `def compute(x: WithUserId) = ...` still only gives you access to `user_id` and implicit conversion works in that case.

**Comment by martinbomio** [comment]
@nevillelyh Suggestion works. Here's an example: 
```scala
trait WIthUserId[T] {
  def userId(x: T): String
}

implicit val someToWithUserId = new WithUserId[SomeWithUserId] {
  def userId(x: SomeWithUserId): String = x.user_id
}
```
and then it can be used with context bounds like this:

```scala
def groupByUserId[T : WithUserId](x: SCollection[T]): SCollection[(String, T)] = {
  x.groupBy(x => implicitly[WithUserId[T]].userId(x))
}
```

**Comment by ravwojdyla** [comment]
@martinbomio or you can:

```
sealed trait WithUserId {
  def user_id: String
}

implicit def someToWithUserId(x: SomeWithUserId): WithUserId = new WithUserId {
  def user_id: String = x.user_id
}

def groupByUserId[T <% WithUserId](x: SCollection[T]): SCollection[(String, Iterable[T])] = {
 x.groupBy(_.user_id)
}
```

Can this issue be closed?

**Comment by nevillelyh** [comment]
+1 view bound should be the cleanest solution here

**Comment by martinbomio** [comment]
Yes, we can close it. Thanks for the quick feedback!
