### ISSUE TITLE
Nulls from closure

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#41]
We use chill's `ClosureCleaner` to clean up lambdas for serialization. There are some edge cases where `val`s from a closure end up being null.

**Comment by ravwojdyla** [comment]
@nevillelyh do you have examples?

**Comment by nevillelyh** [comment]
See https://github.com/spotify/scio/commit/3a3552ab664c3d690ac78db335c02ad286867196
The last 2 fails. `ClosureCleaner` is probably too eager when nulling out references.

**Comment by nevillelyh** [comment]
2 things we can try:
- Change `ClosureCleaner` to be less aggressive in nulling out fields and compare chill's version with Spark's version.
- Try serializing `f` (the pre-clean lambda) first and skip cleaning if it serializes successfully.

**Comment by nevillelyh** [comment]
The following change fixes "lambda with object member from closure" but not the last one "lambda with class member from closure"
```
diff --git a/scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala b/scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
index 0f67839..bc34939 100644
--- a/scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
+++ b/scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
@@ -17,9 +17,16 @@

 package com.spotify.scio.util

+import com.google.cloud.dataflow.sdk.util.SerializableUtils
+
 private[scio] object ClosureCleaner {
   def apply[T <: AnyRef](obj: T): T = {
-    com.twitter.chill.ClosureCleaner(obj)
+    try {
+      SerializableUtils.serializeToByteArray(obj.asInstanceOf[Serializable])
+    } catch {
+      case _: IllegalArgumentException => com.twitter.chill.ClosureCleaner(obj)
+    }
     obj
   }
 }
```

**Comment by nevillelyh** [comment]
https://github.com/spotify/scio/commit/ca1308a67b9da65dd78685a8005cc4cfaf59648f addressed some cases. Closing for now.
