### ISSUE TITLE
scio-bigquery support for 0.10.4 or 0.11.0

### ISSUE THREAD

**Issue by sgireddy** [spotify/scio#4115]
Hi Scio team,

I ran into BEAM issue https://issues.apache.org/jira/browse/BEAM-9399 which was fixed in beam version 2.25 but looks like scio-beam only available in scio 9.6 which uses beam 2.24. Is there a place where I could obtain the latest (0.10x or 0.11.x) version of scio-beam? Is there a reason why scio-beam was not updated to the latest version?

unresolved dependency: com.spotify#scio-bigquery_2.12;0.10.4: not found

**Comment by kellen** [comment]
Hi @sgireddy the scio-bigquery packages were moved as part of `0.10`.

See the migration guide here: https://spotify.github.io/scio/migrations/v0.10.0-Migration-Guide.html#google-cloud-platform-modules
