### ISSUE TITLE
Metrics are saved asynchronously

### ISSUE THREAD

**Issue by kanterov** [spotify/scio#414]
When `--metricsLocation` argument is given, scio automatically saves file with metrics. According to the current implementation, under certain conditions it's possible that metrics would be saved asynchronously, there are two issues with that:

1. Job doesn't crash or log exception if we failed to save metrics
2. It's not guaranteed to save metrics before JVM exit

The workaround is to call `saveMetrics` synchronously after the job is finished.

**Comment by nevillelyh** [comment]
We need to think about this and other in-flight future after `sc.close()` in Scio 0.3.x.
Beam 0.4.0 removed `BlockingDataflowRunner` so everything is async now and the user has to call `sc.close().waitUntilFinish()`. We can either require that or prevent JVM from existing when there're pending futures.

**Comment by ravwojdyla** [comment]
This is now solved with `waitUntilFinish` correct, it will wait till `finalState` is done, and `saveMetrics` is part of that future.

**Comment by kanterov** [comment]
@ravwojdyla can you point to the code or commit that changed this?

**Comment by ravwojdyla** [comment]
@kanterov check e3a652a1

**Comment by kanterov** [comment]
@ravwojdyla looks good, just one note that it isn't in master yet, but would be merged with apache-beam migration.
