### ISSUE TITLE
SMB String key decoding issue with GenericRecords 

### ISSUE THREAD

**Issue by clairemcginty** [spotify/scio#4186]
Unless `"avro.java.string": "String"` property is set, String fields in GenericRecords will get decoded as avro Utf8 objects. This causes `org.apache.avro.util.Utf8`->`java.lang.String` casting issues when the field is used as an SMB key field, because of the way AvroBuckeMetadata tries to [cast the field value from a java `Object` type to key type `K`](https://github.com/spotify/scio/blob/be7166c58450bd59ae5d0048d39ef3ea0d5ed107/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java#L112). This isn't a new issue, and it wasn't impacted by the recent [Beam Avro issue](https://issues.apache.org/jira/browse/BEAM-12628), which only affected SpecificRecords.

example - you can reproduce by removing the schema property & re-running the test.
https://github.com/spotify/scio/blob/8b28f44f3eecb5edb7f859289aca28e79732f431/scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala#L42-L58

IMO, although this issue is fixable on the user side (either by adding the avro schema property, or by setting the `keyClass` SMB field to `CharSequence` rather than `String`) it would be best for users if we can fix it on our side.

**Comment by RustedBones** [comment]
Fixed by #5152 and #5181
