### ISSUE TITLE
Garbled SBT console output after test

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#419]
This happens sometimes after running `test` in SBT console. No prompt and no keystroke feedback.
Possibly messed up stdout/stderr.

**Comment by ravwojdyla** [comment]
FYI could reproduce this problem without `debug` tests which were one of the suspects.

**Comment by nevillelyh** [comment]
Haven't seen this in a while. Probably fixed with the `sbt-pgp` downgrade. Closing for now.
