### ISSUE TITLE
Consider reload4j as a replacement of log4j 1.2

### ISSUE THREAD

**Issue by labianchin** [spotify/scio#4212]
Scio [points to log4j 1.2.7](https://github.com/spotify/scio/blob/e5040254ee5e29d3c58e34937074b90a88a29e8b/build.sbt#L1323). I guess it is used in a few modules, including `scio-parquet` (apparently as a transitive dependency of `hadoop`.

Note now there is [reload4j](https://reload4j.qos.ch/) which "aims to fix the most urgent issues in log4j 1.2.17".

Given that, scio/scio-parquet could exclude log4j 1.x dependencies, replacing with reload4j. Should it?

**Comment by RustedBones** [comment]
Fixed. Now scio uses `log4j-over-slf4j` and does not depend on `log4j` anymore. Users can chose the slf4j logger implementation
