### ISSUE TITLE
Scio core is missing dependency

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#4226]
Registrar class in core uses `TableRowJsonCoder` which is in `beam-sdks-java-io-google-cloud-platform`
https://github.com/spotify/scio/blob/v0.11.1/scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala#L101

however, pom does not declare this dependency:
https://repo1.maven.org/maven2/com/spotify/scio-core_2.12/0.11.1/scio-core_2.12-0.11.1.pom

In such case, user get class not found exception in runtime, unless it pulls dependency from other source, like `scio-avro`

**Comment by RustedBones** [comment]
The dependency is not explicitly specified but is pulled transitively
```
sbt:scio> scio-core/whatDependsOn org.apache.beam beam-sdks-java-io-google-cloud-platform
[info] org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.38.0
[info]   +-org.apache.beam:beam-sdks-java-extensions-sql:2.38.0
[info]     +-com.spotify:scio-macros_2.13:0.11.7+20-70b1a507-SNAPSHOT [S]
[info]       +-com.spotify:scio-core_2.13:0.11.7+20-70b1a507-SNAPSHOT [S]
[info] 
```
users won't face a class not found (also, code in scio-core wouldn't compile)
