### ISSUE TITLE
DoFn Lifecycle method mapping?

### ISSUE THREAD

**Issue by jonopwell** [spotify/scio#425]
Is there a way to map the Java lifecycle methods into scio such as

    @DoFnWithContext.StartBundle
    @DoFnWithContext.FinishBundle
    @DoFnWithContext.ProcessElement

We need to map a connection pool scheme for Google Cloud SQL.

Thanks,

Jon

P.S. We love the library!

**Comment by nevillelyh** [comment]
There isn't an easy way since scala functions are pure.
It's probably better to just write a DoFn and call `scoll.apply(...)`.

P.S. thanks! Would be great if you can add something to https://github.com/spotify/scio/wiki/Powered-By

**Comment by ravwojdyla** [comment]
@jonopwell does it ^ answer the question - can this issue be closed?

**Comment by jonopwell** [comment]
Sure...can be closed.
