### ISSUE TITLE
Staging(scio_bigquery_staging_) tables are created with 90 day expiration 

### ISSUE THREAD

**Issue by mbarths** [spotify/scio#4285]
It looks like staging tables should expire after a day according to [here](https://github.com/spotify/scio/blob/73d731d99bef38d1eefcfd5c89e3a44648550ec4/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala#L294). But `scio_bigquery_staging_` have a 90 day retention. Is there something that I am missing?

**Comment by clairemcginty** [comment]
Looking at the BQ tables from our integration tests, it looks like the _dataset_ is being correctly created with a default 1 day expiration, but the individual _tables_ are overridden with a 90 day expiration. We should look into how we're setting table expiration
