### ISSUE TITLE
Support BigQuery Load jobs for batch loading

### ISSUE THREAD

**Issue by RustedBones** [spotify/scio#4334]
From beam [documentation](https://beam.apache.org/documentation/io/built-in/google-bigquery/#setting-the-insertion-method) 

> When you specify load jobs as the insertion method using BigQueryIO.write().withMethod(FILE_LOADS).

Scio should also give users the possibility to use files to load data to BigQuery

**Comment by brucearctor** [comment]
@RustedBones -- not sure I understand your issue here.  

Is there something you are trying to do that you are not able to ( asking about functionality, not specific syntax/methods ).

**Comment by brucearctor** [comment]
Ah, based on your other issue ( https://github.com/spotify/scio/issues/4333 ), it looks like you're thinking Scio would benefit from the additional BeamIO.Write Methods --> https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.Write.Method.html ?

**Comment by RustedBones** [comment]
That's correct. At the moment those are not exposed in the Scio API.
Both tickets have been opened after user's request, feel free to assign yourself if you want to work on them.
