### ISSUE TITLE
Google DataFlow/Beam 2.0 Support Timeline

### ISSUE THREAD

**Issue by jonopwell** [spotify/scio#435]
By now, you have probably already seen the DataFlow SDK 2.0 [announcement](https://cloud.google.com/dataflow/release-notes/release-notes-java-2).

We are wondering about your support timeline.

**Comment by ravwojdyla** [comment]
We plan to transition to Apache Beam as the underlying dependency (as of version `0.3.0`). You can already give it a try via [alpha release](https://github.com/spotify/scio/releases/tag/v0.3.0-alpha1). Your feedback would be appreciated. Does it answer your question?

**Comment by jonopwell** [comment]
Awesome...thanks Rafal!

On Feb 1, 2017 3:01 PM, "Rafal Wojdyla" <notifications@github.com> wrote:

We plan to transition to Apache Beam as the underlying dependency (as of
version 0.3.0). You can already give it a try via alpha release
<https://github.com/spotify/scio/releases/tag/v0.3.0-alpha1>. Your feedback
would be appreciated. Does it answer your question?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spotify/scio/issues/435#issuecomment-276811314>, or mute
the thread
