### ISSUE TITLE
Make the temporary table prefix and target dataset configurable in the MockBigQuery class

### ISSUE THREAD

**Issue by azaroui** [spotify/scio#4385]
Actually temporary table prefix and staging dataset are defined in TableOps. This prevents us from specifying them when calling the mockTable method in the MockBigQuery.
https://github.com/spotify/scio/blob/main/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala#L48
We need this because we don't necessarily have the authorizations to create datasets on the fly.

**Comment by farzad-sedghi** [comment]
https://github.com/spotify/scio/pull/4474

**Comment by clairemcginty** [comment]
@azaroui can you expand a little more on why you need temp table prefix to be configurable?

**Comment by azaroui** [comment]
@clairemcginty In our case, the devs do not have the authorization to create tables on the source dataset and we have created a dedicated dataset for tests purpose to which all the devs have write authorization. So if I can't pass the dataset as a parameter the test will fail with unauthorized error.
