### ISSUE TITLE
Reduce coder memory footprint

### ISSUE THREAD

**Issue by RustedBones** [spotify/scio#4392]
Coders are responsible for a non negligible memory consumption at runtime.

When analysing heap-dump on a dataflow worker, we can see that coders are duplicated in every TaskExecutors.

Most of the memory allocated from the coders is for their [materializationStackTrace](https://github.com/spotify/scio/blob/3d149ea5076dc35b963d557457bf07360631e8cb/scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala#L252).

Since this one is shared by coder type, we should find a way to reduce the memory allocation by using an intern string representation for instance, instead of duplication the stack trace for every instance

**Comment by kellen** [comment]
Closed in #4397
