### ISSUE TITLE
Clean up various test runners

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#442]
We have tests in ScalaTest, ScalaCheck, and JUnit right now. Would be nice to consolidate and use ScalaTest only to avoid problems with multiple runners.

**Comment by nevillelyh** [comment]
WIP branch https://github.com/spotify/scio/tree/neville/scalacheck
Need to verify that ScalaTest runner with `PropSpec` behaves the same as ScalaCheck runner.

**Comment by andrewsmartin** [comment]
Waiting for a response on https://github.com/scalatest/scalatest/issues/1090, if they really want the default to be 10 then we will have to override it ourselves. Let's see what they say first.
