### ISSUE TITLE
Planed deprecation for v0.13.0

### ISSUE THREAD

**Issue by RustedBones** [spotify/scio#4459]
Cleanup planned deprecation for `v0.13.0` milestone

- [x] elasticsearch 6 module (end of life)
- [x] widen API from `SpecificRecordBase` class to `SpecificRecord` interface
- [x] remove `genAvro` coder
- [x] remove context from `SCollectionWithFanout` as done [here](https://github.com/spotify/scio/pull/4740/commits/3afb6095ba7728dcc7ee77acd4aa65b3672cccd2)

**Comment by shnapz** [comment]
we can also set `val DefaultSampleWithReplacement: Boolean = false` for skewedJoin

**Comment by jjengo** [comment]
Preparing for a 0.13 Scio release. Still need to plan on when we'll cut the release for OSS.
