### ISSUE TITLE
Improve PipelineTestUtils#runWithData

### ISSUE THREAD

**Issue by tkhduracell** [spotify/scio#447]
In tests it would be nice to have a `runWithData(..)` that take test data and a scio-context. 
Now you have to fetch the scio-context from one of the collections, since the `runWithLocalOutput` creates a new context that is not the `ScioContext.forTest()`. 

```scala
    runWithData(interactions, entries) { (int, ent) =>
      val scio: ScioContext = int.context
      Core.pipelineCore(scio, int, ent)
    }
    .toList
    .sortBy(_.getTimestamp)
```

**Comment by nevillelyh** [comment]
Any suggestion what the interface should look like? Would be great if you can submit a PR :)

**Comment by nevillelyh** [comment]
@tkhduracell any thoughts?

**Comment by nevillelyh** [comment]
Gonna close this one for now. Feel free to re-open if you have any updates.
