### ISSUE TITLE
Using App trait causes java.lang.NullPointerException with Side Inputs

### ISSUE THREAD

**Issue by idreeskhan** [spotify/scio#449]
Extending the `App` trait in Scala and running a job from there produces a NullPointerException when using Side Inputs (I specifically testing with SingletonSideInputs)
### Example
```
object PubSubIngester extends App {
  @transient lazy val logger = Logger(LoggerFactory.getLogger(this.getClass.getCanonicalName))

  val (seidrOpts, cmdlineArgs) = ScioContext.parseArguments[SeidrOptions](args)
  val utils = new SeidrUtils(seidrOpts)

  val sc = ScioContext(seidrOpts)

  val sideInput: SideInput[String] =
      sc.parallelize(Option(seidrOpts.getArg)).asSingletonSideInput

  sc.pubsubSubscription(seidrOpts.getSubscription, timestampLabel = "timestamp")
    .withSideInputs(sideInput)
    .map((message, sideInputContext) => (message, sideInputContext(sideInput)))
    .toSCollection
    .map{ case (messageStr, sideStr) => logger.info(s"Message $messageStr, Side $sideStr") }

  val result = sc.close()
}
```

Produces:
> Exception: java.lang.NullPointerException
com.spotify.scio.values.SideInputContext.apply(SideInput.scala:82)
com.bigvikinggames.seidr.etl.google.PubSubIngester$$anonfun$collections$1$1$$anonfun$apply$1.apply(PubSubIngester.scala:92)
com.bigvikinggames.seidr.etl.google.PubSubIngester$$anonfun$collections$1$1$$anonfun$apply$1.apply(PubSubIngester.scala:92)
com.spotify.scio.util.FunctionsWithSideInput$$anon$3.processElement(FunctionsWithSideInput.scala:56)

### Workaround
Moving to using `main` instead of extending `App` works perfectly fine:
```
object PubSubIngester {
  def main(args: Array[String]): Unit = {
    @transient lazy val logger = Logger(LoggerFactory.getLogger(this.getClass.getCanonicalName))

    val (seidrOpts, cmdlineArgs) = ScioContext.parseArguments[SeidrOptions](args)
    val utils = new SeidrUtils(seidrOpts)

    val sc = ScioContext(seidrOpts)

    val sideInput: SideInput[String] =
      sc.parallelize(Option(seidrOpts.getArg)).asSingletonSideInput

    sc.pubsubSubscription(seidrOpts.getSubscription, timestampLabel = "timestamp")
      .withSideInputs(sideInput)
      .map((message, sideInputContext) => (message, sideInputContext(sideInput)))
      .toSCollection
      .map{ case (messageStr, sideStr) => logger.info(s"Message $messageStr, Side $sideStr") }

    val result = sc.close()
  }
}
```

Reproduced locally and on Dataflow. Note added to the FAQ by @ravwojdyla here: https://github.com/spotify/scio/wiki/FAQ#scalaapp-trait-vs-main-method

**Comment by ravwojdyla** [comment]
Conversation: https://gitter.im/spotify/scio?at=58a3238c1465c46a5663a6fe

So i think we will:
- [ ] add warning
- [ ] document this better (https://github.com/spotify/scio/wiki/FAQ#scalaapp-trait-vs-main-method)
