### ISSUE TITLE
PubSubIO.WriteParam isn't inferred correctly in IntelliJ for subtypes

### ISSUE THREAD

**Issue by kellen** [spotify/scio#4512]
e.g. when using:

```scala
val scoll: SCollection[MyMessage] = ???
scoll.write(PubsubIO.proto[MyMessage](topic))(PubsubIO.WriteParam())
```

IntelliJ will infer `Nothing` as the type for the second argument to `write`. Not sure how/if this is possible to fix on our side.

**Comment by RustedBones** [comment]
@kellen Is it still happening ?

**Comment by kellen** [comment]
Appears resolved!
