### ISSUE TITLE
Improve coder testing

### ISSUE THREAD

**Issue by RustedBones** [spotify/scio#4548]
Provided coders should be better unit tested

**Comment by shnapz** [comment]
Clarification:
> this refers to [CoderTest.scala](https://github.com/spotify/scio/blob/main/scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala). We do a lot of testing to make sure that Coders can be serialized, and that the appropriate Coder is chosen (the coderShould notFallback assertion), BUT, what's missing is that we're not consistently testing that the coder actually works
