### ISSUE TITLE
Better streaming test support

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#458]
Something like these:
https://github.com/spotify/scio/blob/master/scio-examples/src/test/java/org/apache/beam/examples/complete/game/LeaderBoardTest.java

**Comment by kanterov** [comment]
Used this code snippet.

```scala
  def testStream[A](sc: ScioContext)(f: TestStream.Builder[A] => TestStream.Builder[A]): SCollection[A] = {
    val cls = implicitly[ClassTag[A]].runtimeClass.asInstanceOf[Class[A]]
    val builder = org.apache.beam.sdk.testing.TestStream.create(
      sc.pipeline.getCoderRegistry.getDefaultCoder(TypeDescriptor.of(cls))
    )

    sc.wrap(sc.pipeline.apply(f(builder).advanceWatermarkToInfinity()))
  }
```

**Comment by regadas** [comment]
@nevillelyh @ravwojdyla @fallonchen @andrewsmartin 

is something like this of interest?

```
scollection should inOnTimePane(window) {
  containInAnyOrder (Seq((blueOne.team, 12), (redOne.team, 4)))
}
```

**Comment by nevillelyh** [comment]
Ideally yes ;) but I'm a little conflicted, because not sure if we'll get 100% feature parity with the Beam API and ScalaTest style DSL is hard to write & maintain.

If there're only 2 forms of assertions like this:
- `PAssert.that(data).<verb>(expected)` (supported today)
- `PAssert.that(data).<timeCondition>(param).<verb>(expected)` (streaming)

Then maybe we can handle them like this:
- `data should <verb> (expected)` (supported today)
- `data should <timeCondition>(param) { <verb> (expected) }` (like you suggested)

Question is are there other possible way of expressing an assertion?

**Comment by regadas** [comment]
@nevillelyh sorry for the late reply

Right now the only forms of assertions I see are the ones you mentioned. I have PR almost ready with a proposal for this.
