### ISSUE TITLE
Support service account impersonation in BigQuery client

### ISSUE THREAD

**Issue by clairemcginty** [spotify/scio#4591]
Currently we support authentication to the BQ client (which is used for performing the BigQuery -> GCS export tasks that support non-storage BQ reads) using Application Default Credentials, as well as by a supplied secret file:

https://github.com/spotify/scio/blob/main/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala#L196-L213

Ideally we could also support [account impersonation](https://cloud.google.com/iam/docs/impersonating-service-accounts) via a new SBT option, something like `bigquery.actAs` that allows you to specify the name of a service account to impersonate?

Note: I haven't done much research on this, if it's possible with the existing options we should document it on the site.

**Comment by shnapz** [comment]
Apparently it requires a code change:
```
ImpersonatedCredentials.create(sourceCredentials, "target_SA_principal")
```
and a new `apply` overload there. Will dig into details more
