### ISSUE TITLE
Serialization issue with nested fuctions

### ISSUE THREAD

**Issue by ElPicador** [spotify/scio#461]
If I have a function inside a `map` is throws an `java.lang.IllegalArgumentException: unable to serialize com.spotify.scio.util.Functions$$anon$7@71b6d77f`

Is there a way to make this work?

I'm using scio 0.2.11 with scala 2.11.8 

Here is a small exemple:

```scala
def method[G](c: List[Char])(f: Char => G): List[G] = {
  c.map { a =>
    f(a)
  }
}

def main(cmdlineArgs: Array[String]): Unit = {
  val (sc, _) = ContextAndArgs(cmdlineArgs)

  sc
    .textFile("gs://foo/*", CompressionType.GZIP)
    .map { e =>
      method(e.toList) { a =>
        a.toString
      }
    }

  sc.close()
}
```

**Comment by andrewsmartin** [comment]
Hi @ElPicador, thanks for reporting. Would it be possible to include the full stacktrace?

**Comment by andrewsmartin** [comment]
@ElPicador I am unable to reproduce with this code snippet. Can you try `-Dsun.io.serialization.extendedDebugInfo=true`? This could give us some more information if the problem is with Java serialization.

**Comment by ElPicador** [comment]
I've created a gist, with the full file, and the resulting output: https://gist.github.com/ElPicador/6b596ab0d73a7935272b89aa3e31f234

**Comment by andrewsmartin** [comment]
@ElPicador I'm unable to reproduce this using a fresh project setup. For reference, this is my minimal build.sbt.

```
name := "scio-ser"

version := "1.0"

scalaVersion := "2.11.8"
scalacOptions := Seq("-target:jvm-1.8", "-deprecation", "-feature", "-unchecked")
javacOptions := Seq("-source", "1.8", "-target", "1.8")

libraryDependencies += "com.spotify" %% "scio-core" % "0.2.11"
```

I can't see how, but I wonder if it's possible that this has something to do with your project setup? Does this still fail for you in a clean project?

**Comment by ElPicador** [comment]
Ok, I manage to found the issue. We enabled the scalac option `-Ydelambdafy` and this option, that should speedup/reduce lambdas, seems not to be compatible with DF.

I'm closing it, as it's not scio related.

**Comment by andrewsmartin** [comment]
That's great to know! Glad you found the problem.
