### ISSUE TITLE
Visibility of classes & methods

### ISSUE THREAD

**Issue by ElPicador** [spotify/scio#462]
We are using scio, and we are pretty happy about it. But we often have issue with going around it/extending it. 

Each time, it's the same issue, we would like to reuse some internal classes/metod but it's private. So we end up with putting our classes in `com.spotify.scio` package.

For exemple, we wanted to put our own Kryo Coders, so instead of subclassing `KryoAtomicCoder` we had to create our own `AtomicCoder` by copy/pasting it.
Same thing with `JobTest`, as we are not using `main` & command line arguments to launch our jobs, so we had to copy/paste `JobTest` to make it work, instead of just subclassing it. Only because `TestDataManager` is private.

We could do a PR for each of those cases, but it's mostly specific to our use case. We also understand the issue of keeping internals closed (easier to move forward).

Any idea on how to tackle this issue?

**Comment by nevillelyh** [comment]
Are `KryoAtomicCoder` and `JobTest` the only ones you want to expose? Can you post some snippet of how you extend them?

I guess we can add some utilities for creating custom coders.
For `JobTest` it depends on how you use it. Is there any reason if you're not using `runWithContext` etc?

**Comment by kanterov** [comment]
I recently tried to optimize encoding of our case classes, I completely agree with demand for opening custom codecs. 

In general, I agree that there should be more public stuff marked documented as internal, instead of disabling any way to extend things if you know what you are doing.

By the way, probably for most of cases, adding custom `IKryoRegistrar` to classpath would work.

**Comment by ElPicador** [comment]
For JobTest, we had to copy/paste the entire class, as we needed to change the `run` method, to not use `main` and pass parameters. The issue was the object `TestDataManager` that is private.

For `KryoAtomicCoder`, we wanted to add custom coders, so we override the attribute kryo with something like:
```
@transient
  override lazy val kryo: ThreadLocal[Kryo] = new ThreadLocal[Kryo] {
    override def initialValue(): Kryo = {
      val k: KryoBase = new ScalaKryoInstantiator().newKryo() //this is new
      k.register(classOf[JIterableWrapper[_]], new JIterableWrapperSerializer)

      k.forClass(new KVSerializer)
      k.forClass[SSOne[Any]](new SSOneKryoSerializer[Any]) //this is new
      k.forClass[SSMany[Any]](new SSManyKryoSerializer[Any]) //this is new
      k.forClass[AveragedValue](new AveragedValueSerializer)
      k.forClass[QTree[Unit]](new QTreeSerializer) //this is new
      k.forClass[Log](new LogSerializer) //this is new
      k.forClass[ParsedLog](new ParsedLogSerializer) //this is new

      k
    }
  }
```

Does this help you?

**Comment by nevillelyh** [comment]
Not sure about the `JobTest` issue since that seems a uncommon use case and most people would use `runWithContext` instead? What does your `run` method and `main` boilerplate look like?

As for `KryoAtomicCoder`, is this something solvable with `KryoRegistrar`?
https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-custom-kryo-serializers

**Comment by ElPicador** [comment]
I agree with you for the `JobTest` but having `TestDataManager` public would have been helpful, as we need some custom code for it.
For the `run` method: we are launching DF jobs programmatically from another scala application, so our `run` method takes directly a subclass of `com.google.cloud.dataflow.sdk.options.PipelineOptions`, so we bypass the command line arguments.

For `KryoAtomicCoder`, we wanted to use directly the [`ScalaKryoInstantiator`](https://github.com/twitter/chill/blob/develop/chill-scala/src/main/scala/com/twitter/chill/ScalaKryoInstantiator.scala) from chill, as it's bundle a lot of nive coder. But maybe it could be used in scio as a sane default?

**Comment by nevillelyh** [comment]
Right now we have `val k = KryoSerializer.registered.newKryo()` in `KryoAtomicCoder#kryo` and `KryoSerializer.registered = new ScalaKryoInstantiator` so it already does that?

As for `JobTest`, how about:
- Move everything before the `try/catch` block in `run()` to a public `setup()` method
- Move everything after the block to a `teardown()` method
- You implement your own `run()` variation

**Comment by ElPicador** [comment]
Oh sorry for Kryo, I checked a while ago and didn't see the change.

For JobTest, fine my be. I can do the PR tomorrow

**Comment by ElPicador** [comment]
Well, I was bored, I did the PR 😄
