### ISSUE TITLE
Basic ElasticsearchIO examples in Java

### ISSUE THREAD

**Issue by richpodraza** [spotify/scio#4665]
I'm looking for something like this: https://spotify.github.io/scio/examples/ElasticsearchMinimalExample.scala.html

But for the Java native ElasticsearchIO (e.g. https://github.com/spotify/scio/blob/main/scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java)

**Comment by RustedBones** [comment]
Hi @richpodraza 
If you want to use the java `ElasticsearchIO` api, you can go with [saveAsCustomOutput](https://github.com/spotify/scio/blob/72423169818a25b0cf9321dc24660a1252890a54/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L1654) with smth like

```scala
val write = org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO.Write
  .withFunction()
  ...
  
data
  .saveAsCustomOutput("write-to-es", write) 
```

May I ask your use-case to see if we are missing smth in the scala wrapper ?

**Comment by richpodraza** [comment]
I doubt anything is missing, I just have very little Scala experience, the relationship between the two isn't super clear to me. But what you wrote resembles what I have now so I think I am close. Here's a couple specific questions:

1. The package name is the same as the Apache ElasticsearchIO but as far as I can tell that's the only similarity. This must be intentional...why?

2. Also the Apache ElasticsearchIO Write transform expects an incoming PCollection<String>, so currently I have a separate DoFn converting my data to a JSON String. Do I understand correctly that is the purpose of the withFunction()? I just pass my data PCollection directly to the Write and provide it the SerializableFunction to convert to JSON String?

**Comment by RustedBones** [comment]
1. I do not know the full historical reasons for that. What I can say is that usually, scio code in those packages was originally written to be contributed back to beam. It's possible that at the time, beam did not have an `ElasticsearchIO`. We should probably revisit that now, and see if we can depend on theirs.

2. You should not pass json directly to the IO. The json conversion is done by the `mapper ` in the `ElasticsearchOptions`. In your case you need to make sure it supports your data you want to index. The `withFunction` should take your model as structured input, to create an `IndexOperation[T]` (`T` being your data type).

**Comment by richpodraza** [comment]
Thanks @RustedBones this answers it for me
