### ISSUE TITLE
0.12.2 maven publication failed?

### ISSUE THREAD

**Issue by turb** [spotify/scio#4676]
Hello,

I wanted to give a try to scio 0.12.2 / Beam 2.44, however it seems that the publication to Maven repos never occured: [Maven Central](https://repo1.maven.org/maven2/com/spotify/scio-core_2.13), [mvnrepository.com](https://mvnrepository.com/artifact/com.spotify/scio-core_2.13) and [Maven Central search](https://search.maven.org/artifact/com.spotify/scio-core_2.13) are missing it.

It seems the GitHub Action [failed with Unexpected server response: 502 Bad Gateway](https://github.com/spotify/scio/actions/runs/4007791827/jobs/6894588376).

**Comment by RustedBones** [comment]
That's correct. We've already done 12 attempts of the [release](https://github.com/spotify/scio/actions/runs/4007791827) GHA without success. Sonantype [status](https://status.maven.org) was indicating some disturbance yesterday but we still didn't manage to publish.

We're currently investigating. Bear with us!

**Comment by clairemcginty** [comment]
Hi @turb! Turns out Sonatype was experiencing extremely heavy traffic, but we managed to get the release completed tonight and all artifacts should be available in Maven.
