### ISSUE TITLE
TupleTag collides in sortMergeTransform of multiple sorted bucket IO

### ISSUE THREAD

**Issue by shnapz** [spotify/scio#4692]
1. Improve documentation to explain that TupleTag should have unique name in the context of SMB transform: https://spotify.github.io/scio/extras/Sort-Merge-Bucket.html
2. On Scala API layer validate that TupleTags are unique, like on `sc.sortMergeTransform` etc.

**Comment by clairemcginty** [comment]
fixed in #4711
