### ISSUE TITLE
Simpler API for SCollection with only one side input?

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#472]
An `SCollection` with a single side input likely represents a majority of side input use cases, and while it's nice having a uniform api to deal with any number of sides, I think it makes it more cumbersome to use for what should be (I think) the most common use case.  I think it would be good to have a separate `SCollectionWithSideInput` class with transforms defined that directly give the user the value contained in the `SideInput`, rather than having to fish it out of the side input context. So pipeline code would look like this:

```
val side = ...   // SideInput[List[Int]]
scoll.withSideInput(side)
    .map { case (item, sideList) => ... } // sideList: List[Int] 
```

Thoughts? Should be fairly easy to delegate most of the work to the current multi-side implementation.

cc @rgruener

**Comment by nevillelyh** [comment]
Not sure about this. Most cases can be handled with `cross`, `hashLoopup` and `hashJoin` already?
