### ISSUE TITLE
Use latest data/partition in type-safe BigQuery annotations

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#474]
`@BigQueryType.fromTable` & `@BigQueryType.fromQuery` currently requires a specific data/partition, i.e. `@BigQueryType.fromQuery("SELECT * FROM `log_%s`", "20170301")` but it'd be nice to use the latest tables available.

We could have a magic string / constant to indicate an order by table date wildcard. So:
- `val LATEST = "[LATEST]"
- `fromTable("dataset.prefix_%s", LATEST) would match newest table in `dataset.prefix_*`

However, join case could be trickier
- `fromQuery("SELECT * FROM dataset1.prefix1_%s JOIN dataset2.prefix2_%s", LATEST, LATEST)` may join tables from different dates depending on availability.
- unless if we have another keyword that indicates matching only the latest available in all sources, like "LATEST_ALL"?

**Comment by keithmcneill** [comment]
I like LATEST_ALL.  I would make LATEST behave like that.  I don't think there is need for multiple keywords to confuse things.  If there is no common partition the compile would fail.  Users could always use dates if that doesn't work.  I think LATEST_ALL will cover almost all cases that people want.
