### ISSUE TITLE
Avro SpecificRecord codec regression in 0.12.5

### ISSUE THREAD

**Issue by mkuthan** [spotify/scio#4763]
After changes (#4713, #4590), Avro SpecificRecord coder doesn't work for avrohugger generated case classes.

Built-in Avro coder gets schema from the static `$Schema` field of generated specific record class.  Such field doesn't exist in case classes generated by avrohugger.

I would ask for reverting changes and use macro for getting Avro schema from specific records. I think that avrohugger is a common way to play with Avro specific records in Scala. 

The macro below works like a charm for case classes generated by avrohugger.
```
_root_.com.spotify.scio.coders.Coder.beam(
      _root_.org.apache.beam.sdk.coders.AvroCoder.of[$companioned](
        classOf[$companioned],
        new $companioned().getSchema,
        true
      )
    )
``` 

See also: #1702, #1754,  #1755, #1758

I also found that similar method for Avro Codec has been implemented in Flink, see: https://github.com/apache/flink/pull/9565/files

**Comment by RustedBones** [comment]
Ha, my bad and sorry for the regression.

We should really add some comments + tests so those removal won't happen again. I did not have the context for the `avrohugger`.

**Comment by mkuthan** [comment]
Hi @RustedBones 

Sorry for the late response. I'm fine if I could easily define my own coder for Avro using Scio API.
In my team we implemented thin IO layer as a reusable library for all piplelines, so we have one place to modify.
