### ISSUE TITLE
GenericRecord Avro coders fail on logical types

### ISSUE THREAD

**Issue by clairemcginty** [spotify/scio#4783]
The default Avro coders will fail with ClassCastExceptions when used on Avro GenericRecords that include logical type.

I think this is a problem that affects only a tiny percentage of users -- usually when you're working with logical types you're using a SpecificRecord, which will already have conversions built into the decode/encode methods.

It's also tricky to solve this; basically, we'd need to either (a) allow AvroCoders to specify custom `GenericData` or `SpecificData` instance variables that contain the logical type conversions, or (b) execute `GenericData.get().addLogicalTypeConversion(new TimeConversions.TimestampConversion)` (or whatever the desired conversion is) every time the Coder is deserialized on a worker. It might end up not being worth it to support the GenericRecord/logical type use case.

**Comment by RustedBones** [comment]
This can potentially be fixed after beam 2.49 if we allow custom datum factories on the `AvroIO`

**Comment by RustedBones** [comment]
User can now declare custom `AvroCoder` with datum factories that add logical types conversions.
We now need to expose the custom datum factories in the IOs.

**Comment by RustedBones** [comment]
Fixed by #5152
