### ISSUE TITLE
`map` on SideInput is a terrible idea and should be deprecated.

### ISSUE THREAD

**Issue by jto** [spotify/scio#4819]
Currently it is possible to do something along the line of:

```scala
coll.asSetSingletonSideInput
      .map(doSmth)
```

When using a Global window (always the case for batch workflows), the result of mapping over the `SideInput` value is not cached. Every time the side input is accessed, `doSmth` is applied to it. When `doSmth` is not a trivial operation, it can make the job _very_ slow.

I think mapping on a `SideInput` should just not be supported. If the values in that SideInput are to be modified, it should be done _before_ the `SCollection` is turned into a view. For example:

```scala
coll.map(doSmth).asSetSingletonSideInput
```  

I implemented this exact fix on an expensive production workflow and it made the runtime go from ~1h30min to ~30min.

**Comment by RustedBones** [comment]
Agreed. I think we can expose `map` after an explicit `.view` call (a bit like scala does), so users will know the operation will be executed on every access.
