### ISSUE TITLE
Integrate TestPipeline#enableAbandonedNodeEnforcement with JobTest

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#494]
This may help cases where a user forgets to call `run()` at the end.

**Comment by nevillelyh** [comment]
This seems trick since in Beam, `TestPipeine` is annotated with a JUnit `@Rule` which triggers the checking. We need to somehow capture that in a `"Test name" should "behave ..." in { JobTest[MyJob.type] ... }` block.

**Comment by ravwojdyla** [comment]
Solved in #515. Closing.
