### ISSUE TITLE
CodeCov reporting 0%

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#499]
https://github.com/spotify/scio/commit/90d9af1c862eaaea65f369064547041f52337986 seems to be the 1st commit with wrong coverage. It didn't change any CircleCI settings though.

**Comment by andrewsmartin** [comment]
The problem was that there was a scalastyle error that prevented tests being run, but still allowed the build to pass due to the way CircleCI captures output. Fixed in 37cbf5d
