### ISSUE TITLE
Encoding errors after upgrade from 0.2.12 to 0.2.13

### ISSUE THREAD

**Issue by ElPicador** [spotify/scio#500]
We upgrade scio, and only scio, and we now have errors while running our jobs:

```
java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Unable to encode element
```

I don't really know what to seek, so feel free to ask question :)

**Comment by ElPicador** [comment]
nb: we downgraded and it worked

**Comment by nevillelyh** [comment]
Do you have the full stacktrace? Any idea what's the element it failed to encode?

**Comment by ElPicador** [comment]
No stacktrace, would have been too easy).
The element was a case class that is an object read from GCS in json format with json4s, with a custom deserialiser.

**Comment by nevillelyh** [comment]
It might be from from `StandardCoder`
```throw new IllegalArgumentException(
          "Unable to encode element '" + value + "' with coder '" + this + "'.", exn);```

So there should be a stacktrace `exn` after this?
Also can you reproduce with a minimal local JSON file with `json4s`?

**Comment by ElPicador** [comment]
I don't have the full exception. Because `value` is a huge object, so Dataflow strips the output. And of course it's nowhere in the logs.

We have this exception only on big objects, and when we do a `groupBy` (yes I know that's not a good practice, but we need it).

**Comment by nevillelyh** [comment]
https://github.com/spotify/scio/pull/505 should address. We are no longer maintaining the Cloud Dataflow SDK based branch though. This will be included in the next Beam based release, most likely 0.3.0-beta3.

**Comment by ElPicador** [comment]
Ok thanks

**Comment by nevillelyh** [comment]
Closing this now that v0.3.0-beta3 is released.
