### ISSUE TITLE
Cli options 

### ISSUE THREAD

**Issue by salehsedighi-ck** [spotify/scio#504]
Is there an easy way to get list of all available options specially default values 
e.g dataflow or bigquery ?

**Comment by ravwojdyla** [comment]
@salehsedighi-ck could you give more context of what are you trying to do? If code/programmatic is fine you might want to take a look [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L98).

**Comment by salehsedighi-ck** [comment]
Long story short, I'm trying to submit a job to Dataflow and it's failing. unfortunately there is no useful log or error message to debug. and I'm hoping to figure out if a parameter is using default value or not and what the value is.

**Comment by ravwojdyla** [comment]
Could you share your error message? Also we have [gitter](https://gitter.im/spotify/scio), if you wanna chat there.

**Comment by ravwojdyla** [comment]
Closing this for now, please provide more info in gitter or reopen if needed.
