### ISSUE TITLE
Benchmark suite for Scio specific pieces

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#506]
Would be nice to put together a benchmark for scio specific features - mainly the serialization, joins etc. This could run as part of some integration step. It would allow us to catch performance regressions, but also see the improvements over time.

**Comment by nevillelyh** [comment]
Let's come up with a list of operations to cover and datasets to use? 

I prefer open datasets like those example BQ tables so they can be reproduced by external contributors.

**Comment by ravwojdyla** [comment]
Agree about the open datasets. Some suggestion to start with:
* all the custom serializers
* set of identical, representative pipelines in pure beam/dataflow and scio to compare against

**Comment by nevillelyh** [comment]
They can also be categorized into things that can be tested locally (serializers) and things that need real workload and clusters.

Also for reference: https://amplab.cs.berkeley.edu/benchmark/

**Comment by nevillelyh** [comment]
WIP https://github.com/spotify/scio/tree/neville/bench
