### ISSUE TITLE
Add nightly build for beam snapshot

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#512]
Our main dependency is Beam, currently we wait for next release of Beam and fix any breaking changes, this unfortunately does not allow us to continuously keep track of what is happening in Beam, and moreover if there is change that would break scio we would only be able to submit PR to beam after the release and wait for next release cycle. How about we:
 * create a branch that depends on current SNAPSHOT of beam (already exists [beam-master](https://github.com/spotify/scio/tree/beam-master))
 * nightly build the branch with tests to get feedback about breaking changes (we can use [nightly-builds](https://circleci.com/docs/1.0/nightly-builds/))

This would allow us to keep track about changes coming in next release of beam and possible react in the same release. An example would be current SNAPSHOT and change in BigQueryIO that would close some of the useful utilities we use in Scio, [example](https://github.com/apache/beam/pull/2271) and [PR](https://github.com/apache/beam/pull/2366) that fixed it before the release.

**Comment by nevillelyh** [comment]
Looks like nightly builds need to be triggered from somewhere else.
https://circleci.com/docs/1.0/nightly-builds/

**Comment by ravwojdyla** [comment]
@nevillelyh correct, but it shouldn't be a problem to have a box with a cron for this.

**Comment by nevillelyh** [comment]
Instead of building from a branch (i.e. `beam-master`) which tends to go stale, we should build this on top of master, by replacing `beamVersion` only.

**Comment by nevillelyh** [comment]
What if there's a breaking change in `SNAPSHOT`? We can't fix it in `scio:master` and have to branch out, which kinda defeats the purpose of having a nightly integration build.

**Comment by nevillelyh** [comment]
Fixed in d7ceae5d926e60de31485dac9f6600f02128b62d

It will do the following nightly:
- checkout `beam-master` branch
- `git rebase master`
- fetch latest Beam snapshot version
- update `beamVersion` in `build.sbt`
- add Apache snapshots resolver
- build

This way we can make sure that `beam-master` is kept up to date with `master` and fix breaking changes in that branch.
