### ISSUE TITLE
Make SplittableDoFn the default Parquet read implementation

### ISSUE THREAD

**Issue by clairemcginty** [spotify/scio#5129]
Initially we made this feature opt-in due to performance concerns on Dataflow Classic (non-Runner-V2: while SDF would use less VPCU/memory overall, it scaled up far less than the legacy implementation, leading to significantly longer job runtime. Anecdotally, it seems like performance has been better with SDF+Dataflow Classic lately -- can we do a final round of performance comparisons of:

- Legacy Parquet Read / Dataflow Classic
- Legacy Parquet Read / Dataflow Runner V2
- SplittableDoFn Parquet Read / Dataflow Classic
- SplittableDoFn Parquet Read / Dataflow Runner V2

and make SDF the default?

**Comment by RustedBones** [comment]
@clairemcginty should we descope this from 0.14 ?
IMHO syncing this change when dataflow runner v2 becomes default would make a lot of sense since it will be optimized for splittable DoFn

**Comment by clairemcginty** [comment]
@RustedBones sounds good. We already [automatically select SplittableDoFn](https://github.com/spotify/scio/blob/v0.13.6/scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadConfiguration.scala#L54-L70) if RunnerV2 is enabled so it'll be a very smooth transition once V2 becomes default.
