### ISSUE TITLE
Nice to have: scala.js UDF for BigQuery

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#517]
So that users can write and test UDFs in Scala, use it both in regular Scio pipelines and as UDFs in BigQuery.

Inspiration: https://twitter.com/kanterov/status/823630288219684865

**Comment by ravwojdyla** [comment]
@andrewsmartin did you try this out already?

**Comment by nevillelyh** [comment]
IIRC we tried UDFs but not scala.js?

**Comment by andrewsmartin** [comment]
I had a WIP branch a while back but accidentally deleted it :/ Happy to revisit though. I'll note that this will be much easier for standard SQL than legacy because of the differences in how UDFs are used, but we only support UDFs for standard SQL anyway so I think we can just limit to standard.

**Comment by nevillelyh** [comment]
My imaginary usage scenario:
- Scala files in `src/main/scalajs`
- Compiled `.class` can be used in regular pipeline jobs and tested in regular tests
- Some SBT wiring to generate `.js` files, and corresponding Scio wiring to pick them up, upload to GCS, and specify URI in query string

Need to look more into scala.js and build setup first though.

**Comment by andrewsmartin** [comment]
Thinking of the user-facing API first, how do we feel about defining UDFs as methods of the `@BigQueryType` case class, to be referenced in the query string? I was hacking around with that a while back but can't remember how far I got with it. Would have to somehow integrate scala.js transforms with macro code

**Comment by andrewsmartin** [comment]
@nevillelyh Just saw your above comment, that seems easier and more flexible. I guess in this case the query would always point to an external .js file, right? Would we want to support in-lining the UDFs as part of the query (by doing something at the macro level) as well or is that too much work?

**Comment by nevillelyh** [comment]
Sounds like too much work. Please the query string might be way too long to be either human readable or even submit to service?

**Comment by andrewsmartin** [comment]
True 👍 GCS approach it is.

**Comment by kanterov** [comment]
There are technical problems with running UDFs in BigQuery. It was never supposed to be widely used, and there is a quota on concurrent executions. Perhaps it doesn't worth simplification, it should be painful, and you should know what you are doing :).

**Comment by andrewsmartin** [comment]
Can we close this for now?

**Comment by nevillelyh** [comment]
Yeah let's close and reopen when there's a better/clear way.
