### ISSUE TITLE
CsvIO limitation of HeaderDecoder and RowDecoder

### ISSUE THREAD

**Issue by albertols** [spotify/scio#5177]
Hi All,

Following:

`case class User(name: String, age: Int)
    implicit val decoder = HeaderDecoder.decoder("fullName", "userAge")(User.apply _)
    val users: SCollection[User] = scioContext.csvFile(path)
 `
 from https://github.com/spotify/scio/blob/main/scio-extra/src/main/scala/com/spotify/scio/extra/csv/CsvIO.scala#L58

I am trying to use Case Classes with more than 22,  fields but I am seeing this limitation

![image](https://github.com/spotify/scio/assets/10211316/7f36fcd8-5838-4954-9566-ee95983c26b0)

From kantan.csv library, I do not where exactly is coming from or if I am missing something here.

https://github.com/nrinaudo/kantan.csv/blob/v0.7.0/core/shared/src/main/boilerplate/kantan/csv/GeneratedHeaderDecoders.scala.template

Thanks guys!

Alberto

P.S: Same with RowDecoder:
https://github.com/nrinaudo/kantan.csv/blob/v0.7.0/core/shared/src/main/boilerplate/kantan/csv/GeneratedRowDecoders.scala.template

![image](https://github.com/spotify/scio/assets/10211316/a852fa04-924f-4557-b054-bc86129f3f14)

**Comment by RustedBones** [comment]
Hi @albertols 

You are facing a very well known scala issue with the [22 limit](https://underscore.io/blog/posts/2016/10/11/twenty-two.html).

Even if the 22 limit has been lifted on case class for a while, most library (including scio) only define their API to a maximum 22 parameters.

I fear you'll have to use a custom decoder implementation in this case.

Closing the issue since this is not scio specific.

**Comment by albertols** [comment]
Thanks for the fast response @RustedBones ,

Maybe the 22 limitation could be included in the comments. I am able to use case classes with more than 22 fields, e.g:

saveAsTypedBigQuery

I will try to give it a go ;) I do not know if https://github.com/tototoshi/scala-csv or similar could dodge the limitation. Maybe, as future enhancement CsvIO could deal with other Decoders/Encoders to avoid this limitation.

Cheers!
