### ISSUE TITLE
Support for capnproto/flatbuffers

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#518]
[capnproto](https://capnproto.org/) ([flatbuffers](https://google.github.io/flatbuffers/)) has some advantages over protobuf. We might want to support it.

**Comment by nevillelyh** [comment]
For Capnproto the official implementation is in C++ only?
https://github.com/sandstorm-io/capnproto
There's an unofficial Java one though
https://github.com/dwrensha/capnproto-java

**Comment by nevillelyh** [comment]
Closing since there's not enough need for this.
