### ISSUE TITLE
org.apache.hadoop.fs.FileSystem conflict in assembly jars

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#52]
2 versions of `org.apache.hadoop.fs.FileSystem` may be included in an assembly jar that depends on `scio-hdfs`, one from `hadoop-common` and one from `hadoop-hdfs`. We should fix it so that end users don't have to add strange merge strategy. Or at least document it.

```
diff hadoop-common/META-INF/services/org.apache.hadoop.fs.FileSystem hadoop-hdfs/META-INF/services/org.apache.hadoop.fs.FileSystem
16,19c16,20
< org.apache.hadoop.fs.LocalFileSystem
< org.apache.hadoop.fs.viewfs.ViewFileSystem
< org.apache.hadoop.fs.ftp.FTPFileSystem
< org.apache.hadoop.fs.HarFileSystem
---
> org.apache.hadoop.hdfs.DistributedFileSystem
> org.apache.hadoop.hdfs.web.HftpFileSystem
> org.apache.hadoop.hdfs.web.HsftpFileSystem
> org.apache.hadoop.hdfs.web.WebHdfsFileSystem
> org.apache.hadoop.hdfs.web.SWebHdfsFileSystem
```

**Comment by ravwojdyla** [comment]
It is documented here -> https://github.com/spotify/scio/wiki/HDFS

**Comment by ravwojdyla** [comment]
One thing we might do is to repackage hadoop in `scio-hdfs` and solve the problem (via our merge strategy) inside `scio` - but than we actually package hadoop inside `scio-hdfs` - it has it's downsides obviously.

This is a pretty common problem tho - maybe just documenting as above is good enough for now?

**Comment by ravwojdyla** [comment]
Another solution - we could also add our own `core-default.xml` file in resources and register most common filesystems - but then we inject our own `core-default.xml`, so what if there is the user already has meaningful `core-default.xml`. No good either.

**Comment by nevillelyh** [comment]
Yeah I'd prefer not to repack something as big as hadoop...

This issue only affects assembly jar right?

For people running locally in their development environment `sbt run-main` should work just fine.

For those who want a deployable artifact maybe look into [sbt-pack](https://github.com/xerial/sbt-pack) which creates a directory/tarball of all dependency jars without needing any merge strategy? On the plus side dependencies can be cached on GCS so no need to upload a fat jar when app changes.

Root cause is our internal system which requires assembly jar but that maybe fixed :)

**Comment by ravwojdyla** [comment]
Agree about repackaging hadoop. This issue seems to appear if you assembly jar and depend on hadoop-{hdfs,common} jars. Documentation for now is probably the most optimal idea.

**Comment by ravwojdyla** [comment]
Workaround is documented [here](https://github.com/spotify/scio/wiki/HDFS). In the mean time sbt-pack was tested and works fine as well. Closing.
