### ISSUE TITLE
fromTable should validate if schema cache is up to date

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#520]
Currently fromTable won't validate if schema of the table in cache is up to date with the schema in BQ (in case of delete->new-table, or modification of schema (like new field)).

**Comment by andrewsmartin** [comment]
After some discussion internally, and noting that this behavior is consistent with the `fromQuery` macro, we decided that for caching it's probably best to live with schema evolution issues. Doing any kind of validation would necessitate a BigQuery API call and somewhat defeat the purpose of the cache. Instead, we'll leave this as is, and as a workaround users can either manually delete the cache or choose to opt-out of caching altogether (https://github.com/spotify/scio/wiki/FAQ#why-are-my-typed-bigquery-case-classes-not-up-to-date).
