### ISSUE TITLE
Taps with PubsubIO

### ISSUE THREAD

**Issue by albertols** [spotify/scio#5232]
I am trying to use a ClosedTap as a pre loaded SCollection, from PubsubIO though (as I expect my load from a topic), to be used later on for some of my app logic.

But I am facing: 

_org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalArgumentException: PCollection with more than one element accessed as a singleton view. Consider using Combine.globally().asSingleton() to combine the PCollection into a single value_

I am following some of the examples:

- https://spotify.github.io/scio/examples/TapOutputExample.scala.html
- https://spotify.github.io/scio/Builtin.html#taps-materialization

But I was not able to found anything with an Unbounded Collection (I want everything that is in that topic preloaded, otherwise I will try from GCS), is it possible ?

thanks team!

Alberto

P.S:  high level snippet
```
def windowOptions = com.spotify.scio.values.WindowOptions(
  allowedLateness = org.joda.time.Duration.ZERO,
  trigger = Repeatedly.forever(AfterProcessingTime.pastFirstElementInPane()), // it needs a trigger in the global window
  accumulationMode = DISCARDING_FIRED_PANES,
  timestampCombiner = TimestampCombiner.LATEST
)

//  1) TAP Context
log.info("Init SCIO Context0 (Tap)...")
val (tapSc, argsTap) = ContextAndArgs(cmdlineArgs)
log.info(s"SCIO argsTap=$argsTap")
val isTap: Boolean = argsTap.getOrElse("is-tap", "false").toBoolean
val pubsubAvroAnalytics: String = argsTap.getOrElse("pubsub-avro-analytics", config.mediation.pubsubAvroAnalytics)

// 2) Reading records from Tap
val optionalOldBers = if (isTap) {
  val pubsubAvroNhub: String = argsTap.getOrElse("pubsub-avro", config.mediation.pubsubAvroNhub)
  val oldAvroBers = PubSubConsumer.readGenericAvroScio[BusinessEventRecord](pubsubAvroNhub, PubsubIO.ReadParam(PubsubIO.Subscription))(ct, tapSc)
  val windowedOldAvroBers = ??? // apply Global window with windowOptions
  //windowedOldAvroBers.count.map{oldAvroBersCount => [log.info](http://log.info/) (s"oldAvroBersCount=$oldAvroBersCount")}
  val oldAvroBersClosedTap = windowedOldAvroBers.materialize
  val initalLoadScioResult = tapSc.run().waitUntilDone()
  Some(initalLoadScioResult.tap(oldAvroBersClosedTap))
} else None

// 3) Second Context
val (sc, args) = if (isTap) {
  log.info("Init SCIO Context ...")
  ContextAndArgs(cmdlineArgs)
} else (tapSc, argsTap)

// 4) Using Tap records in second context
if (optionalOldBers.isDefined) {
  log.info("Loading old Avro BERs ...")
  optionalOldBers.get.open(sc).debug()
  
  ...
  My logic
  ...
}
```

**Comment by kellen** [comment]
Your cause of the exception is somewhere else in your code, but Pubsub sources are unbounded so will not complete in a batch pipeline and materialized data is only available upon pipeline completion, so this is not possible. Furthermore, you're reusing `tapSc`, which if already `run()` will throw an exception.

**Comment by albertols** [comment]
thanks @kellen , I ended up loading historical from GCS without taps and using global windows
