### ISSUE TITLE
Nice to have: wrap Beam JDBC IO and maybe helpers

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#525]

**Comment by syodage** [comment]
Until we have this wrapper available, I used following to write data to Cloud SQL 

```
def main(cmdlineArgs: Array[String]): Unit = {
    val cloudSqlOptions: CloudSqlOptions = PipelineOptionsFactory.fromArgs(cmdlineArgs: _*)
      .withValidation()
      .as(classOf[CloudSqlOptions])

    val (sc, args) = ContextAndArgs(cmdlineArgs)
    val input = args.getOrElse("input", KING_LEAR)

    // initialize accumulators
    val max = sc.maxAccumulator[Int]("maxLineLength")
    val min = sc.minAccumulator[Int]("minLineLength")
    val sumNonEmpty = sc.sumAccumulator[Long]("nonEmptyLines")
    val sumEmpty = sc.sumAccumulator[Long]("emptyLines")

    sc.textFile(input)
      .map(_.trim)
      .accumulateBy(max, min)(_.length)
      .accumulateCountFilter(sumNonEmpty, sumEmpty)(_.nonEmpty)
      .flatMap(_.split("[^a-zA-Z']+").filter(_.nonEmpty))
      .countByValue
      .map(t => KV.of(t._1, t._2))
      .saveAsCustomOutput("CloudSql Writer", getJdbcIoWriter(cloudSqlOptions))

    val result = sc.close().waitUntilFinish()
  }

  def getJdbcProxyUrl(options: CloudSqlOptions): String = {
    String.format("jdbc:mysql://google/%s" +
      "?cloudSqlInstance=%s&socketFactory=com.google.cloud.sql.mysql.SocketFactory",
      options.getDatabase, options.getInstanceConnectionName)
  }


  def getJdbcIoWriter(cloudSqlOptions: CloudSqlOptions): JdbcIO.Write[KV[String, Long]] = {
    JdbcIO.write[KV[String, Long]]()
      .withDataSourceConfiguration(JdbcIO.DataSourceConfiguration
        .create("com.mysql.jdbc.Driver", getJdbcProxyUrl(cloudSqlOptions))
        .withUsername(cloudSqlOptions.getUsername)
        .withPassword(cloudSqlOptions.getPassword))
      .withStatement("insert into wordcount values(?, ?)")
      .withPreparedStatementSetter(new JdbcIO.PreparedStatementSetter[KV[String, Long]] {
        def setParameters(kv: KV[String, Long], query: PreparedStatement): Unit = {
          query.setString(1, kv.getKey)
          query.setLong(2, kv.getValue)

        }
      })
  }

```

**Comment by ravwojdyla** [comment]
@syodage nice, would you like to submit a PR?

**Comment by nevillelyh** [comment]
Hm... Not sure how well this will fit with other IOs though. Looks like need a conversion from `T` to `PreparedStatementSetter` and a `withStatement` string, both of which depend on `T`.

**Comment by syodage** [comment]
@ravwojdyla I can try, as @nevillelyh mentioned, this is kind of different from other IOs.

**Comment by ravwojdyla** [comment]
Worst case those could be just a parameters to the IO tho right?

**Comment by ravwojdyla** [comment]
@syodage sweet, would be awesome if you could try to submit a PR. Probably easiest to just accept `PreparedStatementSetter`, `statement`, `username`, `password`, `jdbc` uri as parameters. Would be nice to also have input method. Could you also provide an example for the cloudsql in the examples module please?

**Comment by nevillelyh** [comment]
@ravwojdyla any idea how `JobTest` would work? Different `In` and `Out` stub classes like bigtable? What in/out types should we match against?

**Comment by ravwojdyla** [comment]
@nevillelyh one option could be to just bypass JDBC altogether in `JobTest`, and in/out would be of type `T` (before any of the JDBC conversions) - which is an attractive and simple idea, cause those tests would focus on the job logic - not the io/out, the downside is that it will not test user specified mappings from/to JDBC (it could be unit tested tho). Another option which might be a little bit more complicated (possible issues with serialization) is to work with JDBC types like `PreparedStatement` (filled) on the output and `ResultSet` on the input - and have some helpers for those. One more option could be to use some DB like H2 to have full blown coverage (rather overkill). I would probably start with the 1st one, just to get start, and if that is working try to make the 2nd option. What do you think?

**Comment by syodage** [comment]
Just to let you guys know, I am working on this and will provide a PR soon.

**Comment by syodage** [comment]
created an early review PR https://github.com/spotify/scio/pull/558 , any feedback would be appriciate.

**Comment by syodage** [comment]
PR is updated with test and example and it is ready for final review. I used option 1 suggested above by @ravwojdyla which bypasses the JDBC read-write layer in JobTests. 
@nevillelyh @ravwojdyla
