### ISSUE TITLE
distinctBy and distinctByKey trigger warning about combineByKey

### ISSUE THREAD

**Issue by turb** [spotify/scio#5294]
When using `distinctByKey`, a warning is triggered:

`WARN com.spotify.scio.values.PairSCollectionFunctions$ - combineByKey/sumByKey does not support default value and may fail in some streaming scenarios. Consider aggregateByKey/foldByKey instead.`

This warning is confusing, since `distinctByKey` (and `distinctBy`) are not mentioned in the message, nor any alternative. It is easy to understand that the warning is triggered because it uses `combineByKey` under the hood.

Would it be possible to:
- include those functions in the message (or have a specific message), and provide a hint for an alternative way
- or (even better) directly use the alternative in the implementation?

**Comment by RustedBones** [comment]
Thanks again for reporting that @turb !
