### ISSUE TITLE
Google PubSub Attribute Access?

### ISSUE THREAD

**Issue by jonopwell** [spotify/scio#535]
Now that Google has the DataFlow 2.0.x (Beam 0.6.y) version available, would it be trivial to enable read/write access to PubSub attributes? As you may know, they were not previously available on the Java API.

Much appreciated if you can help!

Jon

**Comment by nevillelyh** [comment]
We're actually looking at this internally. Stay tuned :)

**Comment by jonopwell** [comment]
Great! Thank you. We could use it ASAP. :-)
