### ISSUE TITLE
Integration with OpenTelemetry

### ISSUE THREAD

**Issue by damjad** [spotify/scio#5379]
I am working on migrating all metrics to OpenTelemetry in our codebase. 

For Scala Apache Beam jobs, we are using Scio for collecting metrics. 

Does ScioMetrics have an integration with OpenTelemetry? or is there any workaround?

An example of how we use them:

```
val metric = ScioMetrics.counter("x", "y")
metric.inc()
```

I will be much obliged with any help.

**Comment by RustedBones** [comment]
Hi @damjad,

Scio does not have an integration with open telementry.
I think there are several ways to report back metrics:
- for batch jobs the easiest is to rely on scio/beam counters and access the values in the `ScioResult` with [counter](https://spotify.github.io/scio/api/com/spotify/scio/ScioResult.html#counter(c:org.apache.beam.sdk.metrics.Counter):com.spotify.scio.metrics.MetricValue%5BLong%5D) and report them with some open telemetry exporter.
- for streaming jobs, it's more difficult. You should probably create a custom [DoFnWithResource](https://spotify.github.io/scio/api/com/spotify/scio/transforms/DoFnWithResource.html) that is able to collect and export metrics.

**Comment by damjad** [comment]
Hi,

Thanks for replying. I asked the question because of two reasons.

1. I saw that OpenCensus is a dependency in the [project](https://github.com/spotify/scio/blob/a12ab54e5ffcd93d34a9ccc450e20bd751202aba/build.sbt#L1850). Is it even used?
2. OpenCensus is [being retired](https://opentelemetry.io/blog/2023/sunsetting-opencensus/) in favor of OpenTelemetry.

**Comment by RustedBones** [comment]
1. opencensus is not a direct dependency of scio. It is pulled transitively by various libs:
```
sbt:scio> scio-core/whatDependsOn io.opencensus opencensus-api
[info] io.opencensus:opencensus-api:0.31.1
[info]   +-com.google.api:gax:2.46.1
...
[info]   +-com.google.cloud:google-cloud-storage:2.32.1
...
[info]   +-com.google.http-client:google-http-client:1.44.1
[info]   +-io.opencensus:opencensus-contrib-http-util:0.31.1
[info]     +-com.google.cloud:google-cloud-storage:2.32.1
...
[info]     +-com.google.http-client:google-http-client:1.44.1
```
We just ensure the version used in scio is the one provided by the google [libraries-bom](https://cloud.google.com/java/docs/bom) to reduce risk of runtime breakage.

2. As this is a transitive deps, we depend on the libraries to update to OpenTelemetry.

**Comment by damjad** [comment]
Thank you for clarifying!
