### ISSUE TITLE
Add a numpy array file IO

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#542]
Could be useful for people using Scio for feature engineering and feeding into scikit-learn or TensorFlow.

**Comment by nevillelyh** [comment]
Are you still working on this or should we close?

**Comment by ravwojdyla** [comment]
not working on it right now.

**Comment by nevillelyh** [comment]
Gonna close this since we standardized on TFRecords. Plus numpy file has a lot of python magic we'd like to avoid.
