### ISSUE TITLE
Intellij compilation fails on duplicate classes from scio-schemas

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#543]
This is not coming from scio itself, but to document this issues: if one wants to compile from intellij, to say run tests etc, Intellij fails with duplicate class from scio-schemas. This most likely is something related to Intellij settings, sbt or some of the plugins. Would be nice to figure this one out so that external contributors are not bothered by this issue.

In the meantime, manual workaround is to unmark `main` as `source directory` in `scio-schema/target/scala-*/src-managed` and recompile/rerun, and keep both `compiled_avro` and `compiled_protobuf` as source directories.

**Comment by nevillelyh** [comment]
Could be related:
http://stackoverflow.com/questions/16885489/intellij-compile-failures-is-already-defined-as/16888290
