### ISSUE TITLE
error message for partitionByKey makaes debugging a bit difficult

### ISSUE THREAD

**Issue by snallapa** [spotify/scio#5468]
when using `partitionByKey` if the pipeline encounters a key that is not in the input set. Right now you get:

```
org.apache.beam.sdk.util.UserCodeException: java.lang.IndexOutOfBoundsException: Partition function returned out of bounds index: -1 not in [0..2)
```
It would be great if the key that was not in the input set was printed, maybe even alongside the input set like `keyset: [], missing key: []`

**Comment by kellen** [comment]
For specifically partitionByKey we are providing the partition function so should be able to capture the key not found when index is returned as `-1`
