### ISSUE TITLE
Versioning strategy?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#562]
So we're at `v0.3.0-beta3` now, and it's been 2+ weeks since this release. The original plan was to wait for Beam 1.0.0 (or 2.0.0 if they decide to be in sync with Dataflow Java SDK) and Scala 2.12 support (blocked by scala/bug#10232 and scala/bug#10233) but there isn't a clear time line yet. IMO Scala 2.12 support is orthogonal and not a blocker on 0.3.0.

I see 2 options:

1. Release 0.3.0 right now, and revisions once Beam 1.0.0 is out
2. Keep releasing `0.3.0-beta{4,5,6...}` until Beam release. We can even do a few `RC` releases after feature freeze.

I'm leaning towards 1 since we never followed semantic versioning and always do small incremental releases. We're also not targeting 1.0.0 to be in sync with Beam versioning. The `betaX` suffix gives people a wrong idea that it's less mature than previous releases.

**Comment by nevillelyh** [comment]
CC @jonopwell

**Comment by kanterov** [comment]
I see it as releasing 0.3.0 now, and 0.4.0 with Beam upgrade.

**Comment by nevillelyh** [comment]
0.3.0 is released. Closing this.

**Comment by jonopwell** [comment]
Thank you!
