### ISSUE TITLE
Collect some accumulator statistics about joins

### ISSUE THREAD

**Issue by alaiacano** [spotify/scio#564]
This is an idea that just came up in slack. If it's feasible I'd love to help build it.

The idea is to get some statistics around joins, for debugging/verification reasons. If I am joining two collections, I could identify the join or something, like: `scollA.join(scollB, statsId="my_join")`

and for `my_join` i could get accumulator results for things like:

* number of elements in LHS
* number of elements in RHS
* number of elements in output
* number of elements dropped because the key was missing in LHS/RHS
* other useful things?

We could then verify output data in cases where, for example, we require that `# in LHS == # in RHS` so that nothing gets dropped from either collection.

**Comment by nevillelyh** [comment]
Right now all joins delegate to `MultiJoin` which is generated with a script.
This is a special case so we probably want to handcraft and little bit. Maybe delegate to the specialized version when `statsId` is specified?

**Comment by jbx** [comment]
Feels out of scope, should be runners job to keep track of stats.
