### ISSUE TITLE
Circle CI not building PRs from forked repos

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#572]
Like this one:
https://github.com/spotify/scio/pull/568

**Comment by ravwojdyla** [comment]
Kinda by design, but still possible, we might need to adjust the circleci script to skip an steps which require secrets. Doc: https://circleci.com/docs/1.0/fork-pr-builds/

**Comment by nevillelyh** [comment]
We should fix it. Will improve process for external contributors. Should be as simple as disable ENVs and skip integration tests and maybe BQ macros in PR builds?

**Comment by nevillelyh** [comment]
CircleCI is leaking ENVs in the UI to the container. Filed a support ticket.

**Comment by nevillelyh** [comment]
Haven't heard from them yet, but maybe we could use Travis just for PRs?

**Comment by nevillelyh** [comment]
Fixed in #592
