### ISSUE TITLE
NIO Refactor TestIO and Taps

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#575]
Right now `TestIO` wiring and `Tap[T]` API is not easy to extend and there's fair amount of duplication. It's also not easy to chain or derive IOs, e.g. Circe-based JSON from `TextIO`. Some of this is due to the `requireNotClosed` in `ScioContext` and also no hierarchy within `TestIO` instances.

Checklist:
- [ ] migrate all IOs to new `ScioIO`
- [ ] remove all old test IOs and rename new `ScioIO`s to old names
- [ ] verify that all tests and examples are backwards compatible
- [ ] verify that `requiredNotClosed` usage is localized and consistent

**Comment by nevillelyh** [comment]
A bit more context. Today to implement a new IO, one needs to do the following:

- Add new IO case class that extends `TestIO` for test wiring in `JobTest`
- Add new read method to `ScioContext`
- Add new save method to `SCollection`
- [Optional] Add new tap class and implementation using `IOChannelFactory` or re-implement logic in the IO

It'd be nice to have most business logic in the same place, say something that extend a `ScioIO` trait, which can also be used in `JobTest` matching. Then all the read methods on `ScioContext` and write methods on `SCollection` can just use the logic in this `ScioIO`.

**Comment by syodage** [comment]
I think this has great value when it comes to clean and maintain code. I am thinking of sending a PR by refactoring TextIO as a first step(if all went well, I will work on other IOs too), Thinking out loud, this will lead us to have lightweight `scio-core` and IO implementation will stay in their own module. My approach would be similar to what we did to jdbc integration here https://github.com/spotify/scio/pull/558 , If I briefly explain what I am planning to do, 
Create a `trait ScioIO` all re-usable code across IOs will go here, 
Create a `class TextIO extends ScioIO with Tap` <- everything related to TextIO goes here, eg: read, write, open 
Then I feel, Instead of `TestIO` subtype, we can use actual IO class in JobTest
@nevillelyh wdyt?

**Comment by nevillelyh** [comment]
Pretty much what I had in mind :)

To recap:

- start a new namespace, maybe `com.spotify.scio.nio`
- `trait ScioIO[T]` as the base, with abstract methods to read (via `ScioContext`), write (via `SCollection`), and read `Tap`
- `case class TextIO(path: String, ...) extends ScioIO[String]` etc
- add `ScioContext#read[T](io: ScioIO[T])` and `SCollection#write[T](io: ScioIO[T])`
- ??? add `JobTest#inputNio` and `JobTest#outputNio` to handle test wiring
- rewrite existing `ScioContext#*File` etc. and `SCollection#saveAs*` to use `nio`

We'll probably hit other issues and have to improvise along the way.

**Comment by syodage** [comment]
Awesome!, thanks for the recap, I will create a new branch and start working on it. 

Getting my hand dirty with type-safety and another advance scala features will be a good experience for me.

**Comment by syodage** [comment]
@nevillelyh I created an initial PR to get some feedback earlier as I followed bit different approach than you suggest. 

I am thinking how 4th steps works, could you explain a bit how `ScioContext#read[T](io: ScioIO[T])` and `SCollection#write[T](io: ScioIO[T])` this works when writing a pipeline?

**Comment by nevillelyh** [comment]
I would add 2 abstract methods to `ScioIO` trait, `read(sc: ScioContext): SCollection[T]` and `write(data: SCollection[T]`. So `ScioContext#read` can call `ScioIO#read(this)` and `SCollection#write` can call `ScioIO#write(this)`.

**Comment by nevillelyh** [comment]
I'm quite happy with the progress so far, maybe `object TextIO` can be merged into `class TextIO` since most of its members are private. Otherwise it looks fine.

@jto WDYT?

**Comment by jto** [comment]
Yes definitely. Plus most methods take a path anyway so it makes sense to have them in TextIO.

The work on this branch is the base for more refactoring.  I'm currently working on removing the dependency on scio-bigquery from scio-core based on this work. The sooner we merge this to master, the better.

**Comment by nevillelyh** [comment]
How do you see a smooth/gradual way of merging this to master?
I kinda don't want to introduce a new API until every IO is covered and old ones are replaced, i.e. after renaming NIO API to legacy ones to minimize breaking change.

**Comment by nevillelyh** [comment]
I mean we can merge to master, but keep the new methods/classes private, and replace legacy ones once everything's ready?

**Comment by jto** [comment]
Yeah something like that. I think we could also change the implementation of the old methods to use the new IOs under the hood.

**Comment by nevillelyh** [comment]
Exactly what I have in mind!

**Comment by jto** [comment]
What's left to do on this ticket ?
I think most of the task are done in [nio](https://github.com/spotify/scio/tree/nio)

- [x]   migrate all IOs to new ScioIO
- [x]   remove all old test IOs and rename new ScioIOs to old names
- [x]   verify that all tests and examples are backwards compatible
- [ ]   verify that requiredNotClosed usage is localized and consistent

Anything else to be done @nevillelyh ?

**Comment by nevillelyh** [comment]
This is getting too long and most of the coding work is done. Created #1179 for actual migration.
