### ISSUE TITLE
BigQuerySelect gets an NPE

### ISSUE THREAD

**Issue by sfines** [spotify/scio#586]
When Using scio 0.3.0 I get an NPE attempting to run a query using bigQuerySelect- 

```
Caused by: java.lang.NullPointerException
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$BigQueryTableSource.getEstimatedSizeBytes(BigQueryIO.java:1002)
	at org.apache.beam.runners.direct.BoundedReadEvaluatorFactory$InputProvider.getInitialInputs(BoundedReadEvaluatorFactory.java:196)
	at org.apache.beam.runners.direct.RootProviderRegistry.getInitialInputs(RootProviderRegistry.java:65)
```

When I attempt to step through the code to see the error it is attempting to find this table: 

0 = {DataMap$Entry@5223} "datasetId" -> "scio_bigquery_staging_eu"
1 = {DataMap$Entry@5224} "projectId" -> "dexcomeupaas"
2 = {DataMap$Entry@5225} "tableId" -> "scio_query_20170501171356_387305368"

Which I don't create; I assume that the SCIO code auto creates (or expects that it was created)

**Comment by nevillelyh** [comment]
`BigQueryClient` should create the table when you do `sc.close()`. Did you see any log messages? It's also possible you have a cached table reference in `.bigquery/` but the table expired (default 24 hours).

**Comment by sfines** [comment]
we don't see any log messages and there's nothing in .bigquery on my machine.

We don't call sc.close() we just call sc.pipeline.run() and let her run....

**Comment by nevillelyh** [comment]
You should call `sc.close()` instead. That method wraps `pipeline.run()` but also does pre-processing like kicking off BigQuery queries. Can you give it a try?

**Comment by sfines** [comment]
That did the trick. Thanks!
