### ISSUE TITLE
Unit test for saveAsPubsubWithAttributes

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#590]
https://github.com/spotify/scio/pull/546#issuecomment-299128082

Will be great to add unit tests as examples for `ScioContext#pubsub*WithAttributes` and `SCollection#saveAsPubsubWithAttributes`

**Comment by dgouyette** [comment]
I will provide it ASAP

**Comment by nevillelyh** [comment]
Awesome thanks!

**Comment by dgouyette** [comment]
I don't know if that enought. But i didn't see other "unit tests" on PubSub*

**Comment by nevillelyh** [comment]
These are fixed in the beam-2.0 branch. Closing for now.
