### ISSUE TITLE
how to create dataflow templates

### ISSUE THREAD

**Issue by chandu0101** [spotify/scio#605]
dataflow allows to run temples using `DataflowTemplateRunner` how can i create templates for my jobs ?

**Comment by ravwojdyla** [comment]
Hi @chandu0101 . Scio is based on beam. To create template use `DataflowRunner` runner and specify `templateLocation` (eg.: `--templateLocation=<location>`) in options (either command line or pragmatically)

**Comment by mahmoudhanafy** [comment]
How to send run time parameters as mentioned [here](https://cloud.google.com/dataflow/docs/templates/creating-templates#modifying-code-to-use-runtime-parameters).

I want to send the table name I'm reading as runtime parameter, I'm using method: `sc.bigtable` which require the table name
When getting the table name at deploying template time I get this exception:
```
Exception in thread "main" java.lang.RuntimeException: Not called from a runtime context.
```

**Comment by ravwojdyla** [comment]
Afaiu Beam's Bigtable IO does not support `ValueProvider` for options.

**Comment by bbhoss** [comment]
Could someone share how to do this with Scala including adding custom options? It seems like I have to use Java for this but I hope I'm wrong.
