### ISSUE TITLE
Bigtable Example Issues

### ISSUE THREAD

**Issue by sfines** [spotify/scio#608]
SCIO'ers - I'm running into trouble trying to independently replicate the Bigtable example. 
Namely I get compile errors on Mutations.newSetCell and sc.ensureTables. 

I have imported: 
com.spotify.scio._
com.spotify.scio.bigtable._
com.google.v2.{Mutation, Row}

My attempts to search the libraries for the existence of the Mutations class and the ensureTables object do not bear fruit.. any suggestions on what I'm doing wrong? 

Thanks, 
SF

**Comment by andrewsmartin** [comment]
What version of Scio are you using? The `Mutations` object is here: https://github.com/spotify/scio/blob/master/scio-bigtable/src/main/scala/com/spotify/scio/bigtable/Mutations.scala

`ensureTables` is a method from the `BigtableAdmin` object, see here: https://github.com/spotify/scio/blob/master/scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala

**Comment by andrewsmartin** [comment]
Also `ensureTables` was just recently added and hasn't made it into a release yet, so you'll need a snapshot version if you want to use it.

**Comment by sfines** [comment]
I'm using 0.3.0, with GSDK/Beam 2.0

**Comment by andrewsmartin** [comment]
Does using a snapshot build fix this? 0.3.1-SNAPSHOT

**Comment by andrewsmartin** [comment]
And if not what's the exact compiler error? Missing class or something else? An error message would help.

**Comment by sfines** [comment]
@andrewsmartin I got it. It appears that my SBT cache was hosed; dropping it and refetching fixed the error.

**Comment by andrewsmartin** [comment]
Great!
