### ISSUE TITLE
Compile Error trying to follow the example in ShaplessDatastoreExample

### ISSUE THREAD

**Issue by sfines** [spotify/scio#613]
I'm trying to implement a data store pipeline following the example ShaplessDatastoreExample- 

It doesn't compile- On scala 2.11 I get a 
```
object com.google.appengine.api.datastore.DatastoreAttributes.DatastoreType is not a value
[error]   val rawDataPostType = DatastoreType[RawDataPost]
[error]
```

Is the example more focused on 2.12 and if so, is there an appropriate 2.11 version?

**Comment by nevillelyh** [comment]
Imported the wrong `DatastoreType`?
Should be `import shapeless.datatype.datastore._`.

**Comment by sfines** [comment]
import shapeless._
import shapeless.datatype.datastore._
