### ISSUE TITLE
Support run-time parameters as input for BigQuery, BigTable, ... names

### ISSUE THREAD

**Issue by mahmoudhanafy** [spotify/scio#637]
It would be good to support run-time parameters as input for table names like BigTable, BigQuery, ...
for ex: 
`BigQueryIO` has method `BigQueryIO.Write.to(ValueProvider<String> tableSpec)`.

**Comment by ravwojdyla** [comment]
Afaiu Beam's Bigtable IO does not support `ValueProvider` for options. Please report that issue to Beam. As for other IOs - we should see if that is doable, if not users should just use Beam IOs for templates.

**Comment by nevillelyh** [comment]
Let's keep the API simple for now and revisit when we're on Beam 2.x. Users can always fallback to custom IO.

**Comment by robertotena** [comment]
Hi, I got this same issue and I wanted to ask if there is an easy way to create a custom IO for Bigtable to accept runtime parameters. I cannot tell very well the difference between creating a custom IO and adding the functionality in Beam.
Thanks

**Comment by nevillelyh** [comment]
The latest BigtableIO supports `ValueProvider` for some options now.
https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

You should be able to use them as is with the custom IO wiring as documented here:
https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-beams-java-api-in-scio
