### ISSUE TITLE
NPE in BigQueryType.fromQuery input for null repeated fields

### ISSUE THREAD

**Issue by tchagnon** [spotify/scio#643]
When using a @BigQueryType.fromQuery generated class to execute a query and parse rows, I'm getting a NullPointerException.  Here's the exception:

```
[info]   Cause: java.lang.NullPointerException:
[info]   at scala.collection.convert.Wrappers$JListWrapper.iterator(Wrappers.scala:88)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info]   at com.spotify.lineup.ingest.GenerateNotifications$TrackEntity$$anonfun$fromTableRow$1$$anonfun$apply$1.apply(GenerateNotifications.scala:16)
[info]   at com.spotify.lineup.ingest.GenerateNotifications$TrackEntity$$anonfun$fromTableRow$1$$anonfun$apply$1.apply(GenerateNotifications.scala:16)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:893)
```

I think I've tracked it down to one of the fields being a REPEATED RECORD in BQ, but the value in the TableRow result being null instead of empty list.  If I set that field to `Seq()` in unit test input, the test passes.  Will post more detail in snippets.

**Comment by tchagnon** [comment]
Internal gist of job snippets: https://ghe.spotify.net/gist/tchagnon/f2a64af7b4a57ac1cf7f7649fc2983dd

I'm sure this won't run, but it's the relevant parts.  I'll write a unit test in scio to try to repro if I get time.

**Comment by ravwojdyla** [comment]
@tchagnon Thanks. How are you specifying the table in the args (could you share an example)? I suspect that the dry run is executed for standard syntax, while the query itself with legacy. Could you try to enforce the syntax with comment `#standardSQL` at the very beginning of the query?

**Comment by ravwojdyla** [comment]
@tchagnon sorry - i actually misunderstood/jump-ahead a bit, so this is not for the query result, this is only for JobTest correct? In that case it actually makes sense, we had similar issue open for legacy syntax (#371), but standard syntax should give us back empty list not null the way, thus it makes sense that you need to do the same in test.

**Comment by ravwojdyla** [comment]
This works fine one a query, the code in the link has a "bug" where it was reading whole table not a query. We still might want to make it easier to specify test data by treating nulls in TableRow as empty seq, that obviously might open some other issues - anyway let's talk about it in separate issue.
