### ISSUE TITLE
Provide sbt skeleton/cookie for ppl to bootstrap scio project

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#662]
For ppl to try out scio they can use scio-repl, which should work out of the box. Eventually ppl need to create their own sbt project, there is a couple of things to remember there tho, like:
 * enable paradise plugin
 * testing libraries
 * preferable the same version of scala as scio

We could probably use the sbt `new` bootstrap functionality too, and host skeleton/cookie.

**Comment by regadas** [comment]
+1 on having it as `giter8` template

**Comment by regadas** [comment]
@ravwojdyla something like this? https://github.com/regadas/scio-seed.g8 still very simple

**Comment by ravwojdyla** [comment]
@regadas cool - looks like a good start, let me move it to spotify repo.

**Comment by ravwojdyla** [comment]
Now available at https://github.com/spotify/scio-template.g8
