### ISSUE TITLE
Consider allow passing config as file

### ISSUE THREAD

**Issue by bcleenders** [spotify/scio#669]
Instead of running 
`sbt runMain com.foo.Bar --numWorkers=100 --diskType=(I dont even remember) --region=... --project=... --autoscaling_algorithm=...` 
etc., it might be nice to have a config file that can be loaded instead (e.g. `sbt runMain com.foo.Bar --conf=~/scio.conf`)

Not sure how big of an issue it would be, since I can do `sbt runMain com.foo.Bar $(cat ~/scio.txt)` too.

**Comment by nevillelyh** [comment]
We can add some helper methods to ser/de `PipelineOptions` <-> JSON files. There isn't a standard for `Args` though, any opinion on this, also JSON or maybe YAML?
