### ISSUE TITLE
groupByKey doesn't work when using Pub/Sub as collection source.

### ISSUE THREAD

**Issue by amogh-git09** [spotify/scio#687]
I changed source of WindowsWordCount example program from text file to cloud Pub/Sub as shown below. I published shakespeare file's data to Pub/Sub which did get fetched properly but none of the transformations after `.groupByKey` seem to work.
```
    sc.pubsubSubscription[String](psSubscription)
      .withFixedWindows(windowSize) // apply windowing logic
      .flatMap(_.split("[^a-zA-Z']+").filter(_.nonEmpty))
      .countByValue
      .withWindow[IntervalWindow]
      .swap
      .groupByKey
      .map {
        s =>
          println("\n\n\n\n\n\n\n This never prints \n\n\n\n\n")
          println(s)
      }
```

**Comment by ravwojdyla** [comment]
@amogh-git09 this should not be the case, we have a number of job that use Pub/Sub and GBK. Could you make sure that there are in fact element going in the GBK transformation, and check the system lag, also try to reduce your example to a [minimal example](https://stackoverflow.com/help/mcve). It might be that the windows are just no closed after GBK.

**Comment by ravwojdyla** [comment]
Closing for now - please reopen with minimal example if problem is still there.
