### ISSUE TITLE
Full stack trace of failures on BigTable operation are never reported

### ISSUE THREAD

**Issue by sisidra** [spotify/scio#704]
See https://github.com/spotify/scio/blob/90d9af1c862eaaea65f369064547041f52337986/scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/PatchedBigtableIO.java#L618
The examples of cause message is reported, but the full stacktrace is not.
That hides possibly valuable debug information.

**Comment by nevillelyh** [comment]
Thanks, would you mind creating a PR?

**Comment by sisidra** [comment]
@nevillelyh do you think reporting stacktrace for each of 10 samples is good idea, or just one?

**Comment by sisidra** [comment]
Or just rethrow with first cause: https://github.com/spotify/scio/blob/90d9af1c862eaaea65f369064547041f52337986/scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/PatchedBigtableIO.java#L641 ?

**Comment by nevillelyh** [comment]
One should be enough. `checkForFailures` is called per element so there's plenty of chance to surface that. How about a `LOG.debug` of the first `exc`?

**Comment by sisidra** [comment]
Here is the PR: https://github.com/spotify/scio/pull/705

**Comment by sisidra** [comment]
I added same first exceptions to suppressed list and let default logging to take care of nicely formatting message (on sidenote, multiline message for that IO exception was interfering with stacktrace anyway - mixed in between lines...).
