### ISSUE TITLE
Extra Beam Sources or Sinks

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#706]
- [ ] Elasticsearch source
- [ ] Cassandra source
- [ ] HadoopOutputFormat sink (Beam really)

**Comment by kubum** [comment]
Hi @nevillelyh 

I would like to know more about Cassandra source. How do you see it is working? Any potential problems or ideas?

Thank you!

**Comment by nevillelyh** [comment]
Don't have any good idea for this. The sink we have is optimized for throughput in batch mode and doesn't work so well in streaming. It uses `BulkWriter` under the hood which exposes some Cassandra internals and there isn't an equivalent `BulkReader`.

Upstream has [CassandraIO](https://github.com/apache/beam/tree/master/sdks/java/io/cassandra/src/main/java/org/apache/beam/sdk/io/cassandra) but it has different API (annotated POJO which may not work in Scala) and doesn't seem to be particularly optimized.
We don't read from Cassandra often so this hasn't been a priority.

**Comment by regadas** [comment]
Moved to https://github.com/spotify/scio-contrib/issues/7
