### ISSUE TITLE
Allow custom prefix and shard naming template for output files

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#722]
Currently files output from `saveAsTextFile` etc use the pattern `part-XXXXX-of-YYYYY`. The underlying SDK has methods to customize this pattern and we should expose them (perhaps via default args like we do now with suffix).

**Comment by nevillelyh** [comment]
What's the use case?

**Comment by andrewsmartin** [comment]
Just convenience for preparing files read by something downstream that expects a certain format. But this is also handled easily by a quick post-processing step or using `.saveAsCustomOutput`, so we can leave this alone for now and revisit if a significant need arises.
