### ISSUE TITLE
Throw exception if the Project Id isn't valid passed to BigQueryClient.apply

### ISSUE THREAD

**Issue by Tomczik76** [spotify/scio#726]
I wasted some time today because I passed an empty string to the BigQueryClient.apply method. An exception was only thrown when I call BigQueryClient.query and the exception was a NullPointerException. It would be a better developer experience if BigQueryClient.apply threw an exception if the project id wasn't valid.

**Comment by nevillelyh** [comment]
Don't think we can check if a project ID exists without hitting the service. Do you think checking for null & empty string is enough? If so feel free to submit a PR. A `require` should be enough.

**Comment by Tomczik76** [comment]
In that case, it would be better if a more useful exception was thrown when the request was made to GCP. I believe the Google BigQuery client will throw an exception for a bad project id. I'd be happy to work on that if it is the desired effect.

**Comment by nevillelyh** [comment]
Sure that'd be great. We can do both, `require` in the constructor and validation when requests are made?

**Comment by Tomczik76** [comment]
Sounds good, it will be a good introduction to the code base for me.

**Comment by nevillelyh** [comment]
@Tomczik76 did you get a chance to look at this?

**Comment by Tomczik76** [comment]
Hey Neville, I haven't I've been too busy. I'll try to allocate some time next week to get to it.

**Comment by anilmuppalla** [comment]
@Tomczik76 are you working on this?
