### ISSUE TITLE
Support toTableReference in BigQueryIO

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#73]

**Comment by nevillelyh** [comment]
https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/io/BigQueryIO.Write#toTableReference-com.google.cloud.dataflow.sdk.transforms.SerializableFunction-

This is the API I'm referring to, which allows saving a single `PCollection` into multiple BigQuery tables with a `BoundedWindow => TableReference` function.

**Comment by nevillelyh** [comment]
Not sure if this should be part of Scio though, since it breaks the `JobTest` semantics. Plus the user can do `SCollection#saveAsCustomOutput` now.

**Comment by andrewsmartin** [comment]
Can we close this?

**Comment by nevillelyh** [comment]
Let's leave it open for a bit longer. I might think about a way to do this properly.

**Comment by nevillelyh** [comment]
@samschlegel also found this: https://github.com/apache/beam/commit/35db7457bf8c95ac693c2c36c5f8909afc3f16ab

We can maybe add these as methods on a implicit class and to skip `JobTest` support.
