### ISSUE TITLE
Try AvroParquet in/out again

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#762]
Using [HadoopInputFormatIO](https://github.com/apache/beam/blob/master/sdks/java/io/hadoop/input-format/src/main/java/org/apache/beam/sdk/io/hadoop/inputformat/HadoopInputFormatIO.java), [AvroParquet](https://github.com/apache/parquet-mr/tree/master/parquet-avro/src/main/java/org/apache/parquet/avro) and maybe my Avro macros https://github.com/nevillelyh/parquet-avro-extra

**Comment by kanterov** [comment]
On Github there are few implementations of Parquet without Hadoop dependency, one is using Apache Arrow, other is from scratch. I think it worths to look into them too.

**Comment by richwhitjr** [comment]
Arrow could be worth a shot. Last I looked it only supported a subset of parquet though. Does open up some interesting possibilities though with calling python from Scio similar to what Spark is doing by sharing memory space.

**Comment by nevillelyh** [comment]
Yeah it'd be nice to have native Parquet IO plus non-Avro-based predicate & projection macros but that's a lot more work :)
#771 is solving the more immediate need of reading legacy parquet files, preferably with the same Avro projection/predicate logic.
