### ISSUE TITLE
Remove DirectRunner dependency from scio-core

### ISSUE THREAD

**Issue by Igosuki** [spotify/scio#777]
Currently, the DirectRunner class is pulled in ScioContext's <init> path through here : 
https://github.com/spotify/scio/blob/613b4a7264f89d0567c418f4c22436182a3098bd/scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala#L52 

This makes it impossible to evict beam-runners-direct-java and all its dependencies while using scio 
to make the fat archive lighter, I don't think pulling this class here is necessary in the first place (but of course I might be wrong).

Can I work on a PR to use other means to guess if the current runner is local or remote ? 
Additionnally, some runners like flink have a local running mode where the url is unspecified and the host is '[local]'.

**Comment by nevillelyh** [comment]
It's a bit complicated. We use `DirectRunner` for testing, e.g. `JobTest` and running locally. It'll be nice to decouple all runners of course :)

Just curious
- What other problems does the direct runner dependency cause, apart from fat jar?
- How would you detect local vs remote without checking for `DirectRunner`?

**Comment by nevillelyh** [comment]
Related #779

**Comment by Igosuki** [comment]
Hey Neville, 

I don't have any problems apart from the fatter jar, I'm running Scio just fine with Flink. There may be potential dependency conflicts between the Flink runtime and Beam dependencies, like with Jackson databind for instance (Beam uses 2.8.8, Flink uses 2.7.4), I resolve these by building my own Flink distro against Beams updated dependencies (like people do with Spark).

As for checking local vs remote, I don't see a solution that is as easy to implement right now. I would probably get the array of public member classes (java.lang.Class#getClasses) and check their canonical names against runners. Then based on that I would implement special cases like spark or flink's [local] in the same method (but this can be done as another feature).
For Dataflow metrics I don't have an idea yet but I can look into it.

**Comment by nevillelyh** [comment]
Great to hear that you got Flink working. Would love to hear more about it if you get a chance :)

We plan to promote `beam-2.0` branch to `master` soon and release 0.4.0. We should make the runner changes in that branch only. I'd also like to review local vs remote logic and maybe eliminate some if possible.

Meanwhile we can look into what you suggested plus removing `DataflowRunner` dep (#779). Feel free to play around with the proposed idea and share WIP.
