### ISSUE TITLE
LATEST should only support date partitioned tables

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#780]
Assume, there is partitioned table: `foo.bar.table`, with 3 days:
* `foo.bar.table_20170426`
* `foo.bar.table_20170427`
* `foo.bar.table_20170428`
and a view `foo.bar.table_foo`. Current implementation of `LATEST` will pick `foo.bar.table_foo` as a max of partitions available for `foo.bar.table_`.  Maybe we should just filter numeric partitions?

**Comment by nevillelyh** [comment]
How would you handle different date/time formats, e.g. `2017-01-01`, `20170101H01`? It might still contain letters?

**Comment by ravwojdyla** [comment]
@nevillelyh https://cloud.google.com/bigquery/docs/creating-partitioned-tables
