### ISSUE TITLE
Support tuning of side input cache size on workers

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#789]
Side input performance depends heavily on the ability to cache in worker memory. The size of the cache can be tuned via `--workerCacheMb` which comes from `DataflowWorkerHarnessOptions`. Currently though this will be ignored by Scio (unless forced using `ScioContext.parseArguments[DataflowWorkerHarnessOptions]`). We should add this option class to the registrar and support it out of the box.

**Comment by nevillelyh** [comment]
The following seems to do the trick
```scala
PipelineOptionsFactory.register(classOf[DataflowWorkerHarnessOptions])
val (sc, args) = ContextAndArgs(cmdlineArgs)
```

**Comment by nevillelyh** [comment]
Added an FAQ item https://github.com/spotify/scio/wiki/FAQ#how-do-i-improve-side-input-performance
