### ISSUE TITLE
annoy/sparkey distributed version

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#793]
Would be interesting to investigate distributed/partitioned versions of building/querying sparkey/annoy sideinputs.

For annoy to support large indexes, instead of grouping to `()` we might be able to build N annoy indexes (by grouping into `1..N`), and have wrapper atop of N annoy indexes that basically query all indexes (given that afair results come back sorted), we would basically just do a final stage of merge sort and return (trimmed) result back to the user.

The same idea for sparkey, but we might need to investigate if we need an extra bloom filter for each partition of sparkey to check membership before query (might be an overkill).

This way it we would parallelize building indexes (+spread out shuffle), queries/download could be concurrent. This requires benchmarking original versions and distributed/partitioned versions.

**Comment by ravwojdyla** [comment]
Regarding Sparkey part, something to look into: https://github.com/stripe/sequins

**Comment by nevillelyh** [comment]
Feels out of scope, can close?

**Comment by ravwojdyla** [comment]
Would vote to keep open, it's an interesting problem especially since there were reports of some indexes builds taking very long time, also this isn't too hard to implement.

**Comment by jto** [comment]
Sparkey sharding was implemented in #2336

**Comment by nevillelyh** [comment]
So sparkey support is done. I'm not sure about annoy since the partition logic can affect _recall_ of top N and it's hard to get right. Closing for now.
