### ISSUE TITLE
Verify splittable DoFn works and add wrapper

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#796]
BEAM-1377 is in 2.1.0

**Comment by torbjornvatn** [comment]
Wouldn't this be a neat feature to get into SCIO now that it's on Beam 2.2.0?

**Comment by nevillelyh** [comment]
Yes it's in our radar, just haven't got around to look at it yet. If you have any experience/input we'd love to hear :)

**Comment by nevillelyh** [comment]
Looked a little closer today.
Example: https://github.com/apache/beam/blob/master/sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java#L84
Avro: https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroIO.java#L312

Seems pretty straightforward to use this as is in something like
```scala
sc.textFile("uris.txt").applyTransform(TextIO.readAll())...
```

We have some users trying it out internally and will update this later.

**Comment by nevillelyh** [comment]
Verified that the following code works:
```scala
package com.spotify.scio.examples.extra

import com.spotify.scio._
import com.spotify.scio.examples.common.ExampleData
import org.apache.beam.sdk.io.{FileSystems, TextIO}

import scala.collection.JavaConverters._

object SDF {

  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    FileSystems.setDefaultPipelineOptions(sc.options)

    val uris = FileSystems
      .`match`(args.getOrElse("input", ExampleData.SHAKESPEARE_ALL))
      .metadata().asScala.map(_.resourceId().toString)

    val f = sc.parallelize(uris)
      .applyTransform(TextIO.readAll())
      .flatMap(_.split("\\W+").filter(_.nonEmpty).map(_.toLowerCase))
      .countByValue
      .materialize

    sc.close()
    f.waitForResult().value.toList.sortBy(-_._2).take(10).foreach(println)
  }
}
```

**Comment by jto** [comment]
We also need to support test in JobTest. (specifically `getTestInput`).
Right now it's easy enough to use `SplittableDoFn` but testing is a pain.

**Comment by nevillelyh** [comment]
We'll probably need the following on `SCollection[String]`:

- `readAll[U](read: PCollection[String] => PCollection[U])` where `read` maybe `TextIO.ReadAll`
- `readAll[U](read: PCollection[String] => PCollection[FileIO.ReadableFile])` where `read` maybe `FileIO.MatchAll` + `FileIO.ReadMatches`

And on `SCollection[FileIO.ReadableFile]`:
- `readAll[U](read: PCollection[ReadableFile] => PCollection[U])` where `read` maybe `TextIO.ReadFiles`

After that we can plug in some sort of test stubbing.
