### ISSUE TITLE
Options for  TableRow typed getters ?

### ISSUE THREAD

**Issue by francescoperera** [spotify/scio#810]
I am new to Scio but I noticed that the typed getters for TableRow either do the type conversion or fall into a default value( which changes between types, string has a `null` as default while `boolean` has false. From my experience, this has been an issue when tables have nullable columns/fields.

I looked at the example and noticed that you can get around this by doing an `if` check 
 
i.e 
```
val colVal = row.getString("colA")
if ( colVal != null )  doSomething else None
```
which is fine but this cannot be generalized across types ( as some types have actual default values and some have null)

I was wondering whether Options for typed getters has been discussed or is possibly getting implemented ? ( In my opinion it will make it easier to interact with tables and parses rows that have nullable fields)

**Comment by nevillelyh** [comment]
Have you looked at the type safe BigQuery API? It's the recommended way for working with BQ data.
https://github.com/spotify/scio/wiki/Type-Safe-BigQuery

**Comment by francescoperera** [comment]
@nevillelyh  thanks for the reply. Yep I tried it (Type-Safe-BigQuery is one of favorite features of Scio), I just wanted  to see whether I can do the same with the traditional BQ API.

( In my opinion and feel free to correct me) one of the drawbacks of the Type-Safe-BigQuery is that based on the nature of the macro you have to define the query ( or table ) ahead of time( at compile time) and then if you want you can update the query( at run time)  with a new table or a specific partition. However I cannot dynamically change the number of columns that I want to read from the table.

i.e based on the the input( the table columns)  from the job, in one run I am doing a select on 3 columns from TableA, but then the next run my input might have a different number of columns.
This might be easier to handle with the traditional BQ API because I can defined the query at runtime based on the input arguments

**Comment by nevillelyh** [comment]
We can probably add something like `getBooleanOpt(name: String): Option[Boolean]`. Wanna submit a PR can we can discuss from there?

**Comment by ravwojdyla** [comment]
@francescoperera this might be slightly of context, but technically, to some extend you can dynamically change the number of columns you read; as long as you follow certain rules around it (no new columns, standard-sql and maybe some other stuff), for example this should work:

```
@BigQueryType.fromQuery("SELECT %s FROM `<table>`", "id, name") class TT
bq.getTypedRows[TT](TT.query.format("name")) // here we only query for column `name`
```

so in this case the compile time schema is a superset of possible runtime options. Not sure if this is helpful for you tho.

**Comment by francescoperera** [comment]
@nevillelyh  yep sure PR sounds good. Are there specific guidelines for PR that you require ( other than branch + open PR)  ?

**Comment by nevillelyh** [comment]
Great. Nothing in particular, but worth checking out the style guide:
https://github.com/spotify/scio/wiki/Style-Guide

**Comment by francescoperera** [comment]
@ravwojdyla  thanks for the tip will keep it in mind, but I am more generally looking for an abstraction that allows me to read or write BQ given an unspecified number of columns, table , partitions.
