### ISSUE TITLE
Pretty printing BQ schema does not show nullable fields within repeated record as option type

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#82]
If we have nullable fields within a repeated record, when pretty printing the schema they are not displayed as option types.

Example: 

Field | Type | Mode 
----- | ------------- | ---------------
strlist | RECORD | REPEATED
strlist.str | STRING | NULLABLE

REPL session:

```
scio> @BigQueryType.fromSchema(
     |     """
     |       |{
     |       |   "fields": [
     |       |     {"mode": "REPEATED", "name": "strlist", "type": "RECORD", "fields": [
     |       |         {"mode": "NULLABLE", "name": "str", "type": "STRING"}
     |       |     ]}
     |       |   ]
     |       |}
     |     """.stripMargin
     |   )
     |   class Row
defined class Row
defined object Row
defined class Strlist$

scio> Row.toPrettyString(2)
res1: String =
(
  strlist: List[(
    str: String)])

scio>
```

The expected output:

```
scio> Row.toPrettyString(2)
res1: String =
(
  strlist: List[(
    str: Option[String])])

scio>
```

**Comment by nevillelyh** [comment]
I believe this was fixed in the latest master. Can you try rebuild a REPL?
```
res1: String =
(
  strlist: List[(
    str: Option[String])])
```

**Comment by andrewsmartin** [comment]
Yep, confirm that it works in latest. I was using release instead. Closing

**Comment by nevillelyh** [comment]
For reference: https://github.com/spotify/scio/commit/22308dd5dd85d613ed6f891e06d31ade0c713a02
