### ISSUE TITLE
Unroll some inefficient flatMap we use internally

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#820]
We sometimes do something like this:

```scala
val lhs: SCollection[String] = //...
val rhs: SCollection[String] = //...

val side = rhs.asListSideInput
lhs.withSideInputs(side)
  .flatMap { (x, s) =>
    s(side).map((x, _))
  }
```

This could be inefficient if `s(side): List[String]` is large since `.map` is eager. We should unroll this into a `DoFn`, loop over the side directly and call `ctx.output()`.

**Comment by nevillelyh** [comment]
WIP https://github.com/spotify/scio/tree/neville/flatmap

**Comment by kanterov** [comment]
Does it make sense for Scala 2.12? AFAIK there is some unrolling and inlining

**Comment by nevillelyh** [comment]
It's not the most for vs while cases but the case of flatMap, join etc, where we have intermediate collections that are emitted to the underlying `ProcessContext#output()`. Skipping the intermediate ones might save memory and speed things up.

**Comment by nevillelyh** [comment]
Closing for now as it doesn't offer much improvement.
