### ISSUE TITLE
Add extract/load to BigQueryClient

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#840]
This could be useful as a pre/post step to a pipeline. Say I want to write data as avro/json to GCS with schema computed at runtime, but I also want my data in BQ: I could have a pipeline that writes avro/json to GCS, and when the pipeline is done just launch BQ load job(s) myself (knowing the URI, schema etc).

**Comment by guidj** [comment]
How would you run tests with this?
Seems I need permissions to run the existing integration tests for scio-bigquery

**Comment by guidj** [comment]
Looking at the code, it seems that some functionality, like `waitForJob` and `logJobStats` is tied to Query type jobs. I'm wondering about the best way to structure BigQueryClient to accomodate other job types.

Here's what I have in mind:

```
sealed trait BQJob {
   //common job fields, like JobReference/Id
}

trait/case class QueryJob extends BQJob
trait/case class LoadJob extends BQJob
trait/case class ExtractJob extends BQJob

//Then, for the common methods, like `waitForJob`

def waitForJobs(jobs: BQJob*) {
   //wait for any type of job
}

def getTable(...)

//where specific functionality is required, use pattern matching on different types
def jobStats(job: BQJob) {
  job match {
    case QueryJob:
      //print query, bytes processed
      //...
  }

  //The functionality specific to any type of job could be encapsulated in an inner object:
  object load {
       def csv(paramsForCsv...)
       def avro(paramsForAvro...)
   }

   object query {
     //....
   }
}

```

Encapsulating functionality would break APIs, so maybe that can be postponed or just done for the new job types

Thoughts?

**Comment by nevillelyh** [comment]
It doesn't have to be integrated into the query job scaffolding right? If we need this for convenience only, it could just be a pair of blocking methods in `BigQueryClient`.

On the other hand, IIRC the BQ job logic is never exposed, so breaking change may be fine?

**Comment by guidj** [comment]
True. I was thinking about `def waitForJobs(jobs: QueryJob*)`, as it's public. But `QueryJob` isn't, so you're right, it's not really exposed

The Job types would be to share methods like waitForJob or logStats, instead of having that implemented by each Job type because most of the logic would be the same (ping the API for job status, sleep). 

I updated the previous comment, the logic in `object query` to clarify what I meant about breaking changes. Instead of calling `runQuery`, `loadCsv` you call `query.run (sync)`, `query.submit (async)`. But as we don't currently expose that logic, maybe best to stick `loadCsv`

**Comment by nevillelyh** [comment]
Make sense. I'm fine with breaking it since it's not supposed to be used by end users.
Wanna draft a PR and we go from there?

**Comment by guidj** [comment]
Alright

**Comment by labianchin** [comment]
Would this provide a way to load avro files into BQ? That would be a very nice replacement of [luigi BigQueryLoadAvro](https://github.com/spotify/luigi/blob/master/luigi/contrib/bigquery_avro.py).

**Comment by guidj** [comment]
Shall we close this based on #1060?
