### ISSUE TITLE
Support additional key-types in annoy API

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#843]
This would be nice so that users don't have to provide their own bijection `T <=> Int` which might not always be possible (imperfect string hashing, Int overflow etc). Annoy4s supports these additional types as keys:

- Long
- String
- UUID

Maybe we can introduce a sealed typeclass `AnnoyKey[T]` and provide instances for the supported key types, so that the implicit class to build annoy can accept `[T: AnnoyKey]`. This would be nice to have for a pipeline I'm working on internally. I'll look into this either today or tomorrow.

**Comment by andrewsmartin** [comment]
Actually just realized this might be trickier since we're using `annoy-java` for reading, which only supports `Int`. Would there be any drawbacks to using annoy4s to read as well? @fallonchen

**Comment by andrewsmartin** [comment]
Looking more closely at annoy4s its implementation for the extra keys is just a simple map from `T` to an `Int` index anyway to use the underlying lib so on second thought the `Int` overflow thing isn't solved by having this. But still I think it's convenient to have and wouldn't introduce much API complexity.

**Comment by nevillelyh** [comment]
There's no easy way. Annoy uses int ID (`[0, n)`) for tracking vectors and users will have to manage String->Int mapping manually with Sparkey or something. And we need 2 indices for bidirectional mapping.

**Comment by andrewsmartin** [comment]
Yeah I'm actually doing something similar internally now, using Sparkey to manage the mapping and copying those up to GCS along with the annoy index. I'll keep this open for now since I might have time this week to look into it, but if I don't get around to it by next week we can close it.

**Comment by nevillelyh** [comment]
Sure. It could probably be some higher level API on top of `extra.annoy` and `extra.sparkey` that simplifies the process of managing 1 annoy index + 2 sparkey indicies right?

**Comment by andrewsmartin** [comment]
Sure, makes sense to do it that way. `annoy-extra-extra`? jk - but yeah will try to have a PR up by EOD tomorrow.

**Comment by nevillelyh** [comment]
LOL `super-extra-annoy-gravy-on-top`

**Comment by fallonchen** [comment]
@andrewsmartin the downside to using annoy4s as a reader is that we then have to make freeing memory for the index the responsibility of the user; we know when to delete the index during writes, but don't know when the user will be done with it during reads

**Comment by andrewsmartin** [comment]
@fallonchen gotcha. Keeping `annoy-java` on the read side should work if we go with this sparkey approach.

**Comment by andrewsmartin** [comment]
The internal `annoy-jni` lib uses the sparkey approach to support string keys - when that is public we could look into using that instead (String keys are the most pressing use case internally, other types can be added later if need be). 

@yonromai FYI

**Comment by yonromai** [comment]
The code is here: https://github.com/spotify/annoy-jni
For now it's still in private mode, it's currently being reviewed by FOSS. Should last too long.
If you wanna play with it, the jar is published in mvn central there: http://repo1.maven.org/maven2/com/spotify/annoy-jni

**Comment by andrewsmartin** [comment]
@yonromai what's the state of annoy-jni? Did it get a green light from FOSS to make public? Just curious because some people internally have expressed interest in using it through scio

**Comment by jbx** [comment]
poke @yonromai 🔼

**Comment by yonromai** [comment]
Light is almost green, hack days are just not quite enough for this kind of stuff
cc @jbx

**Comment by RustedBones** [comment]
Probably won't do as we'll focus on voyager: See https://github.com/spotify/scio/issues/4895
