### ISSUE TITLE
Counter assertions in JobTest

### ISSUE THREAD

**Issue by azymnis** [spotify/scio#846]
I'd like to be able to do something like:

```
JobTest[MyTestJob]
  .counter(customCounter)(_ should be > 10)
  .run()
```

Is this possible right now? Should I look into adding it?

**Comment by nevillelyh** [comment]
WIP branch: https://github.com/spotify/scio/tree/neville/metric

**Comment by azymnis** [comment]
@nevillelyh have you setup a PR with this yet? I can add comments if you want

**Comment by nevillelyh** [comment]
Will do later today

**Comment by nevillelyh** [comment]
@azymnis did you get a chance to look at PR #851?

**Comment by azymnis** [comment]
Looking now @nevillelyh
