### ISSUE TITLE
Support bigquery WRITE_APPEND

### ISSUE THREAD

**Issue by azymnis** [spotify/scio#849]
Is there a reason why `WRITE_APPEND` is not currently supported as a type of write disposition for BQ writes? We use that exclusively for our data processing needs so it would be great if it could be added. I can take this if nobody is working on it.

**Comment by ravwojdyla** [comment]
@azymnis `WRITE_APPEND` is supported. I assume you are talking about `Failure` in a `Tap`; that is because it doesn't make sense from `Tap`'s perspective, but the write will still happen.

**Comment by azymnis** [comment]
@ravwojdyla oh sorry, I just noticed that this is just for test context. I'll close this now
