### ISSUE TITLE
"No schema specified on job or table."  Error when writing an empty table using .saveAsTypedBigQuery

### ISSUE THREAD

**Issue by Tomczik76** [spotify/scio#884]
I repeatedly had a failed job with:
`"errors" : [ { "message" : "No schema specified on job or table.", "reason" : "invalid" } ]`

When writing using .saveAsTypedBigQuery on a @BigQueryType.toTable case class when writing an empty table.

`@BigQueryType.toTable case class Usage(an: String)`

Also, I didn't encounter a failure when using `.saveAsBigQuery` and giving a `TableSchema`

**Comment by nevillelyh** [comment]
@fallonchen IIRC you looked at a similar one?

**Comment by Tomczik76** [comment]
I think I might have made a mistake. I just ran into the same issue with saveAsBigQuery.

**Comment by Tomczik76** [comment]
I'm closing this issue because it seems to be a regression with Apache Beam.

**Comment by nevillelyh** [comment]
@Tomczik76 did you find a BEAM Jira ticket?

**Comment by Tomczik76** [comment]
https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/610

**Comment by nevillelyh** [comment]
Let's keep this open until it's resolved upstream and in Scio :)

**Comment by nevillelyh** [comment]
Upstream bug https://issues.apache.org/jira/browse/BEAM-3067

**Comment by Tomczik76** [comment]
Just to be clear BEAM-3067 states this happens with DirectRunner. I encountered this bug using the DataFlowRunner.

**Comment by andrewsmartin** [comment]
Verified that this has been resolved in Scio 0.4.6 / Beam 2.2.0.
