### ISSUE TITLE
Investigate and create example for streaming job with periodically updating side input

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#890]
The side input could be from a GCS file, a BQ query, etc. but updating at some interval. We might need to use a `GenerateSequence` transform + windowing to periodically refresh the content.

We should add this as some syntactic sugar and/or example.

Reference: https://github.com/spotify/scio/issues/865#issuecomment-333980759

**Comment by nevillelyh** [comment]
@regadas maybe something you'll be interested.

**Comment by nevillelyh** [comment]
Played a bit with the idea in https://github.com/spotify/scio/tree/neville/streaming but haven't got very far.

**Comment by regadas** [comment]
@nevillelyh yeah I can take it

**Comment by nevillelyh** [comment]
#895 #897 are somewhat related.

**Comment by andrisnoko** [comment]
@regadas are you still looking into this? If not, I can take it.

**Comment by regadas** [comment]
@andrisnoko yeah you can take it! completely forgot about this one 😛

**Comment by jbx** [comment]
@andrisnoko pokety poke. Still planning to look into this?

**Comment by bbhoss** [comment]
The example is very helpful, but it doesn't show pulling from an external data source like GCS/BQ. Is there some way to trigger fetching the input with this that I am missing? Seems like we'd need to use the BQ/GCS APIs directly in a map.

**Comment by gregorath** [comment]
@bbhoss did you manage to find how to do this with an external data source?
