### ISSUE TITLE
Expose Kryo#setRegistrationRequired

### ISSUE THREAD

**Issue by kanterov** [spotify/scio#896]
`Kryo#setRegistrationRequired` ensures that every used Kryo coder is pre-registered. It significantly reduces the amount of data shuffled by using class_id lookup instead of fully qualified class names. At the moment, it's possible to enable through custom `KryoRegistrar`:

```scala
@KryoRegistrar
class CustomKryoRegistrar extends IKryoRegistrar {
  def apply(k: Kryo): Unit = {
    k.setRegistrationRequired(true)
  }
}
```

It's especially useful in `DirectRunner` that ensures that data in serializable on each pipeline step without doing fusion. We discussed to expose this in a more convenient way because this is considered as a good practice for optimizing big data pipelines.

**Comment by nevillelyh** [comment]
Where do you see is the best place for this convenience API?
Not sure if we can make this per `JobTest` though since it applies to every `Kryo` instance if we add `class CustomKryoRegistrar` in `src/test`.

**Comment by kanterov** [comment]
Don't know, in Spark, it's done through `conf.set("spark.kryo.registrationRequired", "true")`, but in scio there is singleton Kryo object that doesn't allow to distinguish.

**Comment by andrewsmartin** [comment]
What about exposing this via `ScioOptions`, so it can be set with `.args()` in `JobTest`? Instances of `Kryo` are created through calls to `RichCoderRegistry.getScalaCoder` so a flag could be threaded through if we pass the options in. It's a bit messy, but works?
