### ISSUE TITLE
scio-hdfs and scio-bigtable have inconsistent netty dependencies

### ISSUE THREAD

**Issue by keithmcneill** [spotify/scio#905]
scio-hdfs and scio-bigtable have inconsistent netty dependencies.  scio-hdfs pulls in netty-all-4.0.23.Final.jar while scio-bigtable pulls in netty-buffer-4.1.8.Final.jar.  This caused `java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyClientHandler` which ultimately seems to be caused by inconsistent definitions of: io.netty.buffer.AbstractReferenceCountedByteBuf.

The root cause (inconsistent io.netty.buffer.AbstractReferenceCountedByteBuf) was really hard to find in dataflow.  The NoClassDefFoundError had no reference to AbstractReferenceCountedByteBuf

**Comment by nevillelyh** [comment]
Thanks. Do you know if one of the 2 versions will work for both scenarios? I'd prefer not the shade artifacts to get this to work. Plus libraries like netty are probably not easy to shade due to JNI and other complex dependencies.

**Comment by keithmcneill** [comment]
Gosh sorry I don't know.  

One additional clue is that this didn't seem to be a problem with scio 0.3.x.  Only cropped up with the 0.4.x upgrade.

**Comment by regadas** [comment]
is this still an issue?

**Comment by keithmcneill** [comment]
Unclear.  I don't recall what I was doing to get into this particular pickle.

**Comment by regadas** [comment]
@keithmcneill thx for the reply! since this is can stalled are you ok if we close it and reopen in case if it becomes an issue?

**Comment by keithmcneill** [comment]
Sure, can be closed for now.

**Comment by keithmcneill** [comment]
Thinking back.  I think I got this when I attempted to call a hermes
endpoint from dataflow (just at job startup, not during the normal dataflow
processing).  I ended up in some dependency hell.

Keith
