### ISSUE TITLE
PUT mapping functionality

### ISSUE THREAD

**Issue by elonybear** [spotify/scio#912]
I'm looking to create an index with a particular mapping for documents. This functionality is available in the Java Elasticsearch package. I was hoping this could be extended to Scio. 

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-admin-indices.html

**Comment by nevillelyh** [comment]
@regadas ring any bell?

**Comment by regadas** [comment]
@nevillelyh it does. IMHO if we were to support admin actions It would be inline with what we have under `scio-bigtable` with `TableAdmin`.
