### ISSUE TITLE
Compiling and running Scio on Windows

### ISSUE THREAD

**Issue by marrrcin** [spotify/scio#918]
Hi guys,
I was struggling with the compilation of Scio under Windows, there are some challenges there, but it seems like doable thing.
Are there any plans of supporting Windows for development purposes?

**Changes that I needed to made in order to compile (tag `v0.4.4`) and run Word Count example:**

1. In file `build.sbt` at line `139`:
```
    val separator = if(System.getProperty("os.name").toLowerCase.contains("windows")) ";" else ":"
    val bootClasspath = System.getProperty("sun.boot.class.path").split(separator).map(file(_))
    val jdkMapping = Map(bootClasspath.find(_.getPath.endsWith("rt.jar")).get -> url("http://docs.oracle.com/javase/8/docs/api/"))
    docMappings.flatMap((mappingFn _).tupled).toMap ++ jdkMapping
```
Hard-coded colon should be replaced with conditional like in the code above. The cause of it is:

> The user class path is specified as a string, with a colon (:) separating the class path entries on Solaris, and a semi-colon (;) separating entries on Microsoft Windows systems.
> 
> source: https://docs.oracle.com/javase/8/docs/technotes/tools/findingclasses.html

2. Symbolic link in `scio\scio-core\src\main\resources\version.sbt` does not work on Windows. For the sake of getting Scio work by any means, I've just copy-pasted `version.sbt` from root directory of the project. There are two options:
- copy file from root inside `build.sbt`
- create Windows Hard-link using `mklink /H version.sbt ..\..\..\..\..\scio\version.sbt`
**Please provide opinion on that case.** 

**Should I make pull request for my changes or you are not planning to support Windows at all?**

**Comment by nevillelyh** [comment]
None of us have Windows PC so we never thought about that case :)

For 2, don't have a strong opinion, as long as it can be automated. Some extra task in sbt or script maybe?

Anyway thanks for bringing this up and feel free to submit a PR.

**Comment by marrrcin** [comment]
Is there a way to add dependent task i.e before compilation? I'm new to SBT and I couldn't find any clues how to do this.

**Comment by nevillelyh** [comment]
Maybe something like this:
https://stackoverflow.com/questions/24174441/how-to-execute-shell-command-before-compile-task

Or it might be easier and more maintainable to add a pre-build script? Since we don't need to copy/link when running `sbt compile` every time, just when checking out the repo.

**Comment by marrrcin** [comment]
The solution from the link above does not work (I've tried it), because `<<=` operator is deprecated in SBT.

By _pre-build script_ do you mean some shell/powershell script to be run manually?

**Comment by nevillelyh** [comment]
There's a sbt 1.0 equivalent of that but can't remember off the top of my head.

Actually just found an easier way for `version.sbt`. I removed the symlink and added to compile time resources in `scio-core`. See #920

**Comment by marrrcin** [comment]
That's a very nice solution!
I will create PR with my change then.

**Comment by nevillelyh** [comment]
Closing this for now. Feel free to reopen if other issue pops up.
