### ISSUE TITLE
Dynamic file destinations support

### ISSUE THREAD

**Issue by LukeDefeo** [spotify/scio#919]
Hello i see you guys added support for dynamic destinations for big query. In this commit in beam there is a similar thing for text io 

https://github.com/apache/beam/commit/77ba7a35cdae0b036791cce0682beefeb3fd809b#diff-fbb44cd19552f243afca93d8155c35af

Any plans to support it in an up coming release?

**Comment by nevillelyh** [comment]
Don't have any immediate plan but feel free to submit a PR.
