### ISSUE TITLE
Abstraction Bigtable side lookup

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#922]
WIP branch https://github.com/spotify/scio/tree/neville/bigtable

A `DoFn` that abstract away:
- resource management, i.e. sharing a single Bigtable client
- concurrency, i.e. making async requests under the hood in a safe manner compatible with `DoFn`s threading model
- optional  caching

User implements specific querying logic by overriding:
`ListenableFuture<B> processElement(BigtableSession session, A input)`

What's missing:
- Optional caching, maybe a shared Guava `Cache<K, V>`?
- Error handling, right now it's not customizable and there's no retrying logic
- Unit test
- Benchmarks

**Comment by nevillelyh** [comment]
Error handing in `ListenableFuture` might cause problem potentially.

In Scala and Java 8 futures, we have some transform method that handles both success and failure.
```scala
future.transform(r => { onSuccess(r); r}, t => { onFailure(t); t})
```
```java
return future.whenComplete((r, t) -> {
      if (r != null) {
        onSuccess.apply(r);
      } else {
        onFailure.apply(t);
      }
    });
```

There's no equivalent in Guava, so error handling is done as a callback, which means it might not propagate to the transformed future atomically?
```java
Futures.addCallback(future, new FutureCallback ...);
return Futures.transform(future, new Function ...);
```

**Comment by sajacy** [comment]
From convo: We want to be careful that the input is not always good as the cache key.  For example, if we are pulling metadata about a field on the input.  One way to avoid poor cache hit rate is to implement `A input` as a case class with overridden `equals` that identifies equal keys.  Or allow users to provide a key selector (serializable)function.
