### ISSUE TITLE
Verify BigQueryIO DATETIME format fix and rollback workaround

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#937]
This issue was finally fixed.
https://partnerissuetracker.corp.google.com/issues/35901847

So the workaround we did in #377 can probably be removed. Need to verify it first.

**Comment by syodage** [comment]
@nevillelyh  New Big query datetime and timestamp support both 'T' and ' ' (space) as time separator. So we can either fall back to older one(with space) or stick with the workaround (with 'T') which is official. Anyway I made a PR to remove Fixme and update the comment with new formats for datetime and timestamps. https://github.com/spotify/scio/pull/982
