### ISSUE TITLE
Research/investigate fabuzaid21/yggdrasil 

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#945]
https://github.com/fabuzaid21/yggdrasil has some improvements over spark implementation of decision trees, and some initial benchmarks show that it could scale better for deep trees. Also this could be interesting **only** if xgboost is not scaling well for deep trees.

**Comment by nevillelyh** [comment]
Don't think we'll ever get around to this. Close for now @ravwojdyla?

**Comment by jbx** [comment]
Closing for now. Reopen if you think it's absolutely necessary @ravwojdyla
