### ISSUE TITLE
Programatic way to kill a job after certain time

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#954]
Could be useful for both batch & streaming. Right now it's possible with the raw DF client but not obvious to users. We could abstract it away in `ScioResult` and runner specific result classes.

**Comment by nevillelyh** [comment]
Actually the Dataflow REST API doesn't expose cancel/stop. Other runners (spark, flink, etc.) probably do but until it does there's nothing we can do here.

**Comment by nevillelyh** [comment]
I was wrong, it seems you can actually set a requested state in an `update` request.
https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/update
Such API design and documentation.

**Comment by anilmuppalla** [comment]
the web API's have the ability to set the state, we are using this feature for Galileo (Deployment service for streaming jobs) [under development]. I agree, the documentation and API is just weird.

**Comment by nevillelyh** [comment]
I forgot that `PipelineResult` already has a `cancel()` method. All we need to do is try a timeout:
```scala
if (Try(r.waitUntilFinish(1.minute)).isFailure) {
  import scala.concurrent.duration._
  r.internal.cancel()
}
```
