### ISSUE TITLE
Add support for wildcard tables in MockBigQuery

### ISSUE THREAD

**Issue by meghaakki** [spotify/scio#967]
I have a query that's something like  

```
@BigQueryType.fromQuery(
    """
      |SELECT
      |  A, ARRAY_AGG(DISTINCT B) as B
      |FROM
      |  `project.dataset1.table_*` AS table1
      |INNER JOIN
      |  `project.dataset2.table_%s` AS table2
      |ON (
      |  table1.field1 = table2.field1 AND
      |  (DATE_DIFF(PARSE_DATE('%%E4Y%%m%%d', '%s'),
      |             PARSE_DATE('%%E4Y%%m%%d', _TABLE_SUFFIX),
      |             DAY)
      |    BETWEEN 0 AND 21)
      |)
      |GROUP BY user_id
    """.stripMargin, "$LATEST", "20170801")
  class BQuery
```

When I run a MockBigQuery test to test this, it looks like the input test data and tables can't be staged because of the wildcard in the table name. 

FYI @andrewsmartin

**Comment by nevillelyh** [comment]
Should be a matter of detecting wildcards in the `original` string and replacing it with some random ID.
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala#L54

**Comment by nevillelyh** [comment]
It might be easier to replace `project.dataset1.table_*` with `project.dataset1.table_%s`, add an extra `"*"` argument to `fromQuery`, and replace with single partition when mocking.

**Comment by nevillelyh** [comment]
The following works for me:
```scala
@BigQueryType.fromQuery(
  """
    |SELECT field_a
    |FROM `project.dataset.table_%s`
  """.stripMargin, "*")
class Schema
```

```scala
val mbq = MockBigQuery()
mbq.mockTable("project:dataset.table_20171201")
  .withData(Seq(TableRow("field_a" -> "a")))
mbq.queryResult(Schema.query.format("20171201")).map(_.getString("field_a")) should contain theSameElementsAs (Seq("a"))
```
