### ISSUE TITLE
Have a recommended way of handling DNS resolution in Dataflow workers

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#970]
This issue has popped up many times:

- User code runs in a JVM inside a docker container on DF worker instances
- The container has standard Google DNS entries in `/etc/resolv.conf`
- Thus the user cannot perform lookup from custom DNS servers, e.g. internal or VPN network

To workaround this we probably need:

- Some way to override `/etc/resolv.conf` by adding custom entries. But I read that this file in the container might be read-only?
- Perform the override on worker startup (can't customize workers right now) or maybe `@Setup` in an artificial `DoFn`
- Maybe manipulate JVM DNS cache so it resolves correctly (https://github.com/alibaba/java-dns-cache-manipulator/).

**Comment by labianchin** [comment]
This issue seems more related to Apache Beam or Google Dataflow service. Should we bring this [Apache Beam support](https://beam.apache.org/get-started/support/) or Google Dataflow support? What would be the right place?

**Comment by nevillelyh** [comment]
This is more of a Google/Dataflow thing. It might be solvable with custom DF containers. Before that happens we either wait or try some workarounds.

**Comment by nevillelyh** [comment]
I just realized that `/etc/resolv.conf` is mounted from host in some Docker containers. Is this true for all containers? Is it possible to override?

**Comment by nevillelyh** [comment]
What's the status of this one? @rculbertson

**Comment by jbx** [comment]
ping @rculbertson

**Comment by athuras** [comment]
The internet brought me here; we're not a scio users (yet) but we've been dealing with this problem with our "vanilla" beam-dataflow jobs and it is fairly frustrating.

**Comment by bcleenders** [comment]
For future reference, you can work around this by using [Google Cloud DNS forward zones](https://cloud.google.com/dns/docs/overview#dns-forwarding-zones) to point to your internal DNS infrastructure.

Dataflow workers query 169.254.169.254 internally, which resolves using Cloud DNS. If you setup a forward zone in Cloud DNS to point to your own DNS server (you can set up [private forward zones](https://cloud.google.com/dns/docs/overview#shared-vpc) that point to internal IPs on your VPC, just make sure to whitelist dns traffic from `35.199.192.0/19`), then you can resolve your own queries.

Note: NS records in private forward zones are ignored, this can be a bit confusing if you're trying to debug things :)

**Comment by nevillelyh** [comment]
We're doing this internally now. Closing this.
