### ISSUE TITLE
Stalling jobs with large joins on 0.4.4+

### ISSUE THREAD

**Issue by fallonchen** [spotify/scio#976]
Some internal users have reported stalling jobs with large joins (1B+ RHS, 750M LHS) when using versions of scio later than 0.4.3.

**Comment by andrewsmartin** [comment]
Based on an investigation by the Google support team, it seems like the stalling issue was due to a one-off problem related to shuffling, but there seems to be a definite performance regression in 0.4.4+, perhaps because of the addition of specialized joins. Will investigate further.
