### ISSUE TITLE
SparkeyIO for running tests against Sparkey file output

### ISSUE THREAD

**Issue by elonybear** [spotify/scio#978]
Hi, I was wondering whether there is support for testing Sparkey file output from Scio pipelines? Currently, I'm not seeing any classes or documentation supporting this feature. I'm seeing it as following a similar pattern to AvroIO, ElasticsearchIO, and so on.

Thanks!

**Comment by nevillelyh** [comment]
`.asSparkey` returns an `SCollection[SparkeyUri]` so the easiest might be mapping that into a `SCollection[String]` where the string points a local path, and then assert file content?

You can have something like this in the job code:
```scala
s.asSparkey.saveAsTextFile(args("sparkey"))
```

And in the test code
```scala
.output(TextIO("sparkey")) { s =>
  s should satisfy { uri =>
    // open sparkey file and assert content
  }
}
```

Can you try if this works first?

**Comment by elonybear** [comment]
So I actually have something similar happening. The only issue is that it creates the sparkeys and so running the same test twice throws a duplicate file exception. In the same way that ElasticsearchIO doesn’t actually create the index, it would be very useful for a SparkeyIO class to do something similar.

**Comment by nevillelyh** [comment]
True but it's not really an IO, more like a syntactic sugar that writes files as side effect.

There're 2 workarounds:
- use `asSparkey` without argument so it'll write to a temp location every time
- delete the files after assertion

WDYT?

**Comment by elonybear** [comment]
Hm, those options would definitely work. I think I may go with the first option and have conditional logic for it. Thanks for the help!

**Comment by andrewsmartin** [comment]
Let's close this one for now. In the future there may be a proper Sparkey IO, and the test stuff would be included as part of that (https://github.com/spotify/scio/issues/933)
