### ISSUE TITLE
Feeding a JobTest from src/test/resources

### ISSUE THREAD

**Issue by mikaelstaldal** [spotify/scio#980]
It would be nice to be able to have a `com.spotify.scio.testing.JobTest` to read input from a file in `src/test/resources`?

This can currently be done like this:
```
  "A CoolJob" should "do stuff well" in {
    JobTest("com.mycompany.CoolJob")
      .args("--data=data.tsv")
      .input(TextIO("data.tsv"), testData("/data.tsv"))
      .run()
  }

  private def testData(fileName: String): Seq[String] =
    Source.fromInputStream(getClass.getResourceAsStream(fileName)).getLines().toSeq
```

But a shortcut would be nice.

**Comment by nevillelyh** [comment]
Feels a little out of scope plus this will only cover simple file formats. Not sure if it belongs in scio.

**Comment by mikaelstaldal** [comment]
Ideally, I would like this to work at a lower level, so that it can handle any file format. So you can do something like this:

```
  "A CoolJob" should "do stuff well" in {
    JobTest("com.mycompany.CoolJob")
      .args("--input1=data1.tsv")
      .args("--input2=data2.avro")
      .inputResource("data1.tsv")
      .inputResource("data2.avro")
      .run()
  }
```

and that would read `data1.tsv` and `data2.avro` from `src/test/resources`.

**Comment by nevillelyh** [comment]
Well then one could also ask for symmetric output support, which can easily adds to feature creep. This could also be easily abused, like feeding sampled data without actually covering useful corner cases.
`testData` is a one-liner that anyone can write quickly, if one understand the consequences. I'd prefer to keep it that way.

So again leaning towards to closing this as a "won't fix" but this issue will be searchable to whoever wants to do it.

**Comment by nevillelyh** [comment]
Discussed with the team. Closing for now.
